### PR TITLE
feat: Tax Detail Report

### LINKED ISSUE #21233: [Feature Request] UK VAT Return & Making Tax Digital for VAT
### [Pledge your support for this project here!](https://www.casesolved.co.uk/products/erpnext-features/erpnext-ukvat)
**This integration will allow ERPNext to be published as HMRC Recognised Software on their website.**

## Pre-requisites
Frappe general purpose OAuth2 client (see [here](https://github.com/frappe/frappe/issues/9722))
Multiple Company Tax registrations (see [here](https://github.com/frappe/erpnext/issues/21723)) - Can be implemented with regional-specific custom fields on the Company
Chart of Accounts Map (see [here](https://github.com/frappe/erpnext/issues/21694)) see #25254 

### UK VAT
A VAT return report and digital integration with HMRC that supports all domestic and international goods and service purchase and sales according to UK VAT rules
- Deliver the 9-box UK VAT Return report format, including:
  - Provision for Suppliers and Customers to be marked with regions for specific VAT rules
  - Provision for invoice items to be marked with categories, specifically: Goods, Services and Mobile Phones/Chips
  - A mechanism that applies VAT rates (standard: 20%, reduced: 5%, zero: 0%) and accounts to invoice lines based on the two pieces of information above
  - Transactions not applicable for VAT reporting, e.g. local authority rates, must not have VAT applied and so will not be picked up by the report
  - The 9 boxes must be editable to allow the HMRC submission of special VAT accounting schemes
- OAuth2 & REST-based submission of figures
- Storage of VAT Registration Number (VRN), a 9-digit number

### ERPNext constraints
- Must work on one-off purchase transactions with lines that are not pre-defined as Items
- Must work with the existing ERPNext tax features
- VAT must be captured as normal ledger entries in suitable accounts. This allows existing ledger reports to be used for analysis and debugging
- Tax must **not** be accounted for outside of the CoA; the report must draw its values from General Ledger entries so as to include correcting Journal Entries
- Although there is a "Tax ID" field, the UK has various Tax IDs that relate to a Company (Corporation Tax (UTR), PAYE, VRN, EORI) so the UK will need several IDs
- Although there are Sales/Purchase Taxes and Charges Templates, since they apply a rate to whole invoices and not individual invoice lines, they do not cater for invoices with lines with differing VAT rates and accounting requirements and so cannot be used in the general case or exclusively
- All features should be added as regional customisations in the regional module so as not to pollute the base UI

### Recommendations
- It should be possible for Sales and Purchase VAT to be accounted on separate Accounts, though not essential
- The report should have a drill-down/detail table to allow for analysis
- Item Tax Template should be extended to allow application to Sales and Purchases separately, and ideally the Sales/Purchase Taxes and Charges template should be refactored to apply to line items instead of invoices

## Setup
Boxes 1 to 4 can be generated directly from the Chart of Accounts using standard ERPNext functionality with the following setup:
- Tax Categories for Customers and Suppliers (separately) to identify their region: UK, EU or Rest of World (optional)
- Item Tax Templates set up to apply the correct VAT rate to the correct Account(s), for example:
  - A Reverse Charge Purchase at standard rate requires 20% to be applied to a *VAT on Purchases* Account (used for Box4), and -20% to also be applied to a *VAT on Sales* Account (used for Box1)
  - For common or stock items, Item Groups set up with Items in the correct Group, to automatically apply the correct Item Tax Template based on the Item & Tax Category (optional). Though Item Tax Templates can be applied manually to non-inventory Items

## Additional DocTypes and fields (with fieldtype, etc) if any
See pre-requisites
The CoA Map will need to be extended to include the following functionality:
- Item Tax Template name filter (simple pattern matching similar to SQL like) used to generate tax entries, since it may be necessary to select specific transactions for example Services and Mobile Phone Reverse Charges
- Selection of the related transaction value or tax value for the report
- Sales or Purchase filter to allow VAT to be reported to a single account but maintain report flexibility
- Negative - whether the value should be negated
- Sum multiple entries with the same output field name, allows a report value to be a composite of multiple values

## Discovery (how will the user find the feature you are building)
- Chart of Accounts - View menu: HMRC VAT Returns
- Accounting -> Taxes -> HMRC VAT Returns
- Accounting -> Taxes -> Connect to HMRC
- Company -> HMRC Settings
- User -> Third Party Authentication
## Screen Mockups with buttons and any custom UI (TBD)
- HMRC user permissions definition (scopes); also used as auth fail destination
- (OAuth2 Authorisation flow: out-of-scope)
- VAT Information as tables (auth & VAT return submit success):
  - VAT return obligations (mandatory) with buttons to the VAT report specifying the period and PeriodKey
  - Submitted VAT returns (optional)
  - VAT liabilities (optional)
  - VAT payments (optional)
- VAT Report for a period with 2 use cases:
  - Manual period definition, OAuth2 not required, no submit button
  - Period passed from VAT return obligation button, VAT Return submit button
    - Displays error for failed submissions
### Validations
- Company VRN number existence
- HMRC OAuth2 Provider existence
### Calculations
See Reports section
### Logs
None
## Links to existing DocTypes
Links to VAT Accounts
## Reports
Calculations performed according to this table which is not a complete picture:
[UK VAT return](https://docs.google.com/spreadsheets/d/1wgVkg9sJkeLj5-v0tob5P3kw6Xkh_LVHmBi-HENea2M/edit?usp=sharing)
The report uses Journal Entries specified by the CoA Map for boxes 1 to 4 which are the primary VAT lines
Box 5 is a sum based on boxes 3 & 4
Box 6 to 9 must be generated from the transactions used in boxes 1 to 5, to exclude non-VAT transactions, for example: salaries & exempt purchases

This has not been designed for special VAT accounting schemes, though the 9 boxes on the VAT Return will be editable to allow different schemes to be posted.
[Further information from HMRC](https://www.gov.uk/guidance/how-to-fill-in-and-submit-your-vat-return-vat-notice-70012)

### PR DESCRIPTION
**Pull request by nameduser0**
Provides a generic Tax Detail report that expands Sales and Purchase Invoice details for detailed Sales and Goods Tax reports. But operates from GL Entries, so should be useful for generating any form of Tax report including those that need to include Journal Entry amendments. Has been tested as okay for Payroll reporting for Income Tax returns.

The report can be split into filtered sections whose total appears as a section subtotal and a summary total in v13. The report can then be saved as a Custom report that can be run later using any date filters required.

Requires frappe/frappe#12534
Part-addresses #21233
Documented at https://github.com/frappe/erpnext_documentation/pull/322  .
https://docs.erpnext.com/docs/user/manual/en/accounts/accounting-reports#3-taxes

TaxDetailGif

@surajshetty3416 @barredterra I would appreciate your reviews!

### CODE REVIEW

**Comment by casesolved-co-uk** [comment]
A lot of the sider checks will make the code less readable. Are they final or subject to change?

**Comment by casesolved-co-uk** [comment]
Does this require documentation? It has help text at the bottom of the report.

**Comment by nameduser0** [comment]
> Has test case failures. I'll fix those.

Fixed

**Comment by nameduser0** [comment]
I believe the test error is now due to frappe/frappe#12534

**Comment by deepeshgarg007** [comment]
@casesolved-co-uk is it possible to add sections account-wise, like one section for VAT 0%, one for VAT 15%, etc. in one report. If yes, please guide me through the steps

**Comment by nameduser0** [comment]
> @casesolved-co-uk is it possible to add sections account-wise, like one section for VAT 0%, one for VAT 15%, etc. in one report. If yes, please guide me through the steps

@deepeshgarg007 Yes you should be able to do that. Assuming you already have your separate accounts set up and transactions:

1. Use the Custom Report menu to create a new Custom Report
2. Set the date and company filters for the relevant period
3. Add a section using the New Section button, give it a suitable name
4. Set the column filters to get the transactions for the section, set the Component Type to `Filtered Row Subtotal` & Add Component
5. Select the blank Component to reset the filters & Repeat 4 for more transactions in the section
6. Repeat from 3 for more sections
7. Hit Save & Run

**Comment by deepeshgarg007** [comment]
> > @casesolved-co-uk is it possible to add sections account-wise, like one section for VAT 0%, one for VAT 15%, etc. in one report. If yes, please guide me through the steps
> 
> @deepeshgarg007 Yes you should be able to do that. Assuming you already have your separate accounts set up and transactions:
> 
> 1. Use the Custom Report menu to create a new Custom Report
> 2. Set the date and company filters for the relevant period
> 3. Add a section using the New Section button, give it a suitable name
> 4. Set the column filters to get the transactions for the section, set the Component Type to `Filtered Row Subtotal` & Add Component
> 5. Select the blank Component to reset the filters & Repeat 4 for more transactions in the section
> 6. Repeat from 3 for more sections
> 7. Hit Save & Run

**Comment by deepeshgarg007** [comment]
> > @casesolved-co-uk is it possible to add sections account-wise, like one section for VAT 0%, one for VAT 15%, etc. in one report. If yes, please guide me through the steps
> 
> @deepeshgarg007 Yes you should be able to do that. Assuming you already have your separate accounts set up and transactions:
> 
> 1. Use the Custom Report menu to create a new Custom Report
> 2. Set the date and company filters for the relevant period
> 3. Add a section using the New Section button, give it a suitable name
> 4. Set the column filters to get the transactions for the section, set the Component Type to `Filtered Row Subtotal` & Add Component
> 5. Select the blank Component to reset the filters & Repeat 4 for more transactions in the section
> 6. Repeat from 3 for more sections
> 7. Hit Save & Run

I was not able to find anything to add column filters, can you please add a GIF to explain in the Description?

**Comment by nameduser0** [comment]
> I was not able to find anything to add column filters, can you please add a GIF to explain in the Description?

Done. You need to create a custom report from the Tax Detail report and ensure there are *some* transactions

**Comment by nameduser0** [comment]
What's the holdup please?

**Comment by deepeshgarg007** [comment]
@casesolved-co-uk Please update your branch with the latest `develop` branch and push. The failing test case has been resolved.

**Comment by nameduser0** [comment]
Is there a problem with this or is it just waiting for documentation?
Where would I put the documentation, [here](https://docs.erpnext.com/docs/user/manual/en/customize-erpnext/articles)?

**Comment by barredterra** [comment]
I think the docs could go here: https://docs.erpnext.com/docs/user/manual/en/accounts/accounting-reports#3-taxes

And yes, imho they are required before merging such a big feature. A feature that's not well documented might as well not exist.

**Comment by nameduser0** [comment]
@barredterra Could you remove the tags now please?
@deepeshgarg007 Can this go in now?

**Comment by deepeshgarg007** [comment]
> @barredterra Could you remove the tags now please?
> @deepeshgarg007 Can this go in now?

@casesolved-co-uk yes will do a final review and get this merged

**Review by deepeshgarg007 — APPROVED** [review]

**Comment by nameduser0** [comment]
Woohoo! Thanks @deepeshgarg007 🥇

**Comment by nameduser0** [comment]
@nabinhait Hi Nabin, could you tell me why this hasn't gone into v13.4 or v13.5 please?

**Comment by nabinhait** [comment]
@casesolved-co-uk We take v13 releases from `version-13-hotfix` branch, not from `develop`. This PR should be back-ported to `version-13-hotfix`, please send another PR to that branch.

**Comment by nameduser0** [comment]
@nabinhait So what is the `develop` branch used for, v14?

**Comment by nabinhait** [comment]
> @nabinhait So what is the `develop` branch used for, v14?

Yes

**Pull request merged**
