### PR TITLE
New fields for POS Profile in Sales Invoice and POS Profile Modification

### PR DESCRIPTION
**Pull request by chdecultot**
Hi,

This PR is the first of a bigger project to implement X and Z reports in the POS.
It is linked to issue #7582 

I have completed the issue to propose an approach and I would be very grateful if the Frappé Team could give some inputs before I continue the developments.

This first PR is only the addition of a new field called "pos_profile" in the sales invoice to register the name of the person behind the cash register.
I therefore also modified the pos.js file to register that information:

image

Of course the field is hidden but I just took a screenshot to demonstrate the result in the invoice document.

In order to have a consistent information, I also propose to modify the POS Profile doctype to set the linked user only once. Indeed we should be able to know for sure who was the cashier at a certain point and with the current system we can change it afterwards.

Don't hesitate to let me know your thoughts about this proposal.

Thank you very much.

Best regards,

Charles-Henri

### CODE REVIEW

**Comment by felixvarghese** [comment]
To find out the cashier, can you just use the already existing "created by" field? 

That requires no modification to Sales Invoice and also no modification to POS Profile.

**Comment by chdecultot** [comment]
Hi @felixvarghese,

That's a good point. I think it is good to link it to the POS profile, especially since it is in the roadmap to have multiple POS profiles per users in Q4 2017 (https://github.com/frappe/erpnext/issues/6308 that you created 😉).

As for the modification of the POS Profile, even if it is not agreed to have the information linked to the sales invoice, I don't see any use case where a POS profile should be linked to different users. In my opinion it should be unique to avoid fraudulent use cases. 
If needed it can be duplicated and a new one can be created for a new user.

If you are working with the POS system a lot, don't hesitate to share your use cases, I'm very interested to try to enhance it. 😊

**Comment by felixvarghese** [comment]
If multiple POS profiles come into play, then its true that linking POS Profile in Sales Invoice will be important to generate X and Z reports. Good point.
 
It's currently not possible to link the same POS Profile to multiple users. And in the rough spec I mentioned for multiple profiles, it still won't be possible. Of course, if the spec changes, then that's a different story.

**Comment by rmehta** [comment]
Multiple POS profile is a popular requirement, so will be good to plan for it. 👍

**Pull request merged**
