### PR TITLE
fix: Set batch no in Manufacturing Stock Entry as per transferred raw materials

### PR DESCRIPTION
**Pull request by nmimsnikhil**
Fetched batch number in stock_entry.py and applied to item

Before:
Batch_no_Task

After:
batch_number_fix

### CODE REVIEW

**Comment by pujanthakkar** [comment]
What if there are multiple batches of same item transferred ?

**Comment by pujanthakkar** [comment]
> What if there are multiple batches of same item transferred ?

For Example when we transfer fabric, it comes in multiple batches & what we do is transfer multiple batches by adding multiples rows in stock entry for transfer to manufacture.

Currently in the Manufacture entry all those batches are not fetched and what we have to do is manually enter each batch again. Will this resolve that ?

**Comment by rohitwaghchaure** [comment]
@nmimsnikhil Can you split the quantity in case of multiple batches has been transferred?

**Comment by Alchez** [comment]
Hey @rohitwaghchaure, the frontported PR to [develop](https://github.com/frappe/erpnext/pull/20806) for this one was closed since @nabinhait  said you guys would fix it in the core. Should we still keep this open?

**Pull request closed without merging**
