### PR TITLE
fix(pos): numpad error when changing language

### PR DESCRIPTION
**Pull request by rpineda**
The pull request fixes a small bug that happens on the POS page when the language is changed. Everything works perfect in English, but for example in Spanish. When clicking on the Quantity buttons, the event should change the focus to the input tag qty, but that does not happen.

For this reason I made a small modification in the files:
* erpnext / selling / page / point_of_sale / pos_item_cart.js
* erpnext / selling / page / point_of_sale / pos_number_pad.js

Modification in the file: erpnext / selling / page / point_of_sale / pos_payment.js fixes the error when choosing a customer

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

### CODE REVIEW

**Comment by nextchamp-saqib** [comment]
Keep Alive

**Comment by rpineda** [comment]
Keep Alive x2

**Comment by zulnabil** [comment]
this bug still exist in Indonesia language

**Comment by nextchamp-saqib** [comment]
Fixed with https://github.com/frappe/erpnext/pull/30808

**Comment by tbe** [comment]
This issue still exists for me with erpnext v13.40.2 docker images.

**Pull request closed without merging**
