### PR TITLE
Post GL Entry based on rounded total in Sales/Purchase Invoice

### PR DESCRIPTION
**Pull request by nabinhait**

### CODE REVIEW

**Comment by sathishpy** [comment]
Great. Looks very different from my initial work. Accounting is certainly a complex module and needs a lot of experience to make modifications.

**Comment by nabinhait** [comment]
@sathishpy Have you test it?

**Comment by sathishpy** [comment]
Can you tell me whether it is ok to 'git pull' from https://github.com/nabinhait/erpnext/tree/develop.
It says 'This branch is 1208 commits behind frappe:develop.'. Not sure whether there is a better way to update the code from merge requests.

**Comment by sathishpy** [comment]
Great Job. I just updated to latest release and did some basic testing. It works as expected. It might be better to update the fields dynamically when 'disable rounded total' is selected. However people are not going to use it often, so I don't really care about it much.

**Pull request merged**
