### PR TITLE
fix(translations): rename translation file pt-BR.csv -> pt_br.csv

### PR DESCRIPTION
**Pull request by saullo**
Issue:
When translation files are named with the format pt-BR.csv, there was an unintended fallback to pt.csv instead of recognizing the specific pt-BR translation file.

Resolution:
Upon investigation, it seems to be related to a possible bug in the bench migrate step or a misinterpretation of the file naming convention. To address this, I renamed the pt-BR.csv translation file to pt_br.csv, and this adjustment successfully resolved the issue.

Action Taken:

1. Identified the bug causing the fallback to pt.csv.
2. Renamed the translation file from pt-BR.csv to pt_br.csv.
3. Confirmed that the correction resolved the translation file recognition problem.

Next Steps:
I recommend reviewing the translation file naming conventions in the bench migrate step to ensure compatibility with language codes containing hyphens. It's possible that this could be a broader issue affecting other language codes.

This behavior may be related to the issue discussed in #25883.

### CODE REVIEW

**Comment by bosue** [comment]
Well, I think the fallback is intended, and “pt-BR“ is the universal naming convention for language code variants.

However “pt” is supposed to be a fallback, not to take precedence over “pt-BR”, and I think that’s the problem here!?

In the other issue I read:

> Some messages that are already translated to "pt-BR" are not displayed. Instead, the system display the relative translation to "pt".

This should actually not be the case. A Brazilian Portuguese translation will in most if not all cases be better than none at all, even in Portugal or the Açores.

Once the fallback mechanism properly works, we should move all translations to “pt” unless “pt” is (properly) overridden by the same string in “pt-BR”.

**Review by barredterra — DISMISSED** [review]

**Comment by bosue** [comment]
@barredterra: Sorry, but how is this PR ready to be merged? 🫤

No matter which nomenclature we may want to pick, it should certainly be consistent a) with frappe and b) with what we’re doing in regard to all other language varieties.

Renaming the file may work as a stop-gap, and it does, see frappe/frappe#23235. But of course it doesn‘t fix the underlying problem.

In frappe/frappe, the expectation currently is that the CSV files are named pt-BR.csv or da-DK.csv, see https://github.com/frappe/frappe/blob/develop/frappe/translate.py#L193. That‘s why the CSV files shipped with frappe/frappe are named accordingly, see https://github.com/frappe/frappe/tree/develop/frappe/translations.

The fact this expectation isn‘t followed through, is why we‘re having the current problem at all.

We may change the expectation in frappe/frappe and adopt some other file name convention. I‘m perfectly fine with that. But we should make sure the convention is used consistently, shouldn‘t we?

**Comment by barredterra** [comment]
Sorry, that was a bit quick. I'll leave this to you.

**Comment by bosue** [comment]
Nah, let‘s team up to settle with a working and a good solution. The current chaos doen’t work, but your GNU gettext argument is sound.

The truth may lie in between: “pt_BR.csv“ as used in POSIX and GNU gettext should be the best way forward. But let‘s see how frappe/frappe maintainers see it…

**Comment by barredterra** [comment]
> But let‘s see how frappe/frappe maintainers see it…

I would be surprised if there are strong opinions regarding file names. We'll just have to ensure backwards-compatibility with existing files in other custom apps, as well as with the UI language picker which uses the `ll-CC` format.

**Comment by bosue** [comment]
@barredterra: Fine. As we need to settle with one or the other solution asap in order to get the original bugs fixed, would you mind coming up with a proposal on frappe/frappe?

**Comment by barredterra** [comment]
Yes, I would mind. I'm packed for the rest of the year and my clients don't care much about this issue 😅

**Comment by bosue** [comment]
Just asking because you had a strong opinion on which naming scheme best suits your forthcoming GNU gettext implementation.

In this case, I will work towards getting it fixed one way or the other, whatever is less of a hassle.

**Comment by bosue** [comment]
@saullo: Still waiting for frappe/frappe#23235 to be reviewed. In the end I did propose your nomenclature (`pt_br.csv`), but we’ll have to see which of the three options is chosen.

Thanks for your contribution! I really didn’t mean to be rude, but of course we can’t just rename a single translation file in ERPNext, while not making sure a consistent naming scheme for both CSV read and write operations is in place… 🤷🏻‍♂️

**Comment by saullo** [comment]
@bosue Hey there! It sounds like you've been diving deep into the details. Finding the right naming scheme can be a bit of a puzzle, but it's essential for consistency, especially in something as complex as ERPNext. It seems like you're working hard to find the best solution among the options available. Keep up the great work!

**Comment by bosue** [comment]
Not so much a puzzle. Either of the three conventions will work if we follow through with it…

**Comment by ankush** [comment]
https://github.com/frappe/frappe/pull/23320

**Pull request closed without merging**
