### PR TITLE
fix: Task Depends on not removed from Gantt chart

### LINKED ISSUE #16064: Task Depends on not removed from Gantt chart
Hiiii..
I noted that the (task depends on arrows) still existed after removing from task form.
Version is 10.1.72
I reloaded list many times... but the arrows not removed.
untitled

### PR DESCRIPTION
**Pull request by conncampbell**
> Please provide enough information so that others can review your pull request:

Closes #16064

> Explain the **details** for making this change. What existing problem does the pull request solve?

When removing task dependencies, the field "task_depends_on" is never cleared and recalculated correctly.  It always adds to existing values.  The "task_depends_on" fields seems to be used by the gantt chart, thus it shows dependencies that don't exist on tasks.

### CODE REVIEW

**Comment by conncampbell** [comment]
Any progress on merging this?

**Comment by conncampbell** [comment]
Does anyone know why this pull won't link to the issue #16064?

**Comment by conncampbell** [comment]
@pateljannat Would it be possible to get this pull in the next release?

**Comment by conncampbell** [comment]
Bump

**Comment by conncampbell** [comment]
Still hoping to get this merged.

**Review by ruchamahabal — APPROVED** [review]

**Comment by ruchamahabal** [comment]
Unrelated test failures

**Comment by ruchamahabal** [comment]
@Mergifyio backport version-13-hotfix

**Comment by conncampbell** [comment]
@ruchamahabal Thank you!

**Pull request merged**
