### PR TITLE
feat(delivery): add cutoff item date for so delivery items

### PR DESCRIPTION
**Pull request by blaggacao**
#38053 still addresses a very common use case and a current flaw in the end-2-end buisness workflow.

`no-docs`

### CODE REVIEW

**Comment by blaggacao** [comment]
@deepeshgarg007 @ruthra-kumar Could we look together at this use case and get work together towards a merge? This is, as described in the linked item, a pretty critical feature in any scaled dispatch operations of more than a handful deliveries. We're currently managing roughly 200 daily and without this feature, operations would collapse.

**Comment by blaggacao** [comment]
@ruthra-kumar commit history is now clean. Though, I've not found any existing test infrastructure for bulk transactions, albeit I was full of enthusiasm to write one. :smile: I checked manually though in a testing database and delivery notes are created as expected and only with the items expected.

**Comment by blaggacao** [comment]
@Mergify update

**Comment by ruthra-kumar** [comment]
@blaggacao 
If there are no items within the cut-off date, then a delivery note with empty items table is created. User can unintentionally create lot of junk delivery notes.


[so_to_delivery_note.webm](https://github.com/frappe/erpnext/assets/3272205/c07085e2-60d0-4aad-b7e0-7781bf077d31)

**Comment by blaggacao** [comment]
@ruthra-kumar Thanks a lot for the friendly QA! I worked around this issue in the case of a bulk transaction with the amendment in https://github.com/frappe/erpnext/pull/38561/commits/9a705169fd3916342c14be693ab7a0da2f188fff.

I've tested in on a local database and it appears to behave as intended, now. :handshake: 

I thought it might be good for performance on large bulk transactions to not depend on the python GC, hence: `del obj` (cc @ankush for my education: is manually freeing memory a valid thought, at all?)

**Comment by blaggacao** [comment]
@ruthra-kumar I've been busy myself this week, but maybe we shouldn't let this dry out? I think it's ready.

**Comment by ruthra-kumar** [comment]
Will take a look at it this week.

**Comment by blaggacao** [comment]
@ruthra-kumar maybe we can get this merged this week, still? :pray:

**Comment by ruthra-kumar** [comment]
@blaggacao 
Code looks ok. No junk Delivery notes now.

I think, making this a toggleable feature would be better. Add an option in `Selling Settings` and give the cut-off date popup only if enabled(?)

**Comment by blaggacao** [comment]
@ruthra-kumar added in: b8dac84a9014a66a1acd662d8245c4c2e8bc1823

**Review by ruthra-kumar — APPROVED** [review]

**Comment by ruthra-kumar** [comment]
semgrep failure is unrelated.Ignoring.

**Comment by ruthra-kumar** [comment]
When backporting include https://github.com/frappe/erpnext/pull/40509

**Pull request merged**
