### PR TITLE
fix: GSTIN validation

### PR DESCRIPTION
**Pull request by hrwX**
Changed GST Validation Format
1-2 : State Code
3-11 : Pan
13: Entity Code
14 : Blank
15: Check Digit

### CODE REVIEW

**Comment by sagarvora** [comment]
what's the use case for this? I think it should be more rigid, like so:
[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9]{1}[Z]{1}[0-9A-Z]{1}

Ref:
1. https://www.incometaxindia.gov.in/tutorials/1.permanent%20account%20number%20(pan).pdf
1. https://cleartax.in/s/know-your-gstin/
1. https://taxguru.in/goods-and-service-tax/bulk-gstin-structural-error-check-utility.html

**Comment by hrwX** [comment]
> what's the use case for this? I think it should be more rigid, like so:
> [0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9]{1}[Z]{1}[0-9A-Z]{1}
> 
> Ref:
> 
>     1. https://www.incometaxindia.gov.in/tutorials/1.permanent%20account%20number%20(pan).pdf
> 
>     2. https://cleartax.in/s/know-your-gstin/
> 
>     3. https://taxguru.in/goods-and-service-tax/bulk-gstin-structural-error-check-utility.html

Please refer this:
https://www.gstzen.in/a/format-of-a-gst-number-gstin.html
There's a user with a valid GST number yet theres a validation error for ERPNext.
Consider an example '27PNEA06819B1DE' is a valid gst number yet not being validated in the system and rendered as invalid.

**Review by sagarvora — DISMISSED** [review]
Thanks for the reply.

**Comment by sagarvora** [comment]
Maybe we can also try to incorporate this validation:
https://gauravj75.blogspot.com/2018/01/excel-gstin-checksum-digit-logic.htm

**Comment by karthikeyan5** [comment]
hey, @hrwX @sagarvora 
I had earlier worked on GSTIN Validations in Javascript.

Below is the code I got from GSTN Developer Portal when it used to be available.
https://gist.github.com/karthikeyan5/f7b28e66ac9617603622491950bda77a

Can you hold till EOD before you merge this? 
I will port this code to Python and add it to this PR... 

This checksum validation will save a lot of time for Accountants as it can catch most GSTIN typos well before filing GSTR.

**Comment by karthikeyan5** [comment]
Function to get the check digit for the gstin:
```
def get_gstin_with_check_digit(gstin_without_check_digit):
	''' Function to get the check digit for the gstin.

		param: gstin_without_check_digit
		return: GSTIN with check digit 
	'''
	factor = 1
	total = 0
	code_point_chars = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
	input_chars = gstin_without_check_digit.strip()
	if not input_chars:
		frappe.throw(_("GSTIN supplied for checkdigit calculation is blank"))
	mod = len(code_point_chars)
	for char in input_chars:
		digit = factor * code_point_chars.find(char)
		if digit < 0:
			frappe.throw(_("GSTIN supplied for checkdigit contains invalid character"))
		digit = (digit / mod) + (digit % mod)
		total += digit
		factor = 2 if factor == 1 else 1
	return ''.join([gstin_without_check_digit,code_point_chars[((mod - (total % mod)) % mod)]])
```
can you please add this function in there... then call this without the last character of the provided GSTIN.. then check if the returned GSTIN is equal to the GSTIN given by user.
> eg: if doc.gstin != get_gstin_with_check_digit(doc.gstin[:-1])

**Comment by hrwX** [comment]
> Function to get the check digit for the gstin:
> 
> ```
> def get_gstin_with_check_digit(gstin_without_check_digit):
> 	''' Function to get the check digit for the gstin.
> 
> 		param: gstin_without_check_digit
> 		return: GSTIN with check digit 
> 	'''
> 	factor = 1
> 	total = 0
> 	code_point_chars = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
> 	input_chars = gstin_without_check_digit.strip()
> 	if not input_chars:
> 		frappe.throw(_("GSTIN supplied for checkdigit calculation is blank"))
> 	mod = len(code_point_chars)
> 	for char in input_chars:
> 		digit = factor * code_point_chars.find(char)
> 		if digit < 0:
> 			frappe.throw(_("GSTIN supplied for checkdigit contains invalid character"))
> 		digit = (digit / mod) + (digit % mod)
> 		total += digit
> 		factor = 2 if factor == 1 else 1
> 	return ''.join([gstin_without_check_digit,code_point_chars[((mod - (total % mod)) % mod)]])
> ```
> 
> can you please add this function in there... then call this without the last character of the provided GSTIN.. then check if the returned GSTIN is equal to the GSTIN given by user.
> 
> > eg: if doc.gstin != get_gstin_with_check_digit(doc.gstin[:-1])

Hey @karthikeyan5 I have added you as a collaborator, go ahead and make changes.

**Pull request merged**
