### PR TITLE
feat: Scan Barcode using Camera in mobile

### PR DESCRIPTION
**Pull request by netchampfaris**
**Works only in Mobile**

Show a barcode scanning button in all forms which has a Barcode Scan field.

[Watch Barcode Scanning in Action](https://streamable.com/0wgh0)

Depends on https://github.com/frappe/frappe/pull/8415

### CODE REVIEW

**Comment by govindsmenokee** [comment]
Watch Barcode Scanning in Action link is not working

**Review by surajshetty3416 — APPROVED** [review]

**Review by nabinhait — APPROVED** [review]

**Comment by raymondliew1992** [comment]
Is this working? Cause I do not see the "Scan barcode with camera" button in my android phone.
Android app version: 0.0.14
ERPNext version: v12.1.4

**Comment by asem89** [comment]
The same here, no "Scan barcode by camera" is visible in ERPNext app.

**Comment by asem89** [comment]
The same here, no "Scan barcode by camera" is visible in ERPNext app in STOCK ENTRY.

In Sales Invoice it works. @netchampfaris how to get it in other DocTypes?

**Pull request merged**
