### PR TITLE
Do not require address field in webshop

### PR DESCRIPTION
**Pull request by rasos**
Fixes https://github.com/frappe/erpnext/issues/17559

Mandatory address field is a GDPR issue.

### CODE REVIEW

**Comment by rasos** [comment]
This should be an easy merge. Please make address field optional for webshop sales. We mainly sell digital services, there is no need to deliver a parcel physically.

**Comment by rasos** [comment]
Still an open issue.

**Comment by rmehta** [comment]
please don't comment code. Can we make this a setting?

**Comment by rasos** [comment]
Yes, setting would be even better - there might be some industries which always need an address from webshop orders.

**Comment by rasos** [comment]
resubmitted PR as https://github.com/frappe/erpnext/pull/19096

**Pull request closed without merging**
