### PR TITLE
feat: added continue-shopping button

### PR DESCRIPTION
**Pull request by anupamvs**
Added **Continue Shopping** button on the cart page which redirects to **all-products**
image

`no-docs`

### CODE REVIEW

**Review by prssanna — APPROVED** [review]

**Comment by leventesen** [comment]
@anupamvs & @prssanna 

**Continue Shopping** button is added  but **Request for Quotation** button is deleted

Did you notice that?

In version 13 I couldn't find the **Request for Quotation** button near the **Continue Shopping** button

**Comment by anupamvs** [comment]
@leventesen The changes are unrelatable.

**Comment by leventesen** [comment]
@anupamvs Sorry, do you have any idea where and why **Request for Quotation** button is removed.  Branches are confusing me and I am not expert yet so couldn't find the commit causing to this.

Maybe I should open an issue?

**Comment by anupamvs** [comment]
@leventesen Yes,  please create a issue.

**Pull request merged**
