### PR TITLE
Move Company Field To The Top In BOM

### PR DESCRIPTION
**Pull request by tundebabzy**
Reference: #10099

Presently, when filling BOM, user has to scroll below line of sight in order to enter company name. It's a better user experience for the company field to be on top.

### Before
28607643-68afcb76-71fa-11e7-82aa-a8c8e1172c8d

### Now
screenshot from 2017-08-08 23-58-39

After this, when the company field is changed, the currency field should automatically be changed to the company currency

### CODE REVIEW

**Comment by Terencepcurtis** [comment]
@nabinhait , hi, is there a way I can test or update / check, please so I can comment ?
tks,

**Comment by tundebabzy** [comment]
Hi @Terencepcurtis if you are a developer or can setup ERPNext locally, you can check this on the hotfix branch. If not, the changes will be live in a couple more days.

**Comment by Terencepcurtis** [comment]
@nabinhait hello, did this get approved and go live? as I dont see any changes, ?

please confirm ,

**Comment by Terencepcurtis** [comment]
@nabinhait  hello, any reply i dont see these BOM issues resolved or updated, 

please confirm ??
 





..

**Pull request closed without merging**
