### PR TITLE
fix(payments): early error if payment request is invalid

### PR DESCRIPTION
**Pull request by blaggacao**
# Context

- As a users, create a _Payment Request_ with an invalid datum in terms of the chosen payment gateway

#### Current Behaviour

- Silently, no payment url is created

#### Desired Behaviour

- The user is informed early about the invalid payment request on this particular gateway

# Proposed Solution

- Don't silence exceptions that where meant to bubble up to the user

# Impact / Migration

Calling sites which dependent on a truthy value need to be refactored and cast exceptions themselves, if that's what they want to do.

### CODE REVIEW

**Comment by blaggacao** [comment]
needs backport to v15

**Comment by blaggacao** [comment]
@s-aga-r I beleive this PR survived the refactorings unaltered.

**Comment by s-aga-r** [comment]
@blaggacao test is [failing](https://github.com/frappe/erpnext/actions/runs/6657410799/job/18092064577?pr=37503), please check

**Comment by blaggacao** [comment]
superseded by https://github.com/frappe/payments/pull/53

**Pull request closed without merging**
