### PR TITLE
Healthcare fixes

### LINKED ISSUE #11301: Permission Error when saving Consultation
save-issue

### PR DESCRIPTION
**Pull request by pjamsheer**
#11301 fix  All users with physician role can submit Consultation
fix Physcian schedule creation last time slot is missed
added Vital Signs to Patient dashboard
Allow to create Consultation, Vital Signs on Open status of Appoinment
removed Company reference from Patient document

### CODE REVIEW

**Comment by rmehta** [comment]
@pjamsheer can you add better titles please? Also some screenshots will be useful!

https://github.com/frappe/erpnext/wiki/Contribution-Guidelines

**Comment by rohitwaghchaure** [comment]
@pjamsheer 

Why save is disabled for patient appointment? Also why I can not change the patient, physician and appointment date?

**Comment by pjamsheer** [comment]
Patient Appointment is saved after "Check Availability - select time slot - "Book".
You can change the fields before you "Book".

**Comment by nabinhait** [comment]
@pjamsheer  Please send the PR to hotfix branch

**Pull request closed without merging**
