### PR TITLE
Removal of SMS Settings and SMS Parameters from ERPNext

### PR DESCRIPTION
**Pull request by ckosiegbu**
Both doctypes have now been moved to Frappe. See the conversation here: https://discuss.erpnext.com/t/two-factor-authentication/15636/7?u=chude_osiegbu

This PR is related to https://github.com/frappe/frappe/pull/3763 which contains both the introduction of Two-factor Authentication, as well as the other end of the transfer of SMS Settings and SMS Parameters from ERPNext to Frappe Core

Regards,
Manqala Team

Depends on frappe/frappe#3763

### CODE REVIEW

**Comment by tundebabzy** [comment]
@ckosiegbu
You haven't fixed Travis

**Comment by ckosiegbu** [comment]
@tundebabzy yes couldn't quite put my finger on what was wrong. Perhaps you could give some pointers.

**Comment by tundebabzy** [comment]
Travis doesn't yet know about the new sms settings in frappe. You have to wait for that to be merged first. 

Edit your first comment to point out that this PR depends on the PR that adds sms settings to frappe.

**Comment by tundebabzy** [comment]
> Edit your first comment to point out that this PR depends on the PR that adds sms settings to frappe.
I just reread and saw that you already referenced the PR

**Pull request merged**
