### PR TITLE
fix: grant commission in inter company transaction

### PR DESCRIPTION
**Pull request by khushalt**
On Inter-Company Transaction Sales Order is not fetching grant commission on the Item child table
In case of Normal Sales Order it is fetching Grant commission from Item

Because of which sales calculation is getting affected

### CODE REVIEW

**Comment by khushalt** [comment]
@deepeshgarg007 Can you please review ?

**Comment by khushalt** [comment]
@nextchamp-saqib any update on this PR?

**Comment by khushalt** [comment]
@deepeshgarg007 any upate
?

**Comment by deepeshgarg007** [comment]
This should be fixed via https://github.com/frappe/erpnext/pull/29978
Closing this PR

**Pull request closed without merging**
