### PR TITLE
fix: filter project by customer

### LINKED ISSUE #38889: Project field filters broken in all DocTypes
### Information about bug

The `project` field used to filter away "cancelled" and "closed" projects. However, now the fields show all Projects, cancelled or not. I have tested in Sales Order, Delivery Note, Purchase Order, and Purchase Receipt.
In Sales Order, there is an additional query to filter by Customer. This is also not applied. Setting this filter manually in the browser console shows the `Filters Applied for Customer = your_customer` at the bottom of the dropdown, but the actual results show all Projects regardless of Customer (or status).
The `cost_centre` field is set to automatically fetch the default Cost Centre of the Project, but this doesn't work either. 
Moreover, in Sales Order, I get notifications that the Cost Centre for each row in the `items` table has been set to the default Cost Centre of the Project, but Sales Order Item doesn't actually have a `cost_centre` field.

I have uninstalled all custom apps in case the error was introduced from elsewhere, but the error persists on a vanilla install.

All of this used to work until a while ago. I'm not sure what broke this. (Edit: I checked in an old v14 environment and it doesn't work on that too. Maybe I imagined the whole thing?)

~~Sorry for no pics. Current test environment has production data. Will upload pics asap.~~ Pics in PR

### Module

projects

### Version

erpnext 15.5.0
frappe 15.4.1
india_compliance 15.0.4 (uninstalled)
payments 0.0.1
print_designer 1.0.0
textiles 0.0.1 (uninstalled)
erpnext_plus 0.0.1 (uninstalled)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by SvbZ3r0**
fixes: #38889

### CODE REVIEW

**Comment by SvbZ3r0** [comment]
Before:

https://github.com/frappe/erpnext/assets/57280279/881594e1-c23e-48ff-8772-2429c78b6dcb

https://github.com/frappe/erpnext/assets/57280279/ed181652-056a-4dfe-b60c-728788894c5b

After:

https://github.com/frappe/erpnext/assets/57280279/9301e778-5058-42a0-a8eb-5414c22b745d

**Comment by SvbZ3r0** [comment]
Failing test doesn't look related. Please let me know if it is.

**Comment by ruthra-kumar** [comment]
Closing this PR.  Issue should partially be fixed by https://github.com/frappe/erpnext/pull/39212

set_query for 'project' at individual doctypes can be further tweaked to better handle different scenarios

**Comment by SvbZ3r0** [comment]
Hi @ruthra-kumar , issue is still present as is. The dropdown in the link shows that the customer filter is applied, but the actual results included all Projects regardless of Customer (including cancelled and completed).  Please check.

**Pull request closed without merging**
