### PR TITLE
feat: Tax Detail Report

### PR DESCRIPTION
**Pull request by nameduser0**
Tax Detail Report: Backport of #25254
See also #25884
https://github.com/frappe/erpnext_documentation/pull/322

### CODE REVIEW

**Comment by nameduser0** [comment]
@nabinhait @deepeshgarg007 Test failing due to #25884 which also needs to be backported

**Comment by deepeshgarg007** [comment]
@casesolved-co-uk Please cherry-pick that commit and add to this PR. Editing from maintainers is not allowed

**Comment by Andriesvn** [comment]
Nothing ever happened to getting this on v13?

**Comment by nameduser0** [comment]
No, frankly it suits me that they can't be bothered. I've included it in our UK module available on our hosting service.

**Comment by Andriesvn** [comment]
Sad to hear. 
Question though, How are you handling 0 value Tax detail such as 0% VAT or VAT Exempt values? Since your querying GL entries with this report and ERPNext removes 0 value GL Entries before posting them otherwise validation fails them as you can see here?
https://github.com/frappe/erpnext/blob/86ef9329797f558a4e8ec7f35a6527f86090482a/erpnext/accounts/doctype/gl_entry/gl_entry.py#L79

**Pull request closed without merging**
