### PR TITLE
fix: wrong paid and cn amount on pos invoice

### LINKED ISSUE #38130: Wrong receivables when invoice is partly paid from POS
### Information about bug

1. Create a sales invoice with `Is POS` checked
2. Partly pay it from within the invoice, ie, if the invoice total is 1000, make 100 as paid from the payments table
image

image

3. Check the AR reports
image

### Module

accounts

### Version

ERPNext: v14.48.0 (HEAD)
Frappe Framework: v14.55.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by rtdany10**
Closes https://github.com/frappe/erpnext/issues/38130

### CODE REVIEW

**Comment by rtdany10** [comment]
@ruthra-kumar @deepeshgarg007

**Comment by rtdany10** [comment]
@ruthra-kumar

**Review by ruthra-kumar — APPROVED** [review]

**Comment by rtdany10** [comment]
Looks like unrelated test failure, @ruthra-kumar

**Comment by rtdany10** [comment]
Please backport to v14, v15 also

**Pull request merged**
