### PR TITLE
Payroll Entry DocType

### PR DESCRIPTION
**Pull request by shreyashah115**
#11282 
Summary:
1. New DocType added Payroll Entry.
2. Creates salary slip on submit.
3. Submits salary slip on `Submit Salary Slip` button.
4. Can view salary slip on the basis of `posting_date` filter.
5. UI Test added.

anim

### CODE REVIEW

**Comment by dufani1** [comment]
Hii @shreyashah115 please include the following enhancement if possible
https://discuss.erpnext.com/t/payroll-enhancement/23795/2

**Comment by dufani1** [comment]
And if possible adding fillter for project.. please see the following discussion
https://discuss.erpnext.com/t/add-filter-to-process-payroll-doctype-to-filter-employees/29395/2

**Comment by shreyashah115** [comment]
@dufani1 Okay, will look into it.

**Review by nabinhait — CHANGES_REQUESTED** [review]
- Remove "Process Payroll" directory
- Write a patch to delete "Process Payroll" doctype
- Implement if any changes has been merged into "Process Payroll" after you open the pull request

**Comment by nabinhait** [comment]
@shreyashah115 Closing it for now, please add suggested changes and reopen the PR

**Pull request closed without merging**
