### PR TITLE
[enhance] UAE/KSA VAT/Excise implementation

### PR DESCRIPTION
**Pull request by rohitwaghchaure**
# VAT/EXCISE Tax Implementation for UAE/KSA

### 1. Setting up Tax Registration No for customer, supplier and company

Set tax registation number in the field tax id for the customer, supplier and company

1. For Customer
tax-id-customer

2. For Company
tax-id-company

### 2. Setting up TAX Code for Products
Setup tax code in the item master, system will fetch same code in the sales/purchase invoice on selection of an item.

tax-code-item

### 3. Default Tax Templates

ERPNext provides you default tax template for vat(5%, zero, exempted) and excise(50%, 100%). You can create your own [tax template](/docs/user/manual/en/setting-up/setting-up-taxes.html).

uae-tax-templates

### 3. Making VAT Ready Invoices

If you have setup the TRN of your Customers and Suppliers, and your tax template, you are ready to go for making VAT Ready Invoices!

For **Sales Invoice**,

1. Select the correct Customer and Item and the address where the transaction will happen.
2. Check if the TRN of your Company and Supplier have been correctly set.
3. Check if the TAX Code has been set in the Item
4. Select the  template that you have created based on the type of transaction
5. Save and Submit the Invoice

vat-invoice

### 4. Print Tax Invoice

ERPNext provides 2 default print foramt

1. Simplified Tax Invoice
simplified-invoice

2. Detailed Tax Invoice
detailed-invoice

### CODE REVIEW

**Comment by aiqual** [comment]
Are you going to implement the VAT Return report in this same pull request, or in separate one? The VAT Return report is essential for VAT filing and it is described here [UAE VAT Implementation #11632](https://github.com/frappe/erpnext/issues/11632) and in attached file. 
[VAT Return with Tooltip.pdf](https://github.com/frappe/erpnext/files/1554284/VAT.Return.with.Tooltip.pdf)

**Comment by umuhamed** [comment]
Hi , 

Is it available in production  ?
I think it is required Arabic field for item description also .

**Comment by salsugair** [comment]
Dear rohitwaghchaure,
i wanna add a complication that i noticed accountants discuss a lot.
i know this is applicable for KSA VAT
when you import products:
item iphone; unit price:1000SAR; qty:10units; total:10,000SAR; supplier:apple
you issue a payment to apple for 10,000SAR then,
clearing agent or customs handler have to clear your imported goods from customs and pay the following:
a-customs fee for electronics lets say 7% of 10,000 (this should impact item cost)
b-VAT 5% the total of customs fees (a) + vendor in (10,000SAR from apple) + any other taxes paid to customs department
c-handling fees for clearing agent work 500SAR
e-VAT on clearing agent fees 5% of 500SAR
you cannot add to supplier PO as its handled by clearing agent and the custom fees should impact the cost, and few systems handle it by allowing one PO to have multiple payments to multiple vendor ie: apple and clearing agent
im sorry if my example is not clear enough

**Comment by tundebabzy** [comment]
Hi @salsugair 
The scenario you describe is what Landed Cost Voucher is made for. See https://erpnext.org/docs/user/manual/en/stock/tools/landed-cost-voucher

**Comment by jaywks** [comment]
Where do i submit bug report for this enhancement? where Company TRN (field tax_id) no longer get fetched from Company doctype upon Sales Order creation. This happens in V12 update

**Pull request merged**
