### PR TITLE
fix: Net Weight Calculation fixed

### PR DESCRIPTION
**Pull request by vishdha**
https://github.com/frappe/erpnext/issues/34835

Before:

https://user-images.githubusercontent.com/6947417/231734164-a4640a40-bc2c-4fa4-9954-4c4c4a6e80ef.mp4

After:

https://user-images.githubusercontent.com/6947417/231734145-61d50f0e-aab4-4802-8920-7c583c337be1.mp4

### CODE REVIEW

**Comment by vishdha** [comment]
Backport to Version14

**Comment by deepeshgarg007** [comment]
@vishdha Can you please also add a test case for this so that this scenario is not missed again

**Comment by deepeshgarg007** [comment]
Also a lot of test case failing with this

**Comment by deepeshgarg007** [comment]
@vishdha Have reverted the changes in https://github.com/frappe/erpnext/pull/34847
Closing this PR

**Comment by vishdha** [comment]
Thanks

**Pull request closed without merging**
