### PR TITLE
New manufacturer logic

### PR DESCRIPTION
**Pull request by dottenbr**
I have changed the data fields to links which is important for
manufacturing business to keep the manufacturers and manufacturer part
numbers consistent.

To be checked by Frappe before merge:
- [ ] Please make the Manufacturer Part Number selection dependant on
  the Manufacturer that the user has selected.
- [ ] If user clicks "New Manufacturer Part Number", could you read the
  part number that was selected before?
- [ ] Can we show the associated Item Manufacturer Aliase's in the Item
  Manufactuerer page or is this only for reports?
- [ ] Can we show the associated Item Manufacturer Part No in the Item
  Manufactuer page or again reporting?

### CODE REVIEW

**Comment by rmehta** [comment]
@dottenbr will you be able to close this?

**Comment by dottenbr** [comment]
@rmehta again this should be discussed again. I believe that this is a logical approach for most companies to use this way.

**Comment by rmehta** [comment]
@dottenbr  can you spec this in a clear way?

**Comment by dottenbr** [comment]
Lets drop this for now in favor of "manufacturer-item" pull request.

**Pull request closed without merging**
