### PR TITLE
feat: Accounting entries for service item in Purchase receipt

### PR DESCRIPTION
**Pull request by deepeshgarg007**
Enable Perpetual Inventory for Service Items
Screenshot 2020-06-20 at 11 53 43 AM

Select Default Account for "Service Received But Not Billed" in company master
Screenshot 2020-06-12 at 6 37 11 PM

Purchase Receipt Posting
image

Invoice Posting
image

### CODE REVIEW

**Comment by deepeshgarg007** [comment]
@Mergifyio backport version-13-beta-prerelease

**Comment by rohitwaghchaure** [comment]
@deepeshgarg007  Enable Perpetual Inventory for Service Items checkbox should be in the company. There might be chances that user wants to enable this feature for some company and not all

**Comment by rohitwaghchaure** [comment]
@deepesh Enable Perpetual Inventory for Service Items checkbox should be in the company. There might be chances that user wants to enable this feature for some company and not all

**Review by rohitwaghchaure — APPROVED** [review]

**Comment by deepeshgarg007** [comment]
@Mergifyio backport version-13-beta-pre-release

**Comment by TamerAkram** [comment]
Why not make a payment and a sales invoice and a purchase invoice on the income and expenses accounts without item?
Then it is possible to open many features in the system, especially in non-profit and semi-profitable establishments

**Comment by jigneshpshah** [comment]
@TamerAkram , i hope you are aware , you can do so without choosing/linking to any Item and just put Item Name (text field).

**Pull request merged**
