### PR TITLE
[Enhancement]after PO submitted, still allow change item quantity and price without cancelling the PO

### PR DESCRIPTION
**Pull request by szufisher**
erpnext 2
New feature:
As is : After purchase order submitted, without cancelling the PO first, it is not allowed to change the item quantity and price anymore, if there are linked purchase receipt and invoice etc, especially in closed periods, the cancelling of the linked documents is tedious and sometimes impossible. for further changes to be made, another purchase order to be created instead.

To Be: 

- Setting:
 from the buying setting, there are 2 more options available which enable the administrator to control: activate or deactivate allowing item quantity and price change after submit, in essence the program updated the DocField doctype to activate allow_on_submit for relevant fields in purchase order, purchase order item, purchase taxes and charges.

-  Usage
if activated this feature, then the purchase order can be changed even after submitted and associated with other linked documents e.g purchase receipt and purchase invoices, 
      - new item can be added, 
       - item quantity can be changed, but with restrictions:  quantity after change can not be less than received quantity,
      - item can not be deleted if there are already linked purchase receipt.

### CODE REVIEW

**Comment by szufisher** [comment]
the build failure log indicates  from frappe.desk.page.chat.chat import post
ImportError: No module named chat.chat,
which I can not fix by by myself, anyone can help?

**Comment by manassolanki** [comment]
Have you updated your frappe repo before build?

**Comment by snvora** [comment]
+1

This feature is significant, as core changes may be required, so it's better if it can be easily extended.

Suggestion:
Additional fields in "DocField" (table of doctype or/and customise form table) like
- Allow amend
- Validation's for amend

could make it global for all documents, and extra validations where required could be added.

Other checks like "cannot delete linked item" as you have worked on are good.

**Comment by rmehta** [comment]
@szufisher sorry for the late review. Can you rebase and reopen the PR?

Also explain how are you handling the additional items? Please explain this in your description.

**Pull request closed without merging**
