### PR TITLE
feat(hr): multiple shift v13

### PR DESCRIPTION
**Pull request by alaa-alsalehi**
We need to add multiple shifts to v13 we copy these modifications from [this PR](https://github.com/frappe/erpnext/pull/29955) we fix different issues in dependencies, tests and python old version and be sure the test cases work fine
this is the same description of the original PR
### What Changes?
**Schedule multiple shifts**

- Users can make multiple non-overlapping Shift Assignments for the same employee on the same day

### Shift Request

- Users can make multiple non-overlapping Shift Requests for the same employee on the same day

### Fetching shift in Employee Check In

- When employee check-ins are logged via biometric or manually, the exact shift based on the timestamp is fetched. Before, shifts used to be fetched based on date. Now they are timestamp specific.
- Handles shifts spanning over 2 different days (eg: 23:00 - 2:00), midnight shifts.
- Shift fetching used to fail on timing boundaries, this is fixed.
- Handles 2 consecutive shifts if they are overlapping within grace periods.

### Attendance

- Earlier, only 1 attendance record could be marked for 1 day.
- Now multiple attendance records can be marked for each shift. Eg: an employee can be absent for one shift, present for another on the same day
- Auto Attendance now, takes care of marking shift-specific attendance and not for the whole day
- Earlier, employees with no attendance records on a specific date used to be marked absent via Auto Attendance. Now, this also checks for shift-wise attendance records along with the date. So, only if attendance is not marked for a particular shift/for the whole day, the employee will be marked absent.

### Attendance Reports

- Added shift-wise attendance against employees
- Added legend for status abbr with full form and color.
- Formatter for data to quickly identify cells with lesser cognitive load.
- Refactored Monthly Attendance Sheet code. Can still be better but will leave it for the next iteration.

### CODE REVIEW

**Comment by alaa-alsalehi** [comment]
@ruchamahabal if we rebase it to hotfix there is a chance to accept it if yes we will do it

**Comment by ruchamahabal** [comment]
@ServeMe Since v14 has been released as a major version, we won't be adding or backporting any features to v13. Only fixes will go in for v13. This feature was specifically developed for v14 only.

**Comment by alaa-alsalehi** [comment]
@ruchamahabal I am aware of this rule but we have a need to add it for this release. Any suggestion on how we can do that without breaking the cycle?
we currently have a fork of ERPNext and we merge on it any other suggestions?

**Comment by ruchamahabal** [comment]
@ServeMe Yes, you can either add this feature to your fork or simply upgrade to v14 (better in terms of future maintenance) after assessing the breaking changes

https://github.com/frappe/erpnext/wiki/Migration-Guide-to-ERPNext-version-14

**Pull request closed without merging**
