### PR TITLE
WIP: Alternative BOM Lines

### PR DESCRIPTION
**Pull request by kickapoo**
This the initial Add Alternative Item under Manufacturing Section in Item Doctype.
 It based on community design proposal by newmatik team. (https://discuss.erpnext.com/t/new-feature-bom-components-alternative/31915)

Please help me to make the child table more readable to end users:
https://discuss.erpnext.com/t/contribution-help-for-alternative-bom-lines-change-link-field-display-look/32444

screenshot 2018-01-12 10 45 42

screenshot 2018-01-12 10 45 17

screenshot 2018-01-12 10 44 09

TODO for [Level 1 - Data entry setup]

- [x] An alternative can be a “Two-way” or a “one-way” type. “Two-way” alternative means the parent component is also an alternative of the set alternative items. If it is a “One-way” type, the parent Item is not an alternative of the set alternative item.  A script must be added in Item Doctype "On Save" to handle this.
- [x] Add Naming Series
- [x] Sync List deleting with Two-Way
- [x] Change Table Naming following the Frappe Guidelines.
- [ ] Unit Tests @creamdory 

TODO for [Level 2 - "BOM" Alternative Set-up]

- [ ] If Item select check if Alternative exists and denote row
- [ ] (not final) Set option in bom "with Alternative" so the above validation is valid
- [ ]  List alternative item options in child table

### CODE REVIEW

**Comment by kickapoo** [comment]
@creamdory Please keep track of this.

**Comment by kickapoo** [comment]
@creamdory  Please start pinging pple from community that have interest on this.

**Comment by creamdory** [comment]
@kickapoo , I have made a comment in my previous post here https://discuss.erpnext.com/t/new-feature-bom-components-alternative/31915/2

**Comment by rmehta** [comment]
"Item Alternatives". Please check https://github.com/frappe/erpnext/wiki/Naming-Guidelines

DocType names must be singular!

**Comment by kickapoo** [comment]
Ty @rmehta for your comment. 

I used plural to this one because its a intermediate table (Many-to-Many holder) to Item Alternative. 

What naming do you suggest ?

Currently I have, 
 - Item Alternatives , tables holding Link to Item and Table to Item Alternative.

**Comment by joezsweet** [comment]
would this work for manufacture domain only? ..i mean would be nice to have item alternative in retail as well ..so that if item is not available, the alternative would be ordered ..

**Comment by kickapoo** [comment]
due other work assigned to me, I am currently inactive for this PR

**Comment by leonpollak** [comment]
Please, why the PR is closed without merging?
It is very required feature in the manufacturing process...

**Comment by creamdory** [comment]
Hi @leonpollak , please follow this PR. https://github.com/frappe/erpnext/pull/13121

**Comment by mallesree** [comment]
Any help how to use this feature if exists?

**Pull request closed without merging**
