### PR TITLE
Once primary key is generated, do not allow changing Series #8911

### PR DESCRIPTION
**Pull request by tundebabzy**
DocFields containing `naming_series` are presently have `set_only_once`as 0. Instead of adding more LOC, I think it's a better and easier option to set the `DocFields` with `naming_series` having `set_only_once` to 1.

### Before
peek 2017-06-10 13-57

### After
peek 2017-06-12 14-18

### CODE REVIEW

**Comment by mbauskar** [comment]
@tundebabzy,

You will need to set the set_only_once field for all the doctype containing the field `naming_series`.

Closing the PR for now please reopen the once done.

**Comment by tundebabzy** [comment]
@mbauskar 
The query does that and affects 46 Doctypes. `tabDocType` doesn't have fields `naming_series` and `set_only_once`.

**Comment by rmehta** [comment]
@tundebabzy you need to update all the relevant JSON files otherwise it will not work for new installs. The patches don't run on fresh installs.

**Comment by tundebabzy** [comment]
I forgot to update erpnext/patches.txt and that's probably why the tests were failing.

**Comment by tundebabzy** [comment]
> @tundebabzy you need to update all the relevant JSON files otherwise it will not work for new installs. The patches don't run on fresh installs.

Oh ok. Will work on that now.

**Comment by rmehta** [comment]
quick way of doing that is via a simple python script :)
```
for d in frappe.db.sql('select parent from tabDocField where fieldname="naming_series"):
  doctype = frappe.get_doc('DocType', d[0])
  for f in doctype.fields:
    if f.fieldname=='naming_series': f.set_only_once = 1
    doctype.save()
```

**Comment by mbauskar** [comment]
@tundebabzy, can you rebase and push the changes again?

Please reopen the PR once conflicts are removed

**Comment by tundebabzy** [comment]
My branch for this pull was based on hotfix. Accidentally pushed it to develop and that's the reason for the conflicts. The rebase is now very ugly so i'll squash the changes and push them in a new PR

**Pull request closed without merging**
