### PR TITLE
[ Minor] Fix Events deletion

### PR DESCRIPTION
**Pull request by Zlash65**
Before - 
issue-event

After -
fix-event

### CODE REVIEW

**Comment by Yemeni** [comment]
Is it a fix for this?
https://github.com/frappe/erpnext/issues/15846

**Comment by Zlash65** [comment]
@Yemeni Wasn't able to replicate the issue. But the fix that i sent could have caused trouble nonetheless if left unchecked.

**Comment by rmehta** [comment]
Should this not be in the framework?

**Comment by nabinhait** [comment]
@Zlash65 Yes, move to the frappe

**Comment by sagarvora** [comment]
Closing, to be moved.

**Pull request closed without merging**
