### PR TITLE
    fix: date validation on inpatient record, else condition removing on clinical prod template which is not req

### PR DESCRIPTION
**Pull request by khushalti**
> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

### CODE REVIEW

**Comment by khushalti** [comment]
@deepeshgarg007

**Comment by khushalti** [comment]
any updates? @deepeshgarg007 @nabinhait

**Comment by khushalti** [comment]
@rmehta @nabinhait @deepeshgarg007 any updates on this PR

**Review by pjamsheer — APPROVED** [review]

**Review by nabinhait — APPROVED** [review]

**Comment by khushalti** [comment]
Thanks

**Pull request merged**
