### PR TITLE
fix(regional): DATEV report

### PR DESCRIPTION
**Pull request by barredterra**
- Explicitly set width of report view columns.
- Move some queries from `get_header` into `download_datev_csv` to execute them only once instead of 4 times.
- Distinguish between company and individual in Customer/Supplier data.
- Export only accounts with a number. Truncate account name to max lenth allowed by DATEV.
- Calculate max length of account numbers (was previously fixed to 4).

The files generated with this code have successfully passed the DATEV verification software.

### CODE REVIEW

**Comment by barredterra** [comment]
Travis doesn't fail because of this pull request. It's some problem with the travis setup for python 2.7.

**Comment by barredterra** [comment]
@nabinhait it would be great if this could still make it into version-13 :)

**Comment by deepeshgarg007** [comment]
@barredterra can you update the PR or raise a new PR on the latest develop branch. We cannot update this PR from our side

**Comment by barredterra** [comment]
Done, @deepeshgarg007

**Review by deepeshgarg007 — APPROVED** [review]

**Comment by deepeshgarg007** [comment]
@Mergifyio backport version-13-beta-pre-release

**Pull request merged**
