### PR TITLE
Ability to hold payment for disputed invoices #12048

### LINKED ISSUE #1204: POS - Allow multiple mode of payment in POS Invoice
Allow multiple mode of payment in POS Invoice.

<bountysource-plugin>

---
Want to back this issue? **[Place a bounty on it!](https://www.bountysource.com/issues/1362387-pos-allow-multiple-mode-of-payment-in-pos-invoice?utm_campaign=plugin&utm_content=tracker%2F266088&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F266088&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #12048: Ability to hold payment for disputed invoices
Hello Team

This is regarding ability to hold payment for specific purchase invoice.

Dispute on purchase invoice could arise for many reasons
- Charged different rates than agreed
- Not good quality material and deduction of amount for penalty
- Rejection of some material on quality check. ( Also debit note not raised as it is responsibility of supplier to collect rejected material, which he has not done so far)
- Quantity received does not match. (Happens generally where material is received in Kgs).
- Non fulfillment of post delivery conditions and charge for penalty etc.

We cannot postpone booking of invoices, as it would lead to lots of unaccounted invoices, and tax reports generated would not be accurate. 

Also some payments may be required to put on hold after they have been entered in system.

Implementation of new feature could be as follows
- Hold payment for any purchase invoice. -->Give brief description for reason why payment is put on hold --> how much amount is put on hold --> Optionally hold all payment against supplier (say for legal non-compliances) --> Convey to supplier
- Amount due = Total invoice amount - Amount put on hold (for payment entry) .
- Accounts payable report to show amount put on hold.
- Release Invoice after matter under dispute is resolved --> short description of resolution --> Charge penalty and reduce amount due to that extent --> Convey to supplier

Thanks..:-)

### PR DESCRIPTION
**Pull request by tundebabzy**
Closes #12048

purchase-invoice-hold

##### Set A Release Date
peek 2018-03-13 23-37

##### In Supplier Master
screenshot-2018-3-13 dangote foods - dangote foods

##### Invoices and/or Payment Entry not allowed
peek 2018-03-13 23-46

### CODE REVIEW

**Comment by snvora** [comment]
Hi @tundebabzy 

Great efforts. Thanks:-)
I would like to add as follows:
- If invoice on hold --> Payment entry showing no invoices. It may give a wrong impression that no invoice is due. Instead how about indicating invoice is on hold?
- Invoice clearance may be dependent on quality/accounts clearance (rather than particular date). Instead how about assigning specific people to release invoice (with permission to do that)?
- Also to separately identify invoices, how about changing the status of an invoice to "On Hold"?
- Have you thought about invoice partially on hold?

Issue #12048

**Comment by tundebabzy** [comment]
> If invoice on hold --> Payment entry showing no invoices. It may give a wrong impression that no invoice is due. Instead how about indicating invoice is on hold?

I think it's counter-intuitive to add documents to the reference table if it's not going to be paid. The table should only contain documents for payment. However, in both Supplier and Purchase Invoice Order list view, the status will be 'On Hold'

> Invoice clearance may be dependent on quality/accounts clearance (rather than particular date). Instead how about assigning specific people to release invoice (with permission to do that)?

The release date and comment fields can be customised such that they will only be visible to certain users by tweaking Perm Level in Role Permission Manager. However, in addition to date span holds, I think it makes sense to add explicit hold, just like I did in Supplier master

> Also to separately identify invoices, how about changing the status of an invoice to "On Hold"?

Will be implemented

> Have you thought about invoice partially on hold?

Yes. But I'm not motivated to give it a try. My gut tells me it will involve complexity and I don't want to be that guy

**Comment by snvora** [comment]
>  it's counter-intuitive to add documents to the reference table

Agreed

> tweaking Perm Level in Role Permission Manager

Great Idea.

> However, in addition to date span holds, I think it makes sense to add explicit hold, just like I did in Supplier master

Exactly. Sounds Good.

**Comment by tundebabzy** [comment]
### Explicit block
peek 2018-03-15 12-30

### Date Span Block
peek 2018-03-15 12-31

### Purchase Invoice list
screenshot-2018-3-15 purchase invoice

### Supplier list
screenshot-2018-3-15 supplier

**Pull request merged**
