### PR TITLE
fix(ux): change batch selection message to alert

### PR DESCRIPTION
**Pull request by rtdany10**
Batch not found msgprint to alert if not for throw

### CODE REVIEW

**Comment by rtdany10** [comment]
@s-aga-r seems like the function is getting called multiple times? There are 2 alert box on screen for a single item.

**Comment by rtdany10** [comment]
I guess a better solution would be to add a checkbox in Stock Settings to enable auto batch picking. Thoughts?

**Comment by s-aga-r** [comment]
> I guess a better solution would be to add a checkbox in Stock Settings to enable auto batch picking. Thoughts?

Already added in v15 (for Serial and Batch Bundle)

**Comment by rtdany10** [comment]
How about not displaying the message if `throw` is false?

**Comment by rtdany10** [comment]
@s-aga-r please merge this for now

**Comment by s-aga-r** [comment]
@rtdany10 please make sure to raise PR in the hotfix branch next time.

**Comment by ankush** [comment]
@rtdany10 / @s-aga-r don't release changes like this. 

You can copy PR to hotfix if it's required by doing `@mergify copy branch`

**Comment by rtdany10** [comment]
My bad, will be careful next time

**Pull request merged**
