### PR TITLE
Default batch number selection

### LINKED ISSUE #10562: Default batch number selection
How can we use the FIFO method for batch number while doing the sales invoice? 

Current Scenario:
In case of Pharma/FMCG vertical, complete purchase and sales is dependent on batch and expiry date. Currently, ERPNext have the provision to setup batch number against each item while receiving the product. So from purchase perspective this is good. While doing sales invoice, we have to manually select the batch and add the quantity in it.

Expected Scenario:
While doing the sales invoice, item should automatically fetch the batches as per FIFO method. In case if the first available batch have less quantity it should pickup next available batch and so on. 

Can we do this?

### PR DESCRIPTION
**Pull request by tundebabzy**
Fixed #10562 #11447 

It is a standard and wise practice for those selling items with batches to use First Expiring First Out (FEFO) which is a variant of FIFO just that earliest item to expire is given priority. This avoids the seller having expired stock or obsolete items.

This PR changes ERPNext present behaviour when it comes to auto-fetching batch numbers. In sales invoice, the batch number is not fetched. In other places, it returns the smallest batch that can fulfil the order.

### Before
screenshot from 2017-11-04 22-08-35

### After
screenshot from 2017-11-04 22-01-51

### CODE REVIEW

**Review by nabinhait — CHANGES_REQUESTED** [review]
`transaction.js` is inherited in both selling and buying cycle. But `set_batch_number` should only be called in selling cycle, more specifically in DN and sales invoice (only if update_stock is checked)

Also same functionality should be implemented for `stock_entry.js`, it does not inherit `transaction.js`.

**Comment by tundebabzy** [comment]
`stock_entry.js` calls `erpnext.stock.get_item_details.get_batch_no` directly so it's already taken care of

**Comment by nabinhait** [comment]
@tundebabzy I did not find the call. Can you send the link of github?

**Comment by tundebabzy** [comment]
There is something wrong with the batch selector dialog. It's either the stock entry requirement is added in a separate PR or we fix the selector dialog first.

peek 2017-11-20 15-54

**Comment by tundebabzy** [comment]
Dialog selector fixed in frappe/frappe#4517. Awaiting merge

**Comment by tundebabzy** [comment]
@nabinhait Stock entry presents a batch selector dialog immediately after an Item with has_batch:1 is set. With this work flow, there's no clean way to add batch number automatically as the batch selector is shown before the user has a chance to specify quantity.

That said, I think we can push this and then work on auto fetching into the batch selector dialog in a fresh issue.

**Comment by tundebabzy** [comment]
#11004 for auto fetching batches in batch selector

**Review by nabinhait — APPROVED** [review]

**Comment by elvise** [comment]
@tundebabzy i'm really interested to batch based fifo do you have any planning about this point ?

**Pull request merged**
