### PR TITLE
fix: specify precision for net_amount

### PR DESCRIPTION
**Pull request by rtdany10**
Continuation of https://github.com/frappe/erpnext/pull/38141
Removed optional grand total adjustment functionality, rather it is always adjusted for inclusive taxes.

### CODE REVIEW

**Comment by rtdany10** [comment]
@deepeshgarg007

**Comment by rtdany10** [comment]
@deepeshgarg007

**Comment by rtdany10** [comment]
@deepeshgarg007

**Comment by rtdany10** [comment]
Hi @deepeshgarg007, why defer backport?

**Comment by ruthra-kumar** [comment]
Checking feasibility of backporting this to v14.

**Pull request merged**
