### PR TITLE
feat(Print Format): KSA VAT Invoice

### PR DESCRIPTION
**Pull request by ahmadpak**
Continuation of the KSA VAT feature. New print format for KSAVAT

image

`no-docs`

### CODE REVIEW

**Comment by mhbu50** [comment]
- include TAX ID for both (Customer/Supplier) and the company
- Remove Green color for headers

**Comment by ahmadpak** [comment]
@mhbu50 Tax Identification Numbers will show up if added. 
image

**Comment by deepeshgarg007** [comment]
@Mergifyio backport version-13-hotfix

**Comment by deepeshgarg007** [comment]
@Mergifyio backport version-13-pre-release

**Pull request merged**
