### PR TITLE
fix: Hero Slider Control & Alignment fixes

### PR DESCRIPTION
**Pull request by shariquerik**
**Issue:**
1. When a user tries to change an image using the slider left-right controls, it doesn't work.
2. The Title, Subtitle, Action Button Alignment is below the Slider Controls.

**Cause:**
In the current hero slider HTML, the slider has an `id` attribute which is set as `slider_name`.
Now if the slider name doesn't have any space (e.g. SliderName) in it then the left-right controls work, but if the slider name has space (e.g Slider Name) it doesn't work.

**Solution:**
Creating a unique hash for slider and setting it as `id` instead of `slider_name`

**CONTROLS**
**Before:**
SliderBug

**After:**
SliderFixed

**ALIGNMENT**
**Before:**
image

**After:**
image

### CODE REVIEW

**Comment by harshit-30** [comment]
@shariquerik @marination please review this at your earliest, we need to release this in our next release. 

@shariquerik please do check, if the buttons **(Primary Button)** work properly after the fix.

**Comment by shariquerik** [comment]
> @shariquerik please do check, if the buttons **(Primary Button)** work properly after the fix.

Yes, primary button works fine after the fix, I have tested.

**Review by marination — APPROVED** [review]

**Comment by marination** [comment]
@Mergifyio backport version-13-hotfix

**Comment by marination** [comment]
@Mergifyio backport version-13-pre-release

**Pull request merged**
