### PR TITLE
fix: Allow backdated discharge for inpatient

### PR DESCRIPTION
**Pull request by mujeerhashmi**
The system is not flexible enough to allow backdated patient discharge.

Signed-off-by: Syed Mujeer Hashmi <mujeerhashmi@4csolutions.in>

### CODE REVIEW

**Comment by mujeerhashmi** [comment]
@ruchamahabal please review

**Comment by mujeerhashmi** [comment]
@ruchamahabal Please can we get this merged?

**Comment by mujeerhashmi** [comment]
Keep alive

**Comment by mujeerhashmi** [comment]
@ChillarAnand kindly check this.

**Review by ChillarAnand — APPROVED** [review]

**Comment by ChillarAnand** [comment]
@mujeerhashmi Build is failing. Can you please take a look?

**Comment by mujeerhashmi** [comment]
@ChillarAnand @ruchamahabal  I have fixed the tests and formatting issues. The test cases failing are not related to this patch. Kindly review and merge

**Review by pateljannat — APPROVED** [review]

**Comment by ruchamahabal** [comment]
Medical Department related Patient Appointment test fixed in: https://github.com/frappe/erpnext/pull/27100

**Pull request merged**
