### PR TITLE
Payment terms

### PR DESCRIPTION
**Pull request by tundebabzy**
Todo:
- [x] Payment Term
	- [x] Add validations
        - [x] Test cases Quotes
        - [x] Test cases Sales Order
        - [x] Test cases Sales Invoice
        - [x] Test cases Purchase Order
        - [x] Test cases Purchase Invoice
        - [x] Test Supplier
        - [x] Test Customer
- [x] Payment Terms Template
- [x] Payment Terms Template Detail
- [x] Payment Schedule
	- [x] On selection of Payment Terms Template link, fetch all the terms
	- [x] calculate due dates
	- [x] calculate payment amount
	- [x] on submission, make GLE based on due dates
	- [x] add due_date field in GLE
	- [x] If there is one due date, set it in parent and copy it to the child table
	- [x] If parent due_date is not present, set last due_date as parent due_date
	- [x] Add payment schedule in Quote/SO/SI/PI/PO

Payment Entry
- [x] Fetch outstanding invoices as per due_date in a separate row
- [x] Add due_date in reference table
- [x] post due_date in GLE

Journal Entry
- [x] Make payment entry via Journal Entry, multiple rows based on due dates
- [x] Add due_date field in child table
- [x] Post due_date to GLE
- [ ] Check Payment Entry against Sales/Purchase Order

AR/AP report
- [x] Show ageing based on multiple due dates

Patch
- [x] Create Payment Term and Payment Terms Template based on existing Customer/Supplier Credit Days
- [x] Set default Payment Terms Template in customer/supplier
- [x] Set Payment Schedule table based on parent due_date
- [x] Set due_date in existing GLE
- [x] Set due_date in Journal Entry child table

- [x] Documentation

### CODE REVIEW

**Comment by joolsr** [comment]
@tundebabzy I really need your new Payment Terms which looks great by the way. Any idea roughly when thsi will be completed and into Master ? Otherwise I may have to add back in my custom payment fields for the time being

**Comment by tundebabzy** [comment]
@joolsr Targeted ETA is before September 1

**Comment by joolsr** [comment]
@tundebabzy That's great ! Is that for completion into Develop rather than Master? Sounds like it should be fine for me anyway . Great news

**Comment by tundebabzy** [comment]
@joolsr that will be completion into develop.

**Comment by somicoito** [comment]
really really happy for this new feature!!!

**Comment by giuseppelamatrice** [comment]
Where is the problem on this pull? Can I help you?

**Comment by tundebabzy** [comment]
Honestly, I have no idea. Test cases are passing locally but failing on Travis. 
79f9a4a is the commit that completes the job and the last one that passed on Travis.

**Comment by giuseppelamatrice** [comment]
Can we discuss on Skype? my address is giuseppe.lamatrice@hotmail.it

**Comment by knckrz** [comment]
@tundebabzy Great stuff! Looking forward for this feature. Can't proceed with Erpnext without this. Any idea when will this be available?

**Comment by knckrz** [comment]
Guys, any love for this? For all the effort exerted, this might get buried :(

**Comment by tundebabzy** [comment]
No it won't. It'll get merged :)

**Comment by somicoito** [comment]
YEEEEEEEE

**Comment by knckrz** [comment]
Is this really it guys??

**Comment by FredericLeuba** [comment]
Hello,
I update bench to develop branch but cannot find anything about these changes.
Can you tell me how to use this new stuff to having several invoices for one SO?
regards
Frédéric

**Comment by tundebabzy** [comment]
Thanks for using ERPNext @FredericLeuba. It has not yet been released. It will in a couple of days

**Comment by giuseppelamatrice** [comment]
@tundebabzy MULTIPLE DUE DATE based on payment terms template are calculated on sales invoice OR saved in database table?

**Comment by ahmad18189** [comment]
Any Updates?

**Comment by rebin2002** [comment]
@nabinhait @tundebabzy @giuseppelamatrice 
Any update for these payment terms? also my case is explained in #15831

**Comment by giuseppelamatrice** [comment]
I don't have any idea. Is under develop version

**Comment by sanath2020** [comment]
Any one have a clue that multiple due dates are working in version 11??

**Pull request merged**
