### PR TITLE
fix: serial no material transfer performance issue

### PR DESCRIPTION
**Pull request by rohitwaghchaure**
**Issue**

Material transfer entry with 882 serials nos taking  more than 3 minutes to submit the stock entry

Screenshot 2020-02-25 at 4 00 50 PM

**After Fix**
Taking 30 seconds to submit stock entry

Screenshot 2020-02-25 at 3 31 35 PM

### CODE REVIEW

**Comment by Alchez** [comment]
Awesome! Can we also add in a progress bar? 30 seconds is still too long if there's no feedback at all that something's going on. Even a simple "Transferring serialized items..." or something should work fine, I think.

**Comment by rohitwaghchaure** [comment]
Able to optimize up-to 16 seconds

Screenshot 2020-02-26 at 12 48 13 PM

**Comment by rohitwaghchaure** [comment]
11 Seconds 
Screenshot 2020-02-26 at 1 11 03 PM

**Review by nabinhait — APPROVED** [review]

**Comment by nabinhait** [comment]
@rohitwaghchaure Please send another PR for develop branch

**Pull request merged**
