### PR TITLE
feat: salary extension point column

### PR DESCRIPTION
**Pull request by blaggacao**
Useful for localizations.

### CODE REVIEW

**Comment by blaggacao** [comment]
This is useful and a small and relatively risk-free addition and should not be closed.

**Comment by blaggacao** [comment]
ping

**Comment by blaggacao** [comment]
> Go for it now. The future is promised to no one.   - Wayne Dyer

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> Fears are nothing more than a state of mind.   - Napoleon Hill 

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> What the caterpillar calls the end of the world, the master calls a butterfly.  - Richard Bach

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> Watch your thoughts, they become your words Watch your words, they become your actions Watch your actions, they become your habits Watch your habits, they become your character Watch your character, it becomes your destiny.  - 

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by ruthra-kumar** [comment]
What sort of localization do you infer here?

**Comment by blaggacao** [comment]
## PR Status Update

Upon reflection, I've come to the following conclusion:

1. **Original Intent Unclear**: I'm unable to accurately recall or reconstruct the reasoning behind this PR's creation.

2. **Diminished Importance**: The initial urgency or significance of this change appears to have decreased over time.

3. **Lack of Context**: Without a clear understanding of the original goal, it's challenging to proceed effectively.

## Next Steps

Given these circumstances, I propose the following course of action:

1. **Closing Current PR**: I will close this pull request for now.

2. **Future Reconsideration**: If the need for this change becomes apparent again, I'll open a new PR.

3. **Improved Documentation**: In the event of reopening, I'll ensure to provide comprehensive context and clearly state the objectives to avoid similar uncertainty in the future.

Thank you for your understanding and review of this pull request.

**Pull request closed without merging**
