### PR TITLE
chore: remove use of __future__

### PR DESCRIPTION
**Pull request by ankush**
Removed major lines importing `__future__` using sed:

```bash
sed -i '/^from __future__ import unicode_literals$/d' **/*.py
sed -i '/^from __future__ import unicode_literals, print_function$/d' **/*.py
sed -i '/^from __future__ import print_function, unicode_literals$/d' **/*.py
```

Manually removed remaining ones.

Removing UTF-8 declarations:

```bash
sed -i  '/^# -\*- coding: utf-8 -\*-$/d' **/*.py
```

### CODE REVIEW

**Comment by ankush** [comment]
"+2" changes are new lines at end of 2 files I had to edit manually.

**Comment by ankush** [comment]
Note to anyone who wants to review this. You can't review this manually or in browser tab (browser will most likely crash while viewing diff)


```
git checkout -b ankush-remove_future develop
git pull https://github.com/ankush/erpnext.git remove_future

git diff --unified=0 HEAD~ | grep '^[+-]' | grep -Ev '^(--- a/|\+\+\+ b/)' | grep -v "__future__"
```

This will show all changed lines that don't contain `__future__`.

**Comment by ankush** [comment]
Most test failures seem unrelated to this PR, same errors in other PR to `develop`: https://github.com/frappe/erpnext/pull/25877/checks?check_run_id=2696737342

**Comment by gavindsouza** [comment]
1. We can get rid of the `# -*- coding: utf-8 -*-` line too on the first line of the `.py` files too.
2. Does this PR get rid of `past` library imports too? They're a part of the `future` package.
3. Might as well replace remove other `six` and `PY2` code too while you're doing this?

**Comment by ankush** [comment]
1. Can do it, some editors rely on it, but I guess it's fine to remove it now.
2. Didn't know `past` was part of the future package. 🤯   There are 3-4 instances of its usage, will remove it in a separate commit.
3. Removing six is a lot of manual work for changes and review too, will do it module wise and in separate PRs.

**Pull request closed without merging**
