### PR TITLE
fix: 'Warehouse' filter in the Stock Ledger report

### PR DESCRIPTION
**Pull request by Mitchy25**
The SQL was formed incorrectly.

### CODE REVIEW

**Review by nabinhait — COMMENTED** [review]
@Mitchy25 What was the problem with existing query? 
Even if you refactor using new approach, then you have to use `warehouse in ()` instead of `warehouse = ()`, to handle group warehouse filter. And `in` becomes very slow if there are huge number of children of that group warehouse.

**Comment by Mitchy25** [comment]
Hi @nabinhait,

The original filter didn’t actually filter by warehouse. It instead returned all warehouses. This fixes the filter logic

**Comment by Mitchy25** [comment]
Previous code didnt set the field name 'warehouse' equal to the SQL return. So the SQL returned but didnt change the row return.

**Review by nabinhait — COMMENTED** [review]
I can't replicate the issue of filtering by warehouse. Please check attached GIF. Closing the pull request.
stock-ledger-warehouse-filter

**Pull request closed without merging**
