### PR TITLE
Advance payment patch

### PR DESCRIPTION
**Pull request by Olawale1**
Hi @rmehta 

Trust you're doing great. I've added all the basic components for the Advance Payment functionality

Changes to PY file:

1. Added whitelist method for creating Advance Payment entry 
2. Added whitelist method for calculating Total Advance Paid 

Changes to JS file:

1. Added script and made relevant changes for Advance Payment button
2. Added script for calling Total Advance Paid method
3. Added script to auto-fetch Default Advance Account from Company master

Changes to JSON file:

1. Added field for Default Advance Account in Company master
2. Added field for Advance Payment Required in Expense Claim form
3. Added field for Total Advance Paid in Expense Claim form

Changes to Documentation

1. Added 'Managing Advance Payments' section to the Expense Claim documentation

Screenshots of End Results:

company_advance_account

advance_payment_required

make_advance_payment

advance payment patch2

advance payment patch3

Thanks

Kind regards,

### CODE REVIEW

**Comment by ckosiegbu** [comment]
Hi @Olawale1 

I think this is quite interesting. I have a question on the last screenshot though. When that journal is posted, does it carry information on the Employee Account? By this I mean, If after posting this advance, I were to run the general ledger report, would I be able to attribute the balance to the 3rd party (in this case the employee) under Party Type and Party?

A generalised way to handle the issue of advances for all types of 3rd parties could be to have, in the masters for all Balance Sheet Accounts, a field that links to "Account for Advances". That way, whenever you click "Make Advance Payment", that account is used in the posting instead of the main Creditors/Debtors reconciliation account.

Regards,
Chude

**Comment by rmehta** [comment]
@Olawale1 Please don't tag me directly. There are many devs who check PRs. Thanks!

**Comment by Olawale1** [comment]
Hi @rmehta 

Trust you're doing great. Sorry about tagging, I did that because you were the one who responded on the initial PR and requested changes

I did not go with the option of a single Advance Account because Party and Party Type only work with Receivable/Payable accounts. Advances paid to employees are generally treated as Imprest accounts rather than receivables. It would be somewhat erroneous (in an accounting sense) to run an Accounts Receivable report and have your Imprest accounts showing up there!

Please advise

Thanks

P.S. @ckosiegbu thanks for the input. Pls see explanation in this post. Cheers!

**Comment by Olawale1** [comment]
Hi 

I checked and realised that the Receivables report is restricted to customers and insulated from other party types so I'm going ahead with the single Advance Account option. I'll make the required changes and push another commit to this PR once it's done (hopefully before the end of the day)

Thanks

**Comment by Olawale1** [comment]
Updates Pushed! Updated the documentation too

Kind regards,

**Comment by mbauskar** [comment]
@Olawale1,

Thanks for contributing.

Can you please check the Codecy errors? also please remove any console.log, print statements, Also use the 1 tab for indentation.

Closing this PR for now, Please make the changes and reopen the PR

**Pull request closed without merging**
