### PR TITLE
fix: Skipping total row for tree-view reports

### PR DESCRIPTION
**Pull request by AfshanKhan**
Skipping Total row for tree view doctypes as Total Row shows inflated values for tree view reports

### CODE REVIEW

**Review by deepeshgarg007 — CHANGES_REQUESTED** [review]
@AfshanKhan Please also fix test cases

**Review by deepeshgarg007 — CHANGES_REQUESTED** [review]
@AfshanKhan changes is JSON files where update total row option is checked is also missing. Please push those changes as well

**Comment by AfshanKhan** [comment]
> @AfshanKhan changes is JSON files where update total row option is checked is also missing. Please push those changes as well

pushed @deepeshgarg007

**Comment by deepeshgarg007** [comment]
@AfshanKhan Purchase Analytics?

**Comment by AfshanKhan** [comment]
> @AfshanKhan Purchase Analytics?

It's already true for that @deepeshgarg007

**Comment by deepeshgarg007** [comment]
@Mergifyio backport version-12-hotfix

**Review by deepeshgarg007 — APPROVED** [review]
@AfshanKhan changes is JSON files where update total row option is checked is also missing. Please push those changes as well

**Pull request merged**
