### PR TITLE
Correct South Africa VAT Rate

### PR DESCRIPTION
**Pull request by buff0k**
On 1 April 2018 South Africa increased the VAT rate from 14% to 15%, this proposed change seeks to update the default parameters for a fresh ERPNext installation.

### CODE REVIEW

**Comment by ankush** [comment]
Please send PR to `version-13-hotfix` branch. @buff0k

**Comment by buff0k** [comment]
Changed to version-13-hotfix branch as requested by Ankush Menat

**Comment by deepeshgarg007** [comment]
@buff0k you will also have to rebase your branch. I can see commits not made by you in this PR

**Comment by buff0k** [comment]
Closing this pull request and recreating under correct branch due to issues with rebasing.
New Pull Request created at #25894

**Pull request closed without merging**
