### PR TITLE
feat: Export CRM dashboard

### PR DESCRIPTION
**Pull request by anupamvs**
- Deleted dashboard_fixtures.py for CRM.
- Exported CRM Dashboard

### CODE REVIEW

**Review by nabinhait — DISMISSED** [review]
In all the charts and number cards add dynamic filters for company

**Comment by anupamvs** [comment]
@nabinhait Added!

**Review by nabinhait — APPROVED** [review]

**Comment by nanoharsha** [comment]
@anupamvs could you share what you mean by exporting of dashboard . As we use the CRM functionality I also wanted to check on this.

**Comment by anupamvs** [comment]
@nanoharsha These are the standard JSON generated for the module dashboard. More like this make it easy to customize the dashboard. Like we don't have to write any code for module dashboard.

**Pull request merged**
