### PR TITLE
fix(Integration): Woocommerce issues

### PR DESCRIPTION
**Pull request by ruchamahabal**
1. **Problem**: Delivery URL returned response code 500
     woocommerce_delivery_url

    **Why**: WooCommerce returns webhook_id=value for the first request which is not JSON. So, 
    json.loads does not work.
     
     **After fix**:
       woocommerce_delivery_url_fix

2. **Problem:** While creating Sales Order, it was fetching company from billing data of customer 
       which is not present in the ERPNext instance.
      woocommerce_company_none
       **Fix**: Added default "Company" field (mandatory) in WooCommerce Settings.

3. **Problem**: Delivery Date for Sales Order was set as 7 days post the order placement date.
    **Fix**: Added "Delivery After (Days)" field in WooCommerce Settings. (default = 7 days)

woocomeerc_settings

4. Removed redundant code and function calls.

### CODE REVIEW

**Review by nabinhait — COMMENTED** [review]
I think, while creating item or sales order, if user makes some fields mandatory, it will break. Please confirm how it is handled, if not then we can use `ignore_mandatory` flag.

**Review by nabinhait — APPROVED** [review]

**Comment by zerodiscount** [comment]
@ruchamahabal just tested this on develop branch. does resolve the Delivery URL error. However 
 successful payment (using Razorpay plugin and webhook to woocommerce) is not getting captured as a payment entry in ERPNext against new sales order created. Will appreciate your thoughts - happy to test with other settings if you need. Thanks for your efforts.

**Comment by zerodiscount** [comment]
`[Body] => {\"id\":670,\"parent_id\":0,\"number\":\"670\",\"order_key\":\"wc_order_aWIlpsDQwBMIg\",\"created_via\":\"checkout\",\"version\":\"3.8.0\",\"status\":\"processing\",\"currency\":\"INR\",\"date_created\":\"2019-11-19T05:37:18\",\"date_created_gmt\":\"2019-11-19T00:07:18\",\"date_modified\":\"2019-11-19T05:37:46\",\"date_modified_gmt\":\"2019-11-19T00:07:46\",\"discount_total\":\"0.00\",\"discount_tax\":\"0.00\",\"shipping_total\":\"0.00\",\"shipping_tax\":\"0.00\",\"cart_tax\":\"65.89\",\"total\":\"615.00\",\"total_tax\":\"65.89\",\"prices_include_tax\":true,\"customer_id\":8,\"customer_ip_address\":\"174.100.163.201\",\"customer_user_agent\":\"Mozilla\\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/78.0.3904.97 Safari\\/537.36\",\"customer_note\":\"\",\"billing\":{\"first_name\":\"Test\",\"last_name\":\"Customer\",\"company\":\"\",\"address_1\":\"X XXXXX XXXX\",\"address_2\":\"XXXXXXXXX Marg\",\"city\":\"Mumbai\",\"state\":\"MH\",\"postcode\":\"400071\",\"country\":\"IN\",\"email\":\"XXXX@XXXX.com\",\"phone\":\"123456789\"},\"shipping\":{\"first_name\":\"Test\",\"last_name\":\"Customer\",\"company\":\"\",\"address_1\":\"XXXXX XXXX\",\"address_2\":\"XXXXXXX Marg\",\"city\":\"Mumbai\",\"state\":\"MH\",\"postcode\":\"400071\",\"country\":\"IN\"},\"payment_method\":\"razorpay\",\"payment_method_title\":\"Credit Card\\/Debit Card\\/NetBanking\",\"transaction_id\":\"pay_DhzarsB7ZeIxrX\",\"date_paid\":\"2019-11-19T05:37:45\",\"date_paid_gmt\":\"2019-11-19T00:07:45\",\"date_completed\":null,\"date_completed_gmt\":null,\"cart_hash\":\"7b39cf1416ab459d240b3fe67ab579de\",\"meta_data\":[{\"id\":3162,\"key\":\"is_vat_exempt\",\"value\":\"no\"}],\"line_items\":[{\"id\":47,\"name\":\"VIVO OVERNIGHT Adult Pants SMALL\\/MEDIUM 12 CT\",\"product_id\":331,\"variation_id\":0,\"quantity\":1,\"tax_class\":\"\",\"subtotal\":\"549.11\",\"subtotal_tax\":\"65.89\",\"total\":\"549.11\",\"total_tax\":\"65.89\",\"taxes\":[{\"id\":1,\"total\":\"32.946429\",\"subtotal\":\"32.946429\"},{\"id\":2,\"total\":\"32.946429\",\"subtotal\":\"32.946429\"}],\"meta_data\":[],\"sku\":\"PM12\",\"price\":549.107143}],\"tax_lines\":[{\"id\":49,\"rate_code\":\"IN-MH-SGST-1\",\"rate_id\":1,\"label\":\"SGST\",\"compound\":false,\"tax_total\":\"32.95\",\"shipping_tax_total\":\"0.00\",\"rate_percent\":6,\"meta_data\":[]},{\"id\":50,\"rate_code\":\"IN-MH-CGST-2\",\"rate_id\":2,\"label\":\"CGST\",\"compound\":false,\"tax_total\":\"32.95\",\"shipping_tax_total\":\"0.00\",\"rate_percent\":6,\"meta_data\":[]}],\"shipping_lines\":[{\"id\":48,\"method_title\":\"Free shipping\",\"method_id\":\"free_shipping\",\"instance_id\":\"2\",\"total\":\"0.00\",\"total_tax\":\"0.00\",\"taxes\":[],\"meta_data\":[{\"id\":333,\"key\":\"Items\",\"value\":\"VIVO OVERNIGHT Adult Pants SMALL\\/MEDIUM 12 CT × 1\"}]}],\"fee_lines\":[],\"coupon_lines\":[],\"refunds\":[],\"_links\":{\"self\":[{\"href\":\"https:\\/\\/shop.hygient.com\\/in\\/wp-json\\/wc\\/v3\\/orders\\/670\"}],\"collection\":[{\"href\":\"https:\\/\\/shop.hygient.com\\/in\\/wp-json\\/wc\\/v3\\/orders\"}],\"customer\":[{\"href\":\"https:\\/\\/shop.hygient.com\\/in\\/wp-json\\/wc\\/v3\\/customers\\/8\"}]}}`

**Comment by ruchamahabal** [comment]
updated docs: https://github.com/frappe/erpnext_com/pull/628

**Comment by robertolanuti** [comment]
Hi, I'm running the ERPNext v12.4.1 that contains this fix:

image

However, I can still see the error 500

image

Also, I have tried to place an order and I'm getting the following log:

```
Traceback (most recent call last):
  File "/home/frappe/bench/apps/erpnext/erpnext/erpnext_integrations/connectors/woocommerce_connection.py", line 25, in order
    _order(*args, **kwargs)
  File "/home/frappe/bench/apps/erpnext/erpnext/erpnext_integrations/connectors/woocommerce_connection.py", line 40, in _order
    order = json.loads(frappe.request.data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frappe/bench/apps/frappe/frappe/app.py", line 60, in application
    response = frappe.api.handle()
  File "/home/frappe/bench/apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 22, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/bench/apps/frappe/frappe/handler.py", line 61, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/bench/apps/frappe/frappe/__init__.py", line 1041, in call
    return fn(*args, **newargs)
  File "/home/frappe/bench/apps/erpnext/erpnext/erpnext_integrations/connectors/woocommerce_connection.py", line 27, in order
    error_message = frappe.get_traceback()+"\n\n Request Data: \n"+json.loads(frappe.request.data).__str__()
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```
do you have any idea about that?

**Comment by robertolanuti** [comment]
Hi,

I was able to fix the issue that I was referring in the previous comment by migrating to python 3.

Regards,
Roberto

**Pull request merged**
