### PR TITLE
Daily reminder project

### PR DESCRIPTION
**Pull request by renzodemie**
- [ ] Project Doctype

- Added a Checkbox to "collect daily progress"

- Added an option "Frequency To Collect Progress"

- Added a time to collect progress

- Added a dashboard link to Project Update

- [ ] Project Update Doctype

- Added a table of Users who is involve in the update

- Notifications do not send on holidays

### CODE REVIEW

**Comment by achillesrasquinha** [comment]
Hi, please display some screenshots or workflow, Excited to see what it's about!

**Review by tundebabzy — CHANGES_REQUESTED** [review]
+1 for first contribution

Also fix the conflicts

**Comment by renzodemie** [comment]
Hello. I'm getting this error in Travis-CI 

> FAIL: test_billing (erpnext.restaurant.doctype.restaurant_order_entry.test_restaurant_order_entry.TestRestaurantOrderEntry)

But I PR in the Projects, not on restaurant. Any idea how to fix this? Thanks

**Comment by Olawale1** [comment]
Agree with @achillesrasquinha , some screenshots would really be nice!

Kind regards,

**Pull request closed without merging**
