### PR TITLE
[FedEx Integration]

### PR DESCRIPTION
**Pull request by gupteshwar**
This is a PR for FedEx integration on very initial note and without much of integration code added yet. This covers entire solution structure and base in terms of DocTypes/masters and classes for further coding to be done.

Please, do a review on structure and validate so further development updates will be more aligned towards merging.

More details and tasks to be referred on,
https://discuss.erpnext.com/t/erpnext-foundation-pune-chapter-code-sprint-1-fedex-integration/30018
https://github.com/frappe/erpnext/issues/1146814

### CODE REVIEW

**Comment by revant** [comment]
- Rebase
- Module name Logistics with 's' seems proper https://www.englishforums.com/English/LogisticVsLogistics/mpmmb/post.htm. Logistic is sometimes used as adjective.

DocTypes
- Shipping Plan.
- Shipper : Named appropriately
- Package Details : DocType is generally named singular not pural. e.g. Package, or Package Detail
- FedEx Settings & FedEx Controller : Should this be part of framework, integrations module? like Payment Gateways, Logistics Controllers? @rmehta any comments?

Can you share structure and progress of PR in diagrams and images? It is easy to understand quickly. 

Also can you share sandbox api credentials whenever necessary? Or share a urls to get dev credentials to FedEx api?

**Review by revant — COMMENTED** [review]
check comment https://github.com/frappe/erpnext/pull/11541#issuecomment-346263775

**Comment by rmehta** [comment]
@gupteshwar you want to update the doctypes and start a new PR?

**Comment by gupteshwar** [comment]
Thanks for review. Yes, we will be initiating a new pull request.

**Pull request closed without merging**
