### PR TITLE
fix(selling): Add missing label to company address field

### PR DESCRIPTION
**Pull request by Alchez**
The company address display field in Sales Order is missing a label, and is inconsistent with the same field in Sales Invoice and Delivery Note.

Made to hotfix at #17152.

**Before:**

image

**After:**

image

### CODE REVIEW

**Review by nabinhait — DISMISSED** [review]

**Review by deepeshgarg007 — CHANGES_REQUESTED** [review]
@Alchez Please update the branch and resolve conflicts and push again

**Comment by Alchez** [comment]
@deepeshgarg007 I've resolved the conflicts and used the new JSON format.

**Review by nabinhait — CHANGES_REQUESTED** [review]
@Alchez Why have you changed fieldname from `company_address` to `company_address_name`? It will lead to data loss.

**Comment by Alchez** [comment]
@nabinhait, I was just trying to keep them consistent with the shipping address fields, but you're right. I'll revert that change.

**Comment by nabinhait** [comment]
> @nabinhait, I was just trying to keep them consistent with the shipping address fields, but you're right. I'll revert that change.

It is used as `company_address` in all doctypes and code, let keep it as it is.

**Comment by Alchez** [comment]
@nabinhait I've made the changes, can you have a look again?

**Comment by Alchez** [comment]
@nabinhait, can you have a look at this please?

**Review by deepeshgarg007 — APPROVED** [review]

**Pull request merged**
