### PR TITLE
feat: Increase number of supported currency exchanges

### LINKED ISSUE #25603: Many unsupported exchange rates: Switch from frankfurter.app to exchangerate.host or allow custom API
**Problem:**
Exchange rates are currently fetched from https://www.frankfurter.app/. Unfortunately, this API only supports about 30-40 currencies with many world currencies still being not supported. This makes using a multi-currency setup very cumbersome to impossible to maintain if exchange rates have to be added manually.

**Proposed solution:**
There are other free APIs available that support more exchange rates. One promising API seems to be this one: https://exchangerate.host/ 
It is also free and open source (https://github.com/Formicka/exchangerate.host) and apparently supports 170 currencies (+ 6000 cryptocurrencies - not sure but might be also interesting for some ERPnext users?!).

It doesn't seem to be too complicated to adjust the current code to support. Unfortunately, I am hosting my instance on frappe.cloud, so I don't have the option to work on the code.
In [erpnext/setup/utils.py (L101)](https://github.com/frappe/erpnext/blob/5ce0569f80c622d6d7ff480015e8d79b82bf93b5/erpnext/setup/utils.py#L101) the frankfurter.app API is currently called. It seems one would only need to adjust the API call and link to exchangerate.host and this would directly add >100 additional currencies supported by ERPnext (+many cryptocurrencies).
It would be amazing if someone from the core team could test this. It doesn't seem to be a hard fix.

**Potential alternatives**
Potentially, ERPnext could allow the user to specify the API (and its settings) similar to how it is currently available for SMS APIs (https://docs.erpnext.com/docs/user/manual/en/setting-up/sms-setting). This might be a little bit more work, but would make multi-currency support even more flexible. If the core team wishes to have frankfurter.app still as default, this could be left as a default value. However this way, the user could change to the API they wish to use and could also use a commercial API (such as fixer.io) if they need/want. 

**Additional context**
This issue has been raised already quite some time ago in this thread in the Forum:
https://discuss.erpnext.com/t/is-there-any-plan-for-the-missing-exchange-rates-on-www-frankfurter-app/48782
I believe many companies especially in developing countries with lesser known currencies, that are currently unsupported by the frankfurter.app, would benefit from this.

### PR DESCRIPTION
**Pull request by rtdany10**
Switch from frankfurter.app to exchangerate.host to accommodate more currency usage.
Closes #25603

#no-docs

### CODE REVIEW

**Comment by aschl** [comment]
Any updates? What needs to be done?

**Comment by revant** [comment]
https://discuss.erpnext.com/t/bot-discussion-pr-26237-feat-increase-number-of-supported-currency-exchanges/78569

<strong>Testing Site URL:</strong> https://gh-imp-2021-00412.castlecraft.co.in

#### Credentials
username: `ccunningham@riley.info`
password: ee39ab3258

**Comment by rtdany10** [comment]
@Mergifyio backport version-13-hotfix

**Review by nabinhait — APPROVED** [review]

**Comment by ankush** [comment]
@rtdany10 @nabinhait  the price list tests failure was relevant and started with this PR only.

We shouldn't be making real API calls during tests! 😅

**Comment by rtdany10** [comment]
> @rtdany10 @nabinhait the price list tests failure was relevant and started with this PR only.
> 
> We shouldn't be making real API calls during tests! sweat_smile

Did I more or less create a domino effect?:sweat_smile:
Thank you for updating the tests.

**Comment by ankush** [comment]
Those tests were kinda written badly to begin with but failure shouldn't have been ignored. It's time-consuming to trace test failure once it's introduced.  

---

I haven't rewritten the `get_exchange_rate` tests yet.  Feel free to give it a go. Either patch it out or use some other method to provide values when `frappe.flags.in_test` is true :smile: Also I am not sure why this API is returning conversion rates for `_Test Currency`

**Comment by rtdany10** [comment]
> Those tests were kinda written badly to begin with but failure shouldn't have been ignored. It's time-consuming to trace test failure once it's introduced.
> 
> I haven't rewritten the `get_exchange_rate` tests yet. Feel free to give it a go. Either patch it out or ignore use some other method to provide values when `frappe.flags.in_test` is true :smile: Also I am not sure why this API is returning conversion rates for `_Test Currency`

Sorry about that. I should've been more vigilant. Won't brush off the failing tests easily any more.
Will try to rewrite the test asap! And thank you for clearing up my mess. :sweat_smile: 

P.S rewrite the tests or the function? @ankush

**Pull request merged**
