### PR TITLE
feat: Payments based dunning

### PR DESCRIPTION
**Pull request by marination**
An attempt to revive https://github.com/frappe/erpnext/pull/27528

--------------------------

Related to #26969

Create dunning for all overdue payments of a customer. We use a table similar to the payment schedule in sales invoice to pull all overdue scheduled payments into the Dunning.

- Rate of Interest is the same for all overdue payments.
- Interest amount is calculated for each overdue payment.
- Dunning Fee is applied only once per dunning.

### Changes in accounting

- Dunning amount will no longer be booked to receivables. The reason is that the dunning amount is not paid in many cases / is only intended as a warning. If paid, the dunning amount will be recorded as additional income in Payment Entry. See [here](https://www.rechnungswesenforum.de/forum/buchfuehrung-buchhaltung/allgemein/forderung-mahngebuehren.423727/) and [here](https://www.haufe.de/finance/haufe-finance-office-premium/mahnung-und-mahnverfahren-73-buchung-mahngebuehren-und-verzugszinsen_idesk_PI20354_HI2015327.html) for further reading (in german).

Preview:

new_dunning

Docs: https://docs.erpnext.com/docs/v13/user/manual/en/accounts/dunning?editWiki=1&wikiPagePatch=318ad1abe6
Discuss: https://discuss.erpnext.com/t/dunning-mahnung-warning-notice/49499/30?u=rmeyer

--------------------------

**ToDo:**
- [x] Resolve conflicts
- [x] Manual tests of functionality
- [x] Test of migration patch
- [x] Fix: Manually added Payment Schedule without template or terms keeps dunning unresolved. Partial Fix: #35798 (users must take care of this. A note is added to the docs)
- [x] Possibly add some unit tests 
- [x] Apply changes suggested by reviewers / community
- [x] Check and update the docs

### CODE REVIEW

**Review by barredterra — DISMISSED** [review]
Tested, LGTM

**Comment by marination** [comment]
@deepeshgarg007 This is tested, reviewed and ready to merge. You can give it a last check and let us know if it looks okay.

**Comment by marination** [comment]
@deepeshgarg007 the patch reverses GL entries for unresolved dunnings. Will it be problematic if there are some old unresolved dunnings ? From before the **Accounts Frozen Till Date** ? Those should stay untouched right ?

**Comment by marination** [comment]
@Mergifyio backport version-14-hotfix

**Comment by muchai** [comment]
This could use a backport to version 14 please.

**Comment by bosue** [comment]
@muchai: This is a massive change, so backporting would break lots of custom code in v14 IMO. Also, it‘s still experimental, so not fully settled in v15. We all loved the feature and wanted to see it in v15, but IMO there‘s still much to do until it may be considered stable and be backported. So instead, you might want to upgrade to v15?

But that‘s just my two cents. I personally don‘t care if it‘s backported. I just can‘t consider it finished, and while having quite many advantages, there‘s a couple of drawbacks, including lost features that should probably be reinstated before backporting.

**Pull request merged**
