### PR TITLE
Tax Rule based on County

### PR DESCRIPTION
**Pull request by nabinhait**
Against #5348

### CODE REVIEW

**Comment by jasonbrowne** [comment]
The tax rule based upon county works for us, in our testing so far. We did run into a  problem finding the specific tax rules we need to change as the tax rule list does not show city county and state. As a result of the city, county and state not showing we had to hunt through the tax rule list to find the rules we needed to change. 

Please see the attached jpg.
tax-rule-list

**Comment by jasonbrowne** [comment]
The tax rule based upon county works for us, in our testing so far. We did run into a problem finding the specific tax rules we need to change as the tax rule list does not show city county and state. As a result of the city, county and state not showing we had to hunt through the tax rule list to find the rules we needed to change.
tax-rule-list

**Comment by anandpdoshi** [comment]
Maybe we could use a title field and set it automatically based on what values are available

**Comment by jasonbrowne** [comment]
Anything that makes it easy to identify the Tax Rules that need to be 
changed. If it showed the State, City, and County it would work good.

**Comment by jasonbrowne** [comment]
Team is this part of ERPNext7 yet or will we have to add it to 7?

**Comment by rmehta** [comment]
@jasonbrowne can you specify what issues you are facing?

**Comment by jasonbrowne** [comment]
Sorry, It turns out the issue is with tax rules not importing was due to user error in not having the same settings on both systems. So nothing is wrong.

**Pull request merged**
