### PR TITLE
fix: salary structure assign to employee

### PR DESCRIPTION
**Pull request by pateljannat**
Issue:

1. Create a Salary Structure.
2. From the top menu click on Assign to Employees.
3. Select an Employee and enter From Date.
4. Click on Assign. An error appears.

Screenshot 2021-03-04 at 11 20 36 AM

### CODE REVIEW

**Review by kingraphaii — COMMENTED** [review]
The error is gone, however, the Base salary isn't set when the Salary Structure Assignment is submitted. Could this be the same issue or a different one?

**Comment by pateljannat** [comment]
@kingraphaii Fixed

**Review by kingraphaii — COMMENTED** [review]
Issue seems to be fixed now. Great work @pateljannat

**Comment by zico99211** [comment]
It is succeeded only once when I tried to assign another salary structure it gives me the same error "TypeError: assign_salary_structure() got an unexpected keyword argument 'company'"
please help

**Comment by kingraphaii** [comment]
> It is succeeded only once when I tried to assign another salary structure it gives me the same error "TypeError: assign_salary_structure() got an unexpected keyword argument 'company'"
> please help

Hi.  This PR hasn't been merged yet. To test/have this fix on your instance, please make the changes on your own.

Warm Regards.

**Review by nabinhait — APPROVED** [review]

**Comment by fossdot** [comment]
Hi @pateljannat, The issue still exists on Frappe Cloud. Wanted to know has #24798 been updated on FC?

Salary_assignment_Screenshot

**Pull request merged**
