### PR TITLE
fix: (Healthcare) Add Quick Entry for Patient Address

### PR DESCRIPTION
**Pull request by mujeerhashmi**
Add Address Fields to Patient Quick Entry Form.

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

### CODE REVIEW

**Comment by ChillarAnand** [comment]
@mujeerhashmi Can you please share screenshots for the new changes?

**Comment by mujeerhashmi** [comment]
> @mujeerhashmi Can you please share screenshots for the new changes?

Added the screenshots.

**Comment by ChillarAnand** [comment]
@mujeerhashmi Thanks for sharing the screenshots. 

The quick entry form is becoming lengthy and is difficult to fit in single screen. Can you please add column break in the top fields so that the length of the form reduces?

You can split it into 2 columns as follows.

First name - Last name
Gender - Blood group
DOB - UID
Mobile - Email

**Comment by mujeerhashmi** [comment]
> @mujeerhashmi Thanks for sharing the screenshots.
> 
> The quick entry form is becoming lengthy and is difficult to fit in single screen. Can you please add column break in the top fields so that the length of the form reduces?

I have made the primary address collapsible.
I am not sure how to add column breaks for fields of the doctype. Can you guide me, please?

**Comment by ChillarAnand** [comment]
If we make address as collapsible, users have to click on it to enter details. Instead of this, they can anyway click on edit on full page and enter details. 

We need to remove the collapsible from the quick entry. 

To add column break, you can take look at customer quick entry form.

https://github.com/frappe/erpnext/blob/develop/erpnext/public/js/utils/customer_quick_entry.js#L26

Feel free to ping if you need any other help. @mujeerhashmi

**Comment by mujeerhashmi** [comment]
Can we get this merged please ??

**Comment by ChillarAnand** [comment]
Keep alive.

**Pull request closed without merging**
