### PR TITLE
fix: salary leave calculation

### LINKED ISSUE #27975: Salary Slip not correctly calculating, leave without pay days or partial paid leave days
## Description of the issue
When creating a salary slip that is based on leaves, on a employee with leave days that do not include holidays, the leave without pay is not calculated correctly.   In addition, if the leave has partial paid leave, these days are simply added as leave without pay causing the days to be deducted from pay.  The leave with pay issue also effects attendance based pay.

## Context information (for bug reports)
Payroll settings, "Calculate Payroll Working Days Based On" is set to "Leave" has both issues.
Payroll settings, "Calculate Payroll Working Days Based On" is set to "Attendance" has Leave with pay issue.

**Output of `bench version`**
ERPNext: v13.12.1 (version-13)
Frappe Framework: v13.12.1 (version-13)

## Steps to reproduce the issue

1. Set payroll to "leave" or "Attendance"
2. Create holiday list and apply to employee/company
3. Create leave type with Partially paid leave enabled and  "Include holidays within leaves as leaves" disabled
3. Create leave policy and apply to employee
4. Create and approve leave application that spans holidays NEAR THE END OF THE PAYROLL PERIOD. for example, over the last weekend.
5. Create a Salary slip for employee in period with leave application

### Observed result
With payroll settings to Leave based:
The Leave Without Pay is not correct (Number of lave days in period).
The Payment Days is working days less LWP.
The pay component is deducted for the number of Leave without pay days.

With payroll settings to Attendance based:
The pay component is deducted for the number of Leave without pay days.
The Payment Days is working days less LWP.

### Expected result
With payroll settings to Leave based:
The Leave Without Pay is correct (Number of non paid leave days in period).  
The Payment Days is working days less LWP, but includes the paid leave days.  Alternatively, a separate count for paid leave days is show.
The pay component is deducted for the number of Leave without pay days only.

With payroll settings to Attendance based:
The pay component is deducted for the number of Leave without pay days.
The Payment Days is working days less LWP, but includes the paid leave days.  Alternatively, a separate count for paid leave days is show.
The pay component is deducted for the number of Leave without pay days only.

### Additional Information
The problem appears to be related to the salary_slip.py functions calculate_lwp_or_ppl_based_on_leave_application and calculate_lwp_ppl_and_absent_days_based_on_attendance.

calculate_lwp_or_ppl_based_on_leave_application appears to loop using the working days as the index; however the loop doesn't account for holidays and simply works in order from the start date.  Instead it should increment past holidays.  The current implementation, with 22 working days in a 31 month calendar, will not include holidays past 22 days in the month.

Both functions simply return paid leave days as leave without pay, which is not what is expected.  Either they should not include these days as LWP or return them as a separate value.

### PR DESCRIPTION
**Pull request by conncampbell**
> Please provide enough information so that others can review your pull request:

This pull has two commits, one fixes a problem with Pay per leave not calculating correctly, and the other is a feature that separates out pay per leave into it's own field in pay slips.  Updated tests are included.

> Explain the **details** for making this change. What existing problem does the pull request solve?

Fixes #27975 

Note that the issue only shows up when the leave days are later in the month.

> Screenshots/GIFs

v13 Salary PPL

### CODE REVIEW

**Comment by ankush** [comment]
Please undo formatting only changes; reviewing the actual changes becomes very difficult.

**Comment by conncampbell** [comment]
> Please undo formatting only changes; reviewing the actual changes becomes very difficult.

would you recommend putting formatting in a separate chore commit?  Otherwise, linters will complain.

**Comment by ankush** [comment]
> would you recommend putting formatting in a separate chore commit? Otherwise, linters will complain.

Remove all formatting changes that are not on the same lines or near functional changes.

Linter will ignore existing formatting issues. It's only supposed to look at changed lines.

**Comment by conncampbell** [comment]
I'll need to do some work on this to fix some issues.

**Comment by conncampbell** [comment]
Moved to new pull #28213 28213

**Pull request closed without merging**
