### PR TITLE
feat: Increase number of supported currency exchanges

### PR DESCRIPTION
**Pull request by rtdany10**
Switch from frankfurter.app to exchangerate.host to accommodate more currency usage.
Backport of #26237 

#no-docs

### CODE REVIEW

**Comment by rtdany10** [comment]
@nabinhait

**Comment by rtdany10** [comment]
Unrelated test failing.
@nabinhait can we merge this PR?

**Review by nabinhait — APPROVED** [review]

**Comment by barredterra** [comment]
@rtdany10 maybe we should make this configurable. Currently it's difficult for a user to know where the exchange rates are coming from, and the API is changed frequently. It is a legal requirement in Europe to make sure that exchange rates are trusted and accurate, and that the source is known.

**Comment by rtdany10** [comment]
> @rtdany10 maybe we should make this configurable. Currently it's difficult for a user to know where the exchange rates are coming from, and the API is changed frequently. It is a legal requirement in Europe to make sure that exchange rates are trusted and accurate, and that the source is known.

I agree to the fact that it should be configurable. Although, I don't believe APIs were changed frequently. Even though we switched the API endpoint by this pull request, the source of both the service remain the same, European Central Bank.

**Comment by sagarvora** [comment]
**exchangerate.host** requires an access token now. perhaps we should revert to frankfurter.app and backport configurability.

**Pull request merged**
