### PR TITLE
fix: reference doctype error, while creating payment entry against em…

### PR DESCRIPTION
**Pull request by nijithanil**
Reference doctype error, while creating payment entry against employee

### CODE REVIEW

**Comment by nijithanil** [comment]
Error:

WhatsApp Image 2024-04-15 at 12 25 49 PM

**Comment by ruthra-kumar** [comment]
@nijithanil 
Which version of ERPNext are you using? 
`Expense Claim` and other employee related doctypes are only available if you have installed HRMS app. Is HRMS app installed on your instance?

**Comment by nijithanil** [comment]
The HRMS has been installed, yet it continues to display the error.

WhatsApp Image 2024-04-15 at 12 25 49 PM

HRMS Version:

WhatsApp Image 2024-04-16 at 11 37 23 AM

**Comment by ruthra-kumar** [comment]
HRMS app already adds the allowed reference doctypes. I'm not sure how adding expense claim in ERPNext will help.
https://github.com/frappe/hrms/blob/d937089d6cc56b2a523f4edcf0f89230ad9b994b/hrms/overrides/employee_payment_entry.py#L27-L28

Could you let us know how to replicate this issue?

**Comment by ruthra-kumar** [comment]
Closing this, as the change does not look related.

**Pull request closed without merging**
