### PR TITLE
Adding nested warehousing

### PR DESCRIPTION
**Pull request by cgpurbaugh**
Attempt to create nested warehousing feature.

### CODE REVIEW

**Comment by rmehta** [comment]
@cgpurbaugh push your commits!

**Comment by David-at-GitHub** [comment]
@cgpurbaugh Good morning, could you let me know your progress on this? It sounds interesting.

Thanks, David

**Comment by cgpurbaugh** [comment]
Hi David, 

I attempted to start this, but it was way over my head.

**Comment by rmehta** [comment]
@cgpurbaugh Closing for now. We can look into it if you are willing to sponsor.

**Pull request closed without merging**
