### PR TITLE
refactor!: Remove Regionalisation of France as now there is an App ERPNext France to manage it

### PR DESCRIPTION
**Pull request by FHenry**
> Please provide enough information so that others can review your pull request:

For ERPNext version 15, there is no more need to have regional feature in core ERPNext, for France as now they are all replicate in ERPNext France App managed by Scopen (ERPNext Partner for France region) and there is more feature in this app

https://frappecloud.com/marketplace/apps/erpnext_france
https://github.com/scopen-coop/erpnext_france

If Frappe Team are agree with this change, could you also update to indicate a link to https://github.com/scopen-coop/erpnext_france (or remove/archive) to repository https://github.com/frappe/erpnext_france?

### CODE REVIEW

**Comment by ankush** [comment]
@FHenry leave `!` in PR. Breaking changes need to be correctly identified.

**Comment by FHenry** [comment]
> @FHenry leave `!` in PR. Breaking changes need to be correctly identified.

Ok, Sorry I was thinking that was me by typo wrong, I didn't saw that you've made this change

**Comment by deepeshgarg007** [comment]
@FHenry Please add a depreciation warning in v14, something similar to https://github.com/frappe/erpnext/blob/develop/erpnext/patches/v15_0/saudi_depreciation_warning.py

**Comment by deepeshgarg007** [comment]
@FHenry Unit tests failing, can you check?

**Comment by deepeshgarg007** [comment]
@FHenry Unit tests failing, can you check?

**Comment by FHenry** [comment]
@deepeshgarg007 I've remove the falling test, now CI fail on patch, but that not related to my PR (payment app that have conflicting version of a module)

**Comment by ankush** [comment]
fixed patch test here, unrelated to this PR https://github.com/frappe/erpnext/pull/37079

**Comment by deepeshgarg007** [comment]
Reopen when https://github.com/frappe/erpnext/pull/37016 is fixed

**Pull request closed without merging**
