### PR TITLE
adding account type (payable) to "Payroll Payable" (2120) account

### PR DESCRIPTION
**Pull request by dulhaver**
The "Payroll Payable" (2120) account is missing the account type (payable).
Hope this PR fixes the matter

### CODE REVIEW

**Comment by sagarvora** [comment]
Hello, please try to check why travis might be failing:
https://travis-ci.com/frappe/erpnext/jobs/166957496

**Comment by vrms** [comment]
@sagarvora thanks for the pointer. will check and see whether I can eliminate the problem.

**Comment by vrms** [comment]
sorry @sagarvora can't draw any sense from the travis report, neither can I see any obvious mistake in the line I have added.

That being said ... I do not now python, so the reason may be obvious to anyone who does. Shall I close the PR as it's not mergable as is and I am lacking the expertize to make it work?

**Comment by sagarvora** [comment]
The reason why this is failing is because it might be used as a receivable account in tests. 

I'm closing this for now.

**Pull request closed without merging**
