### PR TITLE
fix : correct logic for overlap error

### PR DESCRIPTION
**Pull request by VihangT**
fixing overlap error logic with taking care of sequential time job cards in overlap job card list

To understand the scenario I have taken live example which is illustrated below. 
Ideally PO-JOB01797 should save their time logs as can be seen below image but instead system is throwing an overlap error with mentioning overlap with PO-JOB00678.
When I run the same code for overlap I found the below mentioned job cards in overlap list.
Technically PO-JOB01797 was operated on different station than other mentioned Job Cards still it showed an error.
Here I am explaining my approach towards this: 

Screenshot from 2023-12-16 14-45-55

My approach towards overlapping is 
1. Sort the overlapping list wrt from_time
2. Create sets of  Job card which can be sequential. 
3. if any job card is overlapping with any job card in given set then create new set.
4. do this till all Job cards are bifurcated in to sets.
5. Count number of Sets for that overlapping list, if number of sets >= production capacity that means new job card can not be accommodate for this time line => So throw overlap Error.

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

### CODE REVIEW

**Comment by rohitwaghchaure** [comment]
@VihangT test cases failing

**Comment by VihangT** [comment]
> @VihangT test cases failing

added 1 change as per linters error

**Comment by VihangT** [comment]
Added 1 change after failing in Python Unit Test (2) where time_logs is empty and has_overlap() is called.

**Comment by VihangT** [comment]
@s-aga-r 
Server (Mariadb) / Python Unit Tests (1) (pull_request) and Server (Mariadb) / Python Unit Tests (2) (pull_request)  are failing due to showing Error in File "/home/runner/frappe-bench/apps/erpnext/erpnext/accounts/doctype/payment_reconciliation/test_payment_reconciliation.py. 

I did not change anything related to that.
@rohitwaghchaure 
Should I need to take any action?
Please let me know if any change is required.

**Comment by rohitwaghchaure** [comment]
@VihangT Can you add test cases

**Pull request merged**
