### PR TITLE
Fixes erpnext issue 6891

### PR DESCRIPTION
**Pull request by jwrober**
Updated all 4 items listed on the issue. Removed old out of date image
files and created new ones. Fixed broken links.

### CODE REVIEW

**Comment by yashodhank** [comment]
@jwrober wesite-home-page.md file and index links are renamed to correct `wesite` to `website` before your pull request, resolve conflict and resend pull request. Thanks for contribution.

**Comment by jwrober** [comment]
I am trying to figure this out. I didn't rename the file, but I guess you guys did. I see this in the top of the diff

```
<<<<<<< HEAD:erpnext/docs/user/manual/en/website/articles/wesite-home-page.md
# Wesite Home Page
=======
<h1>Website Home Page</h1>
>>>>>>> refs/remotes/frappe/develop:erpnext/docs/user/manual/en/website/articles/website-home-page.md
```

any thoughts on how to force my repo to get your changes and then i can update?

**Comment by jwrober** [comment]
ok try now...

**Comment by yashodhank** [comment]
@jwrober pull & merge new changes from remote develop and rebase your pull request.

**Comment by jwrober** [comment]
@yashodhank did that in second commit. I think this is ready now.

**Comment by umairsy** [comment]
Hello James,

Great to see the contribution in the manual! 

On the manual, we maintain width for the screenshots at 680px. Improves aesthetics of overall manual. Will be great if you could take screenshots again with given width and send pull request.

**Comment by jwrober** [comment]
Ok, see updated commit for the PR.

**Review by rmehta — APPROVED** [review]

**Comment by umairsy** [comment]
@jwrober Great! Pull request merged. Thanks for your contribution.

**Pull request merged**
