### PR TITLE
fix: error while hrms app is installed

### PR DESCRIPTION
**Pull request by viralkansodiya**
Hi Frappe

Error When HRMS app is installed and i am trying to import chart of account by **chart of account importer tool**  
without hrms app it is working fine

Screenshot 2023-09-13 112910

### CODE REVIEW

**Comment by viralkansodiya** [comment]
for this error refer this video 
https://youtu.be/-mWOmgHdyl4  @deepeshgarg007

**Comment by viralkansodiya** [comment]
@ruthra-kumar can you help me to solve this bug?

**Comment by deepeshgarg007** [comment]
@viralkansodiya This doesn't look like a proper fix, please share the COA template file you tried to upload

**Comment by viralkansodiya** [comment]
https://youtu.be/-mWOmgHdyl4 Please follow this video @deepeshgarg007
full process to get this error mentioned in this video

**Comment by deepeshgarg007** [comment]
@viralkansodiya I have tried to fix this issue at https://github.com/frappe/erpnext/pull/37238 in a more generic way, closing this PR

**Pull request closed without merging**
