### PR TITLE
fix: Creating landed cost voucher from connections

### PR DESCRIPTION
**Pull request by Vishnu7025**
Upon clicking the Landed Cost voucher button from a Purchase Invoice connection, certain fields in the child table of the Landed Cost voucher are not automatically populated.

https://user-images.githubusercontent.com/105106551/234461860-155c8fd7-a7a4-4e7e-b5df-9c8df2fa1064.mp4

### CODE REVIEW

**Comment by Vishnu7025** [comment]
@leela @ceefour @venetanji

**Comment by Vishnu7025** [comment]
@marination @rtdany10  @rohitwaghchaure

**Comment by Vishnu7025** [comment]
@marination @rtdany10 @rohitwaghchaure

**Comment by Vishnu7025** [comment]
@marination  @rohitwaghchaure

**Comment by marination** [comment]
@Vishnu7025 assign or request a review from a maintainer from the sidebar on the Right Hand Side instead of tagging in the comments. Also I do not have the rights to merge your PR 😬

**Comment by Vishnu7025** [comment]
@rohitwaghchaure

**Pull request closed without merging**
