### PR TITLE
fix: warehouse not mapping correctly during Delivery Note creation.

### PR DESCRIPTION
**Pull request by Vishnu7025**
https://github.com/user-attachments/assets/e9a78147-03f8-450b-aabf-c39eb2b8899e

### CODE REVIEW

**Comment by Vishnu7025** [comment]
@deepeshgarg007 please check and review

**Comment by Vishnu7025** [comment]
@deepeshgarg007 please check and review

**Comment by Vishnu7025** [comment]
@deepeshgarg007 @ruthra-kumar please check and review

**Comment by ruthra-kumar** [comment]
@Vishnu7025 
Could you provide replication steps?

**Comment by Vishnu7025** [comment]
@ruthra-kumar Please create a sales order with item X of quantity 10 and reserve the stock in two different warehouses (e.g., 5 in Warehouse A and 5 in Warehouse B). When creating a delivery note from the sales order, the quantity splits based on the reserved stock, but the warehouse remains the same. For more details, please refer to the video above. If you still can't replicate the issue, please let me know.

**Comment by Vishnu7025** [comment]
@ruthra-kumar

**Comment by ruthra-kumar** [comment]
@Vishnu7025 
The system does correctly pull in the Warehouse from the Sales Order. Given the Stock Reservation Entry (SRE) is made from Sales Order Items and SOI's already have the correct warehouse for each row, the same is copied into Delivery Note item.

https://github.com/user-attachments/assets/3bc60aec-0c62-47d7-a341-7b75954e9fe1




The issue you've mentioned, only happens if Sales Order Item's and its SRE's have a different warehouse.But, I'm not clear on how that scenario can happen. Could you provide an example?

**Comment by Vishnu7025** [comment]
https://github.com/user-attachments/assets/95384f9c-2430-490f-be3a-45a7f426ee09

@ruthra-kumar Yes, you are correct that the system pulls the warehouse from the Sales Order, and the Delivery Note creation process splits items based on the reserved quantities. However, the issue arises when the same item is stored in different warehouses. In such cases, instead of splitting the items by the specific warehouse as defined in the Sales Order, the system only considers the reserved quantities and not the associated warehouse. For more details, please refer to the video

**Comment by ruthra-kumar** [comment]
I've added a test case. Will merge once all test passes.

**Comment by Vishnu7025** [comment]
Thanks for adding the test case! Let me know if you need any further input. Looking forward to the merge once all tests pass.

**Pull request merged**
