### PR TITLE
Feat: Job Card Enhancements

### PR DESCRIPTION
**Pull request by rohitwaghchaure**
- Added sub-operations in the operation document

Screenshot 2021-06-20 at 12 37 48 PM

- Create Job Card based on batch size
For example the qty to manufacture is 100 in the work order and work order has the One operation Cutting with batch size as 30 then system will create 4 job cards for the operation Cutting against the work order.
Job Card 1 - 30 Qty
Job Card 2 - 30 Qty
Job Card 3 - 30 Qty
Job Card 4 - 10 Qty

User can define the batch size in the operation
Screenshot 2021-06-20 at 12 39 10 PM

- Provision to make serial no / batch no for finished goods on submission of work order

**Manufacturing Settings**
Screenshot 2021-06-20 at 12 52 12 PM

**Work order**
Screenshot 2021-06-20 at 12 51 14 PM

- Provision to track corrective operation
Screenshot 2021-06-20 at 12 53 34 PM

- Provision to create corrective Job Card after the job card completed 
image

- Provision to assign Multiple Employees to single job card

Screenshot 2021-06-20 at 12 57 54 PM

-  Provision to complete Sub Operations in the Job Card
image

### CODE REVIEW

**Comment by guilmori** [comment]
@rohitwaghchaure Awesome to see some work done in the manufacturing operations, keep it up! I wanted to chime in and ask your opinion on the current Submit logic of Job Card. It bothers me that it is different from the Work Order. What I mean is for Work Order, you submit before starting the work order. But for Job Card, you submit it to complete. Feels strange to me and is hard to explain the reasoning to the users.

**Comment by ankush** [comment]
@rohitwaghchaure  the failure seems to be related https://github.com/frappe/erpnext/pull/26205/checks?check_run_id=2905248008

**Comment by rohitwaghchaure** [comment]
Fixed

**Comment by sagarvora** [comment]
- Where is the documentation for this?
- This has been released into v13 and is breaking stuff because of the missing employee patch. It's causing a time overlap whenever trying to create another Job Card during same time for another employee.

**Pull request merged**
