### PR TITLE
feat: link old BOMs in BOM Creator

### PR DESCRIPTION
**Pull request by SvbZ3r0**
Foundational work for #38438
@rohitwaghchaure your input is extremely valuable

Pending work:
- [x] Disallow editing sub nodes where data has been pulled from an existing BOM
- [x] Qty edits on a node should propagate downwards if data is pulled from an exisiting BOM
- [x] Validation/checkpoints to ensure direct edits to the Item table do not clash with data from existing BOMs

Nice to have:
- [x] Allow choosing which BOM to use instead of automatically using the default BOM
- [ ] Play nice with BOMs that have Scrap Material (feature request for BOM Creator)
- [ ] Play nice with Items that have Subcontracting BOMs and with BOMs that have Operations (re: #38341)
- [x] RM table is read only if BOM is selected ~~Hide Raw Materials table in `Add Sub Assembly` dialog if `Use Existing BOM` is selected and there is a valid BOM present~~

### CODE REVIEW

**Comment by rohitwaghchaure** [comment]
@SvbZ3r0 Please add GIF or screenshots

**Comment by SvbZ3r0** [comment]
bomcreator1

bomcreator2

**Comment by SvbZ3r0** [comment]
bomcreatorqtyupdate

Btw, what do you guys use for sreen captures?

**Comment by rohitwaghchaure** [comment]
@SvbZ3r0 Thanks for sharing the GIFs

My feedback is as follows 
1. Use existing BOM :- Instead of this checkbox, you can add BOM field and on selection of the BOM fetch the raw materials from the respective BOM. Don't allow to change the raw materials or their quantities.
2.  Qty edits on a node should propagate downwards: I think this should be configurable, what if user want to edit the qty of parent item bu don't want to propagate downwards?

**Comment by SvbZ3r0** [comment]
Thanks for the feedback. 

1. That is how i want to do it too, but I don't know how. Is there some other place in the repo where something similar is done? Specifically, i want to know how to work with Dialog fields; adding event listeners, setting filters, refreshing the fields, etc. 

2. I will do that. Any pointers on how to make it optional?

**Comment by SvbZ3r0** [comment]
https://github.com/frappe/erpnext/assets/57280279/ce95bb49-a895-471b-a4e9-426a8f4b85b2

@rohitwaghchaure feedback implemented

**Comment by SvbZ3r0** [comment]
https://github.com/frappe/erpnext/assets/57280279/a7495226-ec8e-4705-abf0-8b20e67f1a4c

https://github.com/frappe/erpnext/assets/57280279/086b3004-07cf-4e13-b9af-83a8b0014d76

**Comment by SvbZ3r0** [comment]
Hi @rohitwaghchaure ! Anything holding this up? I might be able to work on it some more during the holiday if needed.

**Comment by SvbZ3r0** [comment]
Boop

**Pull request closed without merging**
