### PR TITLE
chore: ignore aider files

### PR DESCRIPTION
**Pull request by blaggacao**
https://aider.chat/

- really good for increasing unit test coverage **fast**

companion to: https://github.com/frappe/frappe/pull/27639

### CODE REVIEW

**Comment by blaggacao** [comment]
@ruthra-kumar For whatever reason, there seems to be a regression inhabiting current develop blocking this PR.

**Comment by ruthra-kumar** [comment]
> @ruthra-kumar For whatever reason, there seems to be a regression inhabiting current develop blocking this PR.

Yup. Seems to have started just couple days back. Will look into.

**Comment by blaggacao** [comment]
There's a Github feature called Merge Trains / Merge Queues which would have avoided this problem reliably.

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

**Comment by ruthra-kumar** [comment]
> @ruthra-kumar For whatever reason, there seems to be a regression inhabiting current develop blocking this PR.

Should be fixed by https://github.com/frappe/frappe/pull/27656

**Pull request merged**
