### PR TITLE
feat: provision to close the Work Order

### PR DESCRIPTION
**Pull request by anupamvs**
Added a provision to permanently close a Work Order. It can not be restarted once it is closed.
work-order

[no-docs]

### CODE REVIEW

**Comment by rohitwaghchaure** [comment]
@anupamvs please add description and fix sider issues

**Comment by ankush** [comment]
Now list view should hide closed WOs by default?

**Comment by anupamvs** [comment]
@mergifyio backport version-13-pre-release

**Comment by anupamvs** [comment]
@mergifyio backport version-13-hotfix

**Review by rohitwaghchaure — DISMISSED** [review]

**Pull request merged**
