### PR TITLE
feat: add login user to driver if available for notifications

### PR DESCRIPTION
**Pull request by blaggacao**
# Use Case

1. Driver is internal user (for example when employee)
2. Send notifications to driver based on data that is only available or maintained on internal users

# Proposed Solution

- [x] add internal user to driver document
- [x] take it from employee, if employee is set and make the field read-only

`no-docs`

### CODE REVIEW

**Comment by blaggacao** [comment]
image

**Comment by ruthra-kumar** [comment]
> Send notifications to driver based on data that is only available or maintained on internal users

Any example of an Internal User specific data?

**Comment by blaggacao** [comment]
> Any example of an Internal User specific data?

Yes, in our case it's Matrix ID (for matrix chat). But it could be email, phone or pager, too.

I should also note, that not every driver is also an employee. Hence, if employee isn't set, then the user field can be set freely.

However, any driver that should be incorporated into the company's notification infrastructure can be required, if not an employee, to be(come) a user.

Thus external service providers, indeed are users so they get notifications, itinerary, maps links, etc via Matrix Chat.

**Comment by blaggacao** [comment]
Maybe I should also add, that in our deployment, this works together with: https://github.com/frappe/frappe/pull/24725

That PR implements the selection of a user field as a notification target.

**Comment by ruthra-kumar** [comment]
Looks like a simple addition. Once the Framework changes are merged, then we can merge this as well.

**Comment by blaggacao** [comment]
@ruthra-kumar can you maybe help recommend the framework changes with a trusted colleague responsible for the framework? It would be nice if we where to avoid the endless and nasty stale bot loop on this one. Thx, that'd be much appreciated!

**Comment by blaggacao** [comment]
ping

**Comment by blaggacao** [comment]
@ruthra-kumar Could you please help to push for https://github.com/frappe/frappe/pull/24725 Thanks!

**Comment by blaggacao** [comment]
ping

**Comment by blaggacao** [comment]
> Go for it now. The future is promised to no one.   - Wayne Dyer

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> Fears are nothing more than a state of mind.   - Napoleon Hill 

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> What the caterpillar calls the end of the world, the master calls a butterfly.  - Richard Bach

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> Watch your thoughts, they become your words Watch your words, they become your actions Watch your actions, they become your habits Watch your habits, they become your character Watch your character, it becomes your destiny.  - 

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> Looks like a simple addition. Once the Framework changes are merged, then we can merge this as well.

@ruthra-kumar fyi, the framework changes have just been merged.

**Pull request merged**
