### PR TITLE
Added Shipping Terms and Shipping Couriers to Customer Address

### PR DESCRIPTION
**Pull request by dottenbr**
Added Shipping Terms and Shipping Couriers as new DocTypes to Customer Address under Selling Module if 'Primary Shipping Address = true'. I believe this improves the system for everybody and thus should be included in the default after careful evaluation of my potentially flawed code and after testting. Hope you will enjoy this contribution.

### CODE REVIEW

**Comment by anandpdoshi** [comment]
Hi @dottenbr 
It looks like "Shipping Courier" is more like "Shipment Tracking" and "Shipping Term" seems like "Shipping Courier" selection. Is it the intended use?

**Comment by dottenbr** [comment]
@anandpdoshi the idea is to have "Shipping Couriers" defined such as DHL, UPS, Fedex. At the moment the only reason for this would be so we dont always write the courier as a Data field in every "Shipping Term". Additionally in case we implement this later we could read the Tracking URL from the courier field to create a tracking URL that can be printed on the delivery note or sent to the customer in the email. So "Shipment Tracking" is not part of what I have done here yet.

Can you check the follwing:

- [ ] Make sure the "Shipping Term" is printed on "Delivery Note" and "Sales Invoice"
- [ ] Make sure the "Shipping Term" is printed on "Sales Order Report"

**Comment by negini** [comment]
i believe it's important if possible to manage and calculate shipping cost / Couriers / Tracing number   not only in sales ,in purchasing too .

**Comment by rmehta** [comment]
@dottenbr what is next in this? shall I close this?

**Pull request closed without merging**
