### PR TITLE
Update Item Price with More Features

### PR DESCRIPTION
**Pull request by bcornwellmott**
Continuing the work done with https://github.com/frappe/erpnext/pull/8511. 

I'm having trouble with the validate_duplicates method in item_price. It is not finding duplicates when there should be. I think it's because of the date comparison, but I'm not certain. Any suggestions would be appreciated.

Other than that it appears good to go. I'll create a gif of it once the duplicates thing starts working.

### CODE REVIEW

**Comment by mbauskar** [comment]
@bcornwellmott,

Thanks for contributing,

Codecy and Travis tests are failing can you please check and fix the same, Closing the PR for now

**Comment by dottenbr** [comment]
#8456 and #10144 are related. I am not sure if you have considered when a price is added to the price list by submitting a quotation if that saves it correctly now.

**Comment by rmehta** [comment]
@kickapoo are you planning to work on this?

**Comment by kickapoo** [comment]
@rmehta Currently no. It pushed for later in our team schedule (I think 2 week from now).

**Comment by nabinhait** [comment]
@bcornwellmott Thanks for the PR. Am closing this and will continue reviewing https://github.com/frappe/erpnext/pull/11464, which addresses the same issue. Please add your valuable inputs there (#11464).

**Pull request closed without merging**
