### PR TITLE
feat: option to disable Item Tax Template and Tax Category

### PR DESCRIPTION
**Pull request by barredterra**
When **Item Tax Template** or **Tax Category** become obsolete we need some option to get rid of them. They might have been used in thousand of items and transactions, so deleting them is not possible.

This PR adds the "Disabled" checkbox to **Item Tax Template** and **Tax Category**, similar to Sales/Purchase Taxes and Charges Template.

### Effect

- When disabled, they can no longer be selected in **Item** master or transaction
- Exception: If **Item Tax Template** is configured in **Item** master, it can still be selected in a transaction, even if the **Item Tax Template** is disabled.

<details>
    <summary>Item Tax Template</summary>
    
    
</details>

<details>
    <summary>Tax Category</summary>

</details>

<details>
    <summary>Item</summary>

</details>

<details>
 <summary>Transaction</summary>

</details>

### CODE REVIEW

**Comment by ankush** [comment]
LGTM. Docs for enable/disable seems kinda too much. Isn't it self-explanatory? :P

**Comment by barredterra** [comment]
@ankush maybe the special case would be interesting to know. Otherwise (or  anyways) we'll get complaints that disabled item tax templates can be selected in a transaction.

**Comment by deepeshgarg007** [comment]
Merging this PR. Failing unit tests are unrelated to this PR and failing on other PRs as well

**Comment by barredterra** [comment]
@Mergifyio backport version-13-hotfix

**Pull request merged**
