### PR TITLE
feat: Turkish Chart Of Accounts

### LINKED ISSUE #41536: Turkey Create chart Of Account
Adaptation of TURKEY's uniform chart of accounts to ERPNext

### PR DESCRIPTION
**Pull request by fzozyurt**
Turkey Chart Of Account Plan Created In JSON Format

no-docs

Setup Wizard:
image
image

Company:
image
image
image

Closes #41536

### CODE REVIEW

**Comment by fzozyurt** [comment]
@deepeshgarg007 @ruthra-kumar @barredterra Can you support the merger?

**Comment by fzozyurt** [comment]
@barredterra I updated Commit, can I get support again regarding approval?

**Comment by fzozyurt** [comment]
@ruthra-kumar @barredterra  Could you add "backport version-15-hotfix" or "backport develop" tag please ?

**Comment by fzozyurt** [comment]
@barredterra Hi,
My Pull Request has not been processed for 1 week. Am I making a mistake somewhere? I realized that a label is required, you added it as well, but the process is not advanced by mergify bot. I don't have much experience in this regard. For this reason, can you support me?

**Comment by barredterra** [comment]
Personally, I review pull requests in my free time, so I can't guarantee if and when  I'll find time to review yours. In general, unless you're paying someone, PRs are processed on a best effort basis. At first glance, this pull request seems to be fine!

**Comment by fzozyurt** [comment]
> Personally, I review pull requests in my free time, so I can't guarantee if and when I'll find time to review yours. In general, unless you're paying someone, PRs are processed on a best effort basis. At first glance, this pull request seems to be fine!

Sorry, I didn't know there was a manual check process. I thought this would be done automatically with Mergify and was worried I was missing something. Thank you for your support.

**Comment by barredterra** [comment]
@TurkerTunali, @yrestom does this look fine to you?

**Comment by TurkerTunali** [comment]
> @TurkerTunali, @yrestom does this look fine to you?

Yes it looks fine.

**Comment by barredterra** [comment]
@fzozyurt is it on purpose that this CoA contains almost no accounts, only groups of accounts? So, using this CoA you cannot start to use the system, you first have to create hundreds of accounts manually.

Also, if you add some accounts, please specify the _Account Type_ for the most important ones, like `"account_type": "Cash"`, `"account_type": "Bank"`, etc.

**Comment by fzozyurt** [comment]
> @fzozyurt is it on purpose that this CoA contains almost no accounts, only groups of accounts? So, using this CoA you cannot start to use the system, you first have to create hundreds of accounts manually.
> 
> Also, if you add some accounts, please specify the _Account Type_ for the most important ones, like `"account_type": "Cash"`, `"account_type": "Bank"`, etc.

@barredterra I made the update you mentioned. Can you check again?

**Pull request merged**
