### PR TITLE
De-clutter, Regionalize and Domainify Accounts Module Configuration

### PR DESCRIPTION
**Pull request by agritheory**
**Problem 1**:
The "Billing" Section of the Accounts config contains items that are 1) not related to billing and 2) has too many entries. 

image

Fix:
image

**Problem 2**:
In the config file, it is possible to positively select entires based on country, but not to hide sections, notably the GST section in the accounts module. This section only effects users in India and should be hidden if there is not an Indian company record.
image

**Problem 3**: 
There are enough Retail functions on this page that they should be consolidated:
image

**Problem 4**:
Subscriptions are way down at the bottom and this ins inconvenient for service companies. If the Service Domain is active it should be moved closer to the top. Likewise Retail. 

accounts-new-layout-services

Retail-optimized layout. 
accounts-new-layout-retail

### CODE REVIEW

**Comment by parsimonyERP** [comment]
👍

**Comment by agritheory** [comment]
I've run Travis three times now and get the same errors, which are not related to my code. @shreyashah115 What is your recommended approach?

**Comment by shreyashah115** [comment]
@agritheory I'd recommend to send the PR on `staging-fixes`?

**Comment by agritheory** [comment]
So I changed the base branch and now it includes a bunch of extra commits. Will reopen.

**Comment by agritheory** [comment]
@shreyashah115 I'm going to close and redo this. Switching the base branch brought in all the commits from develop

**Pull request closed without merging**
