### PR TITLE
fix(Patient): Add system user permissions in Patient Master

### PR DESCRIPTION
**Pull request by hrwX**
- Add system user permissions in Patient Master

### CODE REVIEW

**Review by nabinhait — DISMISSED** [review]

**Comment by nabinhait** [comment]
@hrwX Can you please fix the merge conflict?

**Comment by Anurag810** [comment]
@hrwX Feels Duplicate of #19142

**Comment by hrwX** [comment]
> @hrwX Feels Duplicate of #19142

Can you elaborate your PR ?? There's no context or any description!

**Comment by hrwX** [comment]
> @hrwX Can you please fix the merge conflict?

Resolved the merge conflicts

**Review by nabinhait — APPROVED** [review]

**Pull request merged**
