### PR TITLE
feat: add accounting dimensions in ledger summary reports

### PR DESCRIPTION
**Pull request by Sugesh393**
Issue:
[35884](https://github.com/frappe/erpnext/issues/35884)

Solution:
Addition of Accounting Dimensions filters in Customer Ledger Summary and Supplier Ledger Summary Reports.

Screenshot from 2024-12-05 19-05-58

Screenshot from 2024-12-05 19-06-30

`no-docs`

### CODE REVIEW

**Comment by Sugesh393** [comment]
Hi @ruthra-kumar
I've got Documentation Required check failed because of No Documentation link found.
there wasn't any documentation available for Customer and Supplier Ledger Summary, am I need to create one?

**Comment by ruthra-kumar** [comment]
> Hi @ruthra-kumar I've got Documentation Required check failed because of No Documentation link found. there wasn't any documentation available for Customer and Supplier Ledger Summary, am I need to create one?

No required

**Comment by ruthra-kumar** [comment]
@Sugesh393 

Does this need backporting?

**Comment by Sugesh393** [comment]
@ruthra-kumar 

Not required

**Comment by diptanilsaha** [comment]
@mergifyio backport version-15-hotfix

**Pull request merged**
