### PR TITLE
refactor: age range in one field

### PR DESCRIPTION
**Pull request by Sanket322**
Refactored age range input from four fields to a single comma-separated field

**Before : Four Age range Fields**
image

**After : One Age range field**
image

### CODE REVIEW

**Comment by ruthra-kumar** [comment]
@Sanket322 
Could you explain why a single comma separated value?

**Comment by Sanket322** [comment]
Previously, the system was limited to only four ranges. However, now it can accommodate more or fewer ranges as needed, increasing flexibility.

**Comment by vorasmit** [comment]
@nabinhait / @ruthra-kumar ,

If this implementation is acceptable we'll extend this to other ageing reports.

**Comment by nabinhait** [comment]
> @nabinhait / @ruthra-kumar ,
> 
> If this implementation is acceptable we'll extend this to other ageing reports.

Yes, please go ahead.

**Pull request merged**
