### PR TITLE
feat(customer): add button to quick-create sales order and quotation

### PR DESCRIPTION
**Pull request by blaggacao**
# Context

Consider the following business flow:

1. Customer calls in
2. Sales Agent: "What's your name?"
3. "Max Mustermann"
4. Sales Agent searches in global field, finds customer and opens it to have the 360 view on this incoming caller
5. Customer wants a quote or even a direct sale

Now, the agent has to ~~leave the context of the customer and open a corresponding document and then **search again** for the customer in the appropriate field.~~ click through tabs.

The agent uses a lot of valuable time while having the customer on the phone and letting her wait unnecessarily.

## Proposed Solution

- Add quick actions to customer to either:
  - Create a Sales Order for that Customer
  - Create a Quotationn to that Customer

In the described buisness flow, this considerably speeds up the sales agent's agility while talking to the customer on the phone.

### CODE REVIEW

**Comment by bosue** [comment]
Hmm. All of these actions are already present in “Connections,” aren’t they?

IMG_1774

> Now, the agent has to leave the context of the customer and open a corresponding document and then search again for the customer in the appropriate field.

Really? Do I miss something?

We might want to discuss whether one or another form of the Dashboard should represent the top tab. We might want to think about making all connections accessible through the “Create…” menu. But – unless I‘m really missing out something obvious – I think we need to rethink the whole thing and come up with a general idea, rather than add this and that…

**Comment by blaggacao** [comment]
> All of these actions are already present in “Connections,” aren’t they?

That may well be, however, the purpose of a dashboard is different from a "quick action" in guiding the user flow.

- The dashboards aims to give the user an overview of the situation (including [creation-]links to the cited documents).
- The quick actions aims to guide the user through the primary available actions.

> ~~Now, the agent has to leave the context of the customer and open a corresponding document and then search again for the customer in the appropriate field.~~

Corrected! Thanks! :smile: :handshake: -- That was not accurate, rather the user has to navigate tabs and dashboards. 


> We might want to discuss whether one or another form of the Dashboard should represent the top tab. We might want to think about making all connections accessible through the “Create…” menu. But – unless I‘m really missing out something obvious – I think we need to rethink the whole thing and come up with a general idea, rather than add this and that…

- previously, it was: 
image

- now, it is: 
image

Arguably, the added items are among _the_ most important things that anybody would want to do to a customer. :smile: 

But more than one of commonality, there's of course no principled argument of doing a sales order vs a e.g. subscrpition. It dedpends a bit on the level of customization that ErpNext would pre-suppose to be useful. For one such common scenario, though, I find users may reject it because "I can't make a sales order from a customer master".

I don't mind if this PR wouldn't gather consensus but it struck me as useful enough to extract it out of our customization for consideration.

**Comment by bosue** [comment]
Arguably, listing “Create Price Rule” as the only “Create” action available from the front page doesn’t make any sense.

But adding an arbitrary number of items to the list doesn‘t fix the underlying problem either.

I‘m not saying, Sales Order shouldn‘t be there. My underlying question is:

Do we want to replicate all Dashboard actions in the “Create“ menu, or just a subset, or none at all?

If yes, we want to replicate all or a clearly specified subset of the Dashboard actions, then there should be a provision to do this in a systematic way without redundancies and arbitrary implementations. Either all dashboard actions are automatically replicated there or we mark a certain subset as “important” to have it replicated in the “Create” menu.

See, I’m not against. I’d just like some more sane overall structure instead of dozens of one-off UI decisions… 🤗

**Comment by blaggacao** [comment]
> If yes, we want to replicate all or a clearly specified subset of the Dashboard actions, then there should be a provision to do this in a systematic way without redundancies and arbitrary implementations. Either all dashboard actions are automatically replicated there or we mark a certain subset as “important” to have it replicated in the “Create” menu.

That sounds like a pretty solid idea, actually. :+1: (but maybe for a future overhaul :wink: )

**Comment by bosue** [comment]
Let‘s go ahead with this PR.
It may be a stop-gap ahead of a more generic solution, but there‘s nothing wrong with it.

**Comment by barredterra** [comment]
> there should be a provision to do this in a systematic way without redundancies and arbitrary implementations. 

I added a change that makes this a tiny bit more systematic. All creation methods are defined in a single place and are used by both connections ("+") and custom "Create" buttons.

**Comment by blaggacao** [comment]
> I added a change that makes this a tiny bit more systematic. All creation methods are defined in a single place and are used by both connections ("+") and custom "Create" buttons.

Nice! Did you check that the `!__islocal` condition is still semantically satisfied in the other code path to display these buttons?

**Comment by barredterra** [comment]
Connections are not available for local docs, so should be fine

**Pull request merged**
