### PR TITLE
Healthcare Module

### PR DESCRIPTION
**Pull request by pjamsheer**
- [x] Add documentation pages
- [x] Fix Codacy Issues
- [x] Tag all DocTypes as beta

Added a bounty!

https://www.bountysource.com/issues/44823966-healthcare-module-cleanup

### CODE REVIEW

**Comment by rmehta** [comment]
👍 

- [ ] Can you add a quick video of the workflow?
- [ ] Fix Codacy Errors

**Comment by pjamsheer** [comment]
appointment_inv
consultation
labtest_inv
physician_schedule

**Comment by vrms** [comment]
@pjamsheer have you seen there is a small conflict preventing the merge? Sorry, but I don't understand the code, so I can not help with it directly.

**Comment by vrms** [comment]
previous conflict is solved, all test are passed since a week. 
Anything else standing in the way to merge @rmehta ?

**Comment by rmehta** [comment]
I will test and merge this next week! Thanks for the contribution 👍

**Pull request closed without merging**
