### PR TITLE
fix:  #31562 

### LINKED ISSUE #31562: Renaming cost center automatically adds old company abbreviation
### Information about bug

ERPnext automatically adds the company abbreviation after each cost center. 
After a company abbreviation was changed, renaming a cost center does not work properly. ERPnext still adds the old company abbreviation. It is impossible to remove this part of the name, since ERPnext handles it internally (only the front part of the cost center is editable - not the abbreviation itself). 

A similar issue was previously raised here:
https://github.com/frappe/erpnext/issues/26746
This PR addresses a similar issue but doesn't solve the problem.
https://github.com/frappe/erpnext/pull/27766

**Suggested solution:** 
Allow the modification of the abbreviated part of the name which is currently impossible.

### Module

accounts

### Version

ERPNext: v13.35.0 (HEAD)
Frappe Framework: v13.35.0 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by vamagithub**
### Fixed  -  Renaming cost center automatically adds old company abbreviation #31562 

`closes #31562`

###  Screen-cast of the problem

[Screencast from Monday 18 July 2022 04:24:07  IST.webm](https://user-images.githubusercontent.com/16986940/179497232-e10419d3-dff4-4b49-8a5a-58c3253d70c3.webm)

### Screen-cast (after the fix)

[Screencast from Monday 18 July 2022 04:25:13  IST.webm](https://user-images.githubusercontent.com/16986940/179497660-0f7a6645-cac9-4912-b820-a59f079d3140.webm)

### CODE REVIEW

**Comment by vamagithub** [comment]
Let me know if this works

**Comment by blewsky** [comment]
Any updates on this?

**Comment by vamagithub** [comment]
> Any updates on this?

Waiting for it to Merge

**Comment by deepeshgarg007** [comment]
@vamagithub in the current version the company abbreviation cannot be changed once set, so I believe this issue doesn't exist anymore, closing this PR

**Comment by blewsky** [comment]
@deepeshgarg007 Please reopen the PR and merge it. The bug still persists in v13.36.4. We changed the company name before https://github.com/frappe/erpnext/pull/27766 was merged and cannot revert it now. This bug is really annoying and confusing to our employees. Please merge @vamagithub 's fix. Only 1 line of code has been changed and there doesn't seem to be a downside of this PR. Thanks for your understanding.

**Comment by blewsky** [comment]
Hi @deepeshgarg007 (or @nextchamp-saqib, @ruthra-kumar)
Did you check the code that was changed  by this PR? In my opinion, @vamagithub's code change (1 line!) in the erpnext/accounts/utils.py file (https://github.com/vamagithub/erpnext/commit/2b9d53829a21d28d27df9e4eb9536d5f9b77ec8e) is a cleaner solution. The previous way of setting the name was not a clean implementation and let to many unnecessary problems. 
I do not see any downside in accepting this code suggestion by @vamagithub. Would greatly appreciate if this PR was reopened and merged. Thanks

**Pull request closed without merging**
