### PR TITLE
fix: sales order not saving due type mismatch in promo scheme (#24748)

### LINKED ISSUE #24748: Sales order never saves giving “TypeError: '<' not supported between instances of 'NoneType' and 'float'” after creating Transaction based promo scheme
## Description of the issue

Transaction based promotional scheme is not working as expected, when creating a Sale order you can never save it due this comparison bug blocking the save everytime!

## Context information (for bug reports)

**Output of `bench version`**
```
erpnext 12.18.0
erpnext 12.18.0
```

## Steps to reproduce the issue

1. Create promotional scheme
2. Select Apply On “Transaction”
3. Select “Selling” Party
4. Insert Valid From/Upto Dates
5. Add Row in discount slabs (10-50 qty) with discount 5%.
6. Save.
7. Go to Sale Order
8. Try to create order of any product with the mentioned qty.
9. You will never be able to save due error “TypeError: '<' not supported between instances of 'NoneType' and 'float'”

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "/workspace/development/frappe-bench/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/__init__.py", line 1071, in call
    return fn(*args, **newargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 273, in save
    return self._save(*args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 296, in _save
    self.insert()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 230, in insert
    self.run_before_save_methods()
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 896, in run_before_save_methods
    self.run_method("validate")
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/workspace/development/frappe-bench/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/workspace/development/frappe-bench/apps/erpnext/erpnext/selling/doctype/sales_order/sales_order.py", line 36, in validate
    super(SalesOrder, self).validate()
  File "/workspace/development/frappe-bench/apps/erpnext/erpnext/controllers/selling_controller.py", line 40, in validate
    super(SellingController, self).validate()
  File "/workspace/development/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 21, in validate
    super(StockController, self).validate()
  File "/workspace/development/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 115, in validate
    apply_pricing_rule_on_transaction(self)
  File "/workspace/development/frappe-bench/apps/erpnext/erpnext/accounts/doctype/pricing_rule/utils.py", line 470, in apply_pricing_rule_on_transaction
    if d.validate_applied_rule and doc.get(field) < d.get(pr_field):
TypeError: '<' not supported between instances of 'NoneType' and 'float'
```

## Additional information

Ubuntu 20.04 with official Frappe/ERPNext on Docker image

promo_scheme_bug

## Simple fix

I can fix with a pull request, the last line should look like for everything to work as expected:

if (d.validate_applied_rule and doc.get(field) is not None) and doc.get(field) < d.get(pr_field)

### PR DESCRIPTION
**Pull request by abdouz**
closes #24748

### CODE REVIEW

**Review by ankush — APPROVED** [review]
Tested. LGTM. 👍

**Comment by ankush** [comment]
Hi @abdouz thanks for your contribution, can you please send another PR to `develop` branch too? 

As this issue seems to exist on `develop` too: https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/doctype/pricing_rule/utils.py#L474

**Comment by abdouz** [comment]
@ankush Sure will do, for develop and version-13 or develop only?

**Comment by ruchamahabal** [comment]
@abdouz send a fix to develop branch

**Pull request merged**
