### PR TITLE
fix: reconcile invoice against credit note.

### LINKED ISSUE #35603: Cannot reconcile multi-currency Purchase Invoice against Purchase Invoice Return
### Information about bug

# Use Case
1. Purchase Goods from Supplier
2. Pay Supplier in Full
3. Return Partially Defective Goods
4. Purchase Goods from Supplier
5. Apply Defective Credit to new Purchase Invoice.

# Steps to Reproduce
1. Create a Purchase Invoice $1,000.00 @ 1.35
6. Create Purchase Invoice (Return) $100.00 @ 1.40  **Important: Not against the original invoice.**
7. Attempt to Reconcile the the Purchase Invoice (Return) against the Purchase Invoice.

image

# Cause
During the payment reconciliation process
https://github.com/frappe/erpnext/blob/0c12d4d3c5ebb7d5bd6cf70dfde026c810a7b66a/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py#L330-L331
is always executed, creating a journal entry for the difference in exchange rate.

Then this is executed:
https://github.com/frappe/erpnext/blob/0c12d4d3c5ebb7d5bd6cf70dfde026c810a7b66a/erpnext/accounts/doctype/payment_reconciliation/payment_reconciliation.py#L336-L337

The exchange gain and loss difference need's to be booked in the above transaction for the payment reconciliation to become successful.

Related: https://github.com/frappe/erpnext/issues/34680

### Module

accounts

### Version

ERPNext: v14.0.0-dev (HEAD)

Frappe Framework: v15.0.0-dev (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by dj12djdjs**
closes: https://github.com/frappe/erpnext/issues/35603

### CODE REVIEW

**Comment by ruthra-kumar** [comment]
@dj12djdjs 

This approach doesn't link the Invoice with the Exchange gain/loss amount.

The Invoice will still be missing that Exchange Gain/Loss amount as there is no reference to it. Until it is linked, the purchase invoice will have outstanding.

A separate JE of type `Exchange Gain/Loss` should be created as well.

**Comment by dj12djdjs** [comment]
@ruthra-kumar I'm not sure I understand what you mean the exchange gain/loss is not linked? It is linked via the journal entry reconciling the invoice against the credit.

Example:
image


From there the invoice is now closed:
image


I believe the original code before this PR was attempting to separate the transaction across two journal entries. But I don't think it's possible as one of the journal entries will never be balanced this way.

**Comment by ruthra-kumar** [comment]
> I believe the original code before this PR was attempting to separate the transaction across two journal entries. But I don't think it's possible as one of the journal entries will never be balanced this way.

Got it. Will test some cases locally and will update you.

**Comment by ruthra-kumar** [comment]
LGTM

**Review by ruthra-kumar — APPROVED** [review]

**Comment by dj12djdjs** [comment]
@ruthra-kumar Just curious about the draft. Did you find any issues with this PR?

**Comment by ruthra-kumar** [comment]
@dj12djdjs Tested on few edge cases, like, allocating a payment and debit note at the same time. Looks to be working.
Thanks for the Fix.

**Pull request merged**
