### PR TITLE
Improved Greek Translations for v5.0

### PR DESCRIPTION
**Pull request by gabtzi**
Hi, I've just finished the Greek translations for ERPNext v5.0 if you want to pull them. 
They work OK in my setup.

### CODE REVIEW

**Comment by gabtzi** [comment]
OK no problem thank you very much.

I just chose to add it here as a pull request  instead of using the tool in the url you shared because the editing system there would take too much longer than updating the csv file directly with a csv editor. 
Keep in mind a few terms might not be acurately translated due to lack of specific context but in overall it's much more understandable than google translation.

**Comment by pdvyas** [comment]
Okay, we are trying to improve the UX of the tool. Right now what I do is (tomorrow) update all strings from your pull request that are unedited in the translator.

**Comment by gabtzi** [comment]
Hello,

if you could also export the strings that are edited in the translator (about 100 iirc) I can also do a secondary check on them if you want to check if they're proper Greek or if they need to be revised since I'm a native speaker with a Cambridge and MIchigan Proficiency Certificate in English

**Comment by pdvyas** [comment]
Imported into translator. Will merge new translations to v5 today.

**Pull request closed without merging**
