### PR TITLE
fix: not able to select the item code in work order

### LINKED ISSUE #25922: material request has AttributeError: 'NoneType' object has no attribute 'get'
Hello, Team.

After update version 

image

Traceback (most recent call last):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/api.py", line 54, in handle
    return frappe.handler.handle()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/handler.py", line 67, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1174, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 54, in search_link
    search_widget(doctype, txt.strip(), query, searchfield=searchfield, page_length=page_length, filters=filters, reference_doctype=reference_doctype, ignore_user_permissions=ignore_user_permissions)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 90, in search_widget
    raise e
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 81, in search_widget
    searchfield, start, page_length, filters, as_dict=as_dict)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 1174, in call
    return fn(*args, **newargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/desk/search.py", line 223, in validate_and_sanitize_search_inputs
    return fn(**kwargs)
  File "/home/frappe/frappe-bench/apps/erpnext/erpnext/controllers/queries.py", line 219, in item_query
    if filters.get('supplier'):
AttributeError: 'NoneType' object has no attribute 'get'

image

### PR DESCRIPTION
**Pull request by rohitwaghchaure**
backport https://github.com/frappe/erpnext/pull/25915

### CODE REVIEW

**Comment by ankush** [comment]
might not be required for pre-release: https://github.com/frappe/erpnext/pull/25875  was part of the last release so it shouldn't be causing issue 🤔

**Comment by sammish** [comment]
Hello, Team 

Possible to Hot fix?

**Comment by nabinhait** [comment]
> might not be required for pre-release: #25875 was part of the last release so it shouldn't be causing issue 🤔

The error is coming from Material Request, you fixed it for Work Order only.

**Review by nabinhait — APPROVED** [review]

**Comment by sammish** [comment]
@nabinhait 

Possible to hot-fix release ? It's fixed material request as well.

**Comment by nabinhait** [comment]
> @nabinhait
> 
> Possible to hot-fix release ? It's fixed material request as well.

Yes, it will fix material request as well. I will take a release tonight.

**Comment by sammish** [comment]
> > @nabinhait
> > Possible to hot-fix release ? It's fixed material request as well.
> 
> Yes, it will fix material request as well. I will take a release tonight.

Thank you so much

**Pull request merged**
