### PR TITLE
fix: spec mobile and email fields for notifications

### PR DESCRIPTION
**Pull request by blaggacao**
This is required to be eligible as receiver in Frappe/Notifications

### CODE REVIEW

**Comment by blaggacao** [comment]
ping

**Comment by blaggacao** [comment]
> Go for it now. The future is promised to no one.   - Wayne Dyer

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> Fears are nothing more than a state of mind.   - Napoleon Hill 

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> What the caterpillar calls the end of the world, the master calls a butterfly.  - Richard Bach

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> Watch your thoughts, they become your words Watch your words, they become your actions Watch your actions, they become your habits Watch your habits, they become your character Watch your character, it becomes your destiny.  - 

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> You may say Im a dreamer, but Im not the only one, I hope someday you will join us, and the world will live as one.  - John Lennon

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> I have just three things to teach: simplicity, patience, compassion. These three are your greatest treasures.   - Lao Tzu 

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
@ruthra-kumar An easy one :smile: context: https://github.com/frappe/frappe/pull/24725, specifically:
- https://github.com/frappe/frappe/pull/24725/files#diff-a2945bf21739af1497474a3e0c35cb846f6f99b5b678880e461f341b751ef1d3R87
- https://github.com/frappe/frappe/pull/24725/files#diff-a2945bf21739af1497474a3e0c35cb846f6f99b5b678880e461f341b751ef1d3R91

**Comment by blaggacao** [comment]
> The important thing is this: to be able at any moment to sacrifice what we are for what we could become.  - Charles Dubois

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> Obstacles are those frightful things you see when you take your eyes off your goal.  - Henry Ford

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> Our distrust is very expensive.  - Ralph Emerson

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
> An invincible determination can accomplish almost anything and in this lies the great distinction between great men and little men.  - Thomas Fuller 

---

<sub>Kindly help move this PR forward. Many thanks from Yours Sincerely!</sub>

**Comment by blaggacao** [comment]
@Mergifyio backport version-15-hotfix

**Comment by ruthra-kumar** [comment]
@blaggacao 
What is the purpose of adding 'Options' on a Data field?

**Comment by blaggacao** [comment]
Data fields are detected for eligibility in notifications based on the value of the Option field. E.g.:

- `Email` -> eligible for email notificación 
- `Phone` / `Mobile` -> eligible for SMS / Whatsapp notification
- etc

**Comment by blaggacao** [comment]
This was already the case (eg. for `Phone` / `Mobile`) prior to https://github.com/frappe/frappe/pull/24725 but is there augmented further.

**Pull request merged**
