### PR TITLE
test: get leave allocation records query

### PR DESCRIPTION
**Pull request by ruchamahabal**
Added tests for the query changed in https://github.com/frappe/erpnext/pull/30118 as per this discussion: https://github.com/frappe/erpnext/pull/30118#issuecomment-1073801909

### CODE REVIEW

**Comment by ruchamahabal** [comment]
CI failing due to the changes made in what `frappe.db.exists` returns: 

image

Probably this PR: https://github.com/frappe/frappe/pull/16200 (credits for the guess: @ankush)

**Before**:

image

**After**:

image

We can rectify the usage here, but many other apps might be dependent on this behavior. Thoughts? @surajshetty3416 @barredterra

**Comment by barredterra** [comment]
@ruchamahabal good question, feel free to revert my PR for the time being.

I would, however, argue that somebody misused `frappe.db.exists` when they actually needed `frappe.get_all`. Here's the code in question:

https://github.com/frappe/erpnext/blob/01fd3adedf289aa18947310f06a1b6b38ba7ecd6/erpnext/crm/doctype/appointment/test_appointment.py#L10-L20

This code would actually improve with the new behavior because we could get rid of the `[0][0]` indexes.

**Comment by ankush** [comment]
I agree that this is bad usage, even this API of `exists` should have never returned anything other than Boolean, but alas we can't break this because of 

https://www.hyrumslaw.com/ 

Let's limit this to v14 maybe?

**Comment by barredterra** [comment]
@ankush I agree. Backporting was not intended anyways. I'll send a fix for mentioned issue.

**Comment by ankush** [comment]
I'd propose keeping old behaviour that returned get_all style results but limit to 1 entry since that's what `exists` signifies, unlikely that anyone is using exists to do exactly what get_all does. (Fetching all rows is really stupid too 😆)



@gavindsouza @surajshetty3416

**Comment by barredterra** [comment]
@ankush, the behavior was not consistent before, a mix of `get_value` and `get_all`. The goal of my PR was to keep possible return types simple and limited: `str or None`.

**Comment by ankush** [comment]
keeping the breaking change and added note in https://github.com/frappe/frappe/wiki/Migrating-to-Version-14 (this needs to be updated with all breaking changes 🙈 )

**Pull request merged**
