### PR TITLE
chore: rename daily_depreciation in asset to depreciation_amount_based_on_num_days_in_month [dev]

### PR DESCRIPTION
**Pull request by anandbaburajan**
Renaming `daily_depreciation` in asset's finance book table to `depreciation_amount_based_on_num_days_in_month`.

### CODE REVIEW

**Comment by bosue** [comment]
@anandbaburajan: Sorry for being late to the party, but wouldn‘t `daily_prorated_depreciation` have been sufficiently clear?

I actually think it would have been more correct than this long name, as not just the number of days per month are taken into account, but also the exact from and to days:

`daily_depr_amount * (date_diff(to_date, from_date) + 1)`

IMO, this is daily pro-rated, not just based on num days in month.

If we‘re talking num days in months, we also need to know how the base days per year are defined (360, 365 or act). But that‘s not where we are atm…

**Comment by anandbaburajan** [comment]
@bosue oh, makes sense. Maybe `Daily pro-rated depreciation amount` would make more sense, right? `Daily depreciation` or `Daily pro-rated depreciation` might make it seem like depreciation is happening daily, which is not the case, and which is what triggered me to open the PR.

**Comment by bosue** [comment]
In German we have a word “tagesgenau“ which is not the same as “täglich“ (= “daily”) and means “precise to the day”.

In English I fear we have to live with either “Daily pro-rated depreciation” which doesn’t suggest “Daily depreciation” at all. In the contrary, if it really happens daily, then there’s no point in pro-rating it.

Less idiomatic alternatives might be “Daily accrual depreciation” or “Daily-based depreciation” though.

“Pro-rated depreciation” without any hint at whether individual days of a month or individual months of a year are pro-rated, probably wouldn’t help.

**Comment by anandbaburajan** [comment]
> “Pro-rated depreciation” without any hint at whether individual days of a month or individual months of a year are pro-rated, probably wouldn’t help.

I meant `Daily pro-rated depreciation amount`. Edited my comment right before you commented 😄.

> “Daily pro-rated depreciation” which doesn’t suggest “Daily depreciation” at all

Hmm, I don't think so 😄.

> In the contrary, if it really happens daily, then there’s no point in pro-rating it.

That makes sense, but `Daily depreciation` or `Daily pro-rated depreciation` still does feel like depreciation is happening daily, hence confusing the user. However for some reason which I can't explain, `Daily pro-rated depreciation` does feel better than `Daily pro-rated depreciation amount`.

> In German we have a word “tagesgenau“ which is not the same as “täglich“ (= “daily”) and means “precise to the day”.

Interesting.

**Comment by bosue** [comment]
“Daily pro-rated depreciation amount” (daily_prorated_amount) might work, but might also suggest the amount per single day.

“Prorate depreciation on daily basis” (prorate_on_daily_basis) might be an even better alternative. Or “Depreciate based on daily pro-rata” (daily_prorata_based).

No matter what, all of these are better than the original “Daily depreciation” or – sry to say – “Depreciation based on num days in month”… 💁🏻‍♂️

**Pull request merged**
