### PR TITLE
refactor: E-commerce (port to develop)

### PR DESCRIPTION
**Pull request by marination**
Depends on https://github.com/frappe/frappe/pull/15831

----------

front port of https://github.com/frappe/erpnext/pull/24603

ToDo:

- [x] Finish Porting all commits (fixes and from https://github.com/frappe/erpnext/pull/24603)
- [x] Test functionality manually (need to fix build issue on cart and item full page)
- [x] fix server side tests (cherry pick fixes)

### CODE REVIEW

**Comment by marination** [comment]
No e-commerce tests failing.
Tests failing (datetime issues) due to https://github.com/frappe/frappe/pull/15560, to be fixed in https://github.com/frappe/frappe/pull/15847

**Review by ankush — APPROVED** [review]

**Comment by ankush** [comment]
ignoring unrelated failures, migrations tested locally. LGTM.

**Comment by marination** [comment]
@Mergifyio backport version-14-pre-release

**Comment by marination** [comment]
https://github.com/Mergifyio backport version-14-beta-pre-release

**Comment by marination** [comment]
@Mergifyio backport version-14-beta-pre-release

**Pull request merged**
