### PR TITLE
Update item_table_description.html to fix img width issue #3412

### PR DESCRIPTION
**Pull request by sbkolate**
here is more details
https://github.com/frappe/erpnext/issues/3412

### CODE REVIEW

**Comment by nabinhait** [comment]
@anandpdoshi can you check this?

**Comment by rmehta** [comment]
the real problem is setting max-width in a float environment. need to check again.

**Comment by sbkolate** [comment]
@rmehta 
This issue is still exist in v5.
But max-width correctly working in v4.
Can you please lookout this?

**Comment by rmehta** [comment]
Works fine for me, is this a custom format?

screen shot 2015-07-03 at 10 03 02 am

**Comment by rmehta** [comment]
Sees like a mozilla bug :(

https://github.com/twbs/bootstrap/issues/10690

Fixed.

**Pull request closed without merging**
