### PR TITLE
fix: updater tigger notifications on status updates & perf

### PR DESCRIPTION
**Pull request by blaggacao**
**Prior Limitations**

- The utilization of `frappe.db.sql` for status updates on various fields circumvented the standard document lifecycle.
- As a consequence, these updates were not subject to crucial document hooks, including those responsible for triggering notifications.
- This oversight resulted in the inability to automate important communications, such as triggering an email notification when the `per_delivered` field on a Sales Order exceeded 90% (a critical juncture for order renewal reminders).

**Enhanced Functionality**

- The system now leverages the robust document API, ensuring proper integration with the document lifecycle.
- Performance has been improved by consolidating multiple updates into a single, efficient database operation.
- Notifications are now correctly triggered for changes to previously affected values, including but not limited to:
  - `per_delivered`
  - `per_billed`
  - `delivery_status`
  - `billing_status`

These enhancements not only rectify the previous limitations but also pave the way for more responsive and automated business processes, ultimately improving user experience and operational efficiency.

For our production environment, they represent a critical hotfix.

### CODE REVIEW

**Comment by ruthra-kumar** [comment]
@blaggacao 
`status_updater.py` is one of those really old, untouched file that is a pain to analyze and debug. We've been thinking of refactoring this code for some time. But, we are not planning to keep the file as is.

Here's the rough idea:
Gradually move each DocType's logic out of `status_updater.py` into it's respective `.py` file. Ex: copy logic related to `Sales Invoice` doctype into `sales_invoice.py` file and use them. Once, enough of the code / logic has been moved out and their caller have been rewired, the file can be deprecated altogether.

So, would suggest you to not be concerned too much on refactoring the file as is.

**Comment by blaggacao** [comment]
@ruthra-kumar Can you check this please for any blocker? Otherwise, let's please treat this as a hot fix, it is significantly load bearing (revenue bearing) for our use case as we need to send notifications based on status updates (`status` and percentage fields as proxy for progression of business).

I did **not** place this on auto-merge, however, as a hotfix, imo, backporting is warranted under the circumstances.

**Comment by ruthra-kumar** [comment]
I don't see any issues; atleast on the surface. But, given the core nature of this code, and tangled state it currently is, we can never be 100% sure.

For now, we can go ahead with it.

**Review by ruthra-kumar — APPROVED** [review]

**Comment by blaggacao** [comment]
Ok, let's hold back then for a while with the hotfix, I'll add it back in about 2 weeks from now. :+1:

**Pull request merged**
