### PR TITLE
Total Stock Summary Report

### PR DESCRIPTION
**Pull request by creamdory**
For Issue : https://github.com/frappe/erpnext/issues/8884

### CODE REVIEW

**Comment by nabinhait** [comment]
Screenshot please

**Comment by creamdory** [comment]
HI @nabinhait ! Can I send another PR since I found fixes for the code from my sent PR. I will let you see screenshots in the issue comments https://github.com/frappe/erpnext/issues/8884 and tag you once ready. Thanks!

**Comment by rmehta** [comment]
@creamdory closing this for now.

**Comment by creamdory** [comment]
Ok thanks @rmehta !

**Pull request closed without merging**
