### PR TITLE
feat: Service Item and Finished Good Map

### LINKED ISSUE #33645: Serviceable items to be fetched automatically in PO
Hi Team,

Facing the following issue in V14 instance:
When create "Subcontract PO " from Production plan. The draft PO should be make for service items automatically, but now the PO is creating with blank items. Right now we have to add service items manually in the PO. 

Steps to replicate:
1. Go to the Production plan.
2. From Production plan click on create button and click on Work order/ subcontract PO.
3. Then the subcontract PO (https://v14-test-rcil.frappe.cloud/app/purchase-order/PO%2FFY22%2Fbranch_abbr0044)will be created in draft status. 

Observation:
1. Here the created subcontract PO at the items table, the item code for service item is coming as blank and the user need to enter the service item manually.   

Approaches :
Currently in the production Plan you can include the non stock items(Maintain Stock is unchecked). Can we approach the selection of Serviceable Item at the Production Plan as below.

1. In Sub-Assembly Items Table if Manyfacturing Type is Subcontract provide by default a mandatory and checked checkbox as Include Serviceable Item: Link field to items for which the Maintain Stock checkbox is unchecked 
2. Users select the serviceable item and click on submit.

Expectation:
On submission the serviceable items should be carried forward to the Purchase Orders.

2nd Approach:
1. Create a Item for the subcontracted item foe which the checkbox If subcontracted to a vendor is checked.
2. On selection of the checkbox populate a mandatory field as Serviceable Item: Link field to Items for which the Maintain Stock is unchecked.
3. Save the item by entering the details.

Expectation:
If PO is created from the Production Plan the Subcontracted item master has details of Serviceable Item, automatically populate the details in the PO.

Attaching the Screenshots for your reference.
DrIstQq
seEfImH

Thanks

### PR DESCRIPTION
**Pull request by s-aga-r**
A new DocType `Subcontracting BOM` to map Service Item with Finished Good. The Service Item get auto-picked for Finished Good in the Subcontracted Purchase Order. 

- A Service Item can have n numbers of Finished Goods but a Finished Good can only be mapped to one Service Item at a time.
- There can only be one active Subcontracting BOM against a Finished Good and n number of non-active Subcontracting BOM.
- Service Item, UOM and Qty get updated on changes in FG Item.
- BOM gets auto-picked in the Subcontracting Order based on selected Finished Goods.  
- Conversion Factor = Service Item Qty / Finished Good Qty i.e., Service Item Qty required to create n unit of Finished Good.
- On change in FG Item Qty, the Service Item Qty gets updated based on the Conversion Factor (Subcontracting BOM) if the Service Item UOM is the same which is defined in the Subcontracting BOM. 
- On selection of Service Item (and FG is not set) the Finished Good will be picked (if only one FG is mapped) or a dialog opens to select the FG mapped with that Service Item.

image

**Production Plan** > **Subcontracted Purchase Order**:
- _Before_

  https://github.com/frappe/erpnext/assets/63660334/e617c7e1-7324-4156-96ed-618e86c4e72c

- _After_ 

  https://github.com/frappe/erpnext/assets/63660334/fa4b32dd-4d2c-4bbc-8dcc-4c44e982f2d5

**Auto set Service Item on Finished Good select**:
- _Before_

  https://github.com/frappe/erpnext/assets/63660334/bdc52a59-6b83-4c68-ad0e-95225b687e29

- _After_

  https://github.com/frappe/erpnext/assets/63660334/8f956483-32b9-4858-9b00-8fb311112fc2

**Dialog to select Finished Good on Service Item select**:

   https://github.com/frappe/erpnext/assets/63660334/c4217dc3-e6ce-4007-ac20-346c3da95251

`no-docs` - Will update after merge

Close: https://github.com/frappe/erpnext/issues/33645

### CODE REVIEW

**Comment by SvbZ3r0** [comment]
Hi @s-aga-r, I feel this is the wrong approach for this issue.
Service Item to FG is usually a One to Many relationship. For example, in my industry (textiles), we subcontract various stages of the production process like dyeing, washing, weaving, stitching, etc. Each of these is a service item that can operate on different raw materials to give different FG. Fabric is issued for stitching, and the FG can be a shirt, t-shirt or anything else. Similarly, yarn is issued for dyeing and the FG can be red yarn or blue yarn or anything else. I'm simplifying it by quite a lot, but the point I want to make is that the relationship should set up so that any single FG can have only one service item associated with it, but a service item can be associated with as many FG as you want.

**Comment by s-aga-r** [comment]
> Hi @s-aga-r, I feel this is the wrong approach for this issue.
> Service Item to FG is usually a One to Many relationship. For example, in my industry (textiles), we subcontract various stages of the production process like dyeing, washing, weaving, stitching, etc. Each of these is a service item that can operate on different raw materials to give different FG. Fabric is issued for stitching, and the FG can be a shirt, t-shirt or anything else. Similarly, yarn is issued for dyeing and the FG can be red yarn or blue yarn or anything else. I'm simplifying it by quite a lot, but the point I want to make is that the relationship should set up so that any single FG can have only one service item associated with it, but a service item can be associated with as many FG as you want.

@SvbZ3r0 how can we auto-pick the FG in Purchase Order on the selection of Service Item? Will give a thought to your case also.

**Comment by SvbZ3r0** [comment]
Ideally, we would auto pick the service item based on the FG. That will lead to issues in the UI of the Subcontracting POs with how it is currently set up.

**Comment by s-aga-r** [comment]
> Ideally, we would auto pick the service item based on the FG. That will lead to issues in the UI of the Subcontracting POs with how it is currently set up.

That can't be changed as the rate/amount gets calculated based on the `item_code` and `qty` fields.

**Comment by SvbZ3r0** [comment]
Exactly, and that requires no change since that is the way it should be. 
Which is why, this is more a UI issue. Is there a way to change the child table UI if the PO is marked as a subcontracting PO? If the FG is shown in the child table, we should be able to select the FG and let the service item be auto selected.

**Comment by s-aga-r** [comment]
> Exactly, and that requires no change since that is the way it should be. Which is why, this is more a UI issue. Is there a way to change the child table UI if the PO is marked as a subcontracting PO? If the FG is shown in the child table, we should be able to select the FG and let the service item be auto selected.

Label and other properties can be changed but not the `In List View` as columns get added on setup.

https://github.com/frappe/erpnext/assets/63660334/6fa1c460-cd55-4362-8ef9-d599a8a90ebc

**Comment by SvbZ3r0** [comment]
I know its extremely late for this suggestion, but why not just have a field in the Item form to do this instead of having an entire new Doctype? 
Something like this:
image
image

**Comment by s-aga-r** [comment]
> I know its extremely late for this suggestion, but why not just have a field in the Item form to do this instead of having an entire new Doctype? Something like this: image image

That is the simplest approach to map FG with Service Item which can also be achieved by custom field with `fetch_from`.

But
- The new DocType will be easy to manage, all the finished goods can be mapped in one place.
- Also has a conversion factor thing (1 FG = How many service item qty).
- Default UOM.

**Comment by SvbZ3r0** [comment]
That is true, but ideally we want to mark what Service Item is used for an FG when creating the FG.

Pros of having it in the Item form:
1. Service Item can be selected during Item creation
2. Conversion factor can be entered during Item creation
3. Service Item not limited to single UoM for all its FG (for example, some Suppliers price dyeing by the kg, some by the metre)

Cons:
1. Mapping existing Items is a hassle
2. No singular place to view all FG associated with a Service Item (Is this neccessary?)

Pros of having it in separate Doctype:
1. Map and manage all FG associated with a Service Item in the same place

Cons:
1. New (non-intutive?) workflow for subcontracted Item creation (we need to edit or create an entry in the Map Doctype after Item creation)
3. Service Item UoM is fixed

Another good place to get the Service Item associated with the FG would be in the BOM of the FG. I think this will also make it easier to autopopulate items in the PO stage but I haven't given this much thought so I'm not too sure.

**Comment by s-aga-r** [comment]
> That is true, but ideally we want to mark what Service Item is used for an FG when creating the FG.
> 
> Pros of having it in the Item form:
> 
> 1. Service Item can be selected during Item creation
> 2. Conversion factor can be entered during Item creation
> 3. Service Item not limited to single UoM for all its FG (for example, some Suppliers price dyeing by the kg, some by the metre)
> 
> Cons:
> 
> 1. Mapping existing Items is a hassle
> 2. No singular place to view all FG associated with a Service Item (Is this neccessary?)
> 
> Pros of having it in separate Doctype:
> 
> 1. Map and manage all FG associated with a Service Item in the same place
> 
> Cons:
> 
> 1. New (non-intutive?) workflow for subcontracted Item creation (we need to edit or create an entry in the Map Doctype after Item creation)
> 2. Service Item UoM is fixed
> 
> Another good place to get the Service Item associated with the FG would be in the BOM of the FG. I think this will also make it easier to autopopulate items in the PO stage but I haven't given this much thought so I'm not too sure.

@SvbZ3r0 Based on our internal discussion:
- The configuration should not be added in Item Master or BOM. There are already too many fields in Item Master. Since we have two use cases first is to auto-pick the Service Item on the selection of FG and the second is to show a list of FG on the selection of Service Item to pick from, BOM will not be a good place to configure this. We have decided to go with the new DocType with some changes.

**Comment by SvbZ3r0** [comment]
Got it. Thanks for taking my feedback into account.

**Pull request merged**
