### PR TITLE
Added C3.JS Plot to compare quotes in Print view

### PR DESCRIPTION
**Pull request by bcornwellmott**
This will display a Google Chart of a price comparison between different supplier quotations for a given item.

It will look something like this:
image

### CODE REVIEW

**Comment by rmehta** [comment]
@bcornwellmott lets use the new charting engine c3.js

Generally we should avoid using proprietary APIs in this project.

**Comment by bcornwellmott** [comment]
Understood. I have modified the html file to use the c3.js charting tool instead.

**Comment by bcornwellmott** [comment]
Any way to have this move forward?

**Comment by bcornwellmott** [comment]
@nabinhait / @rmehta Still waiting for this to be merged or some feedback on how to improve it. Please let me know what I can do.

**Pull request merged**
