### PR TITLE
fix: Travis CI: Stop testing on Trusty because it is EOL

### PR DESCRIPTION
**Pull request by cclauss**
Do not hardcode Trusty because it is end of life and Travis CI's default distro is now Xenial.

Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

### CODE REVIEW

**Review by adityahase — APPROVED** [review]
Tests failing ?!

**Review by adityahase — CHANGES_REQUESTED** [review]
Tests failing ?!

**Review by adityahase — CHANGES_REQUESTED** [review]
@cclauss Can you please make sure that CI builds pass?

**Comment by cclauss** [comment]
@adityahase My sense is that __bench__ is failing on lots of pull requests and frappe/bench#855 and frappe/bench#856 demonstrate that __bench__ has not been tested on Python 3 and not on MariaDB.  Perhaps some effort is required to ensure that __bench__ is compatible with MariaDB 10.4 and Python 3.8 running on Xenial before attempting similar things on this repo.

**Comment by adityahase** [comment]
@cclauss I have written the .travis.yml in its entirety. bench has nothing to do with this. It's the 10.3 to 10.4 change that you are forcing on this repository.

You can either remove to 10.3 to 10.4 change or fix the YAML file to make sure that the builds pass.

I'd strongly recommend against removing 10.3 from the builds though. Most of the people are still using it.

**Comment by cclauss** [comment]
Reverted the MariaDB change which is now fixed in #19554.

This is what I mentioned about __bench__ not being ready for Xenial, Python 3, etc.
https://travis-ci.com/frappe/erpnext/jobs/255700498#L545

Simplifying this PR even further...

**Comment by nabinhait** [comment]
@cclauss Closing this as of now, please reopen when other problems are fixed.

**Pull request closed without merging**
