### PR TITLE
Compatibility for pip 10

### PR DESCRIPTION
**Pull request by codingCoffee**
- also some spaces and tabs fixes

### CODE REVIEW

**Comment by bhavikpatel7023** [comment]
Still its not working in my case.


> fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/bin/pip2 install -e /home/frappe/.bench", "msg": "stdout: Obtaining file:///home/frappe/.bench\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n      File \"/home/frappe/.bench/setup.py\", line 2, in <module>\n        from pip.req import parse_requirements\n    ImportError: No module named req\n    \n    ----------------------------------------\n\n:stderr: Command \"python setup.py egg_info\" failed with error code 1 in /home/frappe/.bench/\n"}
> 	to retry, use: --limit @/tmp/.bench/playbooks/site.retry
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=66   changed=35   unreachable=0    failed=1   
> 
> Traceback (most recent call last):
>   File "install.py", line 400, in <module>
>     install_bench(args)
>   File "install.py", line 117, in install_bench
>     run_playbook('site.yml', sudo=True, extra_vars=extra_vars)
>   File "install.py", line 333, in run_playbook
>     success = subprocess.check_call(args, cwd=os.path.join(cwd, 'playbooks'))
>   File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['ansible-playbook', '-c', 'local', 'site.yml', '-e', '@/tmp/extra_vars.json', '--become', '--become-user=frappe']' returned non-zero exit status 2
> HEY! USE SCREEN -bash-4.2# pip --version
> pip 10.0.0 from /usr/lib/python2.7/site-packages/pip (python 2.7)

**Comment by codingCoffee** [comment]
@bhavikpatel7023 I don't think you've updated frappe. The issue has been fixed. Try again.

**Comment by bhavikpatel7023** [comment]
@codingCoffee 
Sorry, but still I'm facing this problem. I'm not updating server but I'm installing on a fresh server.

**Comment by barredterra** [comment]
still getting this error

**Pull request merged**
