### PR TITLE
Non-Depreciable Asset 

### PR DESCRIPTION
**Pull request by agritheory**
Added Non-Depreciable Asset functionality to Asset and Asset Category 

Allow for non-depreciable assets (#11078)

### CODE REVIEW

**Comment by agritheory** [comment]
This is my first code contribution to ERPNext . Do not automatically merge.

**Comment by codingCoffee** [comment]
Hey @agritheory, is this related to the agriculture domain? or is it a PR for the ERPNext core?
In case it is related to the agri domain, could you open a PR in the `agri-farm-erpnext` branch, instead of `develop`

**Comment by agritheory** [comment]
Well, the most common use cases _I_ can think of are in agriculture, but I do think have the ability to have non-depreciable assets is useful as a core feature. Other kinds of businesses besides farms own land, for example. My guess is that it's on the right branch, but if you want I can create PR for it on the `agri-farm-erpnext` branch also?

**Comment by tundebabzy** [comment]
Hi @agritheory 

The present PR contains whole file changes, many unrelated to the problem so I can't easily tell what parts have changed. It also has .pyc files which should not be included. Please check the .gitignore file on your setup and make sure .pyc is included. 

I can't review this PR in this form. What you should do is:
- Checkout the develop branch
- Pull the latest changes from upstream/develop
- Create a new branch from develop branch and checkout the new branch
- Add your changes and create a pull request

Please open a new PR after doing these. BTW, +1 for first PR

**Pull request closed without merging**
