### PR TITLE
feat: Healthcare Service Order(CPOE) and Healthcare Insurance

### PR DESCRIPTION
**Pull request by ruchamahabal**
Introducing Medications and Healthcare Service Order for CPOE according to [HL7 Standards](https://www.hl7.org/fhir/) 

### What is CPOE?

CPOE is basically a more streamlined approach of placing Medical Orders for Medication, Lab Tests, Clinical Procedures, Therapy sessions, etc.

### Healthcare Insurance

- Healthcare Insurance Company
- Healthcare Insurance Contract
- Healthcare Insurance Coverage Plan
- Healthcare Service Insurance Coverage
- Healthcare Insurance Subscription
- Healthcare Insurance Claim
- Insurance Billing
- Healthcare Insurance Payment Request and Payment

### CODE REVIEW

**Comment by mujeerhashmi** [comment]
Any updates on this ??

**Comment by chechani** [comment]
Eagerly waiting for this internal PR to be merged. Neither merged and no activity for two months.

**Comment by ruchamahabal** [comment]
@mujeerhashmi @chechani, we (@akurungadam and I) have identified a lot of [gaps](https://docs.google.com/document/d/1_yphmfCDRKdqnRKvbRxJrOex1ye0VqUUxyEf0w1OwrE/edit?usp=sharing) in the design and collaborating on them.
Most of them are fixed. We will push the changes soon.

**Comment by akurungadam** [comment]
To add to Rucha's comment, the feature set introduces some breaking changes - we are trying to get this work in alignment with the existing domain workflow. Speeding this up anyways, if it needs any further deliberation I think we can split this and push service order first and then go with Insurance. thanks for your patience :)

**Comment by chechani** [comment]
Thx for responding .

**Comment by ruchamahabal** [comment]
Keep alive

**Comment by chechani** [comment]
@akurungadam and @ruchamahabal any update and info about revised PR as informed earlier.  we want to work in the same features for a client.we request if you can break it as medication , service order and insurance then we can contribute in testing faster and update about this

**Comment by ruchamahabal** [comment]
Will reopen after changes.

**Comment by mohsinalimat** [comment]
Any plan to release this feature?

**Comment by whhsn** [comment]
Insurance is a long waited feature - looking forward to test it soon
Thx all

**Comment by leo9223** [comment]
Is this feature added? I am using v13 how to have this feature?

**Pull request closed without merging**
