### PR TITLE
fix:Pricing Rule error AttributeError: 'str' object has no attribute 'get'

### PR DESCRIPTION
**Pull request by khushalti**
#19770 

image

### CODE REVIEW

**Comment by khushalti** [comment]
@deepeshgarg007  can you help me .. Travis build got failed but details are not loading what went wrong

image

**Comment by scmmishra** [comment]
I've restarted the build.

**Review by scmmishra — COMMENTED** [review]
are you sure your fix works.. I'm pretty sure the attribute error is caused on `d` in the list comprehension and not on `self` 

`self` is never gonna be a string in this case, so it will have an attribute `get`

**Comment by khushalti** [comment]
@scmmishra yes it works i have tested...

**Comment by khushalti** [comment]
image
I got above error on Travis build

**Comment by khushalti** [comment]
@scmmishra any further updates on this?

**Comment by scmmishra** [comment]
> @scmmishra yes it works i have tested...

It may work for multiple reasons, your fix is not it.

Just print the type of `self` it's not `str`
`self` is an instance of the Pricing Rule Class, it'll always have an attribute `get`

**Review by nabinhait — APPROVED** [review]

**Comment by RickyHutanoto** [comment]
Suppose this fix also applied to Promotional Scheme

**Pull request merged**
