### PR TITLE
fix: using DN for transfer w/o internal customer

### PR DESCRIPTION
**Pull request by fproldan**
> Please provide enough information so that others can review your pull request:

The field `target_warehouse` depends on itself to be shown

> Explain the **details** for making this change. What existing problem does the pull request solve?

Fix for changes introduced in this PR: https://github.com/frappe/erpnext/pull/27798

### CODE REVIEW

**Comment by ankush** [comment]
> Fix for changes introduced in this PR: #27798


That change was intentional 😅 It depends on internal customer **OR** itself so the field will be shown in case it's already set somehow. This is to avoid confusing behaviour where hidden target warehouse field is set. 


Can you describe what exactly broke after #27798?

**Comment by fproldan** [comment]
I had not understood the "it's already set somehow" part. I thought the purpose of the PR was to make that field editable regardless of whether the customer or supplier is internal.

How the hidden target warehouse field can be set besides if the customer is internal?

**Comment by ankush** [comment]
> How the hidden target warehouse field can be set besides if the customer is internal?


Server scripts / crazy customizations 😐

**Comment by fproldan** [comment]
Okay, I understand the purpose of pr now. Sorry for the misunderstanding.

**Pull request closed without merging**
