### PR TITLE
fix: Allow custom theme to override erpnext stylesheet

### PR DESCRIPTION
**Pull request by netchampfaris**
This will change the order of stylesheets in ERPNext's Website Pages.

Two scenarios:

1. Standard theme, no custom theme
```
<link type="text/css" rel="stylesheet" href="/assets/css/frappe-web-b4.css">
<link type="text/css" rel="stylesheet" href="/assets/css/erpnext-web.css">
```

2. Custom Theme
```
<link type="text/css" rel="stylesheet" href="/assets/css/erpnext-web.css">
<link type="text/css" rel="stylesheet" href="/assets/css/custom_9e63660e.css">
```

We load the custom theme css after erpnext's stylesheet so that custom theme can override it.

### CODE REVIEW

**Comment by rmehta** [comment]
@netchampfaris is this still required?

**Comment by netchampfaris** [comment]
@rmehta [This PR](https://github.com/frappe/frappe/pull/11369) is an alternative solution with a generic design. If that PR is approved, this won't be needed I guess. There are somethings I'd like to fix in that PR though.

**Comment by rmehta** [comment]
@netchampfaris yeah that seems more generic. Can you review / fix that?

**Comment by netchampfaris** [comment]
https://github.com/frappe/frappe/pull/11555

The new changes in Frappe handles this case. Closing.

**Pull request closed without merging**
