### PR TITLE
fix: minor e-invoicing issues

### PR DESCRIPTION
**Pull request by nextchamp-saqib**
Fixes:
- Invoice values is set to zero if rounded total is disabled
- unit rate & gross amount calculation
- e-invoicing setup patch

### CODE REVIEW

**Comment by adityaduggal** [comment]
I am getting this below error in my production server after the latest patch

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)  
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 99, in <module>
    main()
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)  
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 26, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/commands/site.py", line 286, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/migrate.py", line 48, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/rigpl/frappe-bench/apps/erpnext/erpnext/patches/v12_0/setup_einvoice_fields.py", line 34, in execute
    create_custom_fields(custom_fields, update=True)
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 143, in create_custom_fields
    create_custom_field(doctype, df, ignore_validate=ignore_validate)
 File "/home/rigpl/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 127, in create_custom_field
    custom_field.insert()  
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in insert
    self.run_post_save_methods()
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/model/document.py", line 927, in run_post_save_methods
    self.run_method("on_update")
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/model/document.py", line 797, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/model/document.py", line 1073, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/model/document.py", line 1056, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/model/document.py", line 791, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 65, in on_update
    frappe.db.updatedb(self.dt)
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 291, in updatedb
    db_table.sync()
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/database/schema.py", line 37, in sync
    self.alter()
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/database/mariadb/schema.py", line 86, in alter
    raise e
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/database/mariadb/schema.py", line 75, in alter
    frappe.db.sql(query)   
  File "/home/rigpl/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
    self._cursor.execute(query)
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()   
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1118, 'Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs')

```

Any idea as to what should be done apart from disabling this patch

**Comment by nextchamp-saqib** [comment]
> I am getting this below error in my production server after the latest patch
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)  
>   File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 99, in <module>
>     main()
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
>     click.Group(commands=commands)(prog_name='bench')
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)  
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/commands/__init__.py", line 26, in _func
>     ret = f(frappe._dict(ctx.obj), *args, **kwargs)
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/commands/site.py", line 286, in migrate
>     migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/migrate.py", line 48, in migrate
>     frappe.modules.patch_handler.run_all(skip_failing)
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
>     run_patch(patch)
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
>     if not run_single(patchmodule = patch):
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
>     return execute_patch(patchmodule, method, methodargs)
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
>     frappe.get_attr(patchmodule.split()[0] + ".execute")()
>   File "/home/rigpl/frappe-bench/apps/erpnext/erpnext/patches/v12_0/setup_einvoice_fields.py", line 34, in execute
>     create_custom_fields(custom_fields, update=True)
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 143, in create_custom_fields
>     create_custom_field(doctype, df, ignore_validate=ignore_validate)
>  File "/home/rigpl/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 127, in create_custom_field
>     custom_field.insert()  
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/model/document.py", line 260, in insert
>     self.run_post_save_methods()
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/model/document.py", line 927, in run_post_save_methods
>     self.run_method("on_update")
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/model/document.py", line 797, in run_method
>     out = Document.hook(fn)(self, *args, **kwargs)
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/model/document.py", line 1073, in composer
>     return composed(self, method, *args, **kwargs)
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/model/document.py", line 1056, in runner
>     add_to_return_value(self, fn(self, *args, **kwargs))
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/model/document.py", line 791, in <lambda>
>     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 65, in on_update
>     frappe.db.updatedb(self.dt)
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/database/mariadb/database.py", line 291, in updatedb
>     db_table.sync()
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/database/schema.py", line 37, in sync
>     self.alter()
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/database/mariadb/schema.py", line 86, in alter
>     raise e
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/database/mariadb/schema.py", line 75, in alter
>     frappe.db.sql(query)   
>   File "/home/rigpl/frappe-bench/apps/frappe/frappe/database/database.py", line 171, in sql
>     self._cursor.execute(query)
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 170, in execute
>     result = self._query(query)
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 328, in _query
>     conn.query(q)
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 517, in query
>     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 732, in _read_query_result
>     result.read()
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1075, in read
>     first_packet = self.connection._read_packet()
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/connections.py", line 684, in _read_packet
>     packet.check_error()   
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/protocol.py", line 220, in check_error
>     err.raise_mysql_exception(self._data)
>   File "/home/rigpl/frappe-bench/env/lib/python3.6/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
>     raise errorclass(errno, errval)
> pymysql.err.InternalError: (1118, 'Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs')
> ```
> 
> Any idea as to what should be done apart from disabling this patch

Remove unused custom fields in Sales Invoice of fieldtype Data & Select.

**Comment by adityaduggal** [comment]
Thank @nextchamp-saqib Turns out that there are 202 fields in my Sales Invoice Table and since my DB is more than 10 years old the varchars were mostly 255 length when I reduced the size of the varchars to 140 the problem is resolved I would definitely be looking into dropping the unsued fields but turns out that there is no patch in frappe to handle such scenarios. Maybe for some other day but it seems more like a frappe issue than the issue for this patch.

**Comment by deepeshgarg007** [comment]
@adityaduggal  You can use `trim_tables` method in meta.py to remove the unused fields.

**Comment by karantkiruba** [comment]
`Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-jptech/apps/frappe/frappe/utils/bench_helper.py", line 99, in <module>
    main()
  File "/home/frappe/frappe-jptech/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-jptech/env/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-jptech/env/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-jptech/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-jptech/env/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-jptech/env/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-jptech/env/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-jptech/env/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/frappe/frappe-jptech/apps/frappe/frappe/commands/__init__.py", line 26, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/frappe/frappe-jptech/apps/frappe/frappe/commands/site.py", line 286, in migrate
    migrate(context.verbose, rebuild_website=rebuild_website, skip_failing=skip_failing)
  File "/home/frappe/frappe-jptech/apps/frappe/frappe/migrate.py", line 48, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/frappe/frappe-jptech/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/frappe/frappe-jptech/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/frappe/frappe-jptech/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/frappe/frappe-jptech/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/frappe/frappe-jptech/apps/erpnext/erpnext/patches/v12_0/repost_stock_ledger_entries_for_target_warehouse.py", line 56, in execute
    doc.make_gl_entries_on_cancel(repost_future_gle=False)
  File "/home/frappe/frappe-jptech/apps/erpnext/erpnext/controllers/stock_controller.py", line 292, in make_gl_entries_on_cancel
    self.make_gl_entries(repost_future_gle=repost_future_gle)
  File "/home/frappe/frappe-jptech/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 731, in make_gl_entries
    gl_entries = self.get_gl_entries()
  File "/home/frappe/frappe-jptech/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 767, in get_gl_entries
    self.make_item_gl_entries(gl_entries)
  File "/home/frappe/frappe-jptech/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py", line 859, in make_item_gl_entries
    "project": item.project or self.project
AttributeError: 'SalesInvoiceItem' object has no attribute 'project'
`

I am getting the above error while bench update.
Note: My Invoices don't have project linked.

**Pull request merged**
