### PR TITLE
feat: Accounting Dashboard

### PR DESCRIPTION
**Pull request by adityahase**
pc

#### Chart Source
```
Account Balance Timeline
```
#### Filters JSON

```json
{
    "company": "Gadget Technologies Pvt. Ltd.",
    "account": "Bank Accounts - GTPL",
    "timespan": "Last Year",
    "timegrain": "Monthly"
}
```

**Note:** Depends on https://github.com/frappe/frappe/pull/6777

### CODE REVIEW

**Comment by joolsr** [comment]
Can something like this be (re)used for other dashboards ie Sales? Great piece of work ;-)

**Comment by adityahase** [comment]
Not Stale

**Review by netchampfaris — APPROVED** [review]

**Comment by adityahase** [comment]
https://github.com/frappe/erpnext_com/pull/292

**Comment by AlaaBadry** [comment]
is this in v11

**Comment by jaichavan** [comment]
@AlaaBadry No, this will be introduced in version 12 ;)

**Pull request merged**
