### PR TITLE
Work in progress - Spanish Translation of the manual

### PR DESCRIPTION
**Pull request by paulocoronado**
First commit of the spanish translation of the manual.

### CODE REVIEW

**Comment by rmehta** [comment]
@paulocoronado  can you add some text in your pages that this is "work in progress", so we can merge. Thanks!

**Comment by paulocoronado** [comment]
@rmehta please review this pull request.

**Comment by rmehta** [comment]
@paulocoronado  wanted to make it as a visible link, so that people who come to this page, know that it is not a complete manual. I will merge manually.

**Comment by rmehta** [comment]
merge. Look forward to more translation pages :)

**Pull request closed without merging**
