### PR TITLE
fix: report chart fieldtype

### PR DESCRIPTION
**Pull request by zeta17**
Add fieldtype Currency to some currency-related reports

ribet1
Just add currency for fieldtype

### CODE REVIEW

**Comment by deepeshgarg007** [comment]
@zeta17 can you please elaborate on the PR description a bit more like what problem this PR solves, and the before-after screenshots of the charts for the reviewer's understanding

**Comment by zeta17** [comment]
> @zeta17 can you please elaborate on the PR description a bit more like what problem this PR solves, and the before-after screenshots of the charts for the reviewer's understanding

ribet1
Just add currency for fieldtype

**Review by s-aga-r — CHANGES_REQUESTED** [review]
@zeta17 fix the linter issue(s) and use semantic commit titles.

**Comment by deepeshgarg007** [comment]
@Mergifyio backport version-14-hotfix

**Pull request merged**
