### PR TITLE
fix: renamed "supplier_warehouse" to "set_from_warehouse"

### PR DESCRIPTION
**Pull request by AfshanKhan**
```
Traceback (most recent call last):
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/app.py", line 67, in application
    response = frappe.api.handle()
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/handler.py", line 30, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/handler.py", line 70, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/__init__.py", line 1134, in call
    return fn(*args, **newargs)
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/desk/form/save.py", line 21, in savedocs
    doc.save()
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/model/document.py", line 307, in _save
    self.insert()
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/model/document.py", line 238, in insert
    self.run_before_save_methods()
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/model/document.py", line 950, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/model/document.py", line 848, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/model/document.py", line 1135, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/model/document.py", line 1118, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/frappe/frappe/model/document.py", line 842, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/erpnext/erpnext/accounts/doctype/purchase_invoice/purchase_invoice.py", line 69, in validate
    super(PurchaseInvoice, self).validate()
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/erpnext/erpnext/controllers/buying_controller.py", line 62, in validate
    self.validate_for_subcontracting()
  File "/home/frappe/benches/bench-version-13-2021-02-02/apps/erpnext/erpnext/controllers/buying_controller.py", line 290, in validate_for_subcontracting
    if self.doctype in ["Purchase Receipt", "Purchase Invoice"] and not self.supplier_warehouse:
AttributeError: 'PurchaseInvoice' object has no attribute 'supplier_warehouse'
```

### CODE REVIEW

**Review by deepeshgarg007 — CHANGES_REQUESTED** [review]
@AfshanKhan revert the field name in Purchase Invoice again to Supplier Warehouse and add a new field to set "from warehouse" which should only be visible for internal transfers

**Review by nabinhait — CHANGES_REQUESTED** [review]
@AfshanKhan Need to fix this as well.
https://github.com/frappe/erpnext/blob/develop/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py#L636

**Comment by nabinhait** [comment]
> @AfshanKhan Need to fix this as well.
> https://github.com/frappe/erpnext/blob/develop/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py#L636

There are some other places also we need to fix it

**Comment by AfshanKhan** [comment]
> @AfshanKhan revert the field name in Purchase Invoice again to Supplier Warehouse and add a new field to set "from warehouse" which should only be visible for internal transfers

@nabinhait if we do this we wouldn't need to do all these changes. Also, most of the current changes will be discarded.

**Comment by deepeshgarg007** [comment]
> @AfshanKhan Need to fix this as well.
> https://github.com/frappe/erpnext/blob/develop/erpnext/stock/doctype/purchase_receipt/purchase_receipt.py#L636

@nabinhait asked him to revert back the filename to supplier warehouse and add new field for Set From Wareshouse, that should solve all the issues.

**Review by nabinhait — APPROVED** [review]

**Comment by nabinhait** [comment]
@AfshanKhan Please send another PR to pre-release branch

**Comment by AfshanKhan** [comment]
Pre-release PR at https://github.com/frappe/erpnext/pull/24827

**Review by deepeshgarg007 — APPROVED** [review]

**Pull request merged**
