### PR TITLE
feat: Asset capitalization

### PR DESCRIPTION
**Pull request by SaiFi0102**
Documentation (Under Review):
https://docs.erpnext.com/docs/v13/user/manual/en/asset/new?wiki_page_patch=ee64cad18b

Dependent On:
https://github.com/frappe/erpnext/pull/27585

### CODE REVIEW

**Comment by ankush** [comment]
(hotfix label is to avoid auto-closure of PRs by stale bot, looks weird but eh...)

**Comment by SaiFi0102** [comment]
isort error is due to merging develop branch in this PR

**Comment by ankush** [comment]
> isort error is due to merging develop branch in this PR


It's not from the merge. You removed an unused import, so it now fits on a single line. Just add pre-commit hook to avoid this manual work 😄

**Comment by nextchamp-saqib** [comment]
We are planning to separate the Asset module into an App. So, this will be moved to the App once we have moved all the existing features. 

Hence closing this for now. 

cc: @GangaManoj @nabinhait @umairsy

**Comment by nabinhait** [comment]
As we have changed our plan for a separate Asset app, reopening the PR.

**Pull request merged**
