### PR TITLE
fix: do not translate issue priority

### PR DESCRIPTION
**Pull request by hasnain2808**
while auto-creating issues via email, the priority comes in English

If the priorities are translated and saved it is not able to find the priority and throws a link validation error

### CODE REVIEW

**Comment by pateljannat** [comment]
@hasnain2808 have you raised a PR for v13 as well?

**Comment by hasnain2808** [comment]
No,
Should backport after this gets merged na?

**Comment by pateljannat** [comment]
Doesn't happen automatically on erpnext. You'll have to raise a separate PR

**Comment by hasnain2808** [comment]
> Doesn't happen automatically on erpnext. You'll have to raise a separate PR

Yes once this gets merged

**Review by pateljannat — APPROVED** [review]

**Pull request merged**
