### PR TITLE
refactor!: rename Email Campaign to Campaign Run

### PR DESCRIPTION
**Pull request by blaggacao**
# Context

- There are 3 (sic!) different "Campaigns" in the awesome bar (Campaign, Email Campaign & Marketing Campaign); it couldn't be worse
- The name of Email Campaign is clearly a misnomer, because:
  - The nature of Its function is not at all scoped to Email
  - It's _not_ a campaign at all

- It's a Campaign Run

# Proposal

- Rename _Email Campaign_ to _Campaign Run_

# Outlook

Based on this, I'm implementing a mixed email / whatsapp campaign run.

### CODE REVIEW

**Comment by blaggacao** [comment]
The [third commit](https://github.com/frappe/erpnext/pull/40659/commits/f3dbe12d7c7fad0409da08e745fe342a14459954) is entirely optional, and I probably should keep it private on my fork for now. Please let me know what to do. :pray:

**Comment by blaggacao** [comment]
Since this now also includes more CRM capabilities, which we're currently trying out in production, I'll mark as draft to wait for the first iteration or so with our users to vet the entity relation design a little more.

**Comment by blaggacao** [comment]
I'd like to keep proposing this change.

**Comment by barredterra** [comment]
> The [third commit](https://github.com/frappe/erpnext/pull/40659/commits/f3dbe12d7c7fad0409da08e745fe342a14459954) is entirely optional, and I probably should keep it private on my fork for now. Please let me know what to do. 🙏

Probably remove for now to keep the diff small? Maybe open a separate PR with this feature only.

**Comment by blaggacao** [comment]
@deepeshgarg007 could you please reopen and remove the stale artist?

**Pull request closed without merging**
