### PR TITLE
refactor: Clear unallocated mode of payments on submitting POS Invoice

### PR DESCRIPTION
**Pull request by devdiogenes**
Currently when we create a Sales Invoice with POS Payments, when it be submitted, all unallocated modes of payments are deleted [in this function](https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/doctype/sales_invoice/sales_invoice.py#L888).

It doesn't happens in POS Invoice. This commit copies the codes that makes it happens, from Sales Invoice to POS Invoice. 

*Edit: Changed the code from frappe.db to frappe.qb, because of the checks

### CODE REVIEW

**Comment by ruthra-kumar** [comment]
@devdiogenes 

Can you rebase on latest develop and reduce it one or two commits without any merge commits. It makes it easier to backport.

**Comment by devdiogenes** [comment]
@ruthra-kumar 
The changes you requested have been made and pushed. Please take a look and let me know if there's anything else you need.

**Comment by devdiogenes** [comment]
Waiting for review

**Comment by ruthra-kumar** [comment]
@devdiogenes 

PR got closed due to force-pushing a divergent history - my fault.

I've captured your changes on https://github.com/frappe/erpnext/pull/44321

**Pull request closed without merging**
