### PR TITLE
Adding query for item field for some stock reports

### PR DESCRIPTION
**Pull request by bghayad**
Hello;

I add get_query for item field for the below stock reports to be able to search for the item based on the barcode (otherwise, searching for item will be very complex as most of the users are depending on the barcode and not item name):

Stock Summary (it is stock balance page)
Stock Ageing
Item Price Stock
Stock Analytics

Please I need your kindly support to complete the merge.
Regards
Bilal

### CODE REVIEW

**Comment by bghayad** [comment]
Hello;
How can we move on on this github to be merged?
What is missing?
Regards
Bilal

**Comment by bghayad** [comment]
Hello;
@nabinhait 
Can we move on with this merge?
What is missing?

Regards
Bilal

**Comment by bghayad** [comment]
Hello @nabinhait 
Can we move on on this merge?
Regards
Bilal

**Review by nabinhait — APPROVED** [review]
@bghayad Thanks for the PR. Please send another PR for develop branch.

**Pull request merged**
