### PR TITLE
chore: Consolidate da_dk.csv into da-DK.csv

### PR DESCRIPTION
**Pull request by bosue**
Inspired by #38104, this is a first step at consolidating duplicate language variant translation files, also adding missing commas.

Do we have a standard sort order, so by sorting, we‘re not moving around more lines than necessary?

Next steps would be:
- Consolidate with da.csv, only keeping valid overrides in da-DK.csv
- Same with other language variants.

### CODE REVIEW

**Comment by barredterra** [comment]
the correct naming [according to ISO8859-1](https://sites.ualberta.ca/dept/chemeng/AIX-43/share/man/info/C/a_doc_lib/aixbman/baseadmn/locale.htm) would be `da_DK`

**Comment by barredterra** [comment]
The correct naming [according to ISO8859 / UTF-8](https://sites.ualberta.ca/dept/chemeng/AIX-43/share/man/info/C/a_doc_lib/aixbman/baseadmn/locale.htm) would be `da_DK`

> Do we have a standard sort order, so by sorting, we‘re not moving around more lines than necessary?

Some of the files seem to be sorted alphabetically.

**Comment by bosue** [comment]
@barredterra:

> The correct naming [according to ISO8859 / UTF-8](https://sites.ualberta.ca/dept/chemeng/AIX-43/share/man/info/C/a_doc_lib/aixbman/baseadmn/locale.htm) would be da_DK

Not quite. ISO 8859-1 is just the encoding scheme. `da-DK` and `pt-BR` are indeed correct, see for example https://en.wikipedia.org/wiki/Language_localisation#Language_tags_and_codes.

But yeah. In some contexts the hyphen may have to be replaced by an underscore, and in POSIX that‘s the case.

No problem at all with doing the same. It might even be a good idea to stay in line with POSIX. But as already stated in the other issue, we then would have to reconsider and change our naming scheme consistently and in line with frappe/frappe.

**Comment by bosue** [comment]
Until the dispute is settled, I‘m closing this PR.
I have absolutely no interest in participating in an unnecessary scuffle.

**Comment by barredterra** [comment]
Huh, too many standards... As you know, I'm currently working on a PR for supporting GNU gettext, which uses the `ll_CC` scheme as well: https://www.gnu.org/software/gettext/manual/html_node/Locale-Names.html

So probably we'll have to support both and convert back and forth.

**Comment by bosue** [comment]
Not necessarily.

For us it’s an arbitrary decision. So if we’re about to use GNU gettext, it makes a lot of sense to settle with what they are using, though maybe not in the UI.

Regarding filenames, I‘m on board with switching over to da_DK.csv and pt_BR.csv in frappe/frappe (with the necessary BC considerations), then following through in frappe/erpnext. Let‘s go!

**Comment by bosue** [comment]
Finally, in frappe/frappe#23320 the decision was taken to stick with `pt-BR.csv` and `da-DK.csv`, so reopening this one.

**Pull request closed without merging**
