### PR TITLE
Consolidation of Financial Statements

### PR DESCRIPTION
**Pull request by revant**
Phase 1:

 - Added Child Doctype - Company Relationship under Company
 - Select Field - company_type on Company

### CODE REVIEW

**Review by Tropicalrambler — APPROVED** [review]
Looks ok

**Review by Tropicalrambler — APPROVED** [review]
ok

**Comment by rmehta** [comment]
@revant Report missing?

**Comment by revant** [comment]
I've not developed any reports. Not even started anything.

There was some activity on forum for reports. Hope it results into pull request.

For now this pull request is only adding child table and basic validation for Company.

**Comment by rmehta** [comment]
mmm was there is a report too? This does not make sense without a report.

**Comment by revant** [comment]
I am not using any consolidation yet, so won't be developing anything on my own.

I'll try to replicate this post https://discuss.erpnext.com/t/consolidated-fs-by-currency/18122 and send a pull request later.

Closing it for now.

**Comment by fikrut** [comment]
is there any update on developing consolidated financial report?

**Comment by Tropicalrambler** [comment]
Revant,  here are some videos on the consolidation/combination and I made a mockup of the "Combination/Consolidation" of Statements.
I referred to [this Website](http://smallbusiness.chron.com/difference-between-combining-vs-consolidating-financial-statements-31232.html)

I also referred to this handy and clear video on how to consolidate in Quickbooks, which helps to envision the process for what we are aiming to do.
https://www.youtube.com/watch?v=vE3SFh8MVeo

Here are some screenshots of mockups I did:
e7a7b73b69c980d1f7fbc74db1afc58ca1230731_1_519x499

And closer look:
63721a39f420ba3faff2e01552f73f9aba480848_1_690x307

part 2:
76717d3c0d124539ee17328e46477033d2fcfd4c_1_690x332

**Comment by Tropicalrambler** [comment]
Here is the mock up with some test numbers:
screen shot 2017-03-30 at 8 40 47 pm

Close Up 1
screen shot 2017-03-30 at 8 41 04 pm

Close up 2
screen shot 2017-03-30 at 8 41 21 pm

**Pull request closed without merging**
