### PR TITLE
feat: UK HMRC Making Tax Digital for VAT

### LINKED ISSUE #16025: Support for Making Tax Digital (UK)
In the UK taxes are moving towards being submitted electronically via an API under the _Making Tax Digital_ plan. Initially this is just for VAT-registered businesses to submit their VAT returns and needs to be in place by 1st April 2019.

They provide a [list of existing software](https://www.gov.uk/guidance/software-for-sending-income-tax-updates) that can do this. I didn't look at all of them on the list, but I'm not aware that any of them are open source.

The documentation looks pretty good from what I've seen:
- [overview](https://www.gov.uk/government/publications/making-tax-digital/overview-of-making-tax-digital)
- [developer tutorials](https://developer.service.hmrc.gov.uk/api-documentation/docs/tutorials)
- [a somewhat verbose step-by-step walk through](https://developer.service.hmrc.gov.uk/api-documentation/assets/content/documentation/f66c79c2c4fc2f0cf27c158b2411a1b2-MTD-VAT%20End-to-End%20(E2E)%20Customer%20Journeys.pdf) (pdf)
- [developer API docs](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/vat-api/1.0)

What would be involved in getting this supported by erpnext? Is this something that can be implemented as a seperate app/add-on, or would it need to go into the core?

I am a python developer myself and can likely work on this if we choose to use erpnext (which is dependent on being able to implement this).

### LINKED ISSUE #21233: [Feature Request] UK VAT Return & Making Tax Digital for VAT
### [Pledge your support for this project here!](https://www.casesolved.co.uk/products/erpnext-features/erpnext-ukvat)
**This integration will allow ERPNext to be published as HMRC Recognised Software on their website.**

## Pre-requisites
Frappe general purpose OAuth2 client (see [here](https://github.com/frappe/frappe/issues/9722))
Multiple Company Tax registrations (see [here](https://github.com/frappe/erpnext/issues/21723)) - Can be implemented with regional-specific custom fields on the Company
Chart of Accounts Map (see [here](https://github.com/frappe/erpnext/issues/21694)) see #25254 

### UK VAT
A VAT return report and digital integration with HMRC that supports all domestic and international goods and service purchase and sales according to UK VAT rules
- Deliver the 9-box UK VAT Return report format, including:
  - Provision for Suppliers and Customers to be marked with regions for specific VAT rules
  - Provision for invoice items to be marked with categories, specifically: Goods, Services and Mobile Phones/Chips
  - A mechanism that applies VAT rates (standard: 20%, reduced: 5%, zero: 0%) and accounts to invoice lines based on the two pieces of information above
  - Transactions not applicable for VAT reporting, e.g. local authority rates, must not have VAT applied and so will not be picked up by the report
  - The 9 boxes must be editable to allow the HMRC submission of special VAT accounting schemes
- OAuth2 & REST-based submission of figures
- Storage of VAT Registration Number (VRN), a 9-digit number

### ERPNext constraints
- Must work on one-off purchase transactions with lines that are not pre-defined as Items
- Must work with the existing ERPNext tax features
- VAT must be captured as normal ledger entries in suitable accounts. This allows existing ledger reports to be used for analysis and debugging
- Tax must **not** be accounted for outside of the CoA; the report must draw its values from General Ledger entries so as to include correcting Journal Entries
- Although there is a "Tax ID" field, the UK has various Tax IDs that relate to a Company (Corporation Tax (UTR), PAYE, VRN, EORI) so the UK will need several IDs
- Although there are Sales/Purchase Taxes and Charges Templates, since they apply a rate to whole invoices and not individual invoice lines, they do not cater for invoices with lines with differing VAT rates and accounting requirements and so cannot be used in the general case or exclusively
- All features should be added as regional customisations in the regional module so as not to pollute the base UI

### Recommendations
- It should be possible for Sales and Purchase VAT to be accounted on separate Accounts, though not essential
- The report should have a drill-down/detail table to allow for analysis
- Item Tax Template should be extended to allow application to Sales and Purchases separately, and ideally the Sales/Purchase Taxes and Charges template should be refactored to apply to line items instead of invoices

## Setup
Boxes 1 to 4 can be generated directly from the Chart of Accounts using standard ERPNext functionality with the following setup:
- Tax Categories for Customers and Suppliers (separately) to identify their region: UK, EU or Rest of World (optional)
- Item Tax Templates set up to apply the correct VAT rate to the correct Account(s), for example:
  - A Reverse Charge Purchase at standard rate requires 20% to be applied to a *VAT on Purchases* Account (used for Box4), and -20% to also be applied to a *VAT on Sales* Account (used for Box1)
  - For common or stock items, Item Groups set up with Items in the correct Group, to automatically apply the correct Item Tax Template based on the Item & Tax Category (optional). Though Item Tax Templates can be applied manually to non-inventory Items

## Additional DocTypes and fields (with fieldtype, etc) if any
See pre-requisites
The CoA Map will need to be extended to include the following functionality:
- Item Tax Template name filter (simple pattern matching similar to SQL like) used to generate tax entries, since it may be necessary to select specific transactions for example Services and Mobile Phone Reverse Charges
- Selection of the related transaction value or tax value for the report
- Sales or Purchase filter to allow VAT to be reported to a single account but maintain report flexibility
- Negative - whether the value should be negated
- Sum multiple entries with the same output field name, allows a report value to be a composite of multiple values

## Discovery (how will the user find the feature you are building)
- Chart of Accounts - View menu: HMRC VAT Returns
- Accounting -> Taxes -> HMRC VAT Returns
- Accounting -> Taxes -> Connect to HMRC
- Company -> HMRC Settings
- User -> Third Party Authentication
## Screen Mockups with buttons and any custom UI (TBD)
- HMRC user permissions definition (scopes); also used as auth fail destination
- (OAuth2 Authorisation flow: out-of-scope)
- VAT Information as tables (auth & VAT return submit success):
  - VAT return obligations (mandatory) with buttons to the VAT report specifying the period and PeriodKey
  - Submitted VAT returns (optional)
  - VAT liabilities (optional)
  - VAT payments (optional)
- VAT Report for a period with 2 use cases:
  - Manual period definition, OAuth2 not required, no submit button
  - Period passed from VAT return obligation button, VAT Return submit button
    - Displays error for failed submissions
### Validations
- Company VRN number existence
- HMRC OAuth2 Provider existence
### Calculations
See Reports section
### Logs
None
## Links to existing DocTypes
Links to VAT Accounts
## Reports
Calculations performed according to this table which is not a complete picture:
[UK VAT return](https://docs.google.com/spreadsheets/d/1wgVkg9sJkeLj5-v0tob5P3kw6Xkh_LVHmBi-HENea2M/edit?usp=sharing)
The report uses Journal Entries specified by the CoA Map for boxes 1 to 4 which are the primary VAT lines
Box 5 is a sum based on boxes 3 & 4
Box 6 to 9 must be generated from the transactions used in boxes 1 to 5, to exclude non-VAT transactions, for example: salaries & exempt purchases

This has not been designed for special VAT accounting schemes, though the 9 boxes on the VAT Return will be editable to allow different schemes to be posted.
[Further information from HMRC](https://www.gov.uk/guidance/how-to-fill-in-and-submit-your-vat-return-vat-notice-70012)

### PR DESCRIPTION
**Pull request by nameduser0**
Full integration with UK HMRC MTD VAT REST interface using the new Tax Detail Report, Connected App OAuth2 and Virtual DocType interfaces.

- Retrieval of Obligations, Submitted Returns, Liabilities and Payments
- Submission of Returns
- Population of the return from a Custom Tax Detail report (#25254)
- View of the Custom Tax Detail before submission
- Creation of period ending Journal Entry
- Located in the Regional module

### Accounts workspace card
Screen Shot 2021-05-21 at 14 53 47

### VAT Obligations and Return
Screen Shot 2021-05-21 at 14 30 46

screencapture-localhost-8002-app-uk-mtd-vat-return-786417392-18AK-2021-05-21-14_40_34

### VAT Liabilities
screencapture-localhost-8002-app-uk-mtd-vat-liability-2021-05-21-14_41_56

### VAT Payments
screencapture-localhost-8002-app-uk-mtd-vat-payment-2021-05-21-14_41_30

### HMRC Settings
Screen Shot 2021-05-21 at 14 42 34

Closes #21233 
Closes #16025

### CODE REVIEW

**Comment by nameduser0** [comment]
- [ ] Tweaks to fix bugs like 'undefined' in the list views
- [ ] Permissions check
- [ ] Advertisement & Warning about HMRC "fraud" data gathering
- [ ] Creation of Journal Entry
- [ ] Addition of HMRC fraud prevention headers (!) https://developer.service.hmrc.gov.uk/guides/fraud-prevention/connection-method/web-app-via-server/
- [ ] Documentation
- [ ] Automated tests and remove hard-coded scenarios

**Comment by Alchez** [comment]
Hey @casesolved-co-uk, we're interested in this feature too. Is this still in progress?

**Comment by nameduser0** [comment]
> Hey @casesolved-co-uk, we're interested in this feature too. Is this still in progress?

Hi Rohan, yes we have this feature as a private feature. To get access you'll need to purchase our hosted solution. Thanks for the interest.

**Comment by parsimonyERP** [comment]
@casesolved-co-uk Richard, where can I learn more about your hosted solution?

**Comment by nameduser0** [comment]
@parsimonyERP Hi Michael, thanks for the interest. Https://www.casesolved.co.uk We have a few exciting projects on the go including a uk b2b leads generator, Xero (and any other json data) endpoint importer as well as all the HMRC stuff. Website needs an update!

**Comment by umairsy** [comment]
@casesolved-co-uk This is Umair. Product manager at ERPNext. Will be very interested in learning how we can productify or have UK localization listed on our marketplace https://frappecloud.com/marketplace

Will be great if you can write me back here or on umair@erpnext.com

**Comment by nameduser0** [comment]
@umairsy Hi Umair. Thanks for the interest but I've decided to keep the UK integration as a commercial app add-on until I have recouped the investment. I would have liked to have donated it, but I received very little interest in project donations.
Does your marketplace support non-published apps and commercial agreements? I haven't yet decided whether I would license it outside our hosted environment, but open to ideas.

**Pull request closed without merging**
