### PR TITLE
feat: Make patient age translateable

### PR DESCRIPTION
**Pull request by sgtpepper9907**
`no-docs`

### CODE REVIEW

**Comment by marination** [comment]
@sgtpepper9907 please add a description and maybe screenshots of the impact of your PR
And fix Sider too

**Comment by sgtpepper9907** [comment]
This has been already merged into version-12-hotfix https://github.com/frappe/erpnext/pull/24416

**Comment by marination** [comment]
> This has been already merged into version-12-hotfix #24416

@sgtpepper9907 Please fix sider, we'll then merge it

**Comment by sgtpepper9907** [comment]
@marination fixed!

**Review by marination — APPROVED** [review]

**Review by marination — APPROVED** [review]

**Comment by marination** [comment]
@sgtpepper9907 please update the branch, it is out-of-date.

**Pull request merged**
