### PR TITLE
Update pos.html

### PR DESCRIPTION
**Pull request by bobzz-zone**
Add base total

move discount to above net totals because net totals is calculated after discount

### CODE REVIEW

**Comment by anandpdoshi** [comment]
@nabinhait please have a look

**Comment by nabinhait** [comment]
@bobzz-zone Please don't change the order of "Discount Amount". In POS, it is discount amount is applied on Grand Total, hence it is better to keep that field after taxes.

**Comment by bobzz-zone** [comment]
@nabinhait i changed it becuase it seems net total is calculated with the discount so i want to change the place to be : 
total
disc
net_total
tax
grand total

cant i?

**Comment by nabinhait** [comment]
@bobzz-zone But the discount is applied on grand total, hence the discount amount is distributed between items and taxes. Reordering that field will lead to confusion.

**Pull request closed without merging**
