### PR TITLE
Quality Report 8D for Manufacturing

### PR DESCRIPTION
**Pull request by dottenbr**
- [ ] Awaiting feature for "Standard Workflow" as discussed with @anandpdoshi 

Don't merge till then

### CODE REVIEW

**Comment by dottenbr** [comment]
When can we have this added and what do we need to do @anandpdoshi

**Comment by rmehta** [comment]
@dottenbr we were thinking of introducing a new module called quality and adding it there. Interestingly this is the first such request for a report. 

Also the term "8D" sounds like a management jargon. How about "Quality Analysis Report" or something?

**Comment by dottenbr** [comment]
@rmehta thats is a great idea. Its actually called "Eight Disciplines Problem Solving" and customers and suppliers frequently require an "8D Report" whenever there was an issue during manufacturing of a product. At first this may seem technical or complicated but the 8 disciplines are actually good practice. I have tried including discriptions guiding more novice users through report creation. I strongly belice "8D Quality Report" would be the proper name for this, however due to technical constraints of Frappe not allowing a number at the beginning I think "Quality Report 8D" is a fitting name.

**Comment by cgpurbaugh** [comment]
The quality department for my company has been asking for a Quality module.  I thought I was going to have to add one myself, but hopefully this makes it to the next update :)

**Comment by rmehta** [comment]
You can add one too and send in a request. We are already so much behind on issues.

**Comment by dottenbr** [comment]
@rmehta and @anandpdoshi I have created the 8D report. I am not sure what still needs checking on your end. Maybe you can look into this and merge the pull request after some testing. Then @cgpurbaugh can test it and we can improve it together with their quality department.

**Comment by cgpurbaugh** [comment]
@rmehta The last time that I tried to create a new module, I crashed our whole system and we had to reinstall from scratch.  These things are a little over my head.

**Comment by anandpdoshi** [comment]
It still needs the export workflow as a standard one so that it is synced into database during update. Also we need to add some validations in workflow.

**Comment by anandpdoshi** [comment]
I will get that done this week.

**Comment by dottenbr** [comment]
Thank you so much @anandpdoshi and @rmehta

**Comment by anandpdoshi** [comment]
Hi @dottenbr 

We had an internal discussion and we think this should be in a separate app. Do you want to do it? Or should we make the changes?

Also, since we are a bit backlogged for the moment, we decided not to do the standard workflows on priority. Since this code will be moved to a separate app, we can export the Workflow attached to this form as a [Fixture](https://kb.frappe.io/kb/app-development/how-to-add-customizations-to-app).

We want to close this pull request as the only roadblock to it is from our side. So this workaround should get the ball rolling.

**Comment by dottenbr** [comment]
Hi @anandpdoshi sorry this reply has been taking forever. Moving it into a "Quality" app would probably be wise so things can grow from there. I can imagine other quality relevant things in there in the future. It would be best if you did this to do it right. I am not that far yet.

**Comment by dottenbr** [comment]
@rmehta any news on how this will go on?

**Comment by rmehta** [comment]
@dottenbr can you add this to a new app?

**Comment by dottenbr** [comment]
Hi @anandpdoshi and @rmehta I have created a Quality app in which I will collect this and everything else that is quality management relevant and then I will put it up for discussion if this should be integrated in ERPNext stack or if it should stand as its own App. However I am having difficulties moving my DocTypes from the pull request (Manufacturing/Quality...) to my Quality app. I am trying to resolve this and I will ask for help if I can't.

The Quality app lives under https://github.com/newmatik/Quality/

**Comment by dottenbr** [comment]
Alright, instead of moving files around I decided to use the frontend to make duplicates in the new module. Works like a charm!

**Comment by dottenbr** [comment]
Alright everybody. I have moved it to https://github.com/newmatik/Quality. @cgpurbaugh would you be willing to contribute your ideas and/or code to this? @CWTGMBH did you write quality relevant code yourself that we could move in here and merge to the ERPNext stack when done and tested?

 @anandpdoshi you said:
> It still needs the export workflow as a standard one so that it is synced into database during update. Also we need to add some validations in workflow.
And we wrote the following when we created the pull request:
> Awaiting feature for "Standard Workflow" as discussed with @anandpdoshi

I will close the pull request and I hope that @anandpdoshi can contribute the remaining fixes to ERPNext and or nematik/Quality?

**Comment by cgpurbaugh** [comment]
@dottenbr I'll do my best at contributing code, and I'll give you any ideas that I have.  How do I install this though?

**Comment by dottenbr** [comment]
@cgpurbaugh I have written a small instruction here, does this help?
https://github.com/newmatik/Quality/blob/master/README.md

**Pull request closed without merging**
