### PR TITLE
feat: Create Syscohada chart of accounts for affiliated African countries

### PR DESCRIPTION
**Pull request by n-traore**
SYSCOHADA is the accounting system and financial reporting currently adopted by 17 African countries. It provides a standardized framework to enhance transparency and comparability in financial statements for businesses in these regions.

This PR aims at adding this standardized chart of accounts into ERPNext so it is usable by said countries.
If possible, these changes should be backported.

References : 
- https://fr.wikipedia.org/wiki/Plan_comptable_(OHADA)
- https://www.droit-afrique.com/uploads/OHADA-Plan-comptable-2017.pdf

Files added:
-
1. **Generic chart of accounts with code**
`erpnext/accounts/doctype/account/chart_of_accounts/verified/syscohada_plan_comptable_avec_code.json`

2. **Generic chart of accounts**
`erpnext/accounts/doctype/account/chart_of_accounts/verified/syscohada_plan_comptable.json`

3. **Helper to generate individual files for all affiliated countries by specifying country name where applicable**
`erpnext/accounts/doctype/account/chart_of_accounts/verified/syscohada_chart_of_accounts.py`

4. **Helper that will run previous python file to generate charts files for each country whenever the generic ones are updated, then commit the updated files and create a PR to integrate the new files to the repo.**
`.github/helper/update_syscohada_charts.sh`

The files generated for each country will look like: **country**_plan_comptable.json or **country**_plan_comptable_avec_code.json

5. **Github Actions workflow to automate the run of bash script**
`.github/workflows/generate_syscohada_charts.yml`

Files deleted :
-
**Unverified chart file for syscohada**
`erpnext/accounts/doctype/account/chart_of_accounts/unverified/syscohada_syscohada_chart_template.json`

Screenshots :
-
Setup Wizard:

setup_wizard

Company:

societe_1

societe_2

societe_3

no-docs

### CODE REVIEW

**Comment by n-traore** [comment]
@ruthra-kumar @deepeshgarg007 When do you think these changes could be integrated ?

**Comment by ruthra-kumar** [comment]
@n-traore 

Using Github Actions to dynamically create COA templates doesn't look like a good idea. Templates are mostly static.

Create them locally and add them as static `JSON` files. Also the template file look huge. Better to create multiple PR's for different countries.

**Comment by n-traore** [comment]
Hello @ruthra-kumar 
Thanks for your response. The idea behind this is to avoid having to modify mutliple files for each country in case of update to the template, knowing that the only difference is in the country key. I believe that this could be error prone.

Also regarding the PRs, I feel like it would be repetitive to generate 17 different PRs, no ?

**Comment by ruthra-kumar** [comment]
@n-traore 


I would suggest to only include the generation script (.py file), the 2 template files and the generated `JSON` files in the PR.

> The idea behind this is to avoid having to modify mutliple files for each country in case of update to the template, knowing that the only difference is in the country key.

You can still achieve this locally. If a change is required, run the generation script locally and make a PR for the changes.


> I feel like it would be repetitive to generate 17 different PRs

Ok. Let's go with a single PR.

**Comment by n-traore** [comment]
@ruthra-kumar 
Fair enough, I have created a new PR #44453 as per your request. Closing this one.

**Pull request closed without merging**
