### PR TITLE
fix: projects website list visible for guests and all logged in customers

### LINKED ISSUE #39009: Projects page on the website portal is public, anyone can see it
### Information about bug

Under an incognito and unlogged user, I can access the list of projects when they should be private and only accessible when signed in with the correct permissions. erp.example.com/project When I click on erp.example.com/newsletters they are inaccessible and I need to log in, which is correct as I set the newsletters to private.

Could you point me to where in the code base I can look to see if I can fix the privacy issue? Thank you.

### Module

projects, portal

### Version

ERPNext: v15.8.3 (version-15)
Frappe Framework: v15.7.0 (version-15)
Frappe HR: v15.7.1 (version-15)
Payments: v0.0.1 (version-15)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

I checked the logs in the sites folder, but I couldn't find the line items related to this bug. Are there other logs where I can find more information about this bug?

### LINKED ISSUE #39155: projects page on the portal is public anyone can see it
### Information about bug

when you visit erpnext path installation erpnext.domaine.com/project 
any one can see the list of projects you have with images of assignees ...

### Module

portal

### Version

ERPNext: v15.2.0 (version-15)

Frappe Framework: v15.1.0 (version-15)

Helpdesk: v0.10.0 (main)

Frappe HR: v16.0.0-dev (develop)

Frappe LMS: v1.0.0 (main)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by 0xD0M1M0**
fix: projects website list visible for guests and all logged in customers

see the issue for details

Introduced by #36218
closes #39009, #39155

### CODE REVIEW

**Comment by 0xD0M1M0** [comment]
@s-aga-r could you please review the PR?

**Comment by 0xD0M1M0** [comment]
Unrelated test fail

**Review by s-aga-r — CHANGES_REQUESTED** [review]
@0xD0M1M0 also remove the line 317 `user = frappe.session.user`

**Review by barredterra — APPROVED** [review]

**Comment by s-aga-r** [comment]
unrelated failing tests.

**Pull request merged**
