### PR TITLE
Asset Balance Report

### PR DESCRIPTION
**Pull request by kunhimohamed**
> Asset Balance Report

> We can see Asset Balance until the given date.

Screenshot from 2023-03-29 15-29-12

### CODE REVIEW

**Comment by anandbaburajan** [comment]
Hi @kunhimohamed, the Fixed Asset Register report lets you view the purchase amount, **current** depreciated value and **current** asset value. Did you create this "Asset Balance" report because you want to see the asset balance or depreciated value up to a particular date in the past? If yes, can you share why you want to see that? Trying to understand your use-case.

**Comment by kunhimohamed** [comment]
> Hi @kunhimohamed, the Fixed Asset Register report lets you view the purchase amount, **current** depreciated value and **current** asset value. Did you create this "Asset Balance" report because you want to see the asset balance or depreciated value up to a particular date in the past? If yes, can you share why you want to see that? Trying to understand your use-case.

Fixed Asset Register based on Asset Category not an Asset.

**Comment by anandbaburajan** [comment]
> Fixed Asset Register based on Asset Category not an Asset.

@kunhimohamed I didn't get you, can you please elaborate?

**Comment by support-gennextsystems** [comment]
> > Fixed Asset Register based on Asset Category not an Asset.
> 
> @kunhimohamed I didn't get you, can you please elaborate?

Sorry, I am referring old version.

**Comment by kunhimohamed** [comment]
> > Fixed Asset Register based on Asset Category not an Asset.
> 
> @kunhimohamed I didn't get you, can you please elaborate?

Sorry, I am referring old version.

**Pull request closed without merging**
