### PR TITLE
fix: fieldname when updating docfield property

### PR DESCRIPTION
**Pull request by AfshanKhan**
Backport of https://github.com/frappe/erpnext/pull/25516

### CODE REVIEW

**Comment by muchai** [comment]
Could be missing something, but something's not really ok with the fix.

It now displays payments, and allows selection of an invoice.

But it doesn't display invoices, until at least an invoice is selected in the payments section.

**Comment by AfshanKhan** [comment]
> Could be missing something, but something's not really ok with the fix.
> 
> It now displays payments, and allows selection of an invoice.
> 
> But it doesn't display invoices, until at least an invoice is selected in the payments section.

@muchai can you please share a video or gif of the problem?

**Comment by muchai** [comment]
After clicking get unreconciled entries, doesn't display open invoices
image

After selecting at least one invoice
image

When I leave the invoice number field blank, and click on reconcile.
image

In short, this only allows reconciling a payment one invoice, at a time, as is you can't use one payment to reconcile multiple invoices.

**Comment by AfshanKhan** [comment]
@muchai Thanks for the detailed explanation. I get your point. I'll get back to you on this.

**Pull request merged**
