### PR TITLE
fix: from Purchase Order, while creating sales order, is internal customer check was missing in SO

### PR DESCRIPTION
**Pull request by vishdha**
Step1. Create Internal Sales order from PO
Step2. Internal Customer is fetch but is internal customer check was not set
this change will set is_internal_customer = 1

### CODE REVIEW

**Comment by vishdha** [comment]
Backport to version-14

**Comment by vishdha** [comment]
Can someone review and merge this

**Comment by deepeshgarg007** [comment]
@vishdha In Sales Order `is_internal_customer` check is fetched from the customer master. If that was not fetched means the customer was not an internal customer, don't think this change is required. Was this happening even after save?

**Comment by vishdha** [comment]
> @vishdha In Sales Order `is_internal_customer` check is fetched from the customer master. If that was not fetched means the customer was not an internal customer, don't think this change is required. Was this happening even after save?

Hello @deepeshgarg007 the thing you suggested is correct. but just try to replicate this. 
1. Create internal purchase Order
2. Then create Internal Sales Order from Purchase Order
3. once Sales Order form open it contain Internal Customer but is_internal_customer check was not set.
4. our problem is that we use different series for SO. for Normal So - so.###, for Internal So - ISO.##### based on Is_internal_customer checkbox
5. because this is_internal_customer not set when save document series get set to normal SO.### even if our customer is internal customer.
6. Once Series get set we cannot change series after save
7. same you look for line number 2109 this changes applied for SO to PO.

**Comment by vishdha** [comment]
https://user-images.githubusercontent.com/6947417/212834587-f7e535d6-1bd5-48c9-9e7f-092293f06df0.mp4

**Comment by deepeshgarg007** [comment]
image

@vishdha This is set for the `is_internal_customer` field, this also works on the server side there is no way this doesn't work
The use case of the naming series that you have mentioned can be handled via customizations. Closing this PR

**Pull request closed without merging**
