### PR TITLE
Validate negative stock on delivery while missing valuation rate for booking expenses

### PR DESCRIPTION
**Pull request by nabinhait**

### CODE REVIEW

**Comment by RobertSchouten** [comment]
@nabinhait validation is only required on
if frappe.defaults.get_global_default('allow_negative_stock') and frappe.defaults.get_global_default('auto_accounting_for_stock')

**Comment by nabinhait** [comment]
@RobertSchouten This code will only be executed if negative inventory and perpetual inventory enabled.

**Comment by RobertSchouten** [comment]
@nabinhait fails automated tests please address

**Comment by RobertSchouten** [comment]
@nabinhait this also blocks stock entries from being amended before invoicing

**Comment by nabinhait** [comment]
Fixing test cases.
Is the Stock Entry for outward transactions like Material Issue? In that case, it should block that transaction as well.

**Comment by RobertSchouten** [comment]
@nabinhait the stock entry before the delivery note or sales invoice that is trying to b amended.
should currently it means that invoices also have to b cancelled to amend stock entries

**Pull request merged**
