### PR TITLE
chore/small refactor

### PR DESCRIPTION
**Pull request by blaggacao**
- chore: devoid pr of hard to maintain code smells
- feat(payment): add more payment channels than just email and phone (think: chat)
- test: add payment channel tests

^^ on prior PRs part of my current sprint

---

- perf: flush db at once
- refactor: explicate intent on make_payment_request interface

`no-docs`

### CODE REVIEW

**Comment by ruthra-kumar** [comment]
@blaggacao Do you still need this as https://github.com/frappe/erpnext/pull/40643 is merged?

**Comment by blaggacao** [comment]
@ruthra-kumar yes, please, this is a crucial stepping stone for:

- https://github.com/frappe/erpnext/pull/40845 (wip)
- hence: https://github.com/frappe/payments/pull/53 (wip)
- thus contributing my PayZen integration (undergoing 3rd iteration, atm)

:smile: 

(I just rebased)

**Comment by blaggacao** [comment]
@ruthra-kumar it is still green as a package, but you might want to review the *feature* of https://github.com/frappe/erpnext/pull/40424 first. That PR also boast of additional test coverage, establishing a new stability baseline. :shrug:

**Comment by blaggacao** [comment]
Lore ipsum ...

**Comment by blaggacao** [comment]
Closing this in order to focus on https://github.com/frappe/erpnext/pull/40845

**Pull request closed without merging**
