### PR TITLE
fix(HR): Change Due Advance Amount to Pending Amount

### PR DESCRIPTION
**Pull request by abhishekbalam**
Fieldname change from `Due Advance Amount`
To `Pending Amount` as it is confusing.

Changed reference name in the code too for easy 
debugging in the future.

### CODE REVIEW

**Review by deepeshgarg007 — CHANGES_REQUESTED** [review]
You'll also have to write a patch to copy data from old fieldname to new fieldname in existing records

**Comment by abhishekbalam** [comment]
> You'll also have to write a patch to copy data from old fieldname to new fieldname in existing records

Sure, I'll figure it out and push 🖖

**Comment by abhishekbalam** [comment]
@Mergifyio backport version-12-hotfix

**Review by Anurag810 — APPROVED** [review]

**Comment by Anurag810** [comment]
@Mergifyio backport version-12-hotfix

**Pull request merged**
