### PR TITLE
feat: pending payments to reconcile

### PR DESCRIPTION
**Pull request by rtdany10**
Report to get list of parties for whom reconciliation is required.

image

<hr>

Depends on https://github.com/frappe/erpnext/pull/38220

### CODE REVIEW

**Comment by rtdany10** [comment]
`get_partywise_advanced_payment_amount` shows wrong value for POS invoices. 
Ref: https://github.com/frappe/erpnext/issues/38130

Since this PR also uses the same function. I'm moving it to draft

**Comment by rtdany10** [comment]
Depends on https://github.com/frappe/erpnext/pull/38220

**Comment by ruthra-kumar** [comment]
@rtdany10 

Can't the same information be obtained from Accounts Receivable report?

**Comment by rtdany10** [comment]
> @rtdany10
> 
> Can't the same information be obtained from Accounts Receivable report?

Yes, can be done, but not when you have 1000s of customers. AR is a heavy report.

**Comment by dj12djdjs** [comment]
My understanding this report is Accounts Receivable Summary with a filter Advance Amount > 0. I think that since this is a pretty simple report, and the data is already available in the existing accounting report(s) (Accounts Receivable, and Accounts Receivable Summary) this report is better for a customer customization's app.

Currently, it would be easy for the operator to switch between summarized advanced payments, and detailed advanced payments just by switching between Accounts Receivable, and Accounts Receivable Summary
image
image

This is just my thoughts, granted I've not delt with customer(s) dealing with thousands of active AR accounts.

**Comment by rtdany10** [comment]
AR Summary is a heavy report with a lot of computation. Generating that for just checking advance doesn't seem very logical.

> this report is better for a customer customization's app.

Currently its done as such, but I felt this would be a nice addition for bigger organizations with a lot of customers. Especially when FC works by limiting total computation per day.

**Pull request closed without merging**
