### PR TITLE
[enhance] Production Plan

### PR DESCRIPTION
**Pull request by rohitwaghchaure**
# Production Plan

Production plan helps user to plan production aginst the multiple sales orders or the material requests and also plan for the purchase of the raw materials which will be used in the production.

To use the Production Plan, go to:

> Manufacturing > Production > Production Plan

production_plan

#### Production Against Sales Orders

* Select option as Sales Order from the drop down list of get items from. System will show the filters, using that we can pull the sales orders for the production.

sales_order_filter

* Click on Get Sales Orders to fetch sales orders based on above filters

sales_order_items

* Click on Get Items for Production Order to fetch the items from the above sales orders.

sales_order_items

#### Production Against Material Requests

* Select option as Material Request from the drop down list of get items from. System will show the filters, using that we can pull the material requests for the production.

material_request_filter

* Click on Get Material Request to fetch material requests based on above filters

material_requests

* Click on Get Items for Production Order to fetch the items from the above material requests.
material_request_items

## Planning for Material Requests
* Click on get raw materials for production button to fetech raw materials required in the production.

material_request_plan

  * Include Non Stock Items :- To add non stock items in the material request planning.
  * Include Subcontracted Items :- To add subcontracted item's raw materials if use multi level bom is disabled
  * Ignore Existing Ordered Quantity :- If enabled then system will not check the projected quantity to make material request.

# Options To Make Production Order and Material Request
make_po_mr

# Production Plan List
screen shot 2017-12-25 at 2 27 07 pm

https://github.com/frappe/erpnext/issues/11044
https://github.com/frappe/erpnext/issues/7947

### CODE REVIEW

**Comment by sachinhub** [comment]
Hi @rohitwaghchaure , What is the difference between existing production planning tool and this one?

**Comment by rohitwaghchaure** [comment]
@sachinhub 

1. Using production plan, you can maintain the history of your production which is not possible in the production planning tool.

1. In production planning tool if you set Use Multi Level BOM then it applies to all the items selected for the production where as in production plan you can enabled/disabled Use Multi Level BOM against each production item

1. You can see the list of raw materials in the production plan to make material requests. You can also add/delete these items.

**Comment by tundebabzy** [comment]
@rohitwaghchaure
Conflicts

**Comment by sachinhub** [comment]
Ok @rohitwaghchaure will give it a try. We were also working on some enhacements to production planning tool. Mainly following - 

1. Ability to start and finish multiple production orders at a time.
2. Create a consolidated Material Request for all the Raw Materials needed for all Pending Production orders. A single material request will be created which will then used for stock transfer from raw material warehouse.
3. Automatically create stock entries (submit stock entry) along with pre-configured batch number format

**Comment by rmehta** [comment]
The column "Use Multilevel BOM" is confusing... How about "Include Exploded Items" ?

**Comment by rohitwaghchaure** [comment]
@rmehta Sure, I'll make change

**Comment by rohitwaghchaure** [comment]
Fixed!

**Pull request merged**
