### PR TITLE
feat: Disassemble 

### PR DESCRIPTION
**Pull request by rohitwaghchaure**
### **Work Order**

Added button to make "Disassembly Order" from the work order, on click of it system opens the stock entry with type as "Disassembly Order"

Screenshot 2024-08-06 at 10 54 34 PM

### Disassembly Order
Screenshot 2024-08-06 at 4 44 30 PM

Docs https://docs.erpnext.com/docs/user/manual/en/disassembly-order

### CODE REVIEW

**Comment by TurkerTunali** [comment]
Hello Rohit, 
What is the benefit of Disassembly Order? What is it's use case?

**Comment by rknroot** [comment]
> Hello Rohit, What is the benefit of Disassembly Order? What is it's use case?

Disassembly Order is helpful in resource recycling of EOL products.

**Comment by brijendraa** [comment]
It is good feature to have but have you verified its impact on item valuation as semi finished and raw material gets added and finished item gets subtracted.  Also if it has multi level BOM then each exploded items is subject to verification or QC before to add in the stock because all the items can not be disassembled because some items now cannot be reused. Also in ERPNEXT for multi level BOM, it generates Work Orders for each sub assemblies ie multiple Work Orders, so what it disassembly is done on Final product having Multi level BOM and need disassembly after sales return as a result of rejection by customer. Impact on accounts posting also need careful analysis.

**Comment by rohitwaghchaure** [comment]
> It is good feature to have but have you verified its impact on item valuation as semi finished and raw material gets added and finished item gets subtracted. Also if it has multi level BOM then each exploded items is subject to verification or QC before to add in the stock because all the items can not be disassembled because some items now cannot be reused. Also in ERPNEXT for multi level BOM, it generates Work Orders for each sub assemblies ie multiple Work Orders, so what it disassembly is done on Final product having Multi level BOM and need disassembly after sales return as a result of rejection by customer. Impact on accounts posting also need careful analysis.

The valuation rate, users must adjust for raw materials and semi-finished goods because it depends on the depreciation cost of the components.

**Pull request merged**
