### PR TITLE
refactor: Leave Application should not be in hook.py

### PR DESCRIPTION
**Pull request by kittiu**
I am not sure this is correct, but AFAIK, Leave Application should be in hrms app, is it not?

### CODE REVIEW

**Comment by barredterra** [comment]
@kittiu please also create a PR to https://github.com/frappe/hrms that adds this line there, so that we don't lose any functionality.

**Comment by kittiu** [comment]
> @kittiu please also create a PR to https://github.com/frappe/hrms that adds this line there, so that we don't lose any functionality.

Thanks and done.

https://github.com/frappe/hrms/compare/develop...kittiu:hrms:patch-1

**Comment by ruchamahabal** [comment]
> https://github.com/frappe/hrms/compare/develop...kittiu:hrms:patch-1


@kittiu Can you create the pull request on hrms?

**Comment by kittiu** [comment]
https://github.com/frappe/hrms/pull/691
Sorry for previous mistake. Here you go.

**Pull request merged**
