### PR TITLE
fix: Add validation for warehouse in material transfer

### LINKED ISSUE #41643: Transfer (warehouse should not allow user to choose same)
### Information about bug

image

### Module

stock

### Version

Frappe : 15.28.0
ERPNext : 15.25.0

Frappe : 14.75.0
ERPNext : 14.70.2

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by Nihantra-Patel**
version 15 and 14

fixes: #41643

**Before:**

https://github.com/frappe/erpnext/assets/141945075/6a9a4746-4bcc-452f-992b-5518b0f5fb0c

**After:**

https://github.com/frappe/erpnext/assets/141945075/5084ad96-90cd-464d-91dc-468126f4d4b4

### CODE REVIEW

**Comment by deepeshgarg007** [comment]
@Nihantra-Patel These validations are already present. Please check the entire code before adding any changes

https://github.com/frappe/erpnext/blob/develop/erpnext/stock/doctype/stock_entry/stock_entry.py#L613

**Comment by Nihantra-Patel** [comment]
Hi @deepeshgarg007,

Right, validation is set, but it does not set for the Material Transfer.

Please again check the condition. self.purpose not in 

https://github.com/frappe/erpnext/blob/c41b2398816564fee5219f8fabd983211d308e4c/erpnext/stock/doctype/stock_entry/stock_entry.py#L609-L613

so, can we remove the Material Transfer from the condition? and update PR?

**Comment by dj12djdjs** [comment]
@Nihantra-Patel It looks like this condition was added for the "Inventory Dimensions" feature.

In this case, the condition makes sense.

Consider you have 1 warehouse "Stores" and several inventory dimension records. If you want to transfer stock in the same warehouse but different dimension records, then the source and target warehouse must be the same.

**Comment by thida-bcn** [comment]
> @Nihantra-Patel It looks like this condition was added for the "Inventory Dimensions" feature.
> 
> In this case, the condition makes sense.
> 
> Consider you have 1 warehouse "Stores" and several inventory dimension records. If you want to transfer stock in the same warehouse but different dimension records, then the source and target warehouse must be the same.

There might be different use case
1) using dimension

2) without dimension
should not accept same location

**Pull request closed without merging**
