### PR TITLE
Update de.csv

### PR DESCRIPTION
**Pull request by wojosc**
Missing translation

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

### CODE REVIEW

**Comment by barredterra** [comment]
https://translate.erpnext.com/help

> 3. Please accept my bulk translations in CSV
> Sorry but we cannot be unfair to those who have edited and verified the translations on the portal. Please update translations on the portal only!

**Comment by wojosc** [comment]
> https://translate.erpnext.com/help
> 
> > 1. Please accept my bulk translations in CSV
> >    Sorry but we cannot be unfair to those who have edited and verified the translations on the portal. Please update translations on the portal only!

Thank you for your consideration. Do you know if it is possible to block the translation here?

Is there any documentation on how and where translations are supposed to be done?

Thanks.

**Comment by barredterra** [comment]
Docs on translation are mostly non-existent. Maybe a good topic for the next documentation sprint.

**Review by nabinhait — APPROVED** [review]

**Comment by wojosc** [comment]
Hi @nabinhait , what do you say, how shall we go about translations so that we don't work against each other here.

**Pull request merged**
