### PR TITLE
refactor: rewrite buying reports queries in qb

### PR DESCRIPTION
**Pull request by s-aga-r**
- [x] Procurement Tracker
- [x] Purchase Order Analysis
- [x] Supplier Quotation Comparison

#32735

### CODE REVIEW

**Review by deepeshgarg007 — APPROVED** [review]

**Comment by deepeshgarg007** [comment]
@Mergifyio backport version-14-hotfix

**Comment by v3ss0n** [comment]
qb looks like sqlalchmey core , i am wondering why you guys don't use sqlalchemy directly and enjoy a lot of benefits

**Comment by s-aga-r** [comment]
> qb looks like sqlalchmey core , i am wondering why you guys don't use sqlalchemy directly and enjoy a lot of benefits

@v3ss0n The [Frappe Query Builder](https://frappeframework.com/docs/user/en/api/query-builder) is written around [PyPika](https://github.com/kayak/pypika). SQLAlchemy is an ORM whereas PyPika is a Query Builder.

**Comment by v3ss0n** [comment]
sqla-core is query builder. You can use it without ORM features.  But cool , hope to see PG integration soon.

**Comment by v3ss0n** [comment]
PyPika is unmaintained for a year .  SQLalchemy-core is not orm it is query builder arguably highest quality , most well maintained SQL framework out there. 
https://docs.sqlalchemy.org/en/20/core/

Anyways , looking forward for the PG integration.

**Pull request merged**
