### PR TITLE
    fix: date validation, setting up default company, customer/supplier manadatory property on Blanket Order

### PR DESCRIPTION
**Pull request by khushalti**
Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

### CODE REVIEW

**Comment by khushalti** [comment]
i got below error for Travis Checks
image

**Comment by khushalti** [comment]
any hint?

**Comment by khushalti** [comment]
@deepeshgarg007 ?

**Comment by deepeshgarg007** [comment]
> @deepeshgarg007 ?

**Comment by deepeshgarg007** [comment]
> any hint?

@khushalti The above test case fails randomly sometimes. Its fine, will review and merge

**Comment by khushalti** [comment]
@deepeshgarg007  Thanks !!

**Review by deepeshgarg007 — APPROVED** [review]

**Pull request merged**
