### PR TITLE
Multi currency

### PR DESCRIPTION
**Pull request by nabinhait**

### CODE REVIEW

**Comment by nabinhait** [comment]
ERPNext  Demo in multi currency: 
https://github.com/frappe/erpnext_demo/pull/14

**Comment by nabinhait** [comment]
To-do list against Github Issue #1002

- [x] Add Account Currency to Account & Party
- [x] Add Debit (in Alt Currency) and Credit (in Alt Currency) to GL Entry
- [x] [validation] Do not allow currency to change if any transaction has been made for both Party and Account
- [x] Currency input on creation of account from Chart of Accounts
- [x] In GL Entry posting, also post in alternate currency if party and account currencies are alt and match
- [x] Currency in Party and Account (Debtors) must match
- [x] In Journal Entry, on selection of account, select currency for the row.
- [x] In Journal Entry, Sales Invoice, Purchase Invoice post to default currency (DC) (based on exchange rate) and Account Currency (AC)
- [x] Fetch Exchange rate in Journal Entry based on average exchange_rate in case of inter-bank transfer, otherwise fetch current exchange rate
- [x] Currency in transactions must be either in party currency or company currency
- [x] All selected accounts in a transaction must be with transaction currency or in company currency
- [x] Invoice outstanding, advance amount in party account currency
- [x] Invoice paid amount and write off amount in both company currency and transaction currency
- [x] Patch for Outstanding, Paid, advance, write-off amount
- [x] Payment Tool in party currency
- [x] Accounting Currency in Customer / Supplier, patch for existing records
- [x] Force to mention Receivable / Payable account in Customer/Supplier, if party account currency is different from company currency
- [x] Show Receivable / Payable accounts, in accounting currency for customer/supplier and validate
- [x] Update "Advance Paid" in Order, based on party account currency, validate with grand total based on currency
- [x] Test Case
- [x] Patch
  - Set `currency` in Account, GL Entry, Journal Entry
  - Update `base_paid_amount`, `base_write_off_amount`, `party_account_currency` value in sales / purchase invoice
  - Update Exchange Rate, debit/credit in account currency in Journal Entry and GL Entry
  - Set Accounting Currency for party
  - Set party account if default currency of party other than company's default currency
- [x] Reports: Show Balance in account currency if filtered by account and account currency is different from company currency
  - General Ledger
  - Receivable
  - Payable
- [ ] Reports: Show all balances in company currency based on exchange rate as on filter `[Not Clear]`
  - Trial Balance
  - Balance Sheet
  - P&L
  - Financial Analytics
- [ ] Update manual `[In Progress]`
- [x] Add multi currency data in erpnext-demo
- [x] Set currency and exchange rate based on customer in Quotation while making from Opportunity
- [x] Set currency and exchange rate based on Supplier in Supplier Quotation / Purchase Order while making from Material Request

**Comment by nabinhait** [comment]
Screenshots:
customer
supplier
chart-of-accounts
account
sales-invoice
sales-invoice-write-off
journal-entry-exchange-rate
journal-entry-row
gl-entry
payment-tool
general-ledger
accounts-receivable
bank-reconciliation-statement

**Comment by nabinhait** [comment]
Manual Update: 
https://github.com/frappe/manual_erpnext_com/pull/45

**Comment by bobzz-zone** [comment]
@nabinhait is it merged now ?

**Comment by anandpdoshi** [comment]
@bobzz-zone now it is! If you want to test it on your bench, do a `bench switch-to-develop` and run `bench update`

**Comment by bobzz-zone** [comment]
@anandpdoshi @nabinhait i got bugs... on account payable .... there is currency errors , because in the amount column there should be CNY 73.400 but shown CNY 164.658.000 (kurs 1 CNY = IDR 2.243.3) on my data. my company currency is IDR , thanks

**Comment by bobzz-zone** [comment]
i think the error is made when ledger for PI is created the GL entry is not right.....

**Pull request merged**
