### PR TITLE
[Enhancement] Standalone Credit and Debit Notes

### PR DESCRIPTION
**Pull request by javierwonghf**
Allow creation of Standalone Credit Notes and Standalone Debit Notes (without reference to Sales or Purchase Invoices). These Standalone documents can never be created with implications to stock.
- Requires https://github.com/frappe/frappe/pull/4033
- Update Stock is never allowed for Standalone Credit Notes and Standalone Debit Notes

standalone_cn_and_dn

### CODE REVIEW

**Comment by bohlian** [comment]
Hi all. The Travis Ci Build failing due to a test case that does not originate from the PR. Can someone review this please? Thank you.

**Comment by bohlian** [comment]
@nabinhait any chance you could have a look at this please? Thanks man.

**Comment by tundebabzy** [comment]
Hi @bohlian 
Thanks for this PR. You haven't any test case though.

**Comment by rmehta** [comment]
@bohlian sorry for the late review. There are a few UX issues to start with

1. Hard-coding of Print Heading
2. Creating a new stand alone credit note from an invoice (let it be created independently)

Also how do you handle the payment or reconciliation?

**Comment by bohlian** [comment]
@rmehta attempting to rectify some of the issues brought up now.
1. Hard-coding of Print Heading - Honestly this can be removed, it is just that the existing Credit Note via Invoices does that as well so it was just to follow the same standard. Let me know what you think of this, it can be removed.
2. Because the existing style of Credit Notes / Debit Notes are created via the Invoices it would be incredibly strange if there we had to create it via an independent doctype (I really this think would not be a good experience as it will cause confusion) - If it was possible to expose a link in the module screen that says "Credit Note" but actually gets pointed to a Negative invoice I suppose it would be good but I dont think its possible. Do you have any suggestions?

Payment and Reconciliation are already handled by the core (tested and it works), for Payments the CN / DNs are handled exactly like how a Credit Note and Debit Note (with reference to an Invoice) is done. They appear as negative and if there are outstanding balances it will reduce it.

**Comment by adnanmunir83** [comment]
are we going to Merge this PR?

**Comment by nabinhait** [comment]
Thanks for the PR.

We are developing the feature ourself and it is in our this month's to-do list. We will refer this PR while developing the feature. For now closing the PR.

**Comment by darthguru** [comment]
hey is there any update on this feature We really need this method for credit notes

**Comment by nabinhait** [comment]
@darthguru The feature is already developed and merged into develop branch.

**Comment by adnanmunir83** [comment]
@nabinhait can we have this feature merged in V10 as well?

since V11 is not that much stable and it'll take time to become stable. 

will appreciate your comments on this

**Comment by nabinhait** [comment]
@adnanmunir83 Sorry, it will be difficult to have this feature in v10

**Pull request closed without merging**
