### PR TITLE
Retranslate for khmer language.

### PR DESCRIPTION
**Pull request by sophatvathana**
Retranslate for khmer language.

### CODE REVIEW

**Comment by sophatvathana** [comment]
Don't worry i am Cambodian(Khmer) people.

**Comment by rmehta** [comment]
@sophatvathana please update translations at https://translate.erpnext.com 

They will be overwritten otherwise.

**Comment by sophatvathana** [comment]
Yes i see. Thank you so much.

**Comment by sophatvathana** [comment]
When i try to translate i got this message Only user with more than 100 karma can edit verified translations. It mean that i don't have karma.

**Pull request closed without merging**
