### PR TITLE
fix: communication_date in party dashboards

### PR DESCRIPTION
**Pull request by GursheenK**
Ref: https://github.com/frappe/frappe/pull/24884

With recent changes to the order by statement in the `get_communication_data` utility of FW, the party dashboards in ERPNext threw the following error - 

Screenshot 2024-02-21 at 6 47 38 PM

<br>
<br>

**Changes**

- Since the util uses the `communication_date` to sort records, fetch it by mentioning it in the field list.
- Also sort the Activity Log records to match that of the communication data.

### CODE REVIEW

**Comment by ankush** [comment]
@GursheenK add tests for these. it's as simple as just running the code in this case.

**Comment by barredterra** [comment]
Thanks for cleaning up my mess, @GursheenK. I'll take care of adding the test cases.

**Comment by ankush** [comment]
@barredterra added a catchall test - https://github.com/frappe/erpnext/pull/40042

**Comment by ankush** [comment]
@mergifyio backport version-15

**Pull request merged**
