### PR TITLE
refactor: updated print format for general ledger

### PR DESCRIPTION
**Pull request by akashdubey22**
This is Better General Ledger print format. Also request contributors to make it more attractive as this is sent to clients & it needs better presentations than the default print format.

`no-docs`

### CODE REVIEW

**Comment by ruthra-kumar** [comment]
## Before
Portrait: Screenshot 2024-11-11 at 15-13-00 General Ledger
Landscape: Screenshot 2024-11-11 at 15-12-49 General Ledger

## After
Portrait: Screenshot 2024-11-11 at 15-12-04 General Ledger
Landscape: Screenshot 2024-11-11 at 15-11-59 General Ledger

**Comment by akashdubey22** [comment]
As I am not professional programmer, my request to expert is to correct pull request so that ERRORS are removed & changes are successfully merged !!

**Comment by ruthra-kumar** [comment]
@akashdubey22 

Remarks as a separate column is essential. Can you add it back.

**Review by akashdubey22 — COMMENTED** [review]
@ruthra-kumar 
Remarks already exist in printing
I added remarks as a new line when check box is marked in the report. Adding separate column is creating problem in portrait print.

I am not able to remove Remarks line if remark is empty ... can you add this condition ?

Without Check box -  Show Remarks
image



With Check box -  Show Remarks
image

**Comment by akashdubey22** [comment]
> @akashdubey22
> 
> Remarks as a separate column is essential. Can you add it back.

I added remarks as a new line when check box is marked in the report. Adding separate column is creating problem in portrait print.

**Comment by ruthra-kumar** [comment]
@akashdubey22 

> Remarks already exist in printing

Yes. I'm aware.

What I meant was, the remarks should always be in separate column of its own. Not as a separate line on the 'Particulars' column

**Comment by akashdubey22** [comment]
@ruthra-kumar 


> 
> Yes. I'm aware.
> 
> What I meant was, the remarks should always be in separate column of its own. Not as a separate line on the 'Particulars' column

Added Remarks as a separate column and made space adjustments to manage width of page.

image


The only problem is left that while generating PDF, there is no top margin in new page & some style parameters that are getting ignored in PDF

image

**Review by akashdubey22 — COMMENTED** [review]
Tested both paper orientations of A4 sizes, with and without Remarks. Working fine.

**Comment by ruthra-kumar** [comment]
@akashdubey22 

Does the margin issue in PDF persists?

**Comment by ruthra-kumar** [comment]
@akashdubey22 Don't change the PR title

**Comment by akashdubey22** [comment]
@ruthra-kumar 

> 
> Does the margin issue in PDF persists?

Yes, top margin on PDF was always a problem even in old format. Maybe PDF is not following <style> mentioned in this html file.

**Comment by ruthra-kumar** [comment]
@akashdubey22 

388206125-be1b307d-31a9-4562-8f27-8c40ea4303c9
This double width column for 'Opening' is out-of-place. Also the remarks column is included only when enabled on report filter. Maybe better to include it always and move the 'Opening' and 'Closing' texts to the remarks column? Just like the old format

**Comment by akashdubey22** [comment]
@ruthra-kumar 
> 
>  This double width column for 'Opening' is out-of-place. Also the remarks column is included only when enabled on report filter. Maybe better to include it always and move the 'Opening' and 'Closing' texts to the remarks column? Just like the old format

1. Opening is having colspan=2 as there is no data in Remarks. Just an over designing idea by me ! (Can be taken back if you insist)

2. Remarks is hidden for compact printing as most of the time Remarks will be empty. So, additional width is given to PARTICULARS to reduce chance of going it into next line. This saves a lot of page length. I am user of ERPNext since 2018 and have lot of live data in my accounts which deserves saving page length in compact printing mode. And user have functionality of enabling REMARKS anytime if he needs it in display and as well as on print.

**Comment by ruthra-kumar** [comment]
> Opening is having colspan=2 as there is no data in Remarks. Just an over designing idea by me ! (Can be taken back if you insist)

This breaks consistency. Let's go back.

Once this is done, PR should be good to go.

**Comment by akashdubey22** [comment]
@ruthra-kumar 

> > Opening is having colspan=2 as there is no data in Remarks. Just an over designing idea by me ! (Can be taken back if you insist)
> 
> This breaks consistency. Let's go back.
> 
> Once this is done, PR should be good to go.

Done !!


image

**Comment by akashdubey22** [comment]
@ruthra-kumar 

I can't see this change in new update !! Any problems ?

**Comment by akashdubey22** [comment]
@ruthra-kumar 

Not included in new update ?

**Comment by ruthra-kumar** [comment]
The 'Defer Backport' label indicates this change won't be backported and will only be available in upcoming major versions.

**Comment by barredterra** [comment]
Looks like you forgot to make this translatable

**Pull request merged**
