### PR TITLE
Simple Stock Balance Report

### PR DESCRIPTION
**Pull request by cgpurbaugh**
Created a simple stock balance report by copying and modifying the default stock balance report.

### CODE REVIEW

**Comment by fderyckel** [comment]
Any chance we could do the same for stock ledger?
Thanks

**Comment by fderyckel** [comment]
Any chance we could do the same for stock ledger?
Thanks

**Comment by cgpurbaugh** [comment]
@fderyckel If this works, then it should be fairly easy.  But that's if it works.  I'm like a monkey with a typewriter right now.

**Comment by rmehta** [comment]
Will be done by @saurabh6790

**Comment by cgpurbaugh** [comment]
Thanks @rmehta & @saurabh6790 !

**Pull request closed without merging**
