### PR TITLE
fix: leave allocation records query

### PR DESCRIPTION
**Pull request by ruchamahabal**
**Problem**:

Syntax error in query due to missing field sanitization:

```Python
  SELECT
  	SUM(CASE WHEN is_carry_forward = 1 THEN leaves ELSE 0 END) as cf_leaves,
  	SUM(CASE WHEN is_carry_forward = 0 THEN leaves ELSE 0 END) as new_leaves,
  	MIN(from_date) as from_date,
  	MAX(to_date) as to_date,
  	leave_type
  FROM `tabLeave Ledger Entry`
  WHERE
  	from_date <= %(date)s
  	AND to_date >= %(date)s
  	AND docstatus=1
  	AND transaction_type="Leave Allocation"
  	AND employee=%(employee)s
  	AND is_expired=0
  	AND is_lwp=0
  	and leave_type='Special Leave - Husband's Death'
  GROUP BY employee, leave_type
	
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 68, in application
    response = frappe.api.handle()
  File "apps/frappe/frappe/api.py", line 55, in handle
    return frappe.handler.handle()
  File "apps/frappe/frappe/handler.py", line 31, in handle
    data = execute_cmd(cmd)
  File "apps/frappe/frappe/handler.py", line 68, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "apps/frappe/frappe/__init__.py", line 1214, in call
    return fn(*args, **newargs)
  File "apps/frappe/frappe/__init__.py", line 630, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 244, in run
    result = generate_report_result(report, filters, user, custom_columns)
  File "apps/frappe/frappe/__init__.py", line 630, in wrapper_fn
    retval = fn(*args, **get_newargs(fn, kwargs))
  File "apps/frappe/frappe/desk/query_report.py", line 86, in generate_report_result
    res = get_report_result(report, filters) or []
  File "apps/frappe/frappe/desk/query_report.py", line 70, in get_report_result
    res = report.execute_script_report(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 133, in execute_script_report
    res = self.execute_module(filters)
  File "apps/frappe/frappe/core/doctype/report/report.py", line 150, in execute_module
    return frappe.get_attr(method_name)(frappe._dict(filters))
  File "apps/erpnext/erpnext/hr/report/employee_leave_balance/employee_leave_balance.py", line 22, in execute
    data = get_data(filters)
  File "apps/erpnext/erpnext/hr/report/employee_leave_balance/employee_leave_balance.py", line 114, in get_data
    opening = get_leave_balance_on(employee.name, leave_type, add_days(filters.from_date, -1)) #allocation boundary condition
  File "apps/erpnext/erpnext/hr/doctype/leave_application/leave_application.py", line 559, in get_leave_balance_on
    allocation_records = get_leave_allocation_records(employee, date, leave_type)
  File "apps/erpnext/erpnext/hr/doctype/leave_application/leave_application.py", line 591, in get_leave_allocation_records
    """.format(conditions), dict(date=date, employee=employee), as_dict=1) #nosec
  File "apps/frappe/frappe/database/database.py", line 146, in sql
    self._cursor.execute(query, values)
  File "env/lib/python3.6/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "env/lib/python3.6/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "env/lib/python3.6/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "env/lib/python3.6/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "env/lib/python3.6/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "env/lib/python3.6/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "env/lib/python3.6/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "env/lib/python3.6/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1064, "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 's Death'\n\t\tGROUP BY employee, leave_type' at line 16")
```

**Fix**:
Rewrite raw query with `frappe.qb` since it handles field sanitization

### CODE REVIEW

**Comment by ruchamahabal** [comment]
Unrelated test case failure

**Comment by ruchamahabal** [comment]
@Mergifyio backport version-13-hotfix

**Comment by barredterra** [comment]
@ruchamahabal why didn't this PR need a review? Why didn't the method need a test?

**Comment by ruchamahabal** [comment]
@barredterra The query is just rewritten with the query builder and nothing new is introduced/fixed. Also, there is some coverage for this query in getting leave details and balance at many places.

Is something breaking due to this?

**Comment by barredterra** [comment]
Just trying to understand why this PR wasn't subject to normal review and testing procedure. How do you know that you wrote perfect code that works exactly like or strictly better than before?

**Comment by ruchamahabal** [comment]
@barredterra 

> How do you know that you wrote perfect code that works exactly like or strictly better than before?

Fair enough. But as I mentioned earlier since this query had decent coverage, I had manually tested this to make sure it works, and I had also added more test cases in https://github.com/frappe/erpnext/pull/29439 for getting leave details and balance (which internally use this method), I did not add an explicit test here. Nonetheless, I am adding a test explicitly for this via https://github.com/frappe/erpnext/pull/30342

> Just trying to understand why this PR wasn't subject to normal review and testing procedure

Code owners are allowed to self-merge their PRs. You can check the PR history to verify this. And since I am a code owner for HR, I guess I have earned the credibility to do so 😅

**Comment by barredterra** [comment]
Fair enough, although i'm not a big fan of "code owners are allowed to self-merge their PRs".

Looks like even tests and reviews are not enough to keep bugs out, as our discussion in https://github.com/frappe/erpnext/pull/30342#issuecomment-1074101391 shows 😅.

**Comment by ruchamahabal** [comment]
> Fair enough, although i'm not a big fan of "code owners are allowed to self-merge their PRs".

I understand your concern. Devs can have blind spots when it comes to their own code and reviews can catch some mistakes, if not all.

Reviews would be possible for every PR when there are enough maintainers per module since for reviewing the ERPNext codebase you need at least some functional knowledge. But we (code owners) do ask for peer reviews internally when we are pushing out features/small fixes having high impact. We also get such PRs tested from QA before release. Ensuring good coverage and PR descriptions/code documentation are also key practices that code owners need to follow. I won't say we are 100% there yet, but this is improving for sure.

**Pull request merged**
