### PR TITLE
Exploded view for BOM Stock Report

### PR DESCRIPTION
**Pull request by gaurav-naik**
Made changes requested in PR #12475 . Was unable to re-open it, so created a new one.

Used `tabBOM Explosion Item` and `stock_qty` if the "Show exploded view" checkbox is clicked.

Issue for reference: https://github.com/frappe/erpnext/issues/12148

### CODE REVIEW

**Comment by djpalshikar** [comment]
@nabinhait when can I expect this to be released ?

**Comment by nabinhait** [comment]
@djpalshikar Sorry for the delay in merging develop branch to master. Expecting to release it at the end of this month.

**Comment by djpalshikar** [comment]
@nabinhait will it make it to this next release ?

**Comment by nabinhait** [comment]
@djpalshikar v11 release needs some more time. I will cherry-pick this feature to hotfix branch and release it on priority. You can expect it to be released next week.

**Pull request merged**
