### PR TITLE
fix: Allow creating Item as is_fixed_asset in Quick Entry.

### LINKED ISSUE #37505: Item may not be marked a Fixed Asset after saving
You create an item via Quick Entry form without being asked if it is supposed to be a Fixed Asset. When you go on to the full edit form, it’s too late and you can‘t check the box anymore as it‘s disabled as soon as it’s saved:

IMG_1832

This is a bit of an anti-pattern: a non-submittable Doctype that behaves like one and doesn‘t even allow editing in the form of amending.

Workarounds are of course: go straight to the full edit form, or duplicate your item and later delete the original one.

But in the end, the proper solution is that editing it should be possible. Of course this isn‘t easy to do…

For now we should at least add „Is Fixed Asset“ to the Quick Edit form.

### PR DESCRIPTION
**Pull request by bosue**
`is_fixed_asset` currently wasn‘t included in the Quick Entry form.
As the field is `set_only_once` and the doc is being saved, there‘s no way to check the box later.
Effectively, it currently isn‘t possible to create a fixed asset via the Quick Entry form.

Fixing this was slightly less straightforward than expected, but in the second revision could be sufficiently solved:

1. Obviously `is_fixed_asset` had to be added to Quick Entry. 
2. However, Asset Category is mandatory for Fixed Assets, so needs to be added too if we don‘t want to leave the Item in an incorrect state.
3. Now, `is_fixed_asset` and `is_stock_item` are mutually exclusive. An informed decision in the Quick Entry form is only possible if we‘re adding the latter as well, so people can easily grasp the mutual exclusivity and choose one or the other.
4. If need be, `is_stock_item` may stay _on_ by default, so `is_fixed_asset` is initially disabled. To enable `is_fixed_asset`, you first need to disable `is_stock_item`. That’s halfway acceptable. However, `is_stock_item` should not bounce back when disabling`is_fixed_asset` again.
5. Regarding the full form: showing/enabling and hiding/disabling quite distant, mutually exclusive checkboxes is rather confusing. I‘m therefore moving `is_fixed_asset` together with its dependent fields to the top, so it is closer to `is_stock_item`. With the two mutually exclusive fields next to each other from the start, the mutual exclusivity is way easier to grasp.

https://github.com/frappe/erpnext/assets/46800703/2d99140c-4e88-4464-8417-0a49ac803081

All in all, I think this revised approach is a clear UX improvement and a good compromise, particularly if the tests are passing, so BC is given. In a followup we may discuss whether `is_stock_item` should be _on_ by default or not.

It also fixes #37505.

### CODE REVIEW

**Comment by bosue** [comment]
Quite many unittest fails, mostly or all because of `is_stock_item` no longer defaulting to 1 for non-fixed asset items.

Tests can be adapted, but still this IMO means the solution may not be backported to v15, unless a) v15 is not considered stable yet, or a) the breaking change is absolutely unavoidable

And the change is not outright unavoidable. Instead of changing the default, we can also forward users from the Quick Entry form to the regular form whenever `is_fixed_asset` is checked. The rest is some suboptimal UX which may be better than a breaking change.

**Comment by bosue** [comment]
Failing test case (Asset with CWIP accounting) may seem related but isn‘t.
Finally we‘re only changing JS directly and JS via JSON.

Furthermore, that very same test case has been failing on every other test run as well.
Needs to be fixed, but not here.

Ready for review.

**Comment by s-aga-r** [comment]
@bosue 

>> As the field is `set_only_once` and the doc is being saved, there‘s no way to check the box later.

Let's remove the `set_only_once` property and use a similar validation we use for Maintain Stock. Users can check and uncheck the `is_fixed_asset` until any transaction is made against that item.

>> `is_fixed_asset` currently wasn‘t included in the Quick Entry form.

Quick Entry Form should have fewer fields. Although, the user can add the same if needed(?)

**Comment by bosue** [comment]
> Let's remove the set_only_once property and use a similar validation we use for Maintain Stock. Users can check and uncheck the is_fixed_asset until any transaction is made against that item.

> Quick Entry Form should have fewer fields. Although, the user can add the same if needed(?)

I can see that Quick Entry forms should be compact. However, while I‘m not against removing `set_only_once`, even without that restriction I believe `is_fixet_asset` is such a fundamental decision to take that I think it needs to be highlighted.

One could say we‘re actually reusing Items for something quite different to the point that Fixed Asset Items might even better be their own doctype, right? In that case deferring that decision to a later point creates new UX problems, IMHO.

But if we‘re not just trying to fix the creation logic but rethinking the whole thing, let‘s see it from another side:
Items are more or less specific “types” of real-world objects (or in some cases services), right? Services aside, but why shouldn‘t it be possible to create both variable tradable (tradable) goods _and_ fixed assets from an Item? 

I‘m asking this because they may actually be. Some company buys ten desks or computers: one for their new employee, and the other nine for sale. Actually one and the other may even change over time. A car seller may sell their demo car after a while to replace it with a new one. Or a company may turn the MFC copier they couldn‘t sell into a fixed asset, using it themselves.

How about allowing Items to represent current assets (tradables / raw material / consumables), while also allowing to create fixed assets from them?

Three possible implementations:
Instead of the misnomer `is_fixed_asset` (misnomer because the Item itself isn‘t a concrete thing, so won‘t ever be an Asset itself), we may have a switch `allow_asset_creation` or `may_create_assets`.
Or none at all, so every instance of an Item may be used to create a (fixed) Asset.
<details>
  <summary>
Or, optionally, for added control:
  </summary>

we might add a set of checkboxes:

> May represent:
> - [x] tradable
> - [x] raw material
> - [x] consumable
> - [x] asset
(all checked by default, but may be unchecked)
</details>
Sorry for the long elaboration. Did I miss something? I‘m inviting @anandbaburajan as Asset maintainer into the discussion.

**Comment by bosue** [comment]
Thought about it again.

More concretely I‘m proposing:
- **Allow an Item to be both a stock item _and_ blueprint for an `Asset` instead of just one or the other.**
- **Rename `is_fixed_asset` to `may_create_assets` (“May create fixed Assets”) and keep it (unchecked) on the Quick Entry form.**
- Only auto-creation of Assets really needs an Asset Category set, I guess. So we should be able to leave this one out of the Quick Edit form, once the logic is adapted? Otherwise add it, but show only if `may_create_assets` is checked.
- **If previously enabled, allow `may_create_assets` to be disabled later until an actual `Asset` has been created from the item.**
- **Allow `may_create_assets` to be enabled at any time.**
- If preferred, remove `is_stock_item` (“Maintain stock”) again from the Quick Entry form.
- If previously enabled, allow `is_stock_item` to be disabled later unless the Item’s stock isn’t empty.
- Allow `is_stock_item` to be enabled at any time.

In the end, this isn’t even very different from what @s-aga-r proposed.

I can make an alternative PR but will need your feedback before starting to do so. Only if there’s not been any feedback for a while, I would go ahead and see how this may work best.

**Comment by bosue** [comment]
I‘m just wondering whether my last proposal may actually be perfectly compatible with @s-aga-r‘s proposal, while being quite a bit out of scope of the actual bugfix.

I‘ll start implementing the former, and may then launch a followup issue. 👍

**Comment by bosue** [comment]
Bump.

**Comment by bosue** [comment]
Unstale

**Pull request closed without merging**
