### PR TITLE
Updates for German manual

### PR DESCRIPTION
**Pull request by MartinEnder**
Hi, 

did some updates of the translation and inserted "contributed by" at the end of each text including CWT-Logo.

Live long and prosper :-)

Martin

### CODE REVIEW

**Comment by rmehta** [comment]
@MartinEnder we don't think logos is a good idea as it might discourage other contributors!

**Comment by MartinEnder** [comment]
Ok, no problem. I will delete this.

**Comment by MartinEnder** [comment]
Here is the latest update. Deleted the logo and the contribution. Did some minor changes in translating.

**Comment by anandpdoshi** [comment]
@MartinEnder please check the existing documentation

1. The headings should be `h1` and without chapter number i.e. use `# Kunde` instead of `## 5.2 Kunde`
1. Also, add this line below the heading: `<span class="text-muted contributed-by">Beigetragen von CWT Connector & Wire Technology GmbH</span>`

**Comment by anandpdoshi** [comment]
@MartinEnder what software are you using to edit the documentation?

**Comment by MartinEnder** [comment]
Hi Anand,

I will adjust the headings and insert the line. Working on it.
I am working directly through github on the texts. Using github's predefined editor,

Martin

**Comment by rmehta** [comment]
Learning git can be intimidating, but its not too hard. Check this out https://try.github.io/

Direct editing on GitHub only works for small changes.

**Comment by MartinEnder** [comment]
Thank you ☺

Von: Rushabh Mehta [mailto:notifications@github.com]
Gesendet: Montag, 21. Dezember 2015 12:08
An: frappe/erpnext <erpnext@noreply.github.com>
Cc: Ender, Martin <Martin.Ender@cwt-kabel.de>
Betreff: Re: [erpnext] Updates for German manual (#4514)

Learning git can be intimidating, but its not too hard. Check this out https://try.github.io/

Direct editing on GitHub only works for small changes.

**Comment by MartinEnder** [comment]
Would that be okay if we insert

Übersetzt von CWT Connector & Wire Technology GmbH  (that means translated by ...)

instead of 
Beigetragen von ...

?

**Comment by anandpdoshi** [comment]
@MartinEnder yes :+1: 

But also change it else where. I suggest that you learn how to use git and use a nice text editor like atom/textmate to make your changes as it will give your powerful features like multi-file search and replace.

**Comment by anandpdoshi** [comment]
Try Git: https://try.github.io/levels/1/challenges/1

**Comment by MartinEnder** [comment]
Yes, I will do that as soon as possible :-)

**Comment by MartinEnder** [comment]
Changes in Headings and some minor translation changes.

**Comment by MartinEnder** [comment]
Latest changes and error corrections from today.

**Comment by rmehta** [comment]
@MartinEnder This is too much effort for us to merge and commit. We cannot do this again. Please learn git send one commit in your next PR. Thanks!

CC @CWTGMBH

**Comment by anandpdoshi** [comment]
@MartinEnder I am unable to merge this because this branch is too diverged from `develop`. You need to learn git, make these changes in local and push it in as few commits as possible for us to merge this.

**Pull request closed without merging**
