### PR TITLE
feat!: advance payment status on advance payment doctypes

### PR DESCRIPTION
**Pull request by blaggacao**
###### It splits the `advance_payment_doctypes` hook into two `advance_payment_{customer,supplier}_doctypes`.

----

It was #37449 (which went stale). More infos there, as well as [here on discourse](https://discuss.frappe.io/t/help-cash-driven-businesses-better-understand-paid-vs-invoiced/116105/2)

`no-docs`

### CODE REVIEW

**Comment by blaggacao** [comment]
@deepeshgarg007 @rohitwaghchaure @s-aga-r @ruthra-kumar , this feature is still a critical one for cash-oriented commerce operations. It implements the decisive distinction between "invoiced" and "paid" and without this feature our operation would likely collapse. Please let's work together towards getting this merge-ready, thus please share your feedback with me, I'll be happy to correspond quickly and iterate with you, as needed. It's important for me, to share this fundamental business flow improvements with you and the rest of the community as it will have a real impact on the bottom line of real businesses who use ERPNext.

**Comment by ruthra-kumar** [comment]
@blaggacao 

Can you provide a simple scenario? were the existing advance based workflows insufficient / inefficient?

**Comment by blaggacao** [comment]
@ruthra-kumar Thanks a lot for your interest and attention! Here's a precise user journey written down by our power user and continous system improvement representative: https://discuss.frappe.io/t/help-cash-driven-businesses-better-understand-paid-vs-invoiced/116105/2

**Comment by ruthra-kumar** [comment]
@blaggacao Thanks for the contribution.

This does look like a good addition to the existing Sales/Purchase Order and Advance Payment workflow. Will review this later today.

**Comment by ruthra-kumar** [comment]
@blaggacao 

1. Create a Sales Order(Not Requested)
2. Create Payment Request for Sales Order(Requested)
3. Create Partial Payment against Sales Order (Partial Payment)

`advance_payment_status` is correctly updated.

1. Now cancel the Partial Payment. Status stays the same -- Partial Payment.
6. Cancel the Payment Request. Status still stays the same.
7. Cancel the Sales Order and amend it. `Partial Payment` is still incorrectly copied to the amended Sales Order.

**Comment by blaggacao** [comment]
@ruthra-kumar In order to apply the fix in https://github.com/frappe/erpnext/pull/38560/commits/b1aef01a1ff76fcdcf226a76bb64eb2a9b5b6e01 (all status transitions are ok, now &mdash; but please check critically :pray:), I needed to refactor in https://github.com/frappe/erpnext/pull/38560/commits/c88ce552425f077f59e98458799819ff3dd72742 the advance doctypes to get a semantic handle on the "direction" of such doctypes (associated with business input or business output), because the money flow depends on that as well as the disambiguating status nomenclature of "bidirectional" payments ("initiated" vs "requested"). Finally I noticed that the `Prartially/Fully X` nomenclature on so & po had recently been disambiguated, as well, so I aligned in https://github.com/frappe/erpnext/pull/38560/commits/7d8aa469d78560fb5f11f7370db74c517d0d0c00.

**Comment by ruthra-kumar** [comment]
Changes to Plaid(https://github.com/frappe/erpnext/pull/38560/commits/87948d6ef25449b488788d06ad2875ae5c7c8662) appears to be unrelated to this PR. Why include them here?

**Comment by blaggacao** [comment]
oh damn, one sec. I have a different local dev env which fails otherwise.

That was definitely not on purpose, thanks for the catch! I'm going to be more cautious next time! I noticed, but then forgot about it. I force pushed a clean history, below:

**Comment by ruthra-kumar** [comment]
Added a test case for Sales and Purchase Orders to test the status change on basic workflow -- SO/PO -> Payment Request -> Payment Entry.

**Review by ruthra-kumar — APPROVED** [review]

**Comment by blaggacao** [comment]
Thanks for the hands on teaching in: https://github.com/frappe/erpnext/pull/38560/commits/9b4e757b0b0608a90c90d8d77916bd7ba4389095

It's easier than I thought :smile: &mdash; will take a bite.

**Comment by ruthra-kumar** [comment]
https://github.com/frappe/erpnext/pull/39535 should be backported too, when done.

**Comment by ruthra-kumar** [comment]
@mergify backport version-15-hotfix

**Comment by ruthra-kumar** [comment]
@mergify copy version-15-hotfix

**Pull request merged**
