### PR TITLE
feat: Student Group with Student Category filter

### PR DESCRIPTION
**Pull request by mujeerhashmi**
The Student Category field is added to the Student Group doctype.The
students are fetched from Program Enrollment with added Student Category.
This helps in creating student group based on Program,Batch and Student
Category.Which helps in creating fee schedule with fee structures
defined based on student category.

Signed-off-by: Syed Mujeer Hashmi <mujeerhashmi@4csolutions.in>

### CODE REVIEW

**Comment by scmmishra** [comment]
Can you please add working screenshots/gif of your code in works

**Comment by mujeerhashmi** [comment]
@scmmishra Here it is.

StudentGroup_StudentCategory

**Comment by mujeerhashmi** [comment]
Signed off the commit with my company email address.

**Comment by mujeerhashmi** [comment]
@scmmishra Any updates on this.

**Review by nabinhait — APPROVED** [review]

**Pull request merged**
