### PR TITLE
feat: better Item Price list view

### PR DESCRIPTION
**Pull request by FHenry**
Users don't need technical ID of Item Price in list, but they need,by default, the Price List of the Item Price

Before
image

After

image

`no-doc`

### CODE REVIEW

**Comment by deepeshgarg007** [comment]
@FHenry Can you please add a screenshot of how does it look post the change

**Comment by FHenry** [comment]
> @FHenry Can you please add a screenshot of how does it look post the change

@deepeshgarg007 Hi, sure, it's done. You'r right it's better to show difference in screenshots, I'll do that in next PR about changing default list settings. I'm not sure that ID list filter is needed, what do you think ?

**Comment by FHenry** [comment]
@deepeshgarg007 I added the reference column by default as it's supplier or customer of item price, it can be very useful as well. 
I also check that ID standard filter is not removable (cannot find how..., sorry) , we have to let it here, even if it's not usefull for users

**Review by deepeshgarg007 — APPROVED** [review]

**Comment by FHenry** [comment]
@Mergifyio backport version-13-hotfix

**Comment by FHenry** [comment]
@Mergifyio backport version-14-hotfix

**Pull request merged**
