### PR TITLE
feat: Tracking Multi-round interview

### PR DESCRIPTION
**Pull request by Anurag810**
### Interview Type

- You can define Interview types such as panel interviews, walking interviews, etc.

   image

### Interview Round

- Interview Round contains the Expected Average Rating, Skillset, etc.
- You can define designation to filter Job Applicants during Interview creation. Use case: Like Technical Round is only for software Engineers.   
- You can predefine some interviewers associated with that Interview Round which will be fetched during Interview creation.

   image

### Interview

- From here you can submit feedback, reschedule Interviews.

   erpnext_dev_8001_app_interview_HR-INT-2021-0011

- Color-coded calendar view for Interviews

   image

### Interview Feedback

- Feedback given by the interviewer helps to rate their skillset.
   
   image

## Job Applicant Dashboard

- To track job applicant interviews, you don't need to scroll here and there

   image

## HR Settings

image

## Workflow

- Create Interview Type and Interview Round
- Create a Job Applicant.
- Create an Interview.
     - You can create an Interview directly from the job applicant.

        Screenshot 2021-04-27 at 12 38 20 PM
     - You can also create an Interview from Interview Round
        
        Screenshot 2021-04-27 at 1 44 26 PM

   - Or directly by filling the Interview form
- You can reschedule it by clicking on **Reschedule Interview**.
   
    image

- Now you need to submit Interview Feedback.
    - You can submit Interview Feedback directly from the Interview Document by clicking on **Submit Feedback** 
    - It will open modal (Refer to the screenshot). Fill in the details and hit submit button.
    - Note:  interviewers associated can only submit their interviews.

    submit-feedback

- Now,  you can view average ratings of interviews which will be calculated based on multiple Interview feedback submitted by the Interviewer at job applicant in the Interview analysis dashboard.

image

- based on that you can change the status of a job applicant to **Rejected** or **Accepted**

## Validations

- Job Applicants are not allowed to appear twice for the same Interview round.
- The only **Interviewer** associated with the **Interview** will able to submit an **Interview Feedback** for that interview.
- You will not be able to submit Interview feedback before the Scheduled date.
- Overlap validation for interviews
- Interviewer cannot submit other interviewer's feedback.
- Interviewers are not allowed to submit Interview Feedback twice.

## Notifications

- Notification on Interview rescheduling.
- Before the Scheduled time of the interview(as defined in HR Settings).
- Notification for feedback submission
    - It will trigger when the status of the interview changes from **Pending** to **Under Review**. 
    - Daily Notification for feedback submission until and unless the interviewer has not submitted their interview.

- [x] Test cases.
- [ ] Documentation `no-docs` (temp)

### CODE REVIEW

**Comment by Anurag810** [comment]
Also added two more validation for designation(In Interview) and skillset(In Interview Feedbcak)

Fixed or Written all test cases. Travis is unaffected by this pr.
image

@ruchamahabal start review. Mean while, I will add docs.

**Comment by Anurag810** [comment]
@ruchamahabal need to change a little bit in the design part I will take this in a month And also need to Set it through notification

**Comment by ruchamahabal** [comment]
Reopen after changes are completed

**Comment by Anurag810** [comment]
@ruchamahabal as talked to Nabin it will be changed after merging this in the second iteration. You can reopen and review this.

**Comment by ruchamahabal** [comment]
Keep alive

**Review by ruchamahabal — APPROVED** [review]

**Comment by ruchamahabal** [comment]
@mergifyio backport version-13-hotfix version-13-pre-release

**Comment by ruchamahabal** [comment]
@mergifyio backport develop version-13-pre-release

**Comment by ruchamahabal** [comment]
@Mergifyio backport version-13-pre-release

**Comment by ankush** [comment]
pre-release? @ruchamahabal 

we dont use the branch

**Comment by ruchamahabal** [comment]
> pre-release? @ruchamahabal

I had back ported this 2 years ago. Didn't trigger anything today 💀

**Pull request merged**
