### PR TITLE
Added Quote Status to RFQ Suppliers with No Quote

### PR DESCRIPTION
**Pull request by bcornwellmott**
Rebasing https://github.com/frappe/erpnext/pull/10143

### CODE REVIEW

**Comment by mbauskar** [comment]
@bcornwellmott ,

Thanks for contributing,

Please check and fix the Travis issues, closing the PR for now but you can reopen it

**Comment by bcornwellmott** [comment]
The failure has to do with test_sales_order, which hasn't been touched in this PR.

**Review by mbauskar — CHANGES_REQUESTED** [review]
@bcornwellmott,

Tests cases are missing, can you also add the both (python and js) tests cases?

**Comment by bcornwellmott** [comment]
Test failed is leave application... nothing to do with this code. Going to retry.

**Comment by tundebabzy** [comment]
@bcornwellmott
Try merging your branch with changes from its base branch

**Comment by nabinhait** [comment]
@bcornwellmott I don't understand why "no_quote" checkbox is required as a separate field. The status field already has an option "No Quote".

**Pull request closed without merging**
