### PR TITLE
Trial Balance sorted

### PR DESCRIPTION
**Pull request by Helkyd**
With this fix accounts are sorted.

### CODE REVIEW

**Review by tundebabzy — CHANGES_REQUESTED** [review]
Is the title correct? I don't see any part of your code that has anything to do with sorting trial balance

**Review by tundebabzy — CHANGES_REQUESTED** [review]
Also add screenshots/animated gif such as to make review easier after putting a more descriptive title.

Also fix conflicts

**Comment by Helkyd** [comment]
@tundebabzy for some reason added to commits .... and by my local user instead of my Gmail 
erpnext_trial_balance_sort

**Comment by tundebabzy** [comment]
@Helkyd 
Let's have a new PR for this. This one is quite messy

**Pull request closed without merging**
