### PR TITLE
fix: use supplied year for IRS 1099 forms

### PR DESCRIPTION
**Pull request by Alchez**
Backport of #24414.

### CODE REVIEW

**Review by deepeshgarg007 — DISMISSED** [review]

**Comment by deepeshgarg007** [comment]
@Alchez Travis seems to be failing for python 2.7. Can you fix that?

**Comment by Alchez** [comment]
> @Alchez Travis seems to be failing for python 2.7. Can you fix that?

Oh, that's from the f-strings in Python 3.6+

I thought Frappe had dropped Python 2 support, is that not the case anymore?

@deepeshgarg007

**Comment by AfshanKhan** [comment]
> > @Alchez Travis seems to be failing for python 2.7. Can you fix that?
> 
> Oh, that's from the f-strings in Python 3.6+
> 
> I thought Frappe had dropped Python 2 support, is that not the case anymore?
> 
> @deepeshgarg007

@Alchez No, Frappe still supports Python 2 for version 12. It would be great if you can please make the appropriate changes and push them on priority. Thanks

**Comment by Alchez** [comment]
@deepeshgarg007 @AfshanKhan I've changed the format method, should pass for 2.7 now

**Review by AfshanKhan — APPROVED** [review]

**Pull request merged**
