### PR TITLE
feat(buying): quotation number in supplier quotation

### PR DESCRIPTION
**Pull request by hrwX**
- Add `Quotation Number` in Supplier Quotation similar to `Order Confirmation Number` in Purchase Order.

Docs: https://docs.erpnext.com/docs/v13/user/manual/en/buying/supplier-quotation#32-more

### CODE REVIEW

**Comment by barredterra** [comment]
@mergifyio backport version-13-hotfix

**Comment by barredterra** [comment]
@hrwx please mention the new fields in https://docs.erpnext.com/docs/v13/user/manual/en/buying/supplier-quotation

**Comment by hrwX** [comment]
> @hrwX please mention the new fields in https://docs.erpnext.com/docs/v13/user/manual/en/buying/supplier-quotation

Updated https://docs.erpnext.com/docs/v13/user/manual/en/buying/supplier-quotation#32-more

**Review by barredterra — DISMISSED** [review]

**Review by sagarvora — APPROVED** [review]

**Review by sagarvora — CHANGES_REQUESTED** [review]
@barredterra @hrwX 

I actually have a late request: as per convention, perhaps the number field should come before the date. Also worth noting that similar fields in Purchase Invoice and Sales Invoice have their own section with a column break between Number and Date.

**Comment by barredterra** [comment]
Thanks, @sagarvora. @hrwX please change accordingly.

**Comment by hrwX** [comment]
@sagarvora @barredterra Updated the fields order.

**Comment by barredterra** [comment]
@hrwX what are your thoughts about the separate section?

**Comment by hrwX** [comment]
> @hrwX what are your thoughts about the separate section?

- Even if we see in Purchase Order, Order Confirmation and Date do not have their own sections, either we add a new section for both or we keep the fields in the first section of the form itself where its clearly visible.

**Review by barredterra — DISMISSED** [review]

**Comment by sagarvora** [comment]
I think people will get confused between `transaction_date` and `quotation_date`. Any reason why these should differ at all?

**Comment by sagarvora** [comment]
@hrwX Can you please update the docs accordingly?

**Review by sagarvora — APPROVED** [review]

**Comment by barredterra** [comment]
I updated the docs

**Pull request merged**
