### PR TITLE
feat: Extended Item Description for Variant

### PR DESCRIPTION
**Pull request by bhavishyasharma**
Item Code can get very complicated for items with multiple item attributes. Using item description to show attribute names and values to increase readability and ease understanding.

Fields Added: Item Variant Setting (use_extended_description, stript_item_name)

Screenshot 2023-02-15 at 7 43 48 PM

Screenshot 2023-02-15 at 7 43 42 PM

### CODE REVIEW

**Comment by s-aga-r** [comment]
@bhavishyasharma Please fix the test cases.

**Review by s-aga-r — CHANGES_REQUESTED** [review]
@bhavishyasharma Please fix the test cases.

**Comment by bhavishyasharma** [comment]
@s-aga-r Two of the test cases are failing with "Exchange Rate is mandatory. Maybe Currency Exchange record is not created for INR to USD." I am not sure how changes I made are effecting accounts module. These test cases are failing in other PRs as well. Proposed changes only work on Item creation.

**Comment by bhavishyasharma** [comment]
Reopen

**Comment by bhavishyasharma** [comment]
@s-aga-r Updated the branch with latest develop. Please reopen.

**Pull request closed without merging**
