### PR TITLE
refactor(UI): clean up portal pages

### PR DESCRIPTION
**Pull request by sumaiya2908**
***Needs to be merged after [this](https://github.com/frappe/frappe/pull/15436)***

- List View

**Before**
Screenshot 2021-12-24 at 12 09 18 PM

**After**
Screenshot 2021-12-24 at 12 08 11 PM

- Preview

**Before**

Screenshot 2022-01-03 at 12 02 08 PM

**After**

Screenshot 2022-01-03 at 11 41 33 AM

**Mobile View**

Screenshot 2022-01-03 at 11 41 43 AM

***Pages Affected***
- sales/purchase order preview
- Quotations
- Sales/Purchase invoice

### CODE REVIEW

**Comment by marination** [comment]
@sumaiya2908 
#### The empty states feel too empty. Perhaps a white card with the illustration in the center would be better ?
  Screenshot 2022-01-12 at 12 27 34 PM

#### The sidebar items disappear when i go to any page like `/orders`.
Screenshot 2022-01-12 at 12 28 48 PM

The same in v13:
Screenshot 2022-01-12 at 12 29 59 PM

**Comment by sumaiya2908** [comment]
@marination both the issues are to be fixed in the framework. We can go ahead with this PR if everything else is fine.

**Comment by marination** [comment]
@sumaiya2908 can you address the failing linter ?

**Comment by sumaiya2908** [comment]
@marination is there any other test to address for this PR?

**Comment by deepeshgarg007** [comment]
@Mergifyio backport version-14-hotfix

**Comment by deepeshgarg007** [comment]
Fixed Payment Button Placement

Before:
image

After:
Screenshot 2022-10-03 at 10 37 05 PM

**Pull request merged**
