### PR TITLE
fix(ux): move `get_route_options_for_new_doc` to `refresh`

### PR DESCRIPTION
**Pull request by FHenry**
**Information about bug**

Create and validate a Purchase Order with a Item (with Has Batch No = Yes)
Create a Purchase Receipt, edit row of the item to input Batch No
Click on Create a New Batch No
In Quick Entry batch creation form, the Item field is empty

Before : 

https://github.com/user-attachments/assets/fd01e23d-20a9-4b85-8842-089c13827196

After : 

https://github.com/user-attachments/assets/07415070-f359-4b9e-bbdd-9c4f985e5be7

The fix is inspired from similar problem already fix by #37096 but not on Purchase Receipt

### CODE REVIEW

**Comment by FHenry** [comment]
@s-aga-r Could you have a look, please.
It's the same bug you've solve on #37096 for others DocType

**Comment by s-aga-r** [comment]
@FHenry Route options are already set in the [transaction.js](https://github.com/frappe/erpnext/blame/e3cd6539c34891fae6aab3012b8c13145ccc84ec/erpnext/public/js/controllers/transaction.js#L393-L419), which used to be applied to Purchase and Sales DocTypes (with common field names). Could you re-check?

**Comment by FHenry** [comment]
@s-aga-r it work in develop and also in version-15. 
And I didn't see docfield rejected_serial_and_batch_bundle management in transaction.js, but may be it's another point

**Comment by FHenry** [comment]
fix by https://github.com/frappe/erpnext/pull/44028 2 days ago.

**Pull request closed without merging**
