### PR TITLE
feat: show available qty in secondary UOM

### PR DESCRIPTION
**Pull request by rohitwaghchaure**
**Why this feature**

We have observed cases where users set the Default UOM as 'Nos' and the Purchase UOM as 'KG' for certain items. However, the appropriate default UOM should be 'KG' in this context, rather than 'Nos.' They choose 'Nos' because they wish to monitor inventory in terms of 'Nos.' Nevertheless, they can still designate 'KG' as the default UOM and opt to include 'Nos' in the Stock Balance report to view inventory in 'Nos.'

Screenshot 2023-10-03 at 11 30 53 AM

However, it's important to note that not all items will necessarily have 'Nos' as the secondary UOM. To address this issue, we have introduced a provision to define the secondary UOM for each item and added a checkbox to enable the display of 'Qty in Secondary UOM'.

**Configure Secondary UOM on Item master**
Screenshot 2023-10-03 at 11 40 48 AM

**Stock Balance Report**

Screenshot 2023-10-03 at 11 21 56 AM

### CODE REVIEW

**Comment by bosue** [comment]
There’s no question we should cater for this use case one way or the other and improve how it can be handled.

But I‘m a bit bewildered by both the additional complexity and vagueness this adds. “Secondary” doesn’t say anything specific about what it’s being used for, neither does “for reporting”. Finally, reports (are supposed to) state whatever columns are chosen in one report or other.

Probably better call it “Stock UoM”, but then again, isn’t stock the central, thus rightfully the _primary_ scope?

> We have observed cases where users set the Default UOM as 'Nos' and the Purchase UOM as 'KG' for certain items. However, the appropriate default UOM should be 'KG' in this context, rather than 'Nos.'

Why? I mean why is it wrong? If internally, they track their items by ‘Nos’, then this would rightfully be their primary UoM, IMO. And if they happen to purchase the items by ‘kg’, then this would rightfully be the Purchase UoM. Why would we want to turn it upside down?

Working in the services field, I will certainly be missing some implementation details and repercussions. Please help me understand why we might want to implement it this way around!

**Comment by rohitwaghchaure** [comment]
@bosue 

> Working in the services field, I will certainly be missing some implementation details and repercussions. Please help me understand why we might want to implement it this way around!

The customer has raised an issue on the support portal, stating that they booked the wrong stock expenses because their team internally transferred the quantity in kilograms (KG) without changing the default unit of measure (UOM) to 'Nos.' Consequently, they transferred a greater quantity than expected. During a call with them, they informed me that they are willing to use the default UOM as kilograms (KG) because it's challenging to define the conversion factor from KG to 'Nos' due to the absence of standard UOM conversions, such as KG to grams or liters to milliliters, etc. But they want to see the quantity in numbers too.

**Comment by bosue** [comment]
Thank you! 🙏 

It‘s still a bit confusing. But as you suggested before, their use case is catered for.

Question is whether we want to generally add another generic “Secondary UoM“ even though we already have a Default UoM, a Weight UoM, a Purchase UoM and a Sales UoM?

It seems like an edge case altogether, but what do I know. How about simply allowing up to two of the existing ones to be selected in reports?

Otherwise please go ahead. You guys are already busy, so I don‘t want to make your life any harder with my objections that may sometimes hit the point and in other times miss it completely.

Cheers! 🤗

**Comment by muchai** [comment]
Could this be included in Gross Profit report please. Even Include UoM would be useful on Gross Profit. Especially of option item.

**Comment by thida-bcn** [comment]
this one is not available at 
image

**Pull request closed without merging**
