### PR TITLE
Contract Manufacturing : Customer Provided Items

### PR DESCRIPTION
**Pull request by creamdory**
Detailed Information/Description : https://github.com/frappe/erpnext/milestone/82

### Item Doctype

- rename section “Purchase Details” to “Purchase and Replenishment Details”
- new checkbox “Is Customer Provided Item”. Must be validated for “Is Purchase”.
- new Link Field “Customer”, depends on “Is Customer Provided Item”. Must be then mandatory.
- Hard validation in Item to not set valuation

screen shot 2018-11-05 at 1 16 05 pm

screen shot 2018-11-05 at 1 17 49 pm

screen shot 2018-11-05 at 1 18 06 pm

### Production Plan Doctype

- Integration of `Customer Provided Item` in `Production Plan` doctype. Once "Material Request" is generated for this item, it will create a "Material Request" with type "Customer Provided".

screen shot 2018-11-05 at 1 20 39 pm

screen shot 2018-11-05 at 1 21 01 pm

### Stock Entry Doctype

- From "Material Request", user can generate "Stock Entry - Material Receipt" for `Customer Provided Item`
- In Stock Entry, it must auto check “Allow Zero Valuation Rate” and on save, it must hard validated if this is uncheck or not (since this is not read only so user can check or uncheck)

screen shot 2018-11-05 at 1 23 23 pm

- Once several `Stock Entry` are generated for a `Material Request`, it will reflect as status in `Material Request` as `Partially Ordered`.

screen shot 2018-11-05 at 1 23 54 pm

### Web Portal

It would be helpful to Customers to have a visible information for the Material Requests of the items they will provide. Hence, a web portal/view is necessary.

Validation/s:

- View must be filtered with contacts of Customers.
Columns:

Item Column:
- First line shows Item Code.
- Second Line shows Item Name/Description
- Third line shows Customer Part No or Customer Reference from Item Doctype

Work Order Column:
- Shows all the Work Order that the Item is currently required. Must show submitted Work Orders. It should not be consumed yet (means zero consumed_qty in the Work Order Item).

Quantity Column:
- First Line shows the Qty of the Material Request
- Second Line shows the Delivered (Submitted Partial Stock Entry - Material Receipt against Material Request)

screen shot 2018-11-05 at 1 28 06 pm

### CODE REVIEW

**Comment by dottenbr** [comment]
Screenshots and functional overview will follow after tomorrow's presentation.

**Comment by dottenbr** [comment]
@rohitwaghchaure alerting you to check out this new, awesome feature since you are the Manufacturing Module leader.

**Comment by vrms** [comment]
This is real usefull. A possible functional extension could be made for the case that

you purchase raw materials for a customer and store them on your premise to be used up in one ore several manufacturing processes.

For now the flow for such assumingly would be a divided in 2 parts

1. `Sales Invoice` > `payment from Customer` > `Purchase Invoice` >  `Payment to supplier` > `Material Receipt` > `Delivery` (at this point the item is gone from your system)
2. `Stock entry` as "Customer Provided Item"

now for a usecase as described above  it would be helpfull whether the `delivery` could be done directly to a `Stock Entry` as "Customer Provided Item"

**Comment by dottenbr** [comment]
@vrms let me clarify. You want to purchase item A through the normal purchasing cycle and then “deliver” and bill it to the customer and within that make it a customer provided item B. Delivery here sort of means conversion from A to B. That is a good feature.

**Comment by dottenbr** [comment]
@creamdory please provide screenshots and explain how the workflow is, otherwise this PR is not mergeable for the maintainer and must be closed.

**Comment by creamdory** [comment]
@dottenbr , done editing the description. @rohitwaghchaure please check for approval and merging. Thanks!

**Comment by rmehta** [comment]
@creamdory looks good 👍

Please add a PR for the documentation on https://github.com/erpnext/foundation for this.

**Comment by dottenbr** [comment]
@rmehta thanks for the feedback. Our thinking was that we will contribute the documentation within a week after the PR is merged so we can have the final and merged version in the documentation. We wanted to have that as a general rule for us.

**Comment by rmehta** [comment]
@dottenbr you can update the screenshots from a branch! Merge is not required for it. Once I merge it there is no way to track if docs are updated. I think it would be an easy fix to update the docs since you already have screenshots.

**Comment by dottenbr** [comment]
@creamdory please create the documentation and reference it here in the PR so we can get this merged.

**Comment by creamdory** [comment]
@rmehta @dottenbr made the documentation in `Foundation` repo.

**Comment by creamdory** [comment]
@rmehta , can this be merged? Let me know if there are other changes needed. Thanks!

**Comment by dottenbr** [comment]
Thank you @nabinhait and @rmehta for merging this and for your help along the process. I hope this is useful to people. 

@creamdory please announce this feature on discuss so the people who might need it know it’s there now.

**Pull request merged**
