### PR TITLE
[Feature Request] Multiple due dates in the same invoice (#6301)

### PR DESCRIPTION
**Pull request by tundebabzy**
- [ ] Rename to "Payment Term"
- [ ] Add Docs

Here is the first PR toward implementing Multiple due dates/Payment terms in ERPNext. Please check #6301 for the tasks towards completing this.

You can find some commonly used payment terms on https://www.nibusinessinfo.co.uk/content/payment-terms-commonly-used-invoice-payment-terms-and-their-meanings

This PR creates a new Doctype to be used ultimately in calculating Due Dates and determining the appropriate GL postings to be made for an invoice.

With this Doctype, you can then create a payment term for 1% 10 N30 by creating a Payment Due Date document as such:
```
code = '1% 10 N30'
description = '1% cash discount within 10 Days; Net 30 days'
term_days = 30
with_discount = 1
discount_percentage = 1
discount_days = 10
```
or a payment term for 21st of Month following Invoice as such:
```
code = '21 MFI'
description = '21st of Month following invoice'
term_days = 21
count_from_month_end = 1
```

Ultimately, the Buying and Selling Controllers can then determine the due date for each term with this information something like:
```(python)
due_date = self.posting_date
if count_from_end_of_month:
    due_date = get_last_day(due_date)
due_date = add_to_date(get_last_day(due_date), days=term_days)
```

In the Payment Entry, the information will also be available something like:
```(python)
for term in payment_terms:
    if term.with_discount and discount_validity_date(invoice) >= self.posting_date:
        // Post to GL discount
```

### CODE REVIEW

**Comment by tundebabzy** [comment]
### Screenshots
screenshot from 2017-08-05 13-09-55

screenshot from 2017-08-06 23-41-52

screenshot from 2017-08-06 23-42-07

**Comment by rmehta** [comment]
**Payment Due Date** is not a good name for this.

How about **Payment Term** ?

**Comment by tundebabzy** [comment]
True. I'll fix that

**Comment by nabinhait** [comment]
Closing this, reopen it after renaming the doctype.

**Review by mbauskar — APPROVED** [review]

**Pull request closed without merging**
