### PR TITLE
fix: show total amount on report summary

### PR DESCRIPTION
**Pull request by venkat102**
Issue:
Balance sheet report summary showing incorrect amount
ref: [22662](https://support.frappe.io/helpdesk/tickets/22662)

Issue

Fix

Backport needed: v15

### CODE REVIEW

**Comment by ruthra-kumar** [comment]
@venkat102 Rebase this on latest develop

**Comment by venkat102** [comment]
@ruthra-kumar rebased the branch

**Comment by ruthra-kumar** [comment]
@mergify backport version-15-hotfix

**Comment by ruthra-kumar** [comment]
@venkat102 
Rather than a [merge](https://github.com/frappe/erpnext/pull/43426/commits/8751d09d69e51f2201996de366252f360d34302f) commit, would suggest you to do [rebase](https://git-scm.com/docs/git-rebase) on future PR's. PR's with merge commits cannot be auto-backported https://github.com/frappe/erpnext/pull/43426#issuecomment-2412666209


Can you create a manual backport for v15

**Comment by venkat102** [comment]
@ruthra-kumar sure will do rebase in the future PR's
I'll create a manual backport for this

**Comment by venkat102** [comment]
v15 backport: #43708

**Pull request merged**
