### PR TITLE
German Manual

### PR DESCRIPTION
**Pull request by MartinEnder**
German Tranlation for complete Manual, based on translation dated 15-12-2015.

### CODE REVIEW

**Comment by anandpdoshi** [comment]
@MartinEnder This is brilliant! :bow:

**Comment by MartinEnder** [comment]
Thanks a lot :-)

**Comment by anandpdoshi** [comment]
merged manually

**Comment by anandpdoshi** [comment]
@MartinEnder please rebase and send a new pull request for your new changes

I have added "Beigetragen von CWT Connector & Wire Technology GmbH"

**Comment by anandpdoshi** [comment]
@MartinEnder The german translation is live at: http://frappe.github.io/erpnext/user/manual/de/

**Pull request closed without merging**
