### PR TITLE
fix: creating internal sales order from PO not fetching Material Request

### PR DESCRIPTION
**Pull request by vishdha**
fixed: material Request not fetch into sales order for Internal sales order in Purchase order issue fixed

### CODE REVIEW

**Comment by vishdha** [comment]
Merge this into version-14

**Comment by vishdha** [comment]
@s-aga-r what would require to merge this pull request?

**Comment by s-aga-r** [comment]
> @s-aga-r what would require to merge this pull request?

image

**Comment by s-aga-r** [comment]
@vishdha, raised a [PR](https://github.com/frappe/erpnext/pull/33304) to fix the issue.

**Comment by vishdha** [comment]
@s-aga-r can you check this.  Some how i face this issue in version 14 https://github.com/frappe/erpnext/blob/develop/erpnext/buying/doctype/purchase_order_item/purchase_order_item.json
When you create Internal Sales order and Save SO this No Copy: 1 cause issue. it not able to fetch Material Request and Material Request Item then full Tracking purpose will ruin for Tracking MR -> PO -> SO->DN->PR.
PR not able to fetch MR details 

Kindly Reopen This PR
and Test Internal transfer workflow

1. Create MR
2.  Create PO from MR
3. Create SO from PO
4. Create DN from SO
5. Create PR from DN

**Comment by s-aga-r** [comment]
@vishdha working as expected, check the below screenshots for your reference.

MR

image

PO

image

SO

image

DN

image

PR

image

**Pull request closed without merging**
