### PR TITLE
Moved multi-currency

### PR DESCRIPTION
**Pull request by cgpurbaugh**
For #4341

### CODE REVIEW

**Comment by cgpurbaugh** [comment]
(Didn't realize this was a closed issue)

**Comment by amandadtp** [comment]
Thanks

**Comment by amandadtp** [comment]
So which role permission I need to have in order to edit the Currency List?

**Comment by cgpurbaugh** [comment]
System Manager, by default.  It can be changed though.

**Comment by amandadtp** [comment]
I have System Manager role permission, but I am not able to change the currency list.  Any idea why would that be the case?

**Comment by cgpurbaugh** [comment]
Not sure, check the role permission manager.

**Comment by amandadtp** [comment]
It says "For System Manager at level 0 in Currency in row 1: Cannot set Assign Amend if not Submittable"

Not too sure what that means though.

**Comment by cgpurbaugh** [comment]
Amend is only for submittable documents, like Sales Order.  Currency, all you should need is read & write.

**Comment by amandadtp** [comment]
I have checked the Read, Write, Create boxes but I still cannot edit the currency list

**Comment by cgpurbaugh** [comment]
have you tried reloading?

**Comment by amandadtp** [comment]
Still the same.  The currency page, for example, HKD is gray out and I am not able to click on anything except the ERPNext home button and my Login menu.

**Comment by amandadtp** [comment]
FYI. I have just rebooted my computer

**Comment by cgpurbaugh** [comment]
Seems like a bug.  Can you check your console?  (F12)

Does it say "c.sender is undefined"?

I'm getting this error on my V7 build.

**Comment by amandadtp** [comment]
I am not too sure on this (I am not from tech background).  Need to check with IT...

**Comment by amandadtp** [comment]
If this is a bug, where/who I can report this to?

**Comment by cgpurbaugh** [comment]
Make a new issue here.

**Comment by cgpurbaugh** [comment]
@amandadtp I created an issue: #5687

**Pull request closed without merging**
