### PR TITLE
fix: BOM - clear Quality Inspection Template according to Inspection Quality Required

### LINKED ISSUE #30190: When uncheck Inspection Required  in BOM the field Quality Inpection Template is not reset
### Information about bug

When uncheck Inspection Required  in BOM the field Quality Inspection Template is not reset

It can result of unable to delete Inspection Quality Template that are not use on submited BOM but information is steel in database 

### Module

manufacturing

### Version

Frappe version: 13
ERPNext version: 13

### Installation method

_No response_

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by FHenry**
fix: clear Quality Inspection Template according to Inspection Quality Required

closes #30190

### CODE REVIEW

**Comment by ankush** [comment]
Screenshot 2022-03-14 at 5 25 08 PM


@FHenry fix looks acceptable, but the test failing is relevant.

**Comment by FHenry** [comment]
@ankush Yes I see the failing test, and I'm struggling to understand why. On UI "manual" testing it's ok, but not with my test code, I try to find why.

**Comment by ankush** [comment]
I think I got it, it's attempting to call `save` on existing test record 😄 

I'll push the fix.

**Comment by FHenry** [comment]
@ankush `save` method do "create" and not save existing state of the object ? I still have to learn about frappe framework ;-)

**Comment by ankush** [comment]
> @ankush save method do "create" and not save existing state of the object ? I still have to learn about frappe framework ;-)


The problem is it's already submitted because of `docstatus=1` so `validate` function doesn't get called. These oddities are only a problem when writing tests TBH.

**Comment by FHenry** [comment]
@ankush YEs, I just found the correct way to do it( inspiration come from previous coded test) PR is OK

**Review by ankush — DISMISSED** [review]

**Comment by FHenry** [comment]
@ankush Thank's ;-)

**Comment by FHenry** [comment]
@Mergifyio backport version-13

**Pull request merged**
