### PR TITLE
[Hotfix] Salary Slip - Fix Child Table Structure for earning and deduction section

### LINKED ISSUE #13120: Salary Slip - Fix Child Table Structure For Earning & Deductions
Each child table can use full-width instead of being squeezed into one section

screen shot 2018-02-27 at 7 48 51 pm

### PR DESCRIPTION
**Pull request by harsh0214**
Closes #13120 
Before 
befor

After
after

### CODE REVIEW

**Comment by nabinhait** [comment]
@harsh0214 I think that layout was there because of print formats. Can you share the print format of salary slip after this change?

**Comment by harsh0214** [comment]
@nabinhait 
Print Format - Standard
pfsnap

Print Format - Salary Slip Standard
salary slip standard

**Comment by nabinhait** [comment]
@harsh0214 Can you please contribute a print format showing earnings and deductions side-by-side? Otherwise, the print of a salary slip will take 2 pages, which is not so good.

**Comment by nabinhait** [comment]
Closing this for now. Please reopen with the print format.

**Pull request closed without merging**
