### PR TITLE
Optionally allow overlap on Timesheet #12893

### LINKED ISSUE #12893: Optionally allow overlap on Timesheet
In my company salary is calculated based on time spent at work in combination with time spent on differently valued projects. So consequently there is a need to *Optionally allow overlap on Timesheet*.

If I understand correctly in my scenario timesheet should allow activity overlap for the same timesheet, because that is what I was trying to do (see below).

image

But since I'm rather new to erpnext it maybe reasonable even in my scenario to also allow overlap between different timesheets.

See also:
[Discussion from May '17](https://discuss.erpnext.com/t/how-to-make-overlapping-for-timesheet/24054) and [recent discussion](https://discuss.erpnext.com/t/optionally-allow-overlap-on-timesheet/33824).

### PR DESCRIPTION
**Pull request by tundebabzy**
### Default
peek 2018-02-20 23-13

### Ignore Validation
peek 2018-02-20 23-09

Closes #12893

### CODE REVIEW

**Comment by nabinhait** [comment]
@tundebabzy As timesheet doctype is part of Projects module, should we add those settings in Project Settings?

**Comment by tundebabzy** [comment]
Yes. Project Settings will definitely be a more appropriate place. WIP

**Comment by tundebabzy** [comment]
Projects Settings added

**Comment by rmehta** [comment]
@tundebabzy can you check codacy issues.

**Comment by ExsquareBNP** [comment]
Hi
I am looking to have this feature included in my erpnext subscription. How do I go about doing that?

Regards
Renoy Francis

**Comment by ExsquareBNP** [comment]
Hi

I found out how to do it. Please ignore previous comment

Regards
Renoy Francis

**Pull request merged**
