### PR TITLE
Created a new pull request for coupon code functionality.

### PR DESCRIPTION
**Pull request by Solufyin**
Dear @rmehta  and @revant ,

Created a new pull request for coupon code functionality. We improved code as per comment on previous pull request.

https://github.com/frappe/erpnext/pull/12559

Thank.

### CODE REVIEW

**Comment by manassolanki** [comment]
hi @Solufyin 
One more thing which I have noticed in both of your PR is that you have linked the Price List instead of Pricing Rule in the Coupon which is wrong.

**Comment by Solufyin** [comment]
Hello @manassolanki,

As per our previous discussion, we added master doctype "Coupon" and also we take price list link field in "Coupon" Doctype.

In Quotation have price list Link field and based on that discount will apply on selected items in Quotation, So, When we select coupon code in Quotation it will set the related Price list on Quotation and based on that Discount will apply on all the items lines in quotation. and same flow will work with shopping cart.

**Comment by manassolanki** [comment]
Hi @Solufyin 
As per our discussion, we have decided to link the Pricing Rule instead of Price List to link with the Coupon master. As there is already a field for the Pricing Rule in Item child tables of Quotation, Sales Order, Sales Invoice and Delivery Note, so the discount can be applied as per the Pricing Rule in all. 
Please note that the Pricing Rule and Price List is different altogether. Here coupon will apply the discount on the price as set in the Price List accordingly to the Pricing Rule.

**Comment by nabinhait** [comment]
@Solufyin 
@manassolanki is working on top of your pull requests. He will send a fresh PR soon.
Closing this PR.

**Pull request closed without merging**
