### PR TITLE
Shareholder and related doctypes

### PR DESCRIPTION
**Pull request by codingCoffee**

### CODE REVIEW

**Comment by ci2014** [comment]
Very interesting feature! Any source how you got to this idea or how it belongs to an ERP system?

**Comment by codingCoffee** [comment]
@ci2014 Most companies have shareholders. Shouldn't a "batteries-included" ERP system provide a solution to keep a track of them!? :P

**Comment by netchampfaris** [comment]
Add screenshots

**Comment by codingCoffee** [comment]
shareholder_tonystark
sharetransfer_issue_tonystark
sharebalance_1
sharebalance_2
shareledger_1
shareledger_2

**Pull request merged**
