### PR TITLE
Stock in items list

### PR DESCRIPTION
**Pull request by ghost**
Hi,

This PR contains
- stock status in item list (in stock or not in stock)
- change the order by to display "in stock" items first, it is still possible to overload by using weightage in item master
- 4 items in each row, instead of 3, better UX for me

Thanks

item-list-stock

### CODE REVIEW

**Comment by mbauskar** [comment]
@britlog,

Thanks for contributing, can you also add the test user cases for the same, closing this PR for now, but you can reopen it.

**Comment by britlog** [comment]
@mbauskar Hi, could you please explain ? Or give me one exemple. Thanks

**Comment by britlog** [comment]
@mbauskar @rmehta What means "test user cases for the same" ? Please explain, I have planned to work on this point tonight. Thanks

**Comment by rmehta** [comment]
@britlog A test case is a script that will test that the modifications you made actually work.

Here is what I would do:

1. add a file `test_product_search.py` (maybe in `erpnext/tests`)
2. write a test case which calls the method with some parameters and asserts that the requested data was returned.

Read this up for a primer:

https://frappe.io/docs/user/en/guides/automated-testing/unit-testing

Automated testing guarantees (upto a point) that your patches actually work and also if someone changes the behaviour in the future, they will also call that out.

Feel free to post any queries on the forum regarding this.

Thanks!

**Pull request closed without merging**
