### PR TITLE
fix: payment entry to student

### PR DESCRIPTION
**Pull request by mohsinalimat**
Payment entry to student via Payment References(From Journal Entry)

### CODE REVIEW

**Comment by deepeshgarg007** [comment]
@mohsinalimat Please reopen again after adding proper description

**Comment by mohsinalimat** [comment]
@deepeshgarg007 Updated, please check. How to reopen the issue?

**Comment by mohsinalimat** [comment]
> @deepeshgarg007 Updated, please check. How to reopen the issue?

I can't reopen the issue because of I don't have permission.

**Comment by mohsinalimat** [comment]
@deepeshgarg007 Please reopen.

**Comment by mohsinalimat** [comment]
@deepeshgarg007 I have update the description and it's approve PR(https://github.com/frappe/non_profit/pull/11) in non_profit separated custom app.

**Pull request closed without merging**
