### PR TITLE
fix: leave without pay spelling in salary register

### PR DESCRIPTION
**Pull request by khadijazaki**
Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

### CODE REVIEW

**Comment by kennethsequeira** [comment]
@khadijazaki 

1. change the base branch to merge from **master** to **hotfix**. Do not send a PR directly to the master branch

2. you also need to make a change in line 27 of the file:

image

**Comment by kennethsequeira** [comment]
Fix is a duplicate of: https://github.com/frappe/erpnext/pull/16670/ for the master branch. Ref: https://discuss.erpnext.com/t/leave-without-pay-variable-spelling-mistake-in-salary-register/49808/

**Review by nabinhait — APPROVED** [review]

**Comment by khadijazaki** [comment]
Why is this not merged into master branch?

**Comment by kennethsequeira** [comment]
@khadijazaki we do not merge any PR directly into the master branch. Check the [Pull Request Checklist](https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist#which-branch).

**Comment by khadijazaki** [comment]
When this code will be updated in master branch then? As i am using the master branch for my project.

**Pull request merged**
