### PR TITLE
arrear billing

### PR DESCRIPTION
**Pull request by ranjanakmomscode**
Hello Frappe Team ,

 " Allow Arrears Billing " feature will allow you to bill your customers after the posting job has been completed

[Arrears Billing.webm](https://user-images.githubusercontent.com/101258436/227431453-b3b62bac-47d1-4f00-88e3-ffc2c27046c9.webm)

### CODE REVIEW

**Comment by deepeshgarg007** [comment]
@ranjanakmomscode I am not sure if this should be done, the service start and end dates have an impact on your accounting entries and that will not be correct.

If you need this for printing in your invoice you can add custom fields in the Sales Invoice child table.
Closing this PR

**Comment by sammish** [comment]
@deepeshgarg007 Our system is unable to save invoices, which is required by the customer. Can you let me know what the impact will be?

this is ERPNext SLA customer

**Comment by agritheory** [comment]
@ranjanakmomscode @sammish I want to recommend an alternative approach but doing so on this closed issue is bad form. Please tag me in on the forum and we can discuss a design; my username there is tmatteson.

**Comment by sammish** [comment]
@agritheory Please advise your approach to the following discussion
 https://discuss.frappe.io/t/arrears-billing-for-deferred-revenue-invoice/102993

**Pull request closed without merging**
