### PR TITLE
Add Payment Entry for Expenses

### PR DESCRIPTION
**Pull request by bcornwellmott**
This gives the option to pull in expenses for the Payment Entry screen (so you can print cheques for expenses for example).

expense_payment

There are still more features to add in other PRs (trying to keep this small):
 - Add Make-> Payment Entry to Expense Claim
 - Add Salary Slip to Payment Entry
 - Improve paid status visibility on Salary Slip
 - Add single salary slip journal voucher creation option (if desired)

### CODE REVIEW

**Comment by sumitdas4u** [comment]
it is very necessary ..  patch

**Comment by rmehta** [comment]
@bcornwellmott looks great 👍 

docs + tests ? - lets do this the right way 😄

**Comment by bcornwellmott** [comment]
Tests were already done. I added a test from an expense claim. I updated the manuals to reflect Expense Claims and fixed the minor codacy issues.

**Comment by sumitdas4u** [comment]
When will it merge to the release ?am waiting for it

**Comment by sumitdas4u** [comment]
When it will merge

**Comment by rmehta** [comment]
Please don't send such reminders... try and contribute in some way.

**Review by mbauskar — APPROVED** [review]

**Comment by nabinhait** [comment]
Merged manually, closing.

**Pull request closed without merging**
