### PR TITLE
feat: Invoice discounting

### PR DESCRIPTION
**Pull request by Anurag810**
Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

### CODE REVIEW

**Comment by Thunderbottom** [comment]
@frappe-bot create instance

**Comment by Thunderbottom** [comment]
@frappe-bot create instance

**Comment by Thunderbottom** [comment]
@frappe-bot create instance

**Comment by Thunderbottom** [comment]
@frappe-bot create instance

**Review by nabinhait — COMMENTED** [review]
@Anurag810 Travis is failing

**Comment by nabinhait** [comment]
Closing this, created another PR https://github.com/frappe/erpnext/pull/17231

**Pull request closed without merging**
