### PR TITLE
feat: added option to add custom remarks in payment entry

### PR DESCRIPTION
**Pull request by Anurag810**
Added option to add custom remarks in Payment entry.

### CODE REVIEW

**Review by deepeshgarg007 — COMMENTED** [review]
Why add this checkbox and make remarks ready only? I don't see any need for this. Any specific reason? If yes then please update in the description

**Comment by Anurag810** [comment]
Please refer issue: ISS-20-21-04489. it was as suggested by Nabin.

**Review by deepeshgarg007 — CHANGES_REQUESTED** [review]
@Anurag810 You didn't read the full suggestion. The main issue is still there. The standard system generated remarks are still not updated in case of reference or paid amount change

**Review by nabinhait — CHANGES_REQUESTED** [review]
If custom remarks is checked, no need to update the remarks field based on reference.

https://github.com/frappe/erpnext/blob/develop/erpnext/accounts/doctype/payment_entry/payment_entry.py#L456

Replace the line `if self.remarks: return` with `if self.custom_remarks: return`

**Review by deepeshgarg007 — APPROVED** [review]

**Pull request merged**
