### PR TITLE
fix(PP): When SO has No BOM items, "Consolidate Sales Order Items" would cause error

### PR DESCRIPTION
**Pull request by a2504dy**
> **Please provide enough information so that others can review your pull request:**

It is because that on the production_plan, when **Consolidate** under SO, items got from server side again.  
 Using Front-End/Back-End separation to fix this issue & improve performance by reducing server loaded.  

PP_Consolidate_with_no_BOM_Item_Error

> **Explain the **details** for making this change. What existing problem does the pull request solve?**

The followings are fixs & feats for this issue.  
  1. [feat] Modify "**Consolidate Sales Order Items**" event by separate front-end & back-end  
     * Let "**Get Finished Goods for Manufacture**" event get items from server side without judging "items need combined or not"   
     * Let "**Consolidate Sales Order Items**" event get data from server side to purely front-end combine same items.  
  2. [feat] Temporarily store data on global variables for combine items & release items.   

**Suggest**:  
    Sometimes, we need to check items from SO whether be manufactured or purchased.  
    Thus, if we using this patch, "fix: do not fetch items with no active BOM in PP #41833", we could not schedule/order work-order, purchase-order by PM.  

> **Screenshots/GIFs**

* **Consolidate status**  
  1. Set index without limit.  
  2. Combine same items for each independent element.  
  4. Add item or no BOM item will not break consolidate.  
  
  PP_SO_Consolidate

* **Consolidate without using server side communication**  
  Clients use  **_Network_** get items from server side only once.  
  And then, data would store on the web browser temporarily until user close or refersh website.  
  Thus, it could improve the loading speed from server.
  
  PP_SO_Consolidate_no_server

### CODE REVIEW

**Comment by a2504dy** [comment]
Dear @rohitwaghchaure ,
Could you review this PR and give me any feedback ?

Thanks
Gino Yang

**Comment by devdiogenes** [comment]
Hello. Do you know why your pull request not runned the checks? The pull requests I made in the ERPNext is with the same issue

**Comment by a2504dy** [comment]
Hi @devdiogenes ,

I have no idea about the checks & workflow run by ERPNext team.
I think maybe we should ask Frappe dev team.

Hello @rohitwaghchaure , @s-aga-r 
Could you please give me some feedback ?

Thanks

**Comment by a2504dy** [comment]
Hello @rohitwaghchaure , @s-aga-r
I modified this commit e6b49599e572fd5605327487e8225b4122023f9c by workflow testing Linter.

I also use server to do functional test.
And it can work like gif.

Could you please give me some feedback ?
Thanks

**Comment by a2504dy** [comment]
Hello @rohitwaghchaure , @s-aga-r,

Could you please tell me about this change is **OK** or **not** ?

**Comment by a2504dy** [comment]
Hello
Is anyone here ?

**Comment by a2504dy** [comment]
Hi @rohitwaghchaure ,
Could you give me any feedback ?

And also, I found that that is a issue existed, https://github.com/frappe/erpnext/issues/16126 .

Maybe you can use same method to fulfill that issue.

**Pull request closed without merging**
