### PR TITLE
PR#10861 Ability to bypass credit limit check at sales order level

### PR DESCRIPTION
**Pull request by ashish-greycube**

### CODE REVIEW

**Comment by tundebabzy** [comment]
Hi @ashish-greycube 
Thanks for the PR and +1 for opening your first PR. However, I'm going to close this for these reasons:
- Your PR is a single commit covering many areas. Break your changes into multiple small commits. Make sure the commit messages are explanatory. Also, add your commits in such a way that the reviewer will be able to follow what you are doing.
- Add screenshots, animated gifs
- Tests for python

We'll be expecting your amended PR ASAP

**Comment by ashish-greycube** [comment]
@tundebabzy  please find below the comment explaining changes done in each file. Also please note there are in-line comments wherever the code is changed
1)modified:   erpnext/selling/doctype/customer/customer.json
comment :--a checkbox flag is kept which allows whether credit limit check be bypassed at sales order level for customer
1.a)New file: erpnext/selling/doctype/customer/test_customer.js 
comment : auto generated file as customer.json is modified

2)modified:   erpnext/selling/doctype/sales_order/sales_order.py
comment :
--code is updated to bypass credit limit check on submit of sales order if flag is present
--since credit limit is bypassed at sales order level need to check it on make of delivery note or sales invoice

3)modified:   erpnext/accounts/doctype/sales_invoice/sales_invoice.py
comment : -- if delivery note is made from sales invoice we need to check the credit limit as

4.b)modified:   erpnext/selling/report/customer_credit_balance/customer_credit_balance.py
comment : -- Credit limit should now reflect outstanding amount for each customer based on value of flage "bypass credit limit check at sales order level". A new column is added to show the value of this flag
4.a)modified:   erpnext/selling/doctype/customer/customer.py
comment : -- get_credit_limit function which gets called by the above customer_credit_balance report is updated to deduct the amount of sales order for which credit limit is bypassed

New test case files
5) Test case files are prepared to check
(5.a)erpnext/selling/doctype/sales_order/tests/test_sales_order_with_bypass_credit_limit_check.js
comment :-- New feature: i.e. bypass credit limit check at sales order
(5.b)erpnext/selling/doctype/sales_order/tests/test_sales_order_without_bypass_credit_limit_check.js
comment :--Regression test case : the existing default flow is checked i.e. credit limit check happens at sales order level

Request you to review the same and help me in the process

**Comment by nabinhait** [comment]
@ashish-greycube  :+1 for the first PR.
I think single PR is ok for this. All the changes related to single feature. But yes, please add some screenshots, modify docs and add server side tests.

**Comment by ashish-greycube** [comment]
Thanks @nabinhait for the review.
Functional flow along with animated gif and test case result is given at [#18061](https://github.com/frappe/erpnext/issues/10861#issuecomment-338943121)

Also the functional requester turner-james has tested it and is happy with feature

**Comment by jigneshpshah** [comment]
@nabinhait below is the design chart and animated gif that was asked.



Please refer design flow chart as below.

bypass credit limit check from sales order


Animated gif explaining the "Bypass Customer Credit Limit" check feature
and "Customer Credit Balance Report" in action.

Outstanding Amount is not updated on submission of "Sales Order".
It is updated during full/partial payment against "Sales Order" and/or after submitting "Delivery Note". (as per the case)

bypass



Test Case :
Automated test cases passed for both scenarios.

1) With Credit Limit check Bypass at Sales Order 
testwithbypass


2) With Credit Limit check without bypass at Sales Order (default)

testwithoutbypass

**Comment by ashish-greycube** [comment]
@nabinhait please advice what i need to do to get this PR merged as it is in closed stat now. thanks

**Pull request closed without merging**
