### PR TITLE
[minor] fides for add to card button issue

### PR DESCRIPTION
**Pull request by mbauskar**
fixes for https://discuss.erpnext.com/t/shopping-cart-add-to-cart-button-missing/22542

### CODE REVIEW

**Review by nabinhait — APPROVED** [review]

**Comment by addymuliady** [comment]
Hi @nabinhait @KanchanChauhan when can this be in master branch?

We have upgraded to v8 and implementing shopping cart for our clients.

Thanks!

**Comment by mbauskar** [comment]
@addymuliady,

FYI, It is already released into the master branch.

**Comment by ziagithub2018** [comment]
This is the picture of my problem which not showing add to card button.

**Comment by steveaz** [comment]
I am having the same problem. My Add to Cart button has disappeared. image

**Comment by ziagithub2018** [comment]
Hey @steveaz

The problem is with Your Item should have price and option of stock
availability should be checked

**Pull request merged**
