### PR TITLE
fix: add fetch from to item_group and brand

### PR DESCRIPTION
**Pull request by nipunanr**
fix: add fetch from to item_group and brand

### CODE REVIEW

**Comment by nipunanr** [comment]
Is this a possible fix?

**Comment by nipunanr** [comment]
need review

**Comment by devdiogenes** [comment]
Hello. Do you know why your pull request not runned the checks? The pull requests I made in the ERPNext is with the same issue

**Comment by nipunanr** [comment]
> Hello. Do you know why your pull request not runned the checks? The pull requests I made in the ERPNext is with the same issue

Sorry. No Idea about it

**Comment by nipunanr** [comment]
Active

**Comment by nipunanr** [comment]
Active

**Pull request closed without merging**
