### PR TITLE
[Fix] Change Restaurant icon type to module

### PR DESCRIPTION
**Pull request by shreyashah115**
Before:

39620540-24b25a28-4fa9-11e8-8d3c-38c4486e0e7b

Now:

screen shot 2018-06-19 at 9 11 58 am

### CODE REVIEW

**Review by nabinhait — APPROVED** [review]

**Comment by sanath2018** [comment]
How can I get this update? because I did not see this update in my ERP next.

**Comment by shreyashah115** [comment]
Which version are you on?

**Comment by sanath2018** [comment]
erp next version

**Comment by sanath2018** [comment]
restaurent order entryeoor

**Comment by shreyashah115** [comment]
This is some other error.

**Pull request merged**
