### PR TITLE
fix(asset): do not submit journal entries with active workflow

### PR DESCRIPTION
**Pull request by Mangesh-Khairnar**
**Fixes:** Asset creates a depreciation journal entry via the scheduler. If multiple workflow state exists corresponding to a particular docstatus, this makes it impossible to change the workflow state after the submission of a document. This PR stops the submission of a journal entry when the workflow for the same is active. The user would have to manually approve the journal entry via the corresponding workflow.

### CODE REVIEW

**Comment by asbasawaraj** [comment]
@nabinhait Can you check this is okay? This is a breaking change. I would recommend that we set the workflow field also automatically.

**Comment by nabinhait** [comment]
@rmehta Any input on this?

**Comment by rmehta** [comment]
Looks okay to me. I think like deferred, we should have depreciation manual too.

**Comment by nabinhait** [comment]
> Looks okay to me. I think like deferred, we should have depreciation manual too.

@rmehta Thanks for the input. We already have manual depreciation option for asset. Merging it.

**Review by nabinhait — APPROVED** [review]

**Comment by muchai** [comment]
What of a case where the depreciation entries are many? Could there be an option to auto submit depreciation entries even if the workflow is active. Like an optional check under settings.

**Pull request merged**
