### PR TITLE
feat(regional): Add master data to DATEV Export

### PR DESCRIPTION
**Pull request by barredterra**
Add three CSV files with master data to the DATEV Export:

- Account Names
- Customers
- Suppliers

They are provided as a zip file, together with the GL transactions.

Depends on #18200 .

### TODO

- [x] Tests: create Cost Center "_Test Cost Center - _TG"
- [x] Tests: resolve all dependencies of Sales Invoice
- [x] Tests: resolve encoding mismatches

### CODE REVIEW

**Comment by barredterra** [comment]
The travis fail doesn't seem to be my fault.

**Comment by rmehta** [comment]
@barredterra can we add some test cases to ensure test coverage?

**Comment by barredterra** [comment]
Sure, good idea.

**Comment by deepeshgarg007** [comment]
@barredterra  Please resolve merge conflicts, fix test cases and update the branch so that it can be reviewed and merged

**Comment by nabinhait** [comment]
@barredterra Can you please fix travis?

**Comment by barredterra** [comment]
I'm trying. It's the tests that are failing, the feature works (on python 2.7 at least).

I would appreciate any help. I need a **complete** example on how to create a Sales Invoice in a test environment. It's the Sales Invoices dependencies that keep the tests failing right now.

**Comment by barredterra** [comment]
@nabinhait @deepeshgarg007 I finally got the tests to work and resolved all encoding issues between py2 and py3 :)

**Review by nabinhait — APPROVED** [review]

**Pull request merged**
