### PR TITLE
feat: visual plant floor

### PR DESCRIPTION
**Pull request by rohitwaghchaure**
Operators can visualize plant floor using "Visual Plant Floor" feature

### Provision to set the Active / Inactive illustration for the workstation

Screenshot 2023-11-27 at 3 28 06 PM

### Visual Plant Floor

image

### Workstation Job Cards
On Opening of the workstation operators can see open job cards of the respective Workstation / Machine

image

### Workstation Job Card Raw Materials

Users can see the job card raw materials on click of down arrow Icon

raw_materials

### Provision to make Material Request for Job Card from Workstation Dashboard

Screenshot 2023-12-05 at 3 24 47 PM

docs https://docs.erpnext.com/docs/user/manual/en/plant-floor

### CODE REVIEW

**Comment by rtdany10** [comment]
Can we have a default image if not illustration is set by user?

**Comment by precihole** [comment]
Waiting for this feature to go live.

**Comment by rohitwaghchaure** [comment]
> Can we have a default image if not illustration is set by user?

@rtdany10 What should be the default image? The default image should match the workstation/machine. Should we use the first alphabet of the workstation as the default image, similar to how we display items in the POS?

**Comment by rtdany10** [comment]
> > Can we have a default image if not illustration is set by user?
> 
> @rtdany10 What should be the default image? The default image should match the workstation/machine. Should we use the first alphabet of the workstation as the default image, similar to how we display items in the POS?

First alphabet should be good enough ig.

**Comment by rtdany10** [comment]
ping

**Comment by rtdany10** [comment]
ping @rohitwaghchaure

**Comment by FHenry** [comment]
Is backport in version-15 possible ?

**Pull request merged**
