### PR TITLE
fix: parse naming series with FY name

### LINKED ISSUE #37596: Naming Series not Working in Version-15
### Information about bug

When we use **.FY.** as an argument in Naming Series and Set the Doc Name by Naming Series, then we receive an error the system does not allow us to create the record. Example:

1. In Buying Settings, Set the Supplier Name field based on Naming Series
2. Now go to Document Naming Setting and Set the Naming Series: SUP-.FY.-.###
3. Come back to supplier master and try to create a supplier.
4. The System won't allow you to create a supplier.

Same is the case with Customer, Employee. I haven't checked the documents pertaining to Sales and Purchase i.e. Sales/Purchase Invoice, Sales/Purchase Orders etc. but i believe that the problem exists there as well.

### Module

accounts, stock, buying, selling, ecommerce, manufacturing, HR, projects, support, CRM, assets, integrations, quality, regional

### Version

Frappe Version: V15-DEV and V15-Beta
ERPENXT: V15-dev and V15-beta

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"email_delivery_service": "0.0.1",
	"erpnext": "15.0.0-dev",
	"frappe": "15.0.0-dev",
	"india_compliance": "15.0.0-dev"
}
```
### Route
```
Form/Supplier/new-supplier-2
```
### Traceback
```
Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 110, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 49, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1682, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/desk/form/save.py", line 36, in savedocs
    doc.save()
  File "apps/frappe/frappe/model/document.py", line 332, in save
    return self._save(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 354, in _save
    return self.insert()
           ^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 280, in insert
    self.set_new_name(set_name=set_name, set_child_names=set_child_names)
  File "apps/frappe/frappe/model/document.py", line 474, in set_new_name
    set_new_name(self)
  File "apps/frappe/frappe/model/naming.py", line 163, in set_new_name
    doc.run_method("autoname")
  File "apps/frappe/frappe/model/document.py", line 948, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1314, in composer
    return composed(self, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 1296, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/document.py", line 945, in fn
    return method_object(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/buying/doctype/supplier/supplier.py", line 45, in autoname
    set_name_by_naming_series(self)
  File "apps/frappe/frappe/model/naming.py", line 245, in set_name_by_naming_series
    doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/naming.py", line 270, in make_autoname
    return series.generate_next_name(doc, ignore_validate=ignore_validate)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/naming.py", line 69, in generate_next_name
    return parse_naming_series(parts, doc=doc)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/model/naming.py", line 324, in parse_naming_series
    part = frappe.get_attr(method[0])(doc, e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/erpnext/erpnext/accounts/utils.py", line 1249, in parse_naming_series_variable
    return get_fiscal_year(date=date, company=company)[0]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 0

```
### Request Data
```
{
	"type": "POST",
	"args": {
		"doc": "{\"docstatus\":0,\"doctype\":\"Supplier\",\"name\":\"new-supplier-2\",\"__islocal\":1,\"__unsaved\":1,\"owner\":\"info.trackomatic@gmail.com\",\"naming_series\":\"SUP.FY.###\",\"country\":\"India\",\"supplier_type\":\"Company\",\"is_transporter\":0,\"is_internal_supplier\":0,\"language\":\"en\",\"gst_category\":\"Unregistered\",\"allow_purchase_invoice_creation_without_purchase_order\":0,\"allow_purchase_invoice_creation_without_purchase_receipt\":0,\"is_frozen\":0,\"disabled\":0,\"warn_rfqs\":0,\"warn_pos\":0,\"prevent_rfqs\":0,\"prevent_pos\":0,\"on_hold\":0,\"hold_type\":\"\",\"supplier_name\":\"Test Supplier 2\",\"represents_company\":\"\"}",
		"action": "Save"
	},
	"btn": {
		"jQuery37000419932080369127551": {
			"events": {
				"click": [
					{
						"type": "click",
						"origType": "click",
						"guid": 1729,
						"namespace": ""
					}
				]
			}
		},
		"__sn": {
			"type": 2,
			"tagName": "button",
			"attributes": {
				"class": "btn btn-primary btn-sm primary-action",
				"data-label": "Save"
			},
			"childNodes": [],
			"id": 45346
		}
	},
	"freeze": true,
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/frappe.desk.form.save.savedocs",
	"request_id": "07d61904-c15c-4cad-b670-62052bb6d266"
}
```
### Response Data
```
{
	"exception": "KeyError: 0",
	"exc_type": "KeyError",
	"_exc_source": "erpnext (app)"
}
```
```

### LINKED ISSUE #38334: naming series fiscal_year fetch KeyError
### Information about bug

when using `.FY.` (Fiscal Year) with naming series in DocType naming it gives error mentioned below:

`Server Error`
`KeyError: 0`
`Possible source of error: ERPNext (app)`

### Module

accounts

### Version

**ERPNext:** v14.x.x-develop () (develop)

**Frappe Framework:** v15.x.x-develop () (develop)

### Installation method

manual install

### Relevant log output / Stack trace / Full Error Message.

```shell
13:18:02 web.1         | Traceback (most recent call last):
13:18:02 web.1         |   File "apps/frappe/frappe/app.py", line 110, in application
13:18:02 web.1         |     response = frappe.api.handle(request)
13:18:02 web.1         |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/api/__init__.py", line 49, in handle
13:18:02 web.1         |     data = endpoint(**arguments)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
13:18:02 web.1         |     return frappe.handler.handle()
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/handler.py", line 49, in handle
13:18:02 web.1         |     data = execute_cmd(cmd)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/handler.py", line 85, in execute_cmd
13:18:02 web.1         |     return frappe.call(method, **frappe.form_dict)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/__init__.py", line 1673, in call
13:18:02 web.1         |     return fn(*args, **newargs)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
13:18:02 web.1         |     return func(*args, **kwargs)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/desk/form/save.py", line 39, in savedocs
13:18:02 web.1         |     doc.save()
13:18:02 web.1         |   File "apps/frappe/frappe/model/document.py", line 334, in save
13:18:02 web.1         |     return self._save(*args, **kwargs)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/model/document.py", line 356, in _save
13:18:02 web.1         |     return self.insert()
13:18:02 web.1         |            ^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/model/document.py", line 281, in insert
13:18:02 web.1         |     self.set_new_name(set_name=set_name, set_child_names=set_child_names)
13:18:02 web.1         |   File "apps/frappe/frappe/model/document.py", line 476, in set_new_name
13:18:02 web.1         |     set_new_name(self)
13:18:02 web.1         |   File "apps/frappe/frappe/model/naming.py", line 166, in set_new_name
13:18:02 web.1         |     set_name_from_naming_options(autoname, doc)
13:18:02 web.1         |   File "apps/frappe/frappe/model/naming.py", line 204, in set_name_from_naming_options
13:18:02 web.1         |     set_name_by_naming_series(doc)
13:18:02 web.1         |   File "apps/frappe/frappe/model/naming.py", line 245, in set_name_by_naming_series
13:18:02 web.1         |     doc.name = make_autoname(doc.naming_series + ".#####", "", doc)
13:18:02 web.1         |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/model/naming.py", line 270, in make_autoname
13:18:02 web.1         |     return series.generate_next_name(doc, ignore_validate=ignore_validate)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/model/naming.py", line 69, in generate_next_name
13:18:02 web.1         |     return parse_naming_series(parts, doc=doc)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/frappe/frappe/model/naming.py", line 324, in parse_naming_series
13:18:02 web.1         |     part = frappe.get_attr(method[0])(doc, e)
13:18:02 web.1         |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
13:18:02 web.1         |   File "apps/erpnext/erpnext/accounts/utils.py", line 1258, in parse_naming_series_variable
13:18:02 web.1         |     return get_fiscal_year(date=date, company=company)[0]
13:18:02 web.1         |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
13:18:02 web.1         | KeyError: 0
13:18:02 web.1         | 
13:18:02 web.1         | 127.0.0.1 - - [25/Nov/2023 13:18:02] "POST /api/method/frappe.desk.form.save.savedocs HTTP/1.1" 500 -
```

### PR DESCRIPTION
**Pull request by GursheenK**
Closes https://github.com/frappe/erpnext/issues/38334
Closes https://github.com/frappe/erpnext/issues/37596

### CODE REVIEW

**Review by nabinhait — APPROVED** [review]

**Comment by nabinhait** [comment]
@Mergifyio backport version-15-hotfix

**Comment by nabinhait** [comment]
@Mergifyio backport version-14-hotfix

**Comment by ankush** [comment]
@GursheenK please add test for this specific usage, this is quite common use case.

**Comment by cogk** [comment]
Hello!

I'm not sure how it's possible for these two lines of code to coexist, isn't there a bug somewhere?
https://github.com/frappe/erpnext/blob/d0ea598cdfb203882fca887d2ba34938c4c75b8e/erpnext/accounts/utils.py#L212

https://github.com/frappe/erpnext/blob/d0ea598cdfb203882fca887d2ba34938c4c75b8e/erpnext/accounts/utils.py#L1283

**Comment by GursheenK** [comment]
Thanks! @cogk. On second look, did realise this was being caused due to the `get_fiscal_years` utility returning an unexpected return type for master documents.

>Maybe a namedtuple-like class could be useful here? The erpnext.utils.get_fiscal_year JS util expects a tuple.

<br>

This is already kind of conditionally handled by the following lines when the fiscal year gets matched- 

https://github.com/frappe/erpnext/blob/c67b0a3a6408075785211da20603fbcd829825bb/erpnext/accounts/utils.py#L128-L131

**Pull request merged**
