### PR TITLE
fix: Invoice amount in KSA E Invoice QR Code

### PR DESCRIPTION
**Pull request by deepeshgarg007**
Replaced Invoice Amount with Grand Total instead of Net Total in QR Code

### CODE REVIEW

**Comment by deepeshgarg007** [comment]
@Mergifyio backport version-13-hotfix

**Comment by deepeshgarg007** [comment]
@Mergifyio backport version-13-pre-release

**Comment by sagarvora** [comment]
Could've been rounded total too?

**Comment by shiraski** [comment]
hi i want implement this qr code in our invoice can you any one help me to solve this issue

**Comment by nasirrr** [comment]
> Could've been rounded total too?

What do you mean?

**Pull request merged**
