### PR TITLE
feat(accounts): add german CoA "SKR03" (GnuCash)

### PR DESCRIPTION
**Pull request by barredterra**
This CoA was generated from the one that comes with GnuCash.

skr03_gnucash

### CODE REVIEW

**Comment by barredterra** [comment]
Travis failing is due to bad tests, not because of this pull. 

It says "Account Number XXXX already used in account XXXX", but the account definitely exists only once in the CoA.

**Comment by wojosc** [comment]
I would go for this one as it already works in GNU-Cash and is being used.

**Review by nabinhait — CHANGES_REQUESTED** [review]
We need to identify all account types listed in https://charts.erpnext.com/coa-help. If there is no account existing with specific account type, please add a new one under proper group.

**Comment by nabinhait** [comment]
@barredterra closing it for now, please reopen after identifying all account types.

**Comment by barredterra** [comment]
- [x] Bank: The account group under which bank account will be created. (1200)
- [x] Cash: The account group under which cash account will be created. (1000)
- [x] Cost of Goods Sold: The account to book the accumulated total of all costs used to manufacture / purchase a product or service, sold by a company.  (4996)
- [x] Depreciation: The expense account to book the depreciation of the fixed assets. (4831, 4832, 4855)
- [x] Accumulated Depreciation: The asset account is used to reduce Fixed Asset value while making depreciation entry.  ("Wertberichtigungen zu Sachanlagen") ([Source 1](https://buchhaltung-lernen.de/abschreibungen/indirekte-abschreibungen-auf-sachanlagen.html), [Source 2](http://www.waldlandwelt.de/cgi-bin/waldlandwelt.pl?140-buchungssaetze/abschreibungen-direkt-indirekt))

> "Accumulated depreciation is a liability account to which the depreciation is balanced. This account will be reversed when the asset is sold or retired. For example, if the asset value is say 10000 in the beginning. Let us say it depreciates at 1000 per year. Then each time depreciation is passed, the accumulated depreciation account will be credited with 1000. The asset account will remain at 10000. Say after 5 years the asset is sold for 6000.then the asset account and  accumulated depreciation account will get reversed. Cash or bank will be debited for 6000 and balance 1000 passed to profit on sale of assets." – Rajesh Kannan

- [x] Capital Work in Progress: Capital Work in Progress (Asset) account contains all expenses incurred on the asset until it is converted into working condition. (0129)
- [x] Asset Received But Not Billed: A temporary liability account which holds the value of assets received but not billed yet and used in Purchase Receipt for receiving assets. (1702)
- [x] Expenses Included In Asset Valuation: The other expenses included in valuation of an asset, apart from direct material costs. (3800)
- [x] Expenses Included In Valuation: The other expenses included in landed cost/valuation of an item/product, apart from direct material costs (used in Perpetual Inventory). (4997, 4998)
- [x] Fixed Asset: The account to maintain the costs of fixed assets. (0200, 0300, ...)
- [x] Payable: The account which represents the amount owed by a company to its creditors. (1600)
- [x] Receivable: It is a current asset account, which represents the money to be received by the company, against the goods delivered or services rendered to the customers. (1400)
- [x] Stock: The asset account for booking the inventory value. (3970, 3980)
- [x] Stock Adjustment: An expense account to book any adjustment entry of stock/inventory, and generally comes at the same level of Cost of Goods Sold. (2320)

  Only for fixed asset, assets do not need this account:
  > Whatever the cause of the loss of goods, the business operator does not need to identify or record it. ([Source](https://www.haufe.de/finance/finance-office-professional/diebstahlschwundverderb-3-diebstahl-oder-schwund-von-waren_idesk_PI11525_HI4722880.html))

- [x] Stock Received But Not Billed: A temporary liability account which holds the value of stock received but not billed yet and used in Perpetual Inventory. (1700)

For the ones that are not checked I need a better explanation with examples and / or help from a German accountant as I could not find any equivalent in the [SKR03](https://www.datev.de/web/de/datev-shop/material/skr-03-englisch/).

Edit: 1700, 3800, 4830 were suggested by a German accountant.

**Comment by barredterra** [comment]
@nabinhait please reopen

**Comment by deepeshgarg007** [comment]
@barredterra can you please check travis and fix. Group accounts for some account types are missing

**Comment by barredterra** [comment]
Done, @deepeshgarg007 .

**Review by deepeshgarg007 — APPROVED** [review]

**Pull request merged**
