### PR TITLE
feat: HR UI/UX Enhancements

### PR DESCRIPTION
**Pull request by Anurag810**
Merge after: https://github.com/frappe/frappe/pull/10206 (New Multi-select list Dialog)
Merge after: #21990 (Payroll Module)

**Payroll Entry:**
Employee Selector:
image

Added employee filter HTML:
image

Validation if salary slip is already created for all employees selected.
image

Show Message for the skipped employees.
image

Allowed users to add and remove employee Manually.

**Salary Structure:**
Added:
image

**leave period**
image

### CODE REVIEW

**Review by scmmishra — CHANGES_REQUESTED** [review]
Feedback on MultiSelect

- [x] 1. Auto fetch on input
- [x] 2. Use like filter
- [x] 3. Search Term -> Search
- [x] 4. Table Title Muted
- [x] 5. Filter Field Events
- [x] 6. Purchase Order Not working
- [x] 7. Don’t write null, show empty
- [x] 8. List View HTML `title`
- [x] 9. Move Filters Up
- [x] 10. TypeError: "this.filter_group is undefined" when not showing filters

**Comment by Anurag810** [comment]
Will work on this After #21990

**Comment by deepeshgarg007** [comment]
@Anurag810 Closing this. Please reopen after resolving conflicts

**Review by nabinhait — COMMENTED** [review]
Fix merge conflict for module change

**Comment by Anurag810** [comment]
will cover this in other pr

**Pull request closed without merging**
