### PR TITLE
[Enhance] Standalone debit/credit note

### LINKED ISSUE #12871: Standalone debit / credit note
Allow negative (return) Sales / Purchase Invoices without any reference.

Its outstanding will be maintained in the negative invoice itself.

https://github.com/frappe/erpnext/issues/8769

Implementation:

- [ ] remove validation that does not allow negative invoice without reference
- [ ] add test case

### PR DESCRIPTION
**Pull request by rohitwaghchaure**
#### Standalone Credit Note
credit_note

#### Standalone Debit Note

debit_note

Dependent PR https://github.com/frappe/frappe/pull/5628
Fixed https://github.com/frappe/erpnext/issues/12871

### CODE REVIEW

**Comment by adnanmunir83** [comment]
Excellent Job @rohitwaghchaure 

Much awaited feature for all members.

**Comment by creamdory** [comment]
Hi @rohitwaghchaure ! This is perfect! Thanks! :D Hope this will be merged soon!

**Comment by rohitwaghchaure** [comment]
**Have made some changes in the UX, now instead of opening debit/credit note from modules, user can directly enable the field Is Return(Credit/Debit Note) from Sales/Purchase Invoice**
#### Standalone Cebit Note
credit_note


#### Standalone Debit Note
debit_note

**Comment by creamdory** [comment]
@rohitwaghchaure so this will be inside the existing purchase and sales invoice now with the "RET" naming series. Cool! Thanks! :)

**Comment by olamide2** [comment]
Great Rohit

Now we only need a way to do this from PoS view and I will be a very happy bunny.

Good work

**Comment by creamdory** [comment]
Hi @rohitwaghchaure , @nabinhait , @rmehta , any chance that this can be merged this week or this is already scheduled to be merged in a particular date? :D This will be really helpful for us! Thanks!

**Review by nabinhait — CHANGES_REQUESTED** [review]
The changes looks good and worked perfectly on my local testing.

Todo:
- [ ] tests
- [ ] docs

**Comment by PawanMeh** [comment]
Only thing missing currently is the ability to apply an existing debit note to a new payment against a new invoice. Assuming this would be part of later releases.

**Comment by albertusgeyser** [comment]
Good Day

Hope this will be added soon as this very important in our company to credit for pallets send one by one, but returned at once.

Thank You

Albertus Geyser

**Comment by albertusgeyser** [comment]
Good Day

Just to see if possible to select series automatically from SINV to SCR(Sales Credit) when selecting credit note?

Thank You
Albertus

**Comment by adnanmunir83** [comment]
can we have this PR in V10 as well?  because v10 is stable where as v11 will give some hard time initially once go live.

**Comment by heatherpotter** [comment]
Is this in v10 or only v11? ERPNext Cloud?  

I also found this which looks good too: https://github.com/agritheory/creditmemo

**Pull request merged**
