### PR TITLE
[POS Enhancement] Render additional/custom fields of Sales Invoice on POS Page

### PR DESCRIPTION
**Pull request by saurabh-bhosale**
**Description:**
To allow additional or custom fields of Sales Invoice to be shown on POS Page. Fields of Sales Invoice that are to be shown on POS Page should be selected in the childtable of '_**POS Settings**_' which are then rendered on POS Page according to an additional checkbox in **_POS Profile_** named "**_Show additional customer details_**" and saved in the respective sales invoice on submit of POS Invoice.

UI rendering on POS needs to be handled well by allowing the section to be a collapsible one. Need suggestions for improvisation.

jmi_pr_2

### CODE REVIEW

**Comment by olamide2** [comment]
@rohitwaghchaure 

that is people's choice, I think its great to have this feature, really exciting from a PoS perspective

**Comment by rohitwaghchaure** [comment]
@olamide2 

You're right but with this PR, all custom fields/Invoice fields are going above the customer field. In invoice user starts with the customer. I think giving all extra fields in the pop up will not break the current layout, @saurabh-bhosale you can also add the pay button in the modal.

I am closing the issue, kindly make changes and reopen the PR.

**Comment by bkm888** [comment]
This particular PR is of great interest to me due to the type of clients I am setting up in ERPNext. This feature is really critical to support Mobile Sales Reps. You can read more about them in this PR:
https://github.com/frappe/erpnext/pull/12564
Essentially they use the POS module from a tablet and they carry it with them on their truck as they visit customers and sell product directly from the back of the truck. Imagine the bakery that sends trucks out to different markets to provide fresh bread and muffins. They need filed like PO#, or some location ID, or even a street address in order to differentiate the customer along their route. The PO# filed is one of the MOST requested but there are many others. 

The fact that @rohitwaghchaure only asks about how to implement points to further agreement that the feature mas merit. It doesn't really matter how it gets implemented as long as it it there in support of mobile sales. This is all part of the next important steps in making the POS module a strong tool for supporting sales of all types and business models.

Like wise, @olamide2 is very correct in his point about customer choice. This allows the customer to better fit POS into their business model.

bkm@jmibarcodes.com

**Comment by Olawale1** [comment]
Hi @saurabh-bhosale 

Trust you're doing great. Just wondering if you're still working on this. It's been more than 2 months since changes were requested

Cheers!

**Comment by Olawale1** [comment]
Hi @saurabh-bhosale 

Any updates here?

Cheers

**Comment by erpwala** [comment]
Hi all,

One major part of any pos is salesman, who is attending customer.

Item sold by salesman should be capture in pos. 
Because in most of scenario company declares incentive on items.
 so in order to find out that which sales man earned incentive on what items.
And incentive is also vary from item to item.

So how we can put salesman on pos billing windows.

Secondly at point of sales 
, customer also gives in advance to cashier's for items.
So advance paid by customer should accept in pos. And also accept Credit note issued.

Is it any simple steps to achieve above scenario.

Or how I can achieve this , pls guide.

**Comment by erpwala** [comment]
> **Description:**
> To allow additional or custom fields of Sales Invoice to be shown on POS Page. Fields of Sales Invoice that are to be shown on POS Page should be selected in the childtable of '_**POS Settings**_' which are then rendered on POS Page according to an additional checkbox in **_POS Profile_** named "**_Show additional customer details_**" and saved in the respective sales invoice on submit of POS Invoice.
> 
> UI rendering on POS needs to be handled well by allowing the section to be a collapsible one. Need suggestions for improvisation.
> 
> jmi_pr_2


Hi, @saurabh-bhosale 
I tried to add field but not found pos setting table in erpnext 12.

Can you guide or help me to add ?

**Comment by ahmedmehany111** [comment]
i have the same problem the Pos setting does not contain the table to add field in it

**Pull request closed without merging**
