### PR TITLE
feat: Create Journal Entry from Bank Transaction, requires frappe bugfix - V13

### PR DESCRIPTION
**Pull request by nameduser0**
V13 port of #24492

### CODE REVIEW

**Comment by hasnain2808** [comment]
Please Check https://github.com/frappe/erpnext/pull/24273
Creating Journal Entry from Bank Transaction

**Comment by nameduser0** [comment]
> Please Check #24273

I've left a review. I think you need to consider other use-cases for your code.
For example, automatic bank reconciliation via Plaid and creation of missing JE's based on previously manually created vouchers, reconciled against matching bank transactions. Also JE creation with manual intervention.

**Comment by hasnain2808** [comment]
> > Please Check #24273
> 
> I've left a review. I think you need to consider other use-cases for your code.
> For example, automatic bank reconciliation via Plaid and creation of missing JE's based on previously manually created vouchers, reconciled against matching bank transactions. Also JE creation with manual intervention.

All of these were considered and possible

**Comment by nameduser0** [comment]
Moving from #24492:
- [ ] fix: payment document
- [ ] fix: autoreconcile on payment/JE creation
- [ ] fix: move Bank Transaction reference to JEA and change to `Journal Entry` not `Bank Entry`
- [ ] feat: multi-entry JE to same account/party from Bank Transaction list view

**Pull request closed without merging**
