### PR TITLE
feat: trigger subscription invoice n days before period end

### PR DESCRIPTION
**Pull request by laydros**
Add ability to trigger invoice *n* days before end of period. 

- Allows generation of subscription invoice a configurable number of days before the end of the period.
- This gives the customer time to make arrangements to pay before the end of the subscription period.
- Adds new checkbox "Generate Invoice Early," and a field to specify how many days early.

For issue #22411

**Documentation PR:** [frappe/erpnext_documentation#192](https://github.com/frappe/erpnext_documentation/pull/192)

erpn-subscription_early_invoice

### CODE REVIEW

**Comment by laydros** [comment]
@deepeshgarg007 @nextchamp-saqib do you guys have any feedback on this?

**Comment by deepeshgarg007** [comment]
@laydros the Days until due here can be kept as 10, right? Why do we need a separate field for this?

**Comment by laydros** [comment]
> @laydros the Days until due here can be kept as 10, right? Why do we need a separate field for this?

@deepeshgarg007 the idea is that one could adjust how long before the due date to generate the invoice. For example my employer typically sends the invoice to the customer 60 days before due.

**Comment by deepeshgarg007** [comment]
> > @laydros the Days until due here can be kept as 10, right? Why do we need a separate field for this?
> 
> @deepeshgarg007 the idea is that one could adjust how long before the due date to generate the invoice. For example my employer typically sends the invoice to the customer 60 days before due.

Yes, so in this case the days until due can be kept as 60 and the subscription start date can be put accordingly, why introduce one more field for it?

**Comment by laydros** [comment]
> > > @laydros the Days until due here can be kept as 10, right? Why do we need a separate field for this?
> > 
> > 
> > @deepeshgarg007 the idea is that one could adjust how long before the due date to generate the invoice. For example my employer typically sends the invoice to the customer 60 days before due.
> 
> Yes, so in this case the days until due can be kept as 60 and the subscription start date can be put accordingly, why introduce one more field for it?

I added the additional field in case another user might want to configure the feature for a different time period, and be more useful in general to ERPNext. For my companies use it will be fine to just have a single checkbox to generate the invoice 60 days before due date.

Would you like me to update the code to work in that manner? Should I instead add the field for number of days early to subscription settings?

**Comment by laydros** [comment]
@deepeshgarg007 Hi, I just wanted to follow up if you had seen my last comment. Do you want me to update the code with no date configuration and just hard-code it to 60 days? Or is it something I should try to add to a settings page instead of being on the subscription page?

**Comment by deepeshgarg007** [comment]
@laydros closing this for now. Doesn't seem to be requested by many users. If many people support this then we can reopen.

**Comment by asharamseervi** [comment]
Hi Deepesh, It's not fair to close PR if it not have raised any feature request earlier! Instead you should have discussed, what's actually wrong or how this feature should have contributed as per guidelines, etc.

Subscription module is too generic at ERPNext, and this feature will allow subscribers (customers) to renew or pay early fixed price subscription! Potential prospect was looking for this feature early 2021, dropped due to less features in subscription management!

**Pull request closed without merging**
