### PR TITLE
fix: correct garbage value on Razorpay Payments Page

### PR DESCRIPTION
**Pull request by Abhishek-Chougule**
This PR addresses an issue in the payment_request.py where the encoding format conflicts with Razorpay Payments Page and getting garbage value instead of title and description like [ 10001, 000100, 00111, 0000011, 01111101 ]

### CODE REVIEW

**Comment by Abhishek-Chougule** [comment]
#42562

**Comment by Abhishek-Chougule** [comment]
Garbage Value for title, description and payer_name on Razorpay Payments Page [0010, 00101110, 00011, 00100100010] #42562

**Comment by Abhishek-Chougule** [comment]
@Nihantra-Patel  Can you please re-run workflows as I have fixed Semantic Commits.

**Review by ruthra-kumar — APPROVED** [review]

**Comment by ruthra-kumar** [comment]
Encoded value is sent _as is_ to Payment Gateway. This is incorrect.
```
{
 "amount": 100.0,
 "currency": "INR",
 "description": [
  80,
  97,
  121,
  109,
  101,
  110,
  116,
  32,
  82,
  101,
  113,
  117,
  101,
  115,
  116,
  32,
  102,
  111,
  114,
  32,
  65,
  67,
  67,
  45,
  83,
  73,
  78,
  86,
  45,
  50,
  48,
  50,
  52,
  45,
  49,
  48,
  50,
  52,
  56
 ],
 "order_id": "ACC-PRQ-2024-00048",
 "payer_email": "Administrator",
 "payer_name": [
  74,
  97,
  109,
  101,
  115,
  32,
  77,
  97,
  121
 ],
 "reference_docname": "ACC-PRQ-2024-00048",
 "reference_doctype": "Payment Request",
 "title": [
  83,
  116,
  97,
  116,
  101,
  32,
  77,
  97,
  99,
  104,
  105,
  110,
  101
 ]
}
```

**Pull request merged**
