### PR TITLE
[fix] Sales order link to purchase order not working fixed

### PR DESCRIPTION
**Pull request by vishdha**
Create sales order.
Create material request from the sales order.
Create purchase order from the material request.

Purchase Order Link visible in Sales Order.
Ordered Qty update in a sales order.

### CODE REVIEW

**Comment by snvora** [comment]
Hi,
This is great. 

Will it work if a quotation is first created from the material request and then purchase order is made?

**Comment by vishdha** [comment]
Do you mean from sales order -> material_request -> supplier_quotation -> purchase order.

**Comment by snvora** [comment]
yes

**Comment by vishdha** [comment]
not yet,
I will do it for supplier quotation too.
just need to add docfield in supplier_quotation

**Review by tundebabzy — CHANGES_REQUESTED** [review]
Works well thus far. Only thing remaining is that already created Sales Orders remain as is because the fix only works for new Sales Orders

**Comment by rohitwaghchaure** [comment]
Write patch to update sales order in the purchase order item for the existing purchase orders

**Review by rohitwaghchaure — APPROVED** [review]

**Pull request merged**
