### PR TITLE
[fix] Get items in stock reconciliation based on default warehouse

### PR DESCRIPTION
**Pull request by nabinhait**

### CODE REVIEW

**Comment by anandpdoshi** [comment]
@nabinhait what's the context of this change?

**Comment by nabinhait** [comment]
@anandpdoshi "Get Items" button in stock reconciliation fetches all items. For many users, there are more than 1000 items. Hence it is better to fetch items based on default warehouse. 
Note: While fetching items, we take warehouse input via dialog.

**Comment by Devens** [comment]
I agree. This will be very useful.

**Comment by anandpdoshi** [comment]
@nabinhait what about the case when you want to get all items in a particular warehouse, which is not a default warehouse?

I think the items returned should be a combination of item's that have `warehouse` as default warehouse or have a bin with warehouse `warehouse`

**Comment by nabinhait** [comment]
@anandpdoshi Makes sense, will fix accordingly.

**Comment by nabinhait** [comment]
Fixed as per @anandpdoshi's suggestion

**Comment by nabinhait** [comment]
@rmehta please merge

**Pull request merged**
