### PR TITLE
feat: Added Quotation Comparison to Buying

### PR DESCRIPTION
**Pull request by mymi14s**
## Description
This PR added Quotation Comparison to ERPNEXT. Quotation comparison is a feature that can be used to compare supplier created quotations for Request for Quotation. It is executed in the following order:

- Request for Quotation created with suppliers selected.
- Suppliers fill quotations online or created from desk on behalf of the suppliers.
- Quotation Comparison is fired up.

Quotation Comparison can be used to analyse quotations based on the following

1. Total cost from single supplier.(lowest to Highest).
2. Total Cost from multiple suppliers (each item analysed, lowest price selected from each supplier).
3. Earliest Delivery.

Once quotation is accepted and submitted, Purchase Order can be created directly from the document to one or more suppliers based on how the items were selected by the comparison calculator.

https://user-images.githubusercontent.com/10146518/192277973-c9c7510d-48f8-414b-9c45-4fac43fb62c6.mp4

### CODE REVIEW

**Comment by mymi14s** [comment]
Linter will be fixed, please ignore the updated and add the review changes so I can see the actual issues, thank you.

**Review by s-aga-r — CHANGES_REQUESTED** [review]
@mymi14s Could you add a GIF/Video describing the feature? It will help us to understand better.

**Comment by deepeshgarg007** [comment]
@mymi14s Closing this until a GIF/Video is attached. Please add and reopen

**Comment by mymi14s** [comment]
@deepeshgarg007 a video has been attached.

**Comment by mymi14s** [comment]
@deepeshgarg007 linter test passed.

**Comment by mymi14s** [comment]
@deepeshgarg007 is the video attached enough for the description or is there more that is required. The linter seem to be annoying.

**Comment by mujeerhashmi** [comment]
This is a very cool feature. I guess we got to relook at this @mymi14s @deepeshgarg007.

**Comment by mymi14s** [comment]
It was ignored 🙁.

**Pull request closed without merging**
