### PR TITLE
fix: cannot create task with *Apply Strict User Permissions*

### PR DESCRIPTION
**Pull request by ahmadpak**
If user permissions is set for company and apply strict user permissions is set. The system does not allow to create tasks in the tree view

### CODE REVIEW

**Comment by ahmadpak** [comment]
@ankush Review here please. Mistakenly did wrong rebase

**Comment by pateljannat** [comment]
@ahmadpak can you please add more details to the description like steps to replicate, etc and attach relevant screenshots.

**Comment by ahmadpak** [comment]
@pateljannat Steps to produce
Set the permission settings
image

Set User permission for Company, Employee and Project
image

image


Try creating Tasks in the tree view

**Comment by pateljannat** [comment]
@ahmad18189 this can only happen if the user is trying to create a Task in a Project with a company that the user is not permitted to.

Can you please verify the company of the project and check if the user has permission to that company?

**Comment by pateljannat** [comment]
Reopen if needed. Closing this for now.

**Pull request closed without merging**
