### PR TITLE
General Ledger Summary report added for issue #15404

### PR DESCRIPTION
**Pull request by vijaywm**
https://github.com/frappe/erpnext/issues/15404
A new general ledger summary report is prepared which gives account wise summary.

### CODE REVIEW

**Comment by PawanMeh** [comment]
Could you double check if the filters you have added work, since I see no posting_date in your select list in the query or in where condition.

**Comment by heatherpotter** [comment]
This would be a very nice report to have! We have to spend an hour to create this report in excel so it would save us a lot of time!

**Comment by heatherpotter** [comment]
Can anyone do this for me? I really need it. Willing to pay for this as well.

**Comment by PawanMeh** [comment]
@heatherpotter , I have already done this via PR: https://github.com/frappe/erpnext/pull/16060

It is awaiting merge, are you on v11 or v10?

**Comment by heatherpotter** [comment]
I'm on ERP Next Cloud - currently production environment is on v10 and our test environment is on v11.

**Pull request closed without merging**
