### PR TITLE
fix: Naming Series preview when no previous transaction present

### PR DESCRIPTION
**Pull request by SvbZ3r0**
Fixes Naming Series preview error mentioned in #36234

### CODE REVIEW

**Comment by SvbZ3r0** [comment]
Active

**Comment by SvbZ3r0** [comment]
@deepeshgarg007 Any issues with this PR?

**Comment by deepeshgarg007** [comment]
@SvbZ3r0 doc is still being accessed on line no 1121, so this change might not full resolve the error that you encountered

**Comment by SvbZ3r0** [comment]
Ahh got it. My bad. I'll correct that.

**Comment by deepeshgarg007** [comment]
@SvbZ3r0 Can you add a basic test case for this? codecov check failing

**Comment by SvbZ3r0** [comment]
I.. uh.. have no idea how to write a test case. Point me in the right direction and i will try.

**Pull request merged**
