### PR TITLE
Assign Salary Structure to group of EMP

### PR DESCRIPTION
**Pull request by Alsum**
peek 2018-10-01 16-27

### CODE REVIEW

**Comment by rmehta** [comment]
@Alsum thanks for the contribution!

can you add a few tests to ensure your code works always as planned

https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

https://frappe.io/docs/user/en/guides/automated-testing/unit-testing

**Comment by Alsum** [comment]
> @Alsum thanks for the contribution!
> 
> can you add a few tests to ensure your code works always as planned
> 
> https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist
> 
> https://frappe.io/docs/user/en/guides/automated-testing/unit-testing

@rmehta done

**Comment by nabinhait** [comment]
@Alsum Can you please send this PR to staging-fixes branch.

https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist#which-branch

**Review by Alchez — CHANGES_REQUESTED** [review]

**Comment by rmehta** [comment]
@Alchez  👍  for your PR reviews!

**Pull request closed without merging**
