### PR TITLE
test: inherit from frappe.tests.IntegrationTestCase (treewide)

### PR DESCRIPTION
**Pull request by blaggacao**
Infer probable test spec of unclear test cases (integration vs unit).

see: https://github.com/frappe/frappe/pull/27987

### CODE REVIEW

**Comment by blaggacao** [comment]
@rohitwaghchaure This should fix the problem. I unfortunately fried my main machine just 20 mins ago, will try to fix this asap, but can't cycle locally.

**Comment by blaggacao** [comment]
Unless there are tests which do not concisely declare their test record dependencies, in which case I'll implement a temporary "lump-sump" record loader specifically for erpnext, until that is fixed.

**Comment by ruthra-kumar** [comment]
> Unless there are tests which do not concisely declare their test record dependencies

This is the case for most of the doctypes. Unless the test suite for each of them are manually refactored to be indempotent, merging this change will be almost impossible, as there sure will be breakage somewhere.

**Comment by blaggacao** [comment]
> Unless the test suite for each of them are manually refactored to be indempotent

I was actually planning in doing (attempting) exactly that. I'm so fed up with not being able to test things in isolation. :cry:

**Comment by ruthra-kumar** [comment]
I would suggest you to tackle one doctype at a time.

I've been attempting to make Journal Entry test suite independent https://github.com/frappe/erpnext/pull/43405

**Comment by blaggacao** [comment]
I'm still pondering on a strategy, but here is my draft:

1. Fix missing test records for each doctype (auto create in framework via predictable rule)
2. Store created document content hashes (instead of only names; from `as_json`) at runtime, so that we can assert initial document state for each "managed" test record
3. Remove manual creation in favor of auto-created test records (according to predictable rules), so that predictable rules start to be the basis of test records
4. Start warning on document hash mismatch during test class tear down; fix stuff manually
5. Start erroring on document hash mismatch during test class tear down; ensure bad stuff doesn't come back

Then, we can tackle "unmanaged" test records which are test-local, if need still be.

**Comment by ruthra-kumar** [comment]
> (auto create in framework via predictable rule)

How are you planning to do this?  I don't remember a system in framework for auto-creation of test records.

**Comment by blaggacao** [comment]
In a first step, we really just have to come up with predictable value rules to comply with this:

https://github.com/frappe/frappe/blob/8983b13a3fbf88b268e171bf80fb9f3c831b1c55/frappe/tests/utils.py#L203-L212

Dates & Times 1970-01-01 00:00:00
... we'd have to come up with a good set of rules.

That's litterally it.

**Comment by blaggacao** [comment]
This massed approach, if each step is carefully executed, may actually result in very good progress, the 2nd and 3rd commit of https://github.com/frappe/erpnext/pull/43507 are already promising.

Temporary flakiness may not completely be ruled out, so best we do critical steps on weekends, to minimize potential blast radius as much as possible.

**Comment by blaggacao** [comment]
I see, one major problem in ERPNext is that test records are not declared in metadata (`test_records.json`) but ad-hoc in python code, which makes them hard to track. And unfortunately, some tests depend on such stateful creations.

**Comment by ruthra-kumar** [comment]
> This massed approach, if each step is carefully executed, may actually result in very good progress, the 2nd and 3rd commit of #43507 are already promising.
> 
> Temporary flakiness may not completely be ruled out, so best we do critical steps on weekends, to minimize potential blast radius as much as possible.

I would still prefer small chunks. The thing with mass changes, especially with such inter-dependent test suites, is that tracking the root cause for a breakage would become a nightmare.

**Comment by ruthra-kumar** [comment]
> I see, one major problem in ERPNext is that test records are not declared in metadata (`test_records.json`) but ad-hoc in python code, which makes them hard to track. And unfortunately, some tests depend on such stateful creations.

I actually don't prefer the `test_records.json` approach. It's not easy to comprehend a large JSON file.

For example: https://github.com/frappe/erpnext/blob/cd112795d3dff1f6ad1dda475d184ba6197f54e7/erpnext/accounts/doctype/purchase_invoice/test_purchase_invoice.py#L952

I'll have to open the json file and locate the second item to find what sort of document the test creates.

**Comment by blaggacao** [comment]
> I actually don't prefer the test_records.json approach. It's not easy to comprehend a large JSON file.

Would YAML be ok? (or TOML) &mdash; I agree json is not the best here.

> I would still prefer small chunks. The thing with mass changes, especially with such inter-dependent test suites, is that tracking the root cause for a breakage would become a nightmare.

Hm, that is true. Maybe I should be more precise: level up the constraints for tests, step by step, but on equal footing for all tests. If a constraint isn't bearable by the test suite, then revert to manual one-by-one refactor. :+1:

**Comment by blaggacao** [comment]
> I actually don't prefer the test_records.json approach. It's not easy to comprehend a large JSON file.

We also could write a small Frappe LSP implementation to auto-load test data-structure into a TAB-completable.

**Comment by blaggacao** [comment]
This is almost completed now, through an automatic bisection effectively (after some manual validation of the bisection script) starting here: https://github.com/frappe/erpnext/pull/43542

**Pull request closed without merging**
