### PR TITLE
Python 3 comapatibility Fixes

### PR DESCRIPTION
**Pull request by adityahase**
After [Frappe PR #3984](https://github.com/frappe/frappe/pull/3984) and [ERPNext PR #10519](https://github.com/frappe/erpnext/pull/10519)

`bench run-tests` fails without printing test logs

this and [Frappe PR #4050](https://github.com/frappe/frappe/pull/4050) fixes that and now `bench run-tests` yields test logs

```
...


E..EEEEEEEE.....F........E..EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE.........E
E.......EE.......EEEEEE.....EEEEEEEEEEEEEEEEEEEEE.EEFEEEEEEEEEEE.............
.E....E.E.EEE.....EEEEEEEEEEE........E...E.........EE...FF..F...FFFFFF......E..E..........F
..........FFEEEEEEEF...F.EEEE..EEEEEEE.EE..........EEE..............E..E..EEEEE..EEE..
..E.EEEE.EEEEEEEEEEEEEEEEEEEE.EEEE..E...EEEEEEEEEEEE......................EEE
E.EEEE.E...............EEE..E........E..E.......E...................EEEEEEEEEEF.EEEEEEEEEE
EEEEEE..F.EFEEEEE..EEEE..EEEEEEEEEEEEEEFEEEEEEEE.EEEEEEEEE......E.EE
EEE.EEEEEEEEE.EEEEEEEEE..EEE.EEEEEEE.EEEEEEEE.EEE.E......EE......E.E.......
....................F...EEEEEE...E


...

Ran 661 tests in 272.446s

FAILED (failures=21, errors=327)
```

### CODE REVIEW

**Comment by rmehta** [comment]
Pls rebase

**Comment by adityahase** [comment]
I've rebased and pushed but nothing has happened here, and I cannot reopen this PR.

**Comment by tundebabzy** [comment]
@adityahase 
Open a new pull request. You were supposed to reopen the issue before pushing

**Comment by adityahase** [comment]
@tundebabzy I cannot reopen.

**Pull request closed without merging**
