### PR TITLE
fix(packed_item): ensure proper names for ref integrity

### LINKED ISSUE #37587: Bad Packed Item state when DN bulk-created from SO
### Information about bug

1. Create DN from SO *via list action*
2. Modify the bundle item qty -> packed item list qtys aren't updated, but new rows are created
3. Change the bundle item qty back -> packed item list isn't update; now has wrong qtys

## Cause
The doc mapper used to create a DN from a creates Packed Items at a point in the lifecycle of DN.items when they don't yet have a `.name` set and hence can't be uniquly identified, or identified at all.

This `.name` component of the id key becomes `None` at the time of creation of the Packed Items resulting in `parent_detail_name = None` but after saving the DN, it is being set on the item. And thus no longer `item.name [hash] == packed_item.parent_detail_name [None]`  

### Module

stock

### Version

ERPNext: 17d4ab36c0e28f905b63cfea15213f777cbc0d3e

Frappe: https://github.com/frappe/frappe/commit/6c509f6dd12796ff11e8e75b049fefe915f5fc3c (has the doc mapper code)

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

This diff evidences the error in the business flow.

```diff
commit 652cdd75b56323578b352db15b84be96e6cab6a0
Author: David Arnold <dgx.arnold@gmail.com>
Date:   Thu Oct 19 11:40:15 2023 +0200

    fix(packed_item): assert breaks creation from doc mapper

diff --git a/erpnext/stock/doctype/packed_item/packed_item.py b/erpnext/stock/doctype/packed_item/packed_item.py
index dbd8de4fcb..fb925160ba 100644
--- a/erpnext/stock/doctype/packed_item/packed_item.py
+++ b/erpnext/stock/doctype/packed_item/packed_item.py
@@ -67,6 +67,7 @@ def get_indexed_packed_items_table(doc):
 	"""
 	indexed_table = {}
 	for packed_item in doc.get("packed_items"):
+		assert packed_item.parent_detail_docname
 		key = (packed_item.parent_item, packed_item.item_code, packed_item.parent_detail_docname)
 		indexed_table[key] = packed_item
 
```

### PR DESCRIPTION
**Pull request by blaggacao**
closes: #37587

### CODE REVIEW

**Comment by blaggacao** [comment]
needs backport to v15; I noticed however, that when not used with mass creation, but from the SO form, namings jump every other name in the series; possibly because despite the `name_set` flag, names are doubly assigned somewhere.

**Comment by s-aga-r** [comment]
@blaggacao This is causing an issue https://github.com/frappe/erpnext/issues/38072. 

Moving `target.set_new_name()` under `update_item()` should fix both the issues, can you check once?

**Comment by blaggacao** [comment]
@s-aga-r `make_packing_list(doctarget)` needs to run after `doctarget.set_new_name()`, `update_item` works on `childtarget`. Or did I miss something? I attempted a broader elimination via https://github.com/frappe/frappe/pull/23201 but for a quick fix, the only other option I saw is to add (yet another) flag in the bulk transaction mechanism. But that flag will be abused by future developers, for sure.

**Comment by blaggacao** [comment]
@s-aga-r `update_item` doesn't run once on `source_target`. I attempted a general fix for this problem class in https://github.com/frappe/frappe/pull/23201, but don't know what to do otherwise with this.

The current errors, while very visible, at least don't produce silently inconsistent data.

I don't know really what to do about this other than getting serious about https://github.com/frappe/frappe/pull/23201

Adding yet another flag to the bulk transactions might just spiral the codebase a step further into unmaintainability.

**Comment by blaggacao** [comment]
@s-aga-r Unfortunately, this appears to bring back the original issue.

```diff
diff --git a/erpnext/selling/doctype/sales_order/sales_order.py b/erpnext/selling/doctype/sales_order/sales_order.py
index c5ad524ef7..de6a0e61c9 100755
--- a/erpnext/selling/doctype/sales_order/sales_order.py
+++ b/erpnext/selling/doctype/sales_order/sales_order.py
@@ -837,11 +837,11 @@ def make_delivery_note(source_name, target_doc=None, skip_item_mapping=False):
 		if target.company_address:
 			target.update(get_fetch_values("Delivery Note", "company_address", target.company_address))
 
-		# set target items names to ensure proper linking with packed_items
-		target.set_new_name()
 		make_packing_list(target)
 
 	def update_item(source, target, source_parent):
+		# set target items names to ensure proper linking with packed_items
+		target.set_new_name()
 		target.base_amount = (flt(source.qty) - flt(source.delivered_qty)) * flt(source.base_rate)
 		target.amount = (flt(source.qty) - flt(source.delivered_qty)) * flt(source.rate)
 		target.qty = flt(source.qty) - flt(source.delivered_qty)
```

I tried to eliminate this problem class via https://github.com/frappe/frappe/pull/23201

All other invocations of make_delivery_note that depend on a `self.is_new()` fail. `make_packing_list` in those workflows is invoked by the validation routine at the proper time (which is skipped during bulk creations with a flag).

**Pull request merged**
