### PR TITLE
[domain] ERPNext for Non-profits

### PR DESCRIPTION
**Pull request by vishdha**
- [x] Test Cases
- [x] Documentation

The Non-Profit Modules in ERPNext is designed to meet requirements of NGO and Non-Profit Organization.
module

Current Pull Request contain
1. Membership Doctype
member
membership

membership_type

2.Chapter Doctype
3. Donor
4. Volunteer
5. Grant Application

### CODE REVIEW

**Comment by Yakulu** [comment]
# Non profit feedback

For, thanks for the work done. I see nonprofit as very important domain.

So I have tested locally the PR. I will do some feedbacks and questions here, maybe suggestions. I won't go from wiki page but only done code and current structure.

## Chapters

I guess fields are OK. A couple of remarks :

* Maybe `meetup embed HTML` needs to be hidden per default and more explained with help text ?
* About `route`, maybe help test too ? I got troubles getting chapter details URL working from chapter list on website.

Middle term, integration of conference app for ERPNext generic event handling will be a great addition which can be used by non profit (instead of meetup like).

### Chapter members

I also feel that we may lost information for members : when a contact becomes a chapter member, he must become a user (in sense of ERPNext). If he leaves the chapter, we lose history. Maybe adding an optional `contact` link in `Chapter Member` doctype to allow kind of relation between user and contact can be a good idea.

I guess chapter joining and leaving from websites are not enabled ATM ?

### Chapter message

Not sure about what `chapter message` is for. I guess it is email communication, like newsletter ? `Chapter` field should be a link, not data, am I wrong ?

## Membership

### Membership type

I suggest membership type to be able to be deactivated (for archive, old memberships). It may have default start and stop dates, enabling auto-filling for new membership.
I also wonder about requiring membership type to be linked with a standard product, for handling potential taxes, currencies... but it adds complexity. What do you think ?

### Membership

Apart from automatic dates, forced previous 30 days `renewal` should be configurable (and deactivated if wished). At some point, we will need a subscription receipt.

### Members

What `expires_on` mean ? I guess this is membership information but I may not be there, or only read-only and directly bounded to membership_type.
About `contact` : this is IMO a good thing. Is it possible to add existing contacts too (not only create new) ?
`Accounting` should be setup per default and collapsed I believe.

## Volunteer

To me a `volunteer` can be or not a member (linking should be good here). In this case, volunteer type may have no utility. The same for accounting data on volunteer doctype. For non members, linking to existing contact should be a good thing too.

About `volunteer availability` : I think it is a good idea but quite hard to implement... Either we go through calendar usage (with repeated events for example), either, in my opinion, a simple textarea would be sufficient for many non profit to note volunteer availabilities when needed.

Concerning `volunteer skills` : here my opinion is that we need child table for many 2 many (like tags). Then skills can be autocomplete, reused and then reported / searched with more accuracy.

## Donor

As for members, I guess `accounting` data can be set up per default and collapsed. Donators are people who give money other than memberships. We need to be able to handle here *occasional as regular* donations (here ERPNext subscription ability would be really useful). After donation, we should be able to generate invoice-like *donation receipts*. To me linking with classical products, sales... can offer free reporting and features. But as said before, this is debatable.

## Grant Application

It is not clear to me if `grant` if from non profit to external or from external to the non profit. I guess this is the first case here.
Linking to existing `contact` should be required in my view. Also, linking with accounting makes sense (we gave money to xx, we must register this). Then already received grant can be filled automatically, according to account data.

Again : **thanks for working on this**. Hope I will soon be able to contribute, by code.

**Comment by vishdha** [comment]
Thanks, Fabian, For Reviewing my pull request.
I will Start from End.

## Grant Application
Grant Application breaks into two part Grant Seeker and Grant Maker. Above Pull Contain only Grant Writing Application I'm Wating to Merge this PR so I can work on next part. 
1. I am thinking to used above grant application as grantmaker ( Where   Org can write a grant to seek to fund from External Organization. 
2.GrantSeeker:  Same Grant Application Section Contain Assessment Manager where He will review grant Application and provide number into
 0 - 10 scale. After reviewing, Grant Organization can send an invitation message to an applicant to attend an event and accept money. and provide feedback

##Donor
Yes, Donor Feature needs to improve. I think we need help from the community how to handle Soft Credit, Donation, Pledge etc. your Idea about subscription and donation receipt is great.

## Volunteer
Yes, a volunteer can be or not a member.
Volunteer Skills is child table. a volunteer can put as many as skills in volunteer application form.

##Membership Type
membership type to be linked with a standard product, for handling potential taxes, currencies. Good Idea.
Yes, Membership Type should have enabled/disabled checkbox.
Some Organization Have Membership Period but some Organization can accept membership anytime. so start date and end date depends on Organization need. 

All another point that mention in chapter and membership are Great and definitely, I will work on it. 
Thanks Again @Yakulu

**Comment by Olawale1** [comment]
Hi @vishdha

This is great work you've started on a very important domain. As you mentioned, I'm also eagerly awaiting this to be merged so that other phases can be worked upon

This will open up ERPNext to a whole new vista of opportunities. Great job and well done!

Kind regards,

**Comment by vishdha** [comment]
Grant Application

grant_application

Grant Application Web Portal
grant_applicaion2

Assessment Manager Review
grant_application3

**Comment by Olawale1** [comment]
Hi @vishdha

Trust you're doing great. Perhaps for the next iteration, a very important point to consider is making the Chapter DocType a tree. I happen to be involved with a number of non-profits and they pretty much all have a tree structure for their Chapters 

Kind regards,

**Comment by revant** [comment]
- Installs as expected (frappe-develop branch and erpnext-non_profit branch)
- Chapter Quick Entry Dialog shows route as mandatory. (must be autogenerated)
- Chapter route should be auto generated
- Correction in Error Message (Chapter Message): You are not *authorized* to send message for this Chapter.
- Roles needs re-design: All doctypes are editable to System Manager and Website Manager only. Domain/Role needs a thought to hide doctypes accordingly.
- Remove unused code and commented code. Add appropriate comments if necessary
- Cleanup documentation : Seems copy-pasted from schools (alt="Student")
- Chapter Message name is 10digit hash, add Subject or Chapter as title field to make listview human readable
- Membership :
	- Error: Value missing for Member: Membership Type
	- Quick Entry Dialog Incomplete (remove if not necessary)

- Use Fontawesome for now. (Adding to assets unnecessary)
- Use different background colours of icons.
- What does Volunteer Type do? Documentation is copy of Membership Type. Volunteer Amount is to be paid to volunteer or paid by volunteer or just master record?
- Donor and Donor Type is Complete.
- Grant Application is not understood or discoverable clearly. Needs clearer documentation.
- All documentation is just screenshots. Add comments / explaination of important fields at least. Explaining all fields and process after save/submit/delete in documentation is highly recomended
- grant application email field is data 
	- set option email or validate for email? 
	- tried entering wrong email and it works 
	- can be part of automated test?

**Comment by vishdha** [comment]
-[ ] Installs as expected (frappe-develop branch and erpnext-non_profit branch)

**Pull request merged**
