### PR TITLE
fix: migration v12 to13 problem opportunity

### PR DESCRIPTION
**Pull request by FHenry**
into erpnext/crm/doctype/opportunity/opportunity.json the attribut modified is the same in v12.22.0 as in v13.6.
The result is on apps/erpnext/erpnext/patches/v13_0/rename_issue_doctype_fields.py on 
`frappe.reload_doc('crm', 'doctype', 'opportunity')`
it return false, and the tabOpporunity is not altered with ALTER TABLE xxx MODIFY

### CODE REVIEW

**Comment by ankush** [comment]
We do not accept changes directly to `version-13` branch. Please send PR to `develop` and/or `version-13-hotfix`

**Comment by FHenry** [comment]
@ankush When did you merge version-13-hotfix into version-13 ???? actually there is merge conflict. I'll try to do it but by the way you have a solution to this bug

**Comment by gdlrsilv3** [comment]
hello, I ran into the same error, do you know if this bugfix will be incorporated into the next release of version 13?

**Comment by ankush** [comment]
can either of you share the full error?

The last commit to opportunity.json has changed `modified` so it's not the root cause of whatever issue you are facing. 

ref: https://github.com/frappe/erpnext/commit/3f45901f257f69d9e3155507da020c18c5155cdc#diff-f063e73dce1e065b224a998994d3440df1d536cafc4f2eef7b7cc7d61d26ff81

**Comment by gdlrsilv3** [comment]
sure, this is the full error, I got today, let me know if you need any other info,


Executing erpnext.patches.v13_0.setting_custom_roles_for_some_regional_reports in deverp.mydomain.com (_a3f74ab5815f77f5)
Success: Done in 0.096s
Executing erpnext.patches.v13_0.rename_issue_doctype_fields in deverp.mydomain.com (_a3f74ab5815f77f5)
rename_field: first_response_time not found in Opportunity
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/erpnextuser/mybench/apps/frappe/frappe/utils/bench_helper.py", line 104, in <module>
    main()
  File "/home/erpnextuser/mybench/apps/frappe/frappe/utils/bench_helper.py", line 19, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/erpnextuser/mybench/apps/frappe/frappe/commands/__init__.py", line 27, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/erpnextuser/mybench/apps/frappe/frappe/commands/site.py", line 309, in migrate
    skip_search_index=skip_search_index
  File "/home/erpnextuser/mybench/apps/frappe/frappe/migrate.py", line 67, in migrate
    frappe.modules.patch_handler.run_all(skip_failing)
  File "/home/erpnextuser/mybench/apps/frappe/frappe/modules/patch_handler.py", line 41, in run_all
    run_patch(patch)
  File "/home/erpnextuser/mybench/apps/frappe/frappe/modules/patch_handler.py", line 30, in run_patch
    if not run_single(patchmodule = patch):
  File "/home/erpnextuser/mybench/apps/frappe/frappe/modules/patch_handler.py", line 71, in run_single
    return execute_patch(patchmodule, method, methodargs)
  File "/home/erpnextuser/mybench/apps/frappe/frappe/modules/patch_handler.py", line 91, in execute_patch
    frappe.get_attr(patchmodule.split()[0] + ".execute")()
  File "/home/erpnextuser/mybench/apps/erpnext/erpnext/patches/v13_0/rename_issue_doctype_fields.py", line 47, in execute
    frappe.db.set_value('Opportunity', entry.name, 'first_response_time', mins_to_first_response, update_modified=False)
  File "/home/erpnextuser/mybench/apps/frappe/frappe/database/database.py", line 667, in set_value
    values, debug=debug)
  File "/home/erpnextuser/mybench/apps/frappe/frappe/database/database.py", line 146, in sql
    self._cursor.execute(query, values)
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/pymysql/connections.py", line 725, in _read_packet
    packet.raise_for_error()
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/erpnextuser/mybench/env/lib/python3.6/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'first_response_time' in 'field list'")

**Pull request closed without merging**
