### PR TITLE
Remove party_account_currency from Customer and Supplier, and use currency derived from get_party_account

### PR DESCRIPTION
**Pull request by anandpdoshi**

### CODE REVIEW

**Comment by nabinhait** [comment]
Add a validation in gl_entry.py to ensure transactions for one party can only be made in one currency. Now user can select default receivable accounts in multiple currency for a single party.

**Comment by anandpdoshi** [comment]
@nabinhait Why should that be? Let anyone create multiple accounts for the same party with different currencies if they want to.

**Comment by nabinhait** [comment]
@anandpdoshi in that case, which currency you should consider in reports
like accounts receivable /  payable etc. If you want party's outstanding
balance in which currency it should be?

**Comment by anandpdoshi** [comment]
Show separate row for each account of party.

**Pull request merged**
