### PR TITLE
fix: fiscal year can be shorter than 12 months

### PR DESCRIPTION
**Pull request by barredterra**
Frontport of #23497.

Additional changes:

- Replace unnecessary SQL query in `fiscal_year.get_from_and_to_date()`
- JS used to set `year_end_date` to 12 months after `year_start_date`. Disable this for short years.
- `year_start_date` and `year_end_date` used to be editable and made read_only via JS. Remove the related js code and enable `set_only_once` for these fields.

Bildschirmfoto 2020-11-05 um 12 55 59

### CODE REVIEW

**Comment by rohitwaghchaure** [comment]
@barredterra travis failing

**Review by nabinhait — APPROVED** [review]

**Comment by martinhbramwell** [comment]
Creation of new fiscal year fails with:

```
AttributeError: 'FiscalYear' object has no attribute 'is_short_year'
```

**Comment by barredterra** [comment]
@martinhbramwell please create a new issue with a full stack trace and/or instructions how to reproduce this. Thanks in advance!

**Comment by martinhbramwell** [comment]
https://github.com/frappe/erpnext/issues/24232

**Pull request merged**
