### PR TITLE
feat: Employee reminders

### PR DESCRIPTION
**Pull request by NagariaHussain**
- [x] New Reminders Section in HR Settings
- [x] Work Anniversary Reminders
- [x] Holiday Reminders

Screenshot 2021-08-24 at 2 55 29 PM

Show a warning in case a change in frequency of holiday reminders will lead to missing reminders for a date range:

https://user-images.githubusercontent.com/34810212/118953441-70875c80-b97a-11eb-8a12-489e5cb66318.mp4

Refactoring:

1. New `employee_reminders` and `test_employee_reminders` modules
2. is_holiday: "Explicit is better than implicit"
3. get_holidays_for_employee 
4. HR Settings Reminders Section
5. Holiday Reminders on the day of the event was removed in: https://github.com/frappe/erpnext/pull/25735/commits/836dfffc3093d5af16be5e85426e965a22e7ef21

Tests:

1. is_holiday: Previously there were no explicit tests for this function
2. Reminder emails
 
`no-docs` (temp)

### CODE REVIEW

**Comment by ruchamahabal** [comment]
Keep alive

**Comment by NagariaHussain** [comment]
😎 Keep alive!

**Review by pateljannat — APPROVED** [review]

**Comment by chechani** [comment]
Excellent ! Should be extended to Contacts

**Comment by michellealva** [comment]
@NagariaHussain can the reminders be only sent to active employees? I guess right now it is sent even to the inactive ones.

**Pull request merged**
