### PR TITLE
fetch queries for the students in the student group

### LINKED ISSUE #9143: Fetch query for the student link in student group
Only the students enrolled to a particular program should come in student link field

### PR DESCRIPTION
**Pull request by manassolanki**
fixes https://github.com/frappe/erpnext/issues/9143

### CODE REVIEW

**Comment by mbauskar** [comment]
@manassolanki codacy build failed, please commit the changes and reopen the PR

**Comment by manassolanki** [comment]
@mbauskar Done one change and SQL injection is handled by the frappe.db.sql

**Comment by rmehta** [comment]
@manassolanki frappe.db.sql only escapes when you use comma (,) for substitution instead of `%`

Try using {0} type formatting for non escaped and then use comma (,)

**Comment by manassolanki** [comment]
Done changes

**Review by mbauskar — APPROVED** [review]

**Pull request merged**
