### PR TITLE
Item Alternate Image Features in e-commerce site.

### PR DESCRIPTION
**Pull request by Solufyin**
Hello @nabinhait
Added Item Alternate Image Features in e-commerce site.

As per your changed request #12709 We have developed Item Alternate Image Features.
We keep both features in single doctype. Slideshow and Item alternate image functionality shown in e-commerce site.

**The User can use two alternative choices:**
1) If user is select slideshow option in slideshow dropdown then user is able to see **slideshow functionality** in e-commerce site.

slideshow1

2) If user is not select slideshow option in slideshow dropdown then a user is able to see **Item Alternate Image functionality** in e-commerce site.

We configured images in slideshow item doctype in below snapshot:
con

**Please find attached video for more information:**

[item_alternate_image.mp4.zip](https://github.com/frappe/erpnext/files/2231523/item_alternate_image.mp4.zip)

Thanks

### CODE REVIEW

**Comment by jigneshpshah** [comment]
@netchampfaris , @nabinhait  any updates on this , eager to see this getting merged.

**Comment by federicocalvo** [comment]
Hi, it is in V11 roadmap merge? Thanks

**Comment by federicocalvo** [comment]
Hi @Solufyin , @nabinhait , it is not clear if this issue is blocked by some aspect of code or if it is for some other reason, to be able to collaborate with this issue.

**Comment by 1ubuntuuser** [comment]
@Solufyin This looks like a nice addition. Are you using it for your own customers? @nabinhait why did you close this?

**Pull request closed without merging**
