### PR TITLE
[Minor] Project in Purchase Order, Purchase Invoice and Purchase Receipt

### PR DESCRIPTION
**Pull request by KanchanChauhan**

### CODE REVIEW

**Comment by dottenbr** [comment]
We noticed that the Project Dashboard has those DocTypes in it but the DocTypes don't have the Project field to link them. We believe they should!

screen shot 2018-03-26 at 3 58 41 pm

**Comment by nabinhait** [comment]
Project field is already there in Item table of those doctypes. We just have to fix the linking in the Project dashboard.

**Comment by KanchanChauhan** [comment]
@nabinhait Why is it on Item since it is on doctype level in other doctypes like Sales Order, Production Order. May be it can be on doctype level as well.

**Comment by nabinhait** [comment]
Because in purchase cycle, we can buy materials together for multiple projects for getting better deal from supplier. But in sales cycle, it is in our hand.

**Pull request closed without merging**
