### PR TITLE
fix: Offline pos fix

### PR DESCRIPTION
**Pull request by hrwX**
Offline POS Item Groups, Search Item and Load More Items fix.

pos-fix

### CODE REVIEW

**Comment by jaqobk** [comment]
Thank you @hrwX I was facing this issue and had reported it here>>

https://github.com/frappe/erpnext/issues/16357

Hope it shall be merged soon

**Review by netchampfaris — APPROVED** [review]

**Comment by jaqobk** [comment]
hi,
I did a bench update but the problem still exists.
Kindly help...

**Comment by Muzzy73** [comment]
Fix is in V11.03 Check your version. Maybe you are using V10. @jaqobk

**Comment by jaqobk** [comment]
Hi guys am facing this issue again after upgrading to version 12.. what could be the issue now..

I had this issu in january too and this commit fixed my issue then.

kindly help

**Pull request merged**
