### PR TITLE
Update share_balance.json

### LINKED ISSUE #39891: Change types of field in Share Balance
### Information about bug

rate and amount should be currency and not int. 

https://github.com/frappe/erpnext/blob/22291d32e6dfee445b15a2519e111a781b73abd5/erpnext/accounts/doctype/share_balance/share_balance.json#L202

https://github.com/frappe/erpnext/blob/22291d32e6dfee445b15a2519e111a781b73abd5/erpnext/accounts/doctype/share_balance/share_balance.json#L83

### Module

accounts

### Version

latest

### Installation method

None

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by tinodj**
fix #39891

rate and amount should be Currency and not Int.

> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

### CODE REVIEW

**Comment by tinodj** [comment]
hey please merge/fix this. Thank you!

**Comment by tinodj** [comment]
hey please merge/fix this. Thank you!

**Comment by deepeshgarg007** [comment]
@tinodj You have directly updated the values in the JSON file. Please update the field type using UI or update the modified timestamp and then reopen the PR.

**Comment by tinodj** [comment]
hmm... I am sorry, I am new to this. Can you please let me know what means 'update the field type using UI'. Can you please instruct/send me some links where I can read about it?

**Pull request closed without merging**
