### PR TITLE
Nameing series generate [HASH] with prefix

### PR DESCRIPTION
**Pull request by artykbasar**
This modification is needed to support the change on the core naming series change:
https://github.com/frappe/frappe/pull/13665/commits/dc96cc92c6b716433278f2cf58ce173c3cb7910a

### CODE REVIEW

**Comment by artykbasar** [comment]
Please let me know if you will need any information for this pull request to get approved

**Comment by ankush** [comment]
Thanks for your contribution!


- Check sider errors. Should be fixable by using raw strings for regex - `r'...'`
- make your commit message semantic. `git commit --amend` and force push.
- wait till Frappe PR is reviewed/merged.

**Comment by artykbasar** [comment]
Thanks for your reply @ankush.
> Thanks for your contribution!
> 
> * Check sider errors. Should be fixable by using raw strings for regex - `r'...'`

should I add that raw string sign even original code is without that sign.

> * wait till Frappe PR is reviewed/merged.

I will let you know as soon as frappe PR is approved.

**Comment by ankush** [comment]
>should I add that raw string sign even original code is without that sign.

Yeah, as long as the intended behaviour is the same, not a problem!

**Pull request closed without merging**
