### PR TITLE
Daily Reminder

### PR DESCRIPTION
**Pull request by renzodemie**
This PR is related to #3466

**Creating new project**
p1 - create project

**Receiving email to update**
p2 - update project

**Receiving daily**
p3 - summary

### CODE REVIEW

**Comment by Olawale1** [comment]
Hi @renzodemie 

This is really great work! Will the log of project updates also be available directly in the project document?

Kind regards,

**Comment by renzodemie** [comment]
hello @Olawale1 

What we did is we linked the project updates in the Dashboard of Project Doctype.

**Comment by Olawale1** [comment]
Hi @renzodemie ,

That's Awesome! We really look forward to this getting merged as soon as possible 

Well done!

**Comment by renzodemie** [comment]
That's great to hear @Olawale1

**Pull request merged**
