### PR TITLE
Invoice round off does not get reflected in accounts #8816

### PR DESCRIPTION
**Pull request by sathishpy**
rounding-fix-test

### CODE REVIEW

**Comment by sathishpy** [comment]
Can someone help me in fixing the travis build failure? It looks like 'bench run-ui-tests --app erpnext' failed, but not clear which specific test. I have previously tried to run all the tests under account module, but couldn't find how to do the same. Any help here is greatly appreciated.

**Comment by sathishpy** [comment]
Still working on fixing the test failures

**Comment by sathishpy** [comment]
Re-opening the pull request as most of the issues are resolved. Also expecting some help from others since this is my first pull request.

**Comment by sathishpy** [comment]
I have managed to fix the last test failure, will re-open after pushing that.

**Comment by sathishpy** [comment]
@nabinhait 
Could you please take a look at these changes and give your feedback/merge the changes

**Comment by sathishpy** [comment]
I don't know how I could have avoided all the changes related to rebasing my repo with upstream polluting this pull request. If there is any way to undo them, please do let me know

**Comment by sathishpy** [comment]
All tests are passing in my test setup, so not sure why travis build failed. Closing and re-opening to check whether it is transient. 
spoojary@osboxes:~/test-bench$ bench run-tests --doctype "Sales Invoice"
........................................
----------------------------------------------------------------------
Ran 40 tests in 26.468s

OK
spoojary@osboxes:~/test-bench$ bench run-tests --doctype "Purchase Invoice"
....................
----------------------------------------------------------------------
Ran 20 tests in 12.329s

OK

Also adding a screenshots of my testing.
invoice-roundig

**Comment by nabinhait** [comment]
@sathishpy I have fixed those test cases in the latest release. Can you please rebase and push again?

**Comment by sathishpy** [comment]
Hi @nabinhait,
Did you manage to get some time to take a look at this one? I have done the rebasing and all the server tests have passed. However there is a client test failure, which isn't as clear as server test. I have trouble even running them on my setup. Really appreciate your time here.

**Comment by sathishpy** [comment]
To keep others informed, there was some issue with the merge process, but we are working on it to resolve the same.

**Comment by nabinhait** [comment]
Sent a new PR #11542 for this

**Pull request closed without merging**
