### PR TITLE
Allow Zero Valuation Rate in Material Request

### PR DESCRIPTION
**Pull request by jcbdigitalhub**
#14666 

- [x] Have you followed the guidelines in our Contributing document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?
- [x] Have you lint your code locally prior to submission?
- [x] Have you successfully run tests with your changes locally?
- [x] Does your commit message have an explanation for your changes and why you'd like us to include them?
- [ ] Docs have been added / updated
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Did you modify the existing test cases? If yes, why?

---

What type of a PR is this? 

- [ ] Changes to Existing Features
- [ ] New Feature Submissions
- [x] Bug Fix
- [ ] Breaking Change

--- 

- Motivation and Context (What existing problem does the pull request solve):
- Related Issue:  #14665 Material Request cannot proceed to create Stock Entry for items with zero valuation rate.
- Screenshots (if applicable, remember, a picture tells a thousand words): 

**Please don't be intimidated by the long list of options you've to fill. Try to fill out as much as you can. Remember, the more the information the easier it is for us to test and get your pull request merged** :grin:

### CODE REVIEW

**Comment by nabinhait** [comment]
@osstechnolab Can you please explain the purpose of this field in Material Request level?

**Comment by osstechnolab** [comment]
@nabinhait Error occurs when creating stock entry from material requests for items with zero valuation rate.  The make_stock_entry does not update the allow_zero_valuation_rate thus stock entry not allowing it to be created.

**Comment by nabinhait** [comment]
In that case, the user creating Stock Entry can check "Allow Zero Valuation Rate" there. How the user who is creating Material Request will know that he/she needs to check "Allow Zero Valuation Rate"?

**Comment by osstechnolab** [comment]
@nabinhait The user will not know from material request.  But the thing is the make stock entry cannot proceed from material request.  Another option is to remove validation of zero valuation rate from material request.

**Comment by nabinhait** [comment]
OK, I understand the issue now, but adding the field is not the proper solution. Can you please raise a github issue for this? We will push a fix.

**Comment by osstechnolab** [comment]
#14665

**Pull request closed without merging**
