### PR TITLE
fix: Subcontracting Receipt has no reference field for Purchase Order

### PR DESCRIPTION
**Pull request by Ninad1306**
Issue from PR: https://github.com/frappe/erpnext/commit/4f8a8a5e9901e3a3b8f24d195f1354e833648e3e

Screenshot 2024-11-07 at 4 42 43 PM

### CODE REVIEW

**Comment by rohitwaghchaure** [comment]
@Mergifyio backport version-14

**Comment by nikitadattapawar06** [comment]
I'm encountering the same error on my cloud instance of ERPNext. How can I resolve this issue for erpnext which is hosted on cloud?

**Comment by Ninad1306** [comment]
> I'm encountering the same error on my cloud instance of ERPNext. How can I resolve this issue for erpnext which is hosted on cloud?

When the fix is released in next release cycle then update your cloud instance of ERPNext.

**Comment by nikitadattapawar06** [comment]
Ok thank you for your reply
Could anyone provide more information about the release schedule or any approx release schedule

**Comment by Ninad1306** [comment]
This fix has been released in [v14.75.2](https://github.com/frappe/erpnext/releases/tag/v14.75.2).

**Comment by nikitadattapawar06** [comment]
Ok thank you

**Comment by Ponyooooo** [comment]
thank you. When will this be released on the frappe cloud?

**Comment by Ninad1306** [comment]
It is released there also, you have to update the app.

**Pull request merged**
