### PR TITLE
feat(marketplace): seller profile page

### PR DESCRIPTION
**Pull request by karthikeyan5**
- [x] added a link to seller profile from the Item page
- [x] seller featured items: sellers can now feature upto 8 items on their profile
- [x] added customer review and product view stats on the seller profile page

Screenshots:

- link to seller profile and seller profile
try 6

- Managing Featured Items
try2 - 1

### CODE REVIEW

**Comment by netchampfaris** [comment]
@karthikeyan5 Screenshots/GIF of these pages in action?

**Comment by karthikeyan5** [comment]
GIF of the features have been added.

**Comment by rmehta** [comment]
@karthikeyan5 looks good. Is there a related Hub PR that needs to be merged?

**Review by rmehta — APPROVED** [review]

**Comment by karthikeyan5** [comment]
Yes, there is a Hub PR.
https://github.com/erpnext/hub/pull/51

**Pull request merged**
