### PR TITLE
fix(pr): set advace Payment status based on Payment Request status

### LINKED ISSUE #40642: Wrong advance payment status in edge case
### Information about bug

** Prepare Diff **
```diff
diff --git a/erpnext/controllers/status_updater.py b/erpnext/controllers/status_updater.py
index e5f341fc25..70124a8584 100644
--- a/erpnext/controllers/status_updater.py
+++ b/erpnext/controllers/status_updater.py
@@ -201,6 +201,8 @@ class StatusUpdater(Document):
 						},
 					):
 						self.status = s[0]
+						if self.status == "To Pay" and self.doctype == "Sales Order":
+							import pdb; pdb. set_trace() 
 						break
 				elif getattr(self, s[1])():
 					self.status = s[0]
```

**Trigger Diff**

```ipython
In [1]: pr = frappe.get_doc("Payment Request", "ACC-PRQ-2024-02549")

In [2]: pr.set_as_paid()

-> break
(Pdb) w

-> pr.set_as_paid()
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py(289)set_as_paid()
-> self.make_invoice()
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/erpnext/erpnext/accounts/doctype/payment_request/payment_request.py(233)make_invoice()
-> si.submit()
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/frappe/frappe/utils/typing_validations.py(31)wrapper()
-> return func(*args, **kwargs)
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/frappe/frappe/model/document.py(1045)submit()
-> return self._submit()
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/frappe/frappe/model/document.py(1028)_submit()
-> return self.save()
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/frappe/frappe/model/document.py(335)save()
-> return self._save(*args, **kwargs)
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/frappe/frappe/model/document.py(388)_save()
-> self.run_post_save_methods()
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/frappe/frappe/model/document.py(1128)run_post_save_methods()
-> self.run_method("on_submit")
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/frappe/frappe/model/document.py(959)run_method()
-> out = Document.hook(fn)(self, *args, **kwargs)
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/frappe/frappe/model/document.py(1319)composer()
-> return composed(self, method, *args, **kwargs)
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/frappe/frappe/model/document.py(1301)runner()
-> add_to_return_value(self, fn(self, *args, **kwargs))
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/frappe/frappe/model/document.py(956)fn()
-> return method_object(*args, **kwargs)
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/erpnext/erpnext/accounts/doctype/sales_invoice/sales_invoice.py(468)on_submit()
-> self.update_against_document_in_jv()
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/erpnext/erpnext/controllers/accounts_controller.py(1498)update_against_document_in_jv()
-> reconcile_against_document(lst, active_dimensions=active_dimensions)
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/erpnext/erpnext/accounts/utils.py(543)reconcile_against_document()
-> frappe.get_doc(t, n).set_total_advance_paid()
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/erpnext/erpnext/controllers/accounts_controller.py(1904)set_total_advance_paid()
-> self.set_advance_payment_status(advance_paid, order_total)
  /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/erpnext/erpnext/controllers/accounts_controller.py(1932)set_advance_payment_status()
-> self.set_status(update=True)
> /home/blaggacao/src/gitlab.com/pristina/infraestructura/apps/erpnext/erpnext/controllers/status_updater.py(206)set_status()
-> break
```

### Observed

- `set_as_paid` does end up setting the originating SO as "To Pay"

### Expected

- `set_as_paid` does **not** end up setting the originating SO as "To Pay"

### PR DESCRIPTION
**Pull request by blaggacao**
fix: https://github.com/frappe/erpnext/issues/40642

fixup for: https://github.com/frappe/erpnext/pull/38560

@ruthra-kumar 

---

EDIT

How to validate the sequence:

- Checkout the commit of the first test failure and run
  ```
  bench run-tests --doctype "Purchase Order" --test test_purchase_order_advance_payment_status
  ```
- Checkout its fix and run the command again
- Checkout the second test failure and run:
  ```
  bench run-tests --doctype "Sales Order" --test test_sales_order_advance_payment_status
  ```
- Checkout its fix and run  the command again

Keep the first commit as without it, individual tests can't be run manually with the above commands.

### CODE REVIEW

**Comment by blaggacao** [comment]
@ruthra-kumar This needed a little bit more refactoring, but it should be considered a hotfix to the prior PR.

There where several scenarios not captured by `on_submit` that are now captured by `on_change`.

**Comment by ruthra-kumar** [comment]
@blaggacao 

Can you provide a simple scenario with the expected and current outcome to better understand the edge case? Details in https://github.com/frappe/erpnext/issues/40642 is insufficient.

**Comment by blaggacao** [comment]
@ruthra-kumar a `pr.set_as_paid()` should never end up triggering the following changes:

1.  `so.advance_payment_status = "To Pay"` ->  `so.advance_payment_status = "Paid"`
2.  `so.advance_payment_status = "Paid"` ->  `so.advance_payment_status = "To Pay"`

It *must* not do the second transition.

However, the second transition is triggered on the condition:
- An invoice "steals" the _Payment Entry_ from the SO
- This leaves the SO without advance payment entries
- Consequentially the `advance_payment_status` gets reset in the second step above (only) in the presence of https://github.com/frappe/erpnext/pull/37069/files#diff-ec41388db21239d04370bada0b1e4df5b7b620771895a14adc9ac8f214e4099dR656-R660


Now, this PR implements a more reliable status inference for the `advance_payment_status` solely on the stati of associated _Payment Request_ which are immune against _Payment Entry_ "stealing" by the Sales Invoice.

Is this complicated? Yes. :smile:

**Comment by blaggacao** [comment]
I've prepared https://github.com/frappe/erpnext/pull/40837 - I can't test locally, atm, (no reproducible test environment at hand), but with a bit of luck, it should trigger the observed issue on the original code.

**Comment by blaggacao** [comment]
qed: https://github.com/frappe/erpnext/actions/runs/8525409230/job/23352265277?pr=40837#step:13:274 (this is actually a second issue)

@ruthra-kumar

**Comment by ruthra-kumar** [comment]
> * An invoice "steals" the _Payment Entry_ from the SO

Do this happens on advance Payment Entries that book advance is a separate party account ('Book Advance Payments in Separate Party Account' enabled in Company master)?

**Comment by ruthra-kumar** [comment]
> However, the second transition is triggered on the condition:
> 
> * An invoice "steals" the _Payment Entry_ from the SO
> * This leaves the SO without advance payment entries
> * Consequentially the `advance_payment_status` gets reset in the second step above (only) in the presence of https://github.com/frappe/erpnext/pull/37069/files#diff-ec41388db21239d04370bada0b1e4df5b7b620771895a14adc9ac8f214e4099dR656-R660

Do this happens on advance Payment Entries that book advance is a separate party account (Book Advance Payments in Separate Party Account enabled in Company master)?

**Comment by blaggacao** [comment]
> Do this happens on advance Payment Entries that book advance is a separate party account (Book Advance Payments in Separate Party Account enabled in Company master)?

Nope, this was disabled:

image


Afaic, the "stealing" is a normal procedure to reassign payment entries from a SO to a SI.

See for example this remark on a PE:
```
Monto COP 134000.0 recibido de CUST-2024-00471
Referencia de la transacción nro ACC-PRQ-2024-02813 fechada 2024-03-21
Monto COP 134000.0 Sales Order contra SAL-ORD-2024-03067
```

But which is now only liked against the SI:

image

**Comment by blaggacao** [comment]
Here is some "in-flagranti" evidence of the "steal":

image

**Comment by ruthra-kumar** [comment]
It is not stealing per say 😄 . More like allocation is moved **from** SO/PO **to** SI/PI. Yes, this is normal.

**Comment by blaggacao** [comment]
I'm not sure why my prepared test doesn't trigger the problem. Maybe the move ("steal") is done asynchronously? 

This is already a week old and I have forgotten the exact details, assuming that the provided test cases and trace-back would be support enough. I can just assert that in our production instance we had the issue that "Paid" SOs re-appeared as "To Pay" upon payment creation.

**Comment by ruthra-kumar** [comment]
Now, the status appears to become unidirectional. Once the status reaches 'Fully Paid', if you cancel the associated Payment Entry, it is still in 'Fully Paid' status. Similar to https://github.com/frappe/erpnext/pull/38560#issuecomment-1904160206

This might require some more testing, will check on this more tomorrow.

**Comment by blaggacao** [comment]
At least in my test branch, now the move ("steal") isn't reproduced: https://github.com/frappe/erpnext/actions/runs/8526022102/job/23354354567?pr=40837#step:13:559

I don't know why, but if it where, we'd trigger the issue.

@ruthra-kumar maybe you just happen to know the necessary diff to the tests? I can then merge them here to proof that this PR at least fixes the reported issue(s).

**Comment by blaggacao** [comment]
@ruthra-kumar 

Ah, I know why: because `pr.set_as_paid()` is only invoked by `webshop`, here: https://github.com/frappe/webshop/blob/eb2f34c8f211d35a047fad5792671e58a1af4dfb/webshop/webshop/doctype/override_doctype/payment_request.py#L43

~~So without the presense of `webshop` we can't sensibly test this scenario.~~ Actually, [we can](https://github.com/frappe/erpnext/compare/d0364528742bc0440cff92cb7d1b58ea12c4759d..04ee681ee213be2f96ff1c449c242f2dfd20cd06)

As I've mentioned to you on other PR comments, I'm in the process of refactoring some of these interfaces with the goal of reaching a more robust payment infrastructure, because this is a significant source of issues in production for us. So we might need to advance here as one little step towards the bigger picture, because I can't yet present the final result in a waterfall-style, it also would be likely impossible to review.

**Comment by blaggacao** [comment]
ok, now we have a reproducer: https://github.com/frappe/erpnext/actions/runs/8526461301/job/23355760424?pr=40837#step:13:559

**Comment by blaggacao** [comment]
How to validate the sequence:

- Checkout the commit of the first test failure and run
  ```
  bench run-tests --doctype "Purchase Order" --test test_purchase_order_advance_payment_status
  ```
- Checkout its fix and run the command again
- Checkout the second test failure and run:
  ```
  bench run-tests --doctype "Sales Order" --test test_sales_order_advance_payment_status
  ```
- Checkout its fix and run  the command again

Keep the first commit as without it, individual tests can't be run manually with the above commands.

**Comment by blaggacao** [comment]
@ruthra-kumar 

> Now, the status appears to become unidirectional. Once the status reaches 'Fully Paid', if you cancel the associated Payment Entry, it is still in 'Fully Paid' status. 

Once an invoice has been created, and the payment has moved, the advance payment management has been forgone from Sales Team (tracking on SO) to Accounts Team (tracking on Invoice).

Consequentially, the references in the payment entry have moved from the SO to SI.

Therefore, when the PE is canceled, and since the PR references have **not** also moved to the SI (might be a bug), the PR is not updated.

But even if the PR was updated because the bug might have been fixed, then still the SO (and correctly so for the matter of the Sales domain) would remain "Fully Paid" since payment management has already passed down to Accounting (SI). The SO keeps the record of the historical state at the time of hand over.

This is correct. :green_circle: 

The PR not correctly updating might be an independent bug. I've marked the tests with a `# TODO` comment. This is ancient behavior, though.

Should we fix it, regarless at this occasion? - Absolutely! :exclamation:

**Comment by blaggacao** [comment]
@ruthra-kumar Please, let's find a proper hotfix for this soon. :pray: Please also let me know what you think on the legacy behaviour. In the interest of an expedite hotfix, we might also choose to delay that refactoring a bit?

**Comment by ruthra-kumar** [comment]
> Therefore, when the PE is canceled, and since the PR references have not also moved to the SI (might be a bug), the PR is not updated.

I disagree here. For most cases, Statuses are meant to be derived from other documents within the system. If a document is cancelled, it is should have effect on the status that relies on it. 

> Now, the status appears to become unidirectional. Once the status reaches 'Fully Paid', if you cancel the associated Payment Entry, it is still in 'Fully Paid' status. Similar to [#38560 (comment)](https://github.com/frappe/erpnext/pull/38560#issuecomment-1904160206)

However, this is not happening after your latest commit.

Rest of the change looks ok.

**Review by ruthra-kumar — APPROVED** [review]

**Comment by blaggacao** [comment]
> I disagree here.

I think, I can disagree with myself, too.

However, if my analysis is correct, then this requires some involved refactoring. Meaning that the move ("steal") would need to become a "copy" and the original references would need to be preserved.

Under that auspice, I disagree with myself and agree with you. :-)

Thanks for the merge! :handshake:

**Pull request merged**
