### PR TITLE
adding returns field to cashier closing

### PR DESCRIPTION
**Pull request by elba7r**
adding returns field to cashier closing as its important to add the ability to cashiers to write the amount of returns which has been made from their stations , this give the managers the ability to control and review the returns and prevent any mistakes can be happen in the case when the cashier make the return from his station and give the money back to the customer
Please read the pull request checklist to make sure your changes are merged: https://github.com/frappe/erpnext/wiki/Pull-Request-Checklist

### CODE REVIEW

**Comment by elba7r** [comment]
can u please merge this pull request as its important for wide range of users

**Comment by sagarvora** [comment]
@elba7r Why did you push this to the develop branch? It affects master branch too (staging when you created this PR).

Can you please make a PR to the hotfix for this changes?

**Comment by elba7r** [comment]
How can I do that, i tried from my fork but it does not find any changes to apply, can you advice ?

**Comment by sagarvora** [comment]
@elba7r You'll need to create a new branch

**Comment by elba7r** [comment]
i have opened a pull request ( fix adding return to cachier closing #16911 )

**Pull request merged**
