### PR TITLE
feat: allow arbitrary purchase order items (continued)

### PR DESCRIPTION
**Pull request by dj12djdjs**
Continuation of: https://github.com/frappe/erpnext/pull/33991

- [ ] Add setting to enable this feature in buying setting.
	- [ ] test: property setter doesn't conflict with existing property setters. (When enabling, and disabling the feature)

- [ ] test: purchase flow with feature enabled/disabled.

- [ ] add documentation including real world use case.

### CODE REVIEW

**Comment by casesolved-co-uk** [comment]
@dj12djdjs thanks for picking this up.

Note however my initial intention (and I have more code not shared) was to make this also applicable to sales transactions too.

So I would perhaps put the setting in accounts settings rather than buying?

I started with purchases so that acceptance might be easier.

I can perhaps merge and push my other changes to your PR?

**Comment by dj12djdjs** [comment]
@casesolved-co-uk That would be much appreciated, I've granted you write permission to my fork.

**Comment by SvbZ3r0** [comment]
Looking at how long the development for this feature has been going on, I'm worried my fix for this issue on the Sales and Quotations (#33430) side of the coin might have overlooked quite a few things. The only change I made was to mark the `item_code` field non-mandatory. 
Would you guys care to take a look?

**Comment by casesolved-co-uk** [comment]
Active 🙄

**Pull request closed without merging**
