### PR TITLE
fix: Bank clearance for case loan (disburstment/repayment)

### PR DESCRIPTION
**Pull request by kittiu**
This PR ensure that Bank Clearance and Bank Clearance Summary Report will work with Loan Disburstment.

### CODE REVIEW

**Comment by kittiu** [comment]
Hi, this is my first PR here. In fact, I am using V14, so should I push this PR to Version-14 ?

**Comment by kittiu** [comment]
Please close this for https://github.com/frappe/erpnext/pull/34587

**Comment by kittiu** [comment]
@deepeshgarg007 now, including both disburstment and repayment.

**Review by deepeshgarg007 — APPROVED** [review]

**Comment by kittiu** [comment]
Cool 😘

**Pull request merged**
