### PR TITLE
fix: select sal comp while making sal struct

### PR DESCRIPTION
**Pull request by AfshanKhan**
While making salary structure salary components didn't use to fetch correctly. Changed the query for the same.

### CODE REVIEW

**Review by Anurag810 — APPROVED** [review]

**Comment by muchai** [comment]
Can I chip on this please. Not sure why the filter for salary component on salary structure, filters for company. However, I see a small problem with this.

On Salary component, the accounts section is only visible, based on this condition: eval:doc.statistical_component != 1

It means, if you want to use statistical salary components on Salary Structure, it's won't be possible to select them.

I could be missing more information.

**Comment by AfshanKhan** [comment]
Hi @muchai yeah, you are right. This will solve that issue https://github.com/frappe/erpnext/pull/24424. Thanks for your input.

**Comment by muchai** [comment]
Hi @AfshanKhan seen the changes, tested but still one cannot select statistical components. I think the filter should return for company, or all if company not set on the salary component.

**Comment by AfshanKhan** [comment]
> Hi @AfshanKhan seen the changes, tested but still one cannot select statistical components. I think the filter should return for company, or all if company not set on the salary component.

Hi @muchai this is intentional. The company should be added to the component. Just as a precaution. And this is something a user can add if not present.

**Comment by muchai** [comment]
> > Hi @AfshanKhan seen the changes, tested but still one cannot select statistical components. I think the filter should return for company, or all if company not set on the salary component.
> 
> Hi @muchai this is intentional. The company should be added to the component. Just as a precaution. And this is something a user can add if not present.

Ok. Then the query doesn't still return statistical components. Even the most recent update.

**Comment by AfshanKhan** [comment]
> > > Hi @AfshanKhan seen the changes, tested but still one cannot select statistical components. I think the filter should return for company, or all if company not set on the salary component.
> > 
> > 
> > Hi @muchai this is intentional. The company should be added to the component. Just as a precaution. And this is something a user can add if not present.
> 
> Ok. Then the query doesn't still return statistical components. Even the most recent update.

Check this one https://github.com/frappe/erpnext/pull/24430 If still your statistical components are not returned then maybe they aren't configured correctly

**Comment by muchai** [comment]
> > > > Hi @AfshanKhan seen the changes, tested but still one cannot select statistical components. I think the filter should return for company, or all if company not set on the salary component.
> > > 
> > > 
> > > Hi @muchai this is intentional. The company should be added to the component. Just as a precaution. And this is something a user can add if not present.
> > 
> > 
> > Ok. Then the query doesn't still return statistical components. Even the most recent update.
> 
> Check this one #24430 If still your statistical components are not returned then maybe they aren't configured correctly

Had tried that one. Will check the configurations.

**Comment by muchai** [comment]
Please check on this too: https://github.com/frappe/erpnext/issues/24411

**Comment by Ponyooooo** [comment]
is it correct that this is still not solved? the company filter on the salary structure is the cause of this since when a salary component is a statistical component the user should not provide or encode the default account which ofcourse you will also not need to encode the company. I think the statistical component feature is not doing its job to be added to the salary structure and will not be encoded to a journal entry.

**Pull request merged**
