### PR TITLE
feat: copy emails from lead to customer

### PR DESCRIPTION
**Pull request by barredterra**
When creating a new **Customer** from a **Lead** and _Carry Forward Communication and Comments_ is enabled in **CRM Settings**, then copy communication from **Lead** to **Customer**.

How to test this:

1. Create a new **Lead**
2. Send an email from the **Lead** form (say, to the lead)
3. Klick on Create > Customer, save
4. The email should be visible in the **Customer**'s _Activity_

> no-docs

(will add after merge)

### CODE REVIEW

**Comment by barredterra** [comment]
Unrelated unit test failing (fails on many unrelated PRs)

**Review by deepeshgarg007 — APPROVED** [review]

**Comment by deepeshgarg007** [comment]
@Mergifyio update

**Comment by barredterra** [comment]
The failing unit test is unrelated (fails on other PRs as well)

**Comment by deepeshgarg007** [comment]
@Mergifyio update

**Pull request merged**
