### PR TITLE
feat: maximum overdue invoice count limit

### PR DESCRIPTION
**Pull request by rtdany10**
image

https://github.com/frappe/erpnext/assets/52111700/ec27711c-d72f-45b0-a174-ce83dae78af1

This PR enables a configurable setting to validate against overdue invoices before billing a customer.

### CODE REVIEW

**Comment by bosue** [comment]
Nice, I‘m in favor of implementing rules for a delivery stop, and this may be a quite lean implementation of it.

However, two invoices of EUR 100 each, overdue by a day, would have the same effect as two invoices of EUR 20.000 that have been overdue since last year. On the other hand, a single invoice of EUR 100.000 overdue since last year wouldn‘t stop further delivery.

You can tweak it up or down, but by the single count of invoices overdue, you’ll always have false-positives, false-negatives, or both.

Thus I think these rules need to take into account more aspects, such as amount overdue, time overdue, the overall credit rating, the additional amount requested etc.

And I think the correct and most flexible way to go would be based on #37195. First step would be extending scorecards to customers. Then, if usability and thus reliability currently isn‘t sufficient, we need to improve UX and maybe even add user-facing model testing features.

In any case, by just blocking the invoice we’d be just a bit too late in the process. We wouldn‘t solve the problem that the late-paying customer shouldn‘t have additional goods being shipped to, and now that they are shipped, we need to send an invoice as well. Thus we have to make sure outstanding bills lead to the customer not being supplied in the first case.

@rtdany10: I‘m happy to work with you to make sure your specific use case is perfectly covered!

**Comment by rtdany10** [comment]
My specific use case here is blocking another invoice from being raised if there is/are overdue invoice(s) pending against the party. The invoice value doesn't come into play here. If you want to involve that as well, we have credit limit set against customer for the same.
This is actually a common requirement. @bosue

**Comment by bosue** [comment]
@rtdany10: From your words I can hear your disappointment. I‘m so sorry about that.

In the github tracker here it‘s quite a big problem that you‘ll typically receive one response or none at all. That one response will be that person‘s viewpoint. Others may have a different opinion, but they‘ll never weigh in, so if you‘re not stubborn enough, your PR will fall stale.

Again I‘m convinced that blocking further invoices is a step too late, because once delivered, goods must be billed, no matter whether the customer is creditworthy or not. Also from my business experience, people very often pay late, and you wouldn‘t necessarily block any further sales just because some 5 Euro may be overdue vor a few days. Or you would require prepayment.

But my own experience may not represent business mainstream, so if someone else thinks that lean implementation will cover some 70% of all use cases, that‘s fine.

**Comment by rtdany10** [comment]
> Again I‘m convinced that blocking further invoices is a step too late, because once delivered, goods must be billed, no matter whether the customer is creditworthy or not.

Agreed, but not everyone follows that cycle, there is another cycle where goods are delivered after invoicing which is where this PR brings in a validation.

**Comment by rtdany10** [comment]
> @rtdany10: From your words I can hear your disappointment. I‘m so sorry about that.

Not really, was actually happy to see your suggestion. But extending the scorecard is something big and will take a lot of time. But since the functionality of this PR is a common one, at least in the region that we serve, I would rather have this as an addition instead of waiting for the bigger feature addition.

**Comment by bosue** [comment]
> > Again I‘m convinced that blocking further invoices is a step too late, because once delivered, goods must be billed, no matter whether the customer is creditworthy or not.
> 
> Agreed, but not everyone follows that cycle, there is another cycle where goods are delivered after invoicing which is where this PR brings in a validation.

> But extending the scorecard is something big and will take a lot of time. But since the functionality of this PR is a common one, at least in the region that we serve, I would rather have this as an addition instead of waiting for the bigger feature addition.

I see. Let‘s put the big flexible solution aside and focus on the minimum viable product.

I can see South Asia being overrepresented in ERPNext‘s user base, but I‘m not so sure this is a regional difference. The percentage may vary, but companies all around the world do invoice either ahead of delivery – mostly if expecting advance payment – or with the delivery or after the delivery.

When insisting on advance payment before a good even gets picked from the warehouse, there‘s no credit risk, so neither overdue invoices nor a maxed out credit limit would be a reason not to deliver goods after being payed in advance.

If your cycle, however, is invoicing with delivery, which I expect to be the standard B2B case in any region of the world, then you don‘t want a Sales Order to proceed at all until creditworthyness is restored. So you’ll want any Sales Order to be put on _hold_, only allowing payment requests or actually outright advance payment invoices to proceed.

It remains my firm conviction an I hope you can see, too, that the current logic is at least slightly flawed for many companies, whether South Asian or European or North American ones. Sure, these companies may just not use the functionality at all or fix the logic with their own custom code, while the subset you‘re targeting may be happy with it.

And of course we may do followups. It‘s not like there‘s any major harm being done, as long as the admin is aware of the solution‘s limitations.

I just hoped we may discuss the logic of it so we can figure out a solution. But if that‘s not possible or wished, I‘ll certainly stop insisting. It‘s not like I‘d enjoy running against a wall…

**Comment by bosue** [comment]
Bump.

**Comment by rtdany10** [comment]
Adding a server script seem to be a better way out.
Whoever needs this can add a server script on validate of SO/SI/DN.

**Pull request closed without merging**
