### PR TITLE
fix: Don't allow negative amount on Payment Request #41905

### PR DESCRIPTION
**Pull request by hiteshprajapati**
image

### CODE REVIEW

**Comment by hiteshprajapati** [comment]
@deepeshgarg007 @ruthra-kumar : is anything missing in this change?

**Comment by ruthra-kumar** [comment]
@hiteshprajapati 
The Payment Request with a -ve amount in the screenshot, could you describe how that value came to be? Can you provide a simple replicable scenario?

**Comment by hiteshprajapati** [comment]
> @hiteshprajapati The Payment Request with a -ve amount in the screenshot, could you describe how that value came to be? Can you provide a simple replicable scenario?

@ruthra-kumar : I am not sure whether I understand your question correctly. 
About the screenshot, it is taken while creating payment request with -ve amount after making the code changes locally. Its new Payment Request and not the existing one and when I hit the save button, non-negative validation error returned by framework due to my changes

**Comment by hiteshprajapati** [comment]
> > @hiteshprajapati The Payment Request with a -ve amount in the screenshot, could you describe how that value came to be? Can you provide a simple replicable scenario?
> 
> @ruthra-kumar : I am not sure whether I understand your question correctly. About the screenshot, it is taken while creating payment request with -ve amount after making the code changes locally. Its new Payment Request and not the existing one and when I hit the save button, non-negative validation error returned by framework due to my changes

@ruthra-kumar : could you please provide your thoughts ? Its been here for a while

**Comment by ruthra-kumar** [comment]
@hiteshprajapati 

From the screenshot, it looks like payment request is made against purchase order. But -ve purchase orders are not possible. So, how was the PO made?

**Comment by hiteshprajapati** [comment]
> @hiteshprajapati
> 
> From the screenshot, it looks like payment request is made against purchase order. But -ve purchase orders are not possible. So, how was the PO made?

@ruthra-kumar : Yes, the payment request is made against the purchase order. But you can edit the amount while creating payment request from PO. Please refer this screenshot

https://github.com/user-attachments/assets/3ed2ec6a-0366-4ab8-8477-73b8cccc2360

**Review by ruthra-kumar — APPROVED** [review]

**Pull request merged**
