### PR TITLE
fix: disallow stock-in of same/duplicate serial number

### LINKED ISSUE #31787: [Stock] Duplicate Serial No allowed in Purchase Receipt
### Information about bug

Steps to reproduce:
1. Create a Purchase Receipt with a serial number
2. Create a Delivery Note against that serial number
3. Create a Purchase Receipt against the same serial number again

https://user-images.githubusercontent.com/52111700/183251124-59917452-92a1-4823-89ac-a9b0c192597d.mp4

### Module

stock

### Version

ERPNext: v13.20.1 (HEAD)
Frappe Framework: v13.20.1 (HEAD)

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by rtdany10**
Major issue.
Steps to reproduce and video attached in the linked issue.

Closes #31787

### CODE REVIEW

**Comment by rtdany10** [comment]
We need a patch to fix affected transaction but I have clue on how to proceed with it.
Maybe split the duplicate serial number based on number of inward entries and make the change in SLEs and other documents? But then we again can't figure out which serial number was stock out in which document.

Little help here please

**Comment by rohitwaghchaure** [comment]
@rtdany10 this is not an issue, this behaviour was added intentionally to handle a use case where customer purchase same serial number multiple times. With this behaviour you can only be able to purchase the delivered serial nos only.

**Comment by rohitwaghchaure** [comment]
@rtdany10 To track the serial no's documents you can check the report Serial No Ledger
115990960-b18e8a00-a5e3-11eb-90fe-ac2f82c7267d

**Comment by rohitwaghchaure** [comment]
@rtdany10 This use case was required for Intra Company transactions,
For example there are 3 branches A, B, C in one company
1) Branch A has purchased serial no SN-0001 and delivered to Branch B
2) Now Branch B wants to make purchase entry for the same serial no SN-0001 and wants to deliver to Branch C

Here customer was expecting same serial nos was purchase multiple times, also if you tried to cancel backdated transaction for the serial no SN-0001 then system won't allow you to cancel it and throw the below error

image

**Comment by rohitwaghchaure** [comment]
@rtdany10 Could you close the PR?

**Comment by rtdany10** [comment]
@rohitwaghchaure 
What happens when there is a Sales Return? I can't cancel the document due to future transaction and neither can I generate a return document. Return document throws: `Serial no <serial number here> has been already returned`

P.S Shouldn't branch transfers be Stock Transfer and not purchase?

**Comment by rtdany10** [comment]
@rohitwaghchaure Is there a PR where I can contribute or see the progress to the issue?

**Pull request closed without merging**
