### PR TITLE
fix(customer): quick form and integration fixes

### PR DESCRIPTION
**Pull request by blaggacao**
# Context

Consider three scenarios:

1. When customer is created via quick entry, the name of the contact should follow the name of the customer. Clarification: this is the case where the system is configured for automatic contact creation, presumably a high volume B2C business seeking the agility of a unified creation vs a more elaborate relationship between customers and contacts / addresses.

2. When customer is created via quick entry, and an address is created, it should be the default billing and shipping address

3. When customer is create from a webhook via an integration and permission on the customer are bypassed, then this intent should continue to be honored during address and contact creation

# Proposed Solution

1. Change techincal `name` to human readable `customer_name`
2. Set default shipping and billing address (as even intended, but not implemented by the original code author 6 years ago)
3. Replay eventual flags, if present

### CODE REVIEW

**Comment by bosue** [comment]
2 and 3, yes.

But 1?

Say you‘re receiving a (purchase) order from Apple Inc. or Bosch AG. So your contact‘s name is inferred to be Mx. Apple or Mx. Bosch?

Now you receive a call by Ed Smith‘s bakery. Mrs. Miller orders a new mill. You create the customer, and without asking you, ERPNext will pretend you talked to Ed Smith?

I think we need a Full Name field for the customer‘s contact in the Quick Entry Form. 🤷🏻‍♂️

**Comment by blaggacao** [comment]
> But 1?

> Say you‘re receiving a (purchase) order from Apple Inc. or Bosch AG. So your contact‘s name is inferred to be Mx. Apple or Mx. Bosch?

> Now you receive a call by Ed Smith‘s bakery. Mrs. Miller orders a new mill. You create the customer, and without asking you, ERPNext will pretend you talked to Ed Smith?

I think though that such a business would disable automated contact creation (precisely as the business name doesn't follow the contact name). The current functionality wouldn't make sense otherwise. I agree that a contact name field could work around this, but that also makes the quick entry form much less quick.

Ultimately, such businesses would be better off to specifically create all associated contacts in the Lead form individually.

I made that clarification to the PR. Thanks for this consideration.

**Comment by bosue** [comment]
True. My argument doesn’t go against your change but questions the current implementation altogether. Your fix will improve the situation for B2C contexts while B2B remains problematic. Therefore my argument may be valid, but seems out of scope here… 💁🏻‍♂️

**Comment by blaggacao** [comment]
should be backported to v15

**Review by deepeshgarg007 — APPROVED** [review]

**Comment by barredterra** [comment]
Mapping customer name to first name is a bit better, but still often incorrect, especially when the customer is a company. Contact has a dedicated field for the company name.

**Pull request merged**
