### PR TITLE
refactor: plaid connection

### PR DESCRIPTION
**Pull request by batonac**
This makes the plaid bank connector much more performant and less error-prone.

- `plaid_access_token` is updated in the database directly via `frappe.db.set_value` instead of attempting to loading and save the Bank doc.
- The try/except clause in `add_institution` is expanded to include all updates to the `plaid_access_token`, to catch any errors related to the given `bank_name`
- `add_institution` is refactored to return just the `bank_name` instead of the bank doc, since only the `bank_name` is used in the subsequent `add_bank_accounts` function.
- Throw a dedicated error if `bank_name` is not returned in the Plaid response.

### CODE REVIEW

**Comment by batonac** [comment]
Can I get a review please?

**Comment by batonac** [comment]
@ankush, @deepeshgarg007, @casesolved-co-uk, any comments to help this move forward?

**Comment by casesolved-co-uk** [comment]
1. Plaid have withdrawn their free access via their development environment, so their lowest production plan is around $1500 per month making this integration pretty pointless unless you're setting up as a data warehouse
2. There's nothing broken; working, tested, mature code is always better than new untested unnecessary changes

**Comment by batonac** [comment]
Thanks for the review @casesolved-co-uk.

Re:
> 1. Plaid have withdrawn their free access via their development environment, so their lowest production plan is around $1500 per month making this integration pretty pointless unless you're setting up as a data warehouse

I think you might be misunderstanding Plaid's new fee structure. At least here in the US, they're charging $0.3/account/mo for production access to Transaction Sync.

> 2. There's nothing broken; working, tested, mature code is always better than new untested unnecessary changes

Plaid doesn't always return a bank account from `Plaid.create`--sometimes there's an error. The existing code has no error handling for this scenario. What's broken in that case is the user experience.

**Comment by casesolved-co-uk** [comment]
I guess their UK offering is different to the US then.
I suggest you post a bug with an error log that your PR fixes.

**Pull request closed without merging**
