### PR TITLE
fix: customer group and territory not mandatory

### LINKED ISSUE #36849: Filter group items for selection in Quick Entry form
While in the full-size DocType form, DocType links are correctly filtered to exclude group items:

IMG_1368

… in the quick entry form they’re not, so group items may be selected:

IMG_1367

The latter should not be allowed. Atm unsure if this on Frappe’s or ERPNext’s side, but guessing it’s a general issue as the quick entry form is automatically rendered, not individually specified in a DocType.

### PR DESCRIPTION
**Pull request by RitvikSardana**
While in the full-size DocType form, DocType links are correctly filtered to exclude group items:

image

… in the quick entry form they’re not, so group items may be selected:

image.

So making customer group and territory not mandatory.

### CODE REVIEW

**Comment by bosue** [comment]
Nice improvement and certainly the right choice to _not_ require customer group and territory on every single site (may still be overridden locally)!

But sorry to say, this does not _really_ fix #36849‘s underlying, and broader issue which is the fact that select filters are individual JS code, so don‘t propagate to the Quick Entry form.

**Comment by RitvikSardana** [comment]
@bosue 
you can actually control the quick entry form
you can check it here:
https://github.com/frappe/erpnext/blob/develop/erpnext/public/js/utils/contact_address_quick_entry.js

**Comment by deepeshgarg007** [comment]
@RitvikSardana Do the same for supplier as well

**Review by bosue — COMMENTED** [review]
Can only comment, but looks good, quick and easy. 👍

**Review by bosue — COMMENTED** [review]
Don‘t know why we‘d want to introduce a switch here.

For most tree hierarchies there‘s no point in selecting a group or even root item such as “All customer groups“. Isn‘t exactly this the point of the “Is group item“ flag?

If “Is group item” is overloaded with more meanings we’d rather need a conditional flag “Allow selecting (in spite of being a) group item” on the group item itself. But then again I think we should definitely try hard to avoid even more subtle complexity.

All in all, if an item is supposed to be selected, then it’s a basic parent item and no group item, IMHO.

**Pull request merged**
