### PR TITLE
fix: mysql syntax issue

### PR DESCRIPTION
**Pull request by bhavesh95863**
Getting syntax error when I am trying to select the work order in the picklist

image

### CODE REVIEW

**Review by s-aga-r — CHANGES_REQUESTED** [review]
@bhavesh95863 Could you rewrite this query in [frappe.qb](https://frappeframework.com/docs/v14/user/en/api/query-builder)?

**Comment by bhavesh95863** [comment]
@s-aga-r  yes I will do that.

**Comment by bhavesh95863** [comment]
@s-aga-r I rewrite that query.

**Review by s-aga-r — CHANGES_REQUESTED** [review]
Please fix linter

**Comment by s-aga-r** [comment]
> Please fix linter

@bhavesh95863 setup [pre-commit](https://pre-commit.com/), so you don't need to fix the linter errors manually and next time please open PR in develop branch.

**Review by s-aga-r — APPROVED** [review]

**Comment by bhavesh95863** [comment]
> > Please fix linter
> 
> @bhavesh95863 setup [pre-commit](https://pre-commit.com/), so you don't need to fix the linter errors manually and next time please open PR in develop branch.

sure @s-aga-r

**Pull request merged**
