### PR TITLE
[fix] task visibility fix #5601

### LINKED ISSUE #5601: [V7] Project - Tasks visibility
Steps:

1. Open existing Project.
2. Edit Status for Task.
3. Save Project.

After saving Project, none of the Task is visible in the Project. After a refresh, Tasks are visible again.

project-task-visibility

### PR DESCRIPTION
**Pull request by saurabh6790**

### CODE REVIEW

**Comment by rmehta** [comment]
what is the use case?

**Comment by saurabh6790** [comment]
Due to `if not self.get('__unsaved')` condition its not executing `self.load_tasks()` when you save form after modifications to it.

**Comment by rmehta** [comment]
mm that was to fix another problem.

With your update, try remove all the tasks from the list.

**Comment by saurabh6790** [comment]
Ya, big issue. It's not working if you delete all tasks. Let me check...

**Comment by saurabh6790** [comment]
fixed

**Pull request merged**
