### PR TITLE
Currency filter in Pricing Rule

### PR DESCRIPTION
**Pull request by shreyashah115**
#10993 
price-rule-currency

Summary:
1. Added a new mandatory field `currency` in Pricing Rule DocType.
2. Whenever the `pricing_rule.currency` matches the currency of any particular DocType where the pricing rule is triggered, the amount gets affected, else, the margin amount/ rate is not affected.
3. Renamed field `price_or_discount` and `price` to `rate_or_discount` and `rate`.
4. Added test cases.
5. Added a patch to set currency field in existing Pricing Rule docs.

### CODE REVIEW

**Comment by rmehta** [comment]
@saurabh6790 can we please review and merge this today?

**Comment by saurabh6790** [comment]
@nabinhait Made changes as per the discussion. Please review1

**Comment by saurabh6790** [comment]
@shreyashah115 rebase and push it again.

**Comment by eagoweb** [comment]
Today I migrated from older version 9 and all pricing rules weren't functioning in POS.
After some investigations the column "rate_or_discount" keeps the value "Price" which doesn't allow the system to use the pricing rule.

The following worked for me:
UPDATE [database].`tabPricing Rule` SET rate_or_discount='Rate' WHERE rate_or_discount='Price';

**Pull request merged**
