### PR TITLE
General Ledger improvement for cost/management accountants

### PR DESCRIPTION
**Pull request by ShashaQin**
Fixed https://github.com/frappe/erpnext/pull/4747.

### CODE REVIEW

**Comment by ShashaQin** [comment]
The screenshot of test data. I added project name and support ticket in one of sales invoice, then it would be shown on the its GL Entry report.
sales invoice
general ledger

**Comment by anandpdoshi** [comment]
@nabinhait can you look at this Pull Request? I find the addition of "Support Ticket" into the transactions a bit odd.

**Comment by nabinhait** [comment]
@anandpdoshi Agreed, Support Ticket is very specific case. But we can include project in gl entry.

**Comment by anandpdoshi** [comment]
To be merged manually after:
- [ ] Removing Support Ticket links
- [ ] Removing: `support_ticket`, `root_type`, `report_type`

**Pull request closed without merging**
