### PR TITLE
feat(pricing rule): free qty rounding and recursion qty

### PR DESCRIPTION
**Pull request by rtdany10**
PR Description:
1. Added `Round Free Qty` checkbox to round free item's qty to nearest integer.
2. Added `Recursive For` field to define qty for which recursion should be applied. (Eg: Buy 3, Get 1 and not just Buy 1, Get 1 which is the current mechanism)

image

#no-docs

### CODE REVIEW

**Comment by rtdany10** [comment]
- [x] Give user the ability to choose where to start recursion.
For example: I might be giving free item recursively for the quantity that is transacted over the minimum qty.
Scenario: Min Qty: 5, Transacted Qty: 10. Currently the system makes the whole 10 Nos eligible for free item, which might not be the actual use case. Offer might be applicable only for the qty above the minimum qty, that is, 10-5=5 Nos.

**Comment by rtdany10** [comment]
@deepeshgarg007 please review when you get time

**Comment by rtdany10** [comment]
@ruthra-kumar @deepeshgarg007

**Comment by ruthra-kumar** [comment]
With the below recursive settings, free item gets added twice. Expected only one free item.
Screenshot 2022-10-20 at 5 17 47 PM

output

**Comment by rtdany10** [comment]
> With the below recursive settings, free item gets added twice. Expected only one free item.

Caused by the change in transaction.js, I guess.
Will try to fix asap. @ruthra-kumar

**Comment by rtdany10** [comment]
@ruthra-kumar Please check now, should be fixed :)
Nice catch tho :smile:

**Comment by ruthra-kumar** [comment]
Remove the free item and modify qty on original. You'll still get the incorrect doubling effect.
output1

Standard Recursion doesn't have this effect.
output

**Comment by rtdany10** [comment]
https://user-images.githubusercontent.com/52111700/197124485-ecd7610f-d332-4c29-96d2-3516c66608f6.mp4

@ruthra-kumar can't replicate. Did you rebuild the assets and clear cache?

**Comment by ruthra-kumar** [comment]
> Did you rebuild the assets and clear cache?

Yup. 

Pricing rule:
`{
  "name": "PRLE-0001",
  "owner": "Administrator",
  "creation": "2022-10-20 17:04:51.391273",
  "modified": "2022-10-21 11:44:42.313084",
  "modified_by": "Administrator",
  "docstatus": 0,
  "idx": 0,
  "naming_series": "PRLE-.####",
  "title": "Buy 1 Get 1",
  "disable": 0,
  "apply_on": "Item Code",
  "price_or_product_discount": "Product",
  "mixed_conditions": 0,
  "is_cumulative": 0,
  "coupon_code_based": 0,
  "apply_rule_on_other": "",
  "selling": 1,
  "buying": 0,
  "applicable_for": "Customer Group",
  "customer_group": "All Customer Groups",
  "min_qty": 1,
  "max_qty": 50,
  "min_amt": 0,
  "max_amt": 0,
  "same_item": 1,
  "free_item": "Razor High DPI Mouse",
  "free_qty": 1,
  "free_item_rate": 0,
  "round_free_qty": 1,
  "is_recursive": 1,
  "recurse_for": 1,
  "apply_recursion_over": 0,
  "valid_from": "2022-10-20",
  "company": "LISP 1",
  "currency": "INR",
  "margin_type": "Percentage",
  "margin_rate_or_amount": 0,
  "rate_or_discount": "Discount Percentage",
  "apply_discount_on": "Grand Total",
  "rate": 0,
  "discount_amount": 0,
  "discount_percentage": 0,
  "threshold_percentage": 0,
  "priority": "",
  "apply_multiple_pricing_rules": 0,
  "apply_discount_on_rate": 0,
  "validate_applied_rule": 0,
  "rule_description": "Buy 1 Get 1",
  "promotional_scheme_id": "dda48ede84",
  "promotional_scheme": "Buy 1 Get 1",
  "doctype": "Pricing Rule",
  "items": [
    {
      "name": "7749f30abc",
      "owner": "Administrator",
      "creation": "2022-10-20 17:04:51.391273",
      "modified": "2022-10-21 11:44:42.313084",
      "modified_by": "Administrator",
      "docstatus": 0,
      "idx": 1,
      "item_code": "Razor High DPI Mouse",
      "uom": "Nos",
      "parent": "PRLE-0001",
      "parentfield": "items",
      "parenttype": "Pricing Rule",
      "doctype": "Pricing Rule Item Code"
    }
  ],
  "item_groups": [],
  "brands": [],
  "__last_sync_on": "2022-10-21T06:21:24.183Z"
}`

**Comment by rtdany10** [comment]
https://user-images.githubusercontent.com/52111700/197129431-84287b3a-7b99-4b61-9ea0-715c05f049e7.mp4

Tried with the same config, still can't replicate.
Can you try running `bench clear-cache && bench clear-website-cache` and then test this on Incognito Mode?
@ruthra-kumar

**Comment by ruthra-kumar** [comment]
> Can you try running bench clear-cache && bench clear-website-cache and then test this on Incognito Mode?

Still the same.

Maybe the doc should already be in `Draft` status. Try this,

1. Create invoice with free item
2. Save
3. Remove the FOC item
4. Modify `qty` on original item

**Comment by rtdany10** [comment]
> > Can you try running bench clear-cache && bench clear-website-cache and then test this on Incognito Mode?
> 
> Still the same.
> 
> Maybe the doc should already be in `Draft` status. Try this,
> 
>     1. Create invoice with free item
> 
>     2. Save
> 
>     3. Remove the FOC item
> 
>     4. Modify `qty` on original item

@ruthra-kumar tried this as well, couldn't replicate :/

**Comment by ruthra-kumar** [comment]
> > Can you try running bench clear-cache && bench clear-website-cache and then test this on Incognito Mode?
> 
> Still the same.
> 
> Maybe the doc should already be in `Draft` status. Try this,
> 
> 1. Create invoice with free item
> 2. Save
> 3. Remove the FOC item
> 4. Modify `qty` on original item

You can ignore this. Not replicable on Clean setup.

There is another issue though: Negative/Zero qty free items added if Qty is less than `recurse_over`. ideally it should not add any free item.

Price Rule:
Screenshot 2022-10-29 at 12 05 59 PM

Negative Qty:
output

**Comment by rtdany10** [comment]
Thank you @ruthra-kumar :smile: 
I have added validations on Pricing Rule to avoid the negative quantities.

**Review by ruthra-kumar — APPROVED** [review]

**Comment by ruthra-kumar** [comment]
@Mergifyio backport version-14-hotfix

**Pull request merged**
