### PR TITLE
Errors due to a single quote in Supplier's name #9424

### PR DESCRIPTION
**Pull request by tundebabzy**

### CODE REVIEW

**Comment by tundebabzy** [comment]
#9424

**Comment by mbauskar** [comment]
@tundebabzy ,

Test case `test_make_supplier_quotation_with_special_characters` failed please resolve and reopen the PR

**Comment by mbauskar** [comment]
Thanks for contributing!

Our contribution guidelines require that you add a screenshot showing that your proposed change works with an example. This pull request will be closed, but you can re-open it after adding the requested screenshot.

https://github.com/frappe/erpnext/wiki/Contribution-Guidelines

**Comment by tundebabzy** [comment]
@mbauskar 
The PR does not involve the UI. It just escapes an SQL string.

**Pull request merged**
