### PR TITLE
fix: Set right party name in bank transaction

### PR DESCRIPTION
**Pull request by marination**
Ref: https://github.com/frappe/erpnext/pull/34675

## Issue

- The matching is done on `employee_name`, `customer_name`, `supplier_name`, etc. 
- But it also returns this value as the matched party's `name` and sets it in the Bank Transaction. 
- This works fine if the party's `party_name` and `name` fields are identical (the default for Customer and Supplier), but produces wrong data if the party is named by series (the default for Employee). 
- It doesn't fail, it just puts the `party_name` in the Bank Transaction's link field. 
- The problem surfaces when trying to reconcile the Bank Transaction

Screenshot 2023-09-29 at 4 38 33 PM

## Fix

- Match using `party_name` but set party's docname in Bank Transaction
Screenshot 2023-09-29 at 4 39 55 PM

### CODE REVIEW

**Comment by marination** [comment]
Unrelated ecommerce test failures due to permission issues

**Review by barredterra — COMMENTED** [review]
@marination I think we could get `process.extract` to handle the mapping of `party_name` to `name`. My approach would be to pass a list of tuples `[(party_name, party), ...] ` and a custom preprocessor `lambda choice: choice[0]`. The result should then contain the index of the matched element, so we'll know exactly which one it was without searching the party names again.

Reference: https://maxbachmann.github.io/RapidFuzz/Usage/process.html#extract

**Comment by marination** [comment]
@ruthra-kumar review? its a pretty small fix

**Review by barredterra — APPROVED** [review]
Tested, LGTM

**Pull request merged**
