### PR TITLE
Loyalty Program

### LINKED ISSUE #12322: Shopping Cart Enhancements
- [ ] Mode of Payments selection
     - Cash on Delivery option
     - Option to choose the payment gateway
- [ ] Delivery Schedule
- [ ] Coupons / Gift Cards
     - [ ] Coupon Code Master
     - [ ] Based on the amount/quantity
     - [ ] Flat or percentage based
     - [ ] Underlying linked with the Pricing Rule
     - [ ] Max number of uses
     - [ ] Expiration 
- [ ] Loyalty Points
    - [x] Customer Enrollment in the Loyalty Program
    - [x] Collection from the Sales Invoices
    - [x] Expiry Date
    - [ ] Redemption

### LINKED ISSUE #12790: Loyalty Program
- [x] In Customer, select "Loyalty Program"
- [x] In Sales Invoice, fetch "Loyalty Program"
- [x] Issue "Loyalty Point" on Sales Invoice
- [x] Mode of Payment "Loyalty Point" in POS and Shopping Cart and Payment Entry

### PR DESCRIPTION
**Pull request by manassolanki**
### Note:
- There can be multiple Loyalty Programs.
- All the related customers can be auto opt-in for the program or can also be done manually from the customer doctype. 
- The collection factor can be flat or tiered on the basis of the total spent done by the customer.
- All the loyalty points will be stored in the simple ledger after booking the income (via sales invoice only).
- All the loyalty points earned has expiry date calculated as per the loyalty program.
- Loyalty points will be deleted after canceling the invoice.
- Redemption will be done via the Coupon/Gift Card (WIP) (Depends on https://github.com/frappe/erpnext/pull/12559)

#### Loyalty Program
loyalty program

#### Loyalty Point Entry/Ledger
image

#### Loyalty Point in Customer record
image

Fixes https://github.com/frappe/erpnext/issues/12322
Fixes https://github.com/frappe/erpnext/issues/12790

### CODE REVIEW

**Comment by kossanah** [comment]
Fantastic contribution, I have been looking out for this function.
Please kindly consider:
Message to inform customers about their rewards balance via email, text message, online customer portal. The customer Notifications can be configured as editable Templates  (Email or SMS)on setting.

**Comment by olamide2** [comment]
This is long awaited. The request for customer notification is important

**Comment by olamide2** [comment]
Loyalty points should be a "payment type"

On the payment page the total available points should be displayed and the cashier should have the option to use as much of this as the customer wants as tender. The balance will then be taking from the other tender methods

**Comment by rmehta** [comment]
"Loyalty Program" seems archaic. Use "Loyalty Plan" ?

**Comment by olamide2** [comment]
Or "Customer Reward Program"

**Comment by olamide2** [comment]
Hello all

Do we have an expected time line for this? anything needed to push it along?

Regards

**Comment by manassolanki** [comment]
hi @olamide2 
This will be completed and merged in the develop in the coming week. However, it will be in master only in the next version

**Comment by olamide2** [comment]
We also need to consider the accounting entries for the loyalty transactions.

Accounting standard dictates that value of the loyalty earned during a transaction should be treated as a deferred income which will be released when the loyalty is redeemed or expires

The following are my proposed entries during a transaction when loyalty is earned or redeemed or both

- Credit Sales Account (With Total value of sales)
- Debit Cash Account (With cash actually received, if any)
- Debit Credit Card Account (With value of credit card tender actually received, if any)
- Debit Sales Account (With Value of Loyalty earned if any)  (This is to defer the value of loyalty)
- Credit Loyalty Revenue Deferred Account (With Value of Loyalty earned if any) (This is to defer loyalty value)
- Debit Loyalty Expense Account (With Loyalty redeemed if any) 
- Credit Sales Account (With value of loyalty redeemed if any) (To release loyalty deferred on redemption)
- Debit Loyalty Revenue defered account (With value of Loyalty redeemed if any) (To release loyalty deferred on redemption)
-

**Comment by rmehta** [comment]
@manassolanki closing this for now.

**Comment by olamide2** [comment]
Hello Rushabh
Why is this been closed ? I am asking cause I see it is not been merged ?
May I know what the constraints are as this is a much needed feature by us and I have been following it with keen interest.
Regards 
-------- Original message --------From: Rushabh Mehta <notifications@github.com> Date: 12/02/2018  08:39  (GMT+01:00) To: frappe/erpnext <erpnext@noreply.github.com> Cc: olamide2 <olamideshodunke@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [frappe/erpnext] First Cut for the Loyalty Program (#12631) 
@manassolanki closing this for now.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/frappe/erpnext","title":"frappe/erpnext","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/frappe/erpnext"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rmehta in #12631: @manassolanki closing this for now."}],"action":{"name":"View Pull Request","url":"https://github.com/frappe/erpnext/pull/12631#issuecomment-364847221"}}}

**Comment by kossanah** [comment]
@rmehta Pls we really need this feature like yesterday. Is there any hope for us waiting for this feature to be released?

**Comment by nabinhait** [comment]
@kossanah @olamide2 Sure, it has been closed temporarily and under active development. we have given some feedback to @manassolanki , he will reopen the PR after implementing those.

**Comment by olamide2** [comment]
Glad to see this reopened

Important note..we need this to work with PoS module (both offline and on line versions)

Regards

**Comment by olamide2** [comment]
Hello Nabin
Would you mind explaining why this was closed ?
I know there must be a logical reason, but some of us are following this feature extremely closely and would like to know what the status is at each stage.
Regards 
null

**Comment by nabinhait** [comment]
It is still under active development, @manassolanki will soon reopen after finishing the feature.

**Comment by olamide2** [comment]
hello @manassolanki 

Good job and well done

Can you confirm that this will work for offline and online PoS?

It is important

Regards

**Comment by manassolanki** [comment]
Hi @olamide2 

This will work for online POS and shopping cart. We are planning to implement for the offline POS at the later stage.

**Comment by kossanah** [comment]
Hello is this feature now merged? I am just checking

**Comment by Olawale1** [comment]
Hi @manassolanki 

Thanks for this great work. It was almost heart-breaking to hear this will not be available for offline POS at inception after waiting for so long! Could you please clarify the reason why? As far as I see, the parameters are set in documents which are anyway created by transactions in Offline POS (Customer Master, Sales Invoice) so I thought the points would accrue automatically regardless of which channel the transactions are generated from

Please confirm

Thanks

**Comment by Olawale1** [comment]
Hi @manassolanki 

Also, please confirm that your PR also includes a field in the Customer master for 'Loyalty ID' which can be used to fetch the Customer Name/ID in the POS Screen by scanning/swiping the loyalty card

This is a very small bull important part

Thanks

**Comment by manassolanki** [comment]
Hi @Olawale1 

The Loyalty Program is basically divided into the two sections:
1. Collection of Points: This will be done via the creation of the sales invoice. All the channels whether desk or shopping cart or POS will be used for the collection of loyalty points.
2. Redemption of Points: On redemption, the equivalent amount (in the base currency) of the earned points will be booked in the selected expanse account. Redemption can be done on the desk, shopping cart and online POS only. Now allowing the redemption in the offline POS will create a loophole in the validation of earned loyalty points. This is the reason we are not allowing that in the offline POS. If you have some better solution for handling this loophole, we will be happy to implement that too.

Since every customer can be linked only to the one loyalty program, therefore the customer id can be used as their Loyalty ID

**Comment by Olawale1** [comment]
Hi @manassolanki 

Thanks a lot for the explanation. I understand the issue for offline POS now and will give some thought to finding a solution 

Regarding Loyalty cards, using the regular Customer ID in ERPNext will not suffice in any serious retail business for 2 reasons:

1. It is too slow to try and pull up each customer's details on a payment queue by typing in their customer id! Every second is precious in a retail environment and this is a cumbersome and unnecessary step!

2. It is very prone to errors! Retail businesses traditionally have Tens to Hundreds of thousands of customers. Many of them will have very similar customer IDs. Selecting the wrong ID (which is a very frequent occurrence) would mean that the loyalty points accrue to the wrong person! This is something that must be avoided at all costs 

These are some of the critical reasons why loyalty schemes in retail are linked with Loyalty Cards. Each loyalty card has a unique ID/Barcode which must be linked to the individual customer's record; this happens at the point of registration. All the cashier has to do at the point of sale is scan/swipe the loyalty card to automatically select the correct customer ID. This saves time and significantly reduces the possibility of errors

Hope my explanation is clear enough 

Thanks

**Comment by olamide2** [comment]
With regards to the loophole in using loyalty offline, I assume the loophole refers to the ability for the customer to use more points than they are entitled to while the system is offline and throwing the points into negative.

In my opinion we should give the retailer the option to assume this risk by using the loyalty module in the offline mode. Some retailers will assume that risk gladly.

I will recommend that you put this as an option that the business can activate if they want to assume the risk stated above.

What do you think ?

**Comment by Olawale1** [comment]
I totally agree with @olamide2 and I can tell you without a doubt that most retailers would gladly accept that risk

I think it should be an option with a warning just the same as allowing negative stock

Thanks

**Comment by Olawale1** [comment]
Hi @nabinhait @manassolanki

How soon will this get merged pls? It's such a needed feature for those of us in retail!
We really need you to assist in expediting this

Thanks

**Comment by olamide2** [comment]
Just about giving up hope on this PR.

How can we help if help is needed ?

Regards

**Comment by Olawale1** [comment]
I think a feature that is so important, required, and of interest to lots of ERPNext users should be given some priority 

It would really be nice to have some info on the progress (or lack thereof) of this PR and anything we can do to assist in moving things along

Cheers

**Comment by manassolanki** [comment]
Hi @olamide2 and @Olawale1 
We assure you that Loyalty Points will be there in the V11. If you want to test you can test after pulling this branch into your local setup or if you are using the master then you are already getting this in v11 release.

**Comment by olamide2** [comment]
Awesome! 
Can I ask for more? does it cover offline yet?

**Comment by kossanah** [comment]
@manassolanki 
Thanks for the update, I am happy to hear the feature will be include in V11. Well done

**Comment by OnlyC** [comment]
I'm happy, too. But is there's eta for v11 release?
Also can I have information about below features? Which is already available? Which will be included in next release? and which I should custom by my self for now?
Thank you!

> - COD
> - Additional Payment gateways
> - Discount coupon codes
> - Customer Returns
> - Locationwise shipping carriers
> - Reward/loyalty points
> - Customer referrals
[https://github.com/frappe/erpnext/wiki/E-Commerce-Features-List](url)

**Comment by nabinhait** [comment]
@manassolanki Travis is failing. Also remove the conflicts.

**Review by nabinhait — APPROVED** [review]

**Comment by olamide2** [comment]
Can we merge this already!!

lol

**Review by nabinhait — APPROVED** [review]

**Comment by drhubehs** [comment]
Hi- how can I add loyalty to my erpnext installation on my server? We want to have a loyalty program for our customers who walk into a store location and purchase at a pos. this can also extend to the ecommerce purchases

**Comment by Olawale1** [comment]
Hi @drhubehs

This is a new feature which hasn't been released in the live version yet. It will be released in version 11. To test it now, you'll have to install the 'develop' branch on your server

Since you intend using this in a live environment, I'd advise you wait for version 11 to be released and then update your instance

If you would like to discuss this further, you can do that in the forum @ https://discuss.erpnext.com
This platform is mainly for discussions relating directly to development 

Cheers! :)

**Comment by olamide2** [comment]
Hi @manassolanki 

Thanks for the efforts on this. 

Some issues have been raised on the loyalty points for example check out https://github.com/frappe/erpnext/issues/14930.

Could you also look at making the loyalty available offline based on the suggestions above as quoted below 

_**With regards to the loophole in using loyalty offline, I assume the loophole refers to the ability for the customer to use more points than they are entitled to while the system is offline and throwing the points into negative.

In my opinion we should give the retailer the option to assume this risk by using the loyalty module in the offline mode. Some retailers will assume that risk gladly.

I will recommend that you put this as an option that the business can activate if they want to assume the risk stated above.

What do you think ?**_

**Comment by OnlyC** [comment]
@manassolanki I found another errors in the file: loyalty_point_entry.py

function: get_loyalty_point_entries
if not expiry_date:
	date = today()

should be:
if not expiry_date:
	expiry_date = today()

Sorry I don't know how to PR.

**Comment by olamide2** [comment]
@manassolanki

Can you please help update the two errors identified above by @OnlyC ?

Regards

**Comment by Muzzy73** [comment]
Hi, has anyone been able to migrate loyalty points from previous system into ERPNext without making an Invoice. Businesses have issued Loyalty points on their previous system and these need to be available in production ERPNext. We have tried many ways but not been able to make loyalty points opening. 

Any help would be much appreciated.

**Pull request merged**
