### PR TITLE
[WIP] Bank statement

### PR DESCRIPTION
**Pull request by crossxcell99**
**OVERVIEW**

**Bank**

This doctype allows to specify the actual banks a statement format will be linked to. Multiple accounts can be specified for a bank

 

 

**Bank Statement Format**

A format describing/guiding the interpretation of a (raw) bank statement is specified here. A mapping is made to convert the statement to a known format.

 

**Bank Transaction Type**

Specific bank transactions from a bank statement can be identified here. A match is made against the statement&#39;s transaction description.

 

**Bank Statement**

To make a bank statement record, we specify the bank, statement format, start and end dates of the transactions the statement to be uploaded contains.

The raw statement is attached and &quot;Upload statement&quot; button is used to create records for statement item table. Supported extensions are .xlsx and .csv

The process statement button is used to fill the accounts associated with each statement item.

Upon statement upload and saving of document, a previous bank statement can be gotten which has a similar bank and a preceding non-overlapping statement end date.

### CODE REVIEW

**Comment by ckosiegbu** [comment]
@crossxcell99 can you add the To-do's ?

**Comment by crossxcell99** [comment]
BANK STATEMENT TO-DO

* Creation of journal entries, payment entries or gl entries as required from transaction items in the following ways:
	1. While processing statement (on click of "Process Statement" button)
	2. By using the "Post Manually" button on a bank statement item after manually specifying transaction types

* Improvement on identification of transaction type for bank statement items

**Comment by crossxcell99** [comment]
&quot;_Upload Statement_&quot; button accomplishes two goals as follows:

- **Mapping of bank statement columns to internal representation.**

> First we specify **Bank Statement Format** document record which will used identify columns in the uploaded bank statement to a corresponding internal representation.

> We make a bank statement format by entering the name ( **Statement Format** ) for the statement format an optional **Description** , specifying the **Transaction Type Derivation** which determines if the transaction types in the bank statement are to gotten using the Bank Transaction Type records or from a field in the bank statement to be uploaded.

> When the bank statement is uploaded, its data is used to fill the fields in the bank statement item table. We may add rows to the &quot;Field Mappings&quot; table to define how data gotten from the attached statement (source) is used to fill the fields in the Bank Statement Item fields (target).

> **Source Field** : This is the column name of the statement to be imported.

> **Source Field Abbr** : Here an abbreviation is given for the source field. Abbreviations should be unique.

> **Transformation Rule** : Basic math and string operations can be used to determine how the data should be presented in the internal representation. For example, the value of a target field can be gotten from the sum of two source fields with abbreviations &quot;SR1&quot; and &quot;SR2&quot; with the transformation rule &quot;SR1 + SR2&quot;. (without the quotation marks, for both field abbreviation and transformation rules)

> **Target Field** : The corresponding field title for the internal representation is chosen here from the drop down.

> **Target Field Abbr** : Like &quot;Source Field Abbr&quot;, a unique abbreviation for the target field is entered here.

- **Identifying transactions in bank statement**

> We also need to specify transaction types to be expected from bank statements by creating Bank Transaction Type document records.

> We make a bank transaction type record by selecting the associated **Bank Statement Format** , entering an identification in the **Transaction Type** field (in form of a code as this field is restricted to a length of five), selecting if the transaction is of type credit or debit in the **DR or CR** field and entering an optional **Transaction Description**.

> The data entered in **Transaction Type Match Expression Field** is used to search the transaction description of the bank statement. The manner which this search is made can altered from the check boxes by the side.

> Posting rules can be specified in the Third Party Posting and General Ledger Posting sections.

**Comment by nabinhait** [comment]
@crossxcell99 Thanks for the PR 👍 
As you are discussing with @sathishpy about redesigning it, closing it for now.

**Pull request closed without merging**
