### PR TITLE
 ImportError: No module named past.builtins While saving Quotation

### PR DESCRIPTION
**Pull request by navdeepghai**
```
Traceback (most recent call last):
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/app.py", line 62, in application
12:35:29 web.1            |     response = frappe.handler.handle()
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/handler.py", line 22, in handle
12:35:29 web.1            |     data = execute_cmd(cmd)
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/handler.py", line 53, in execute_cmd
12:35:29 web.1            |     return frappe.call(method, **frappe.form_dict)
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/__init__.py", line 939, in call
12:35:29 web.1            |     return fn(*args, **newargs)
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/desk/form/save.py", line 22, in savedocs
12:35:29 web.1            |     doc.save()
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/model/document.py", line 256, in save
12:35:29 web.1            |     return self._save(*args, **kwargs)
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/model/document.py", line 279, in _save
12:35:29 web.1            |     self.insert()
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/model/document.py", line 218, in insert
12:35:29 web.1            |     self.run_before_save_methods()
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/model/document.py", line 859, in run_before_save_methods
12:35:29 web.1            |     self.run_method("validate")
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/model/document.py", line 755, in run_method
12:35:29 web.1            |     out = Document.hook(fn)(self, *args, **kwargs)
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/model/document.py", line 1024, in composer
12:35:29 web.1            |     return composed(self, method, *args, **kwargs)
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/model/document.py", line 1007, in runner
12:35:29 web.1            |     add_to_return_value(self, fn(self, *args, **kwargs))
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/frappe/frappe/model/document.py", line 749, in <lambda>
12:35:29 web.1            |     fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/erpnext/erpnext/selling/doctype/quotation/quotation.py", line 26, in validate
12:35:29 web.1            |     super(Quotation, self).validate()
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/erpnext/erpnext/controllers/selling_controller.py", line 37, in validate
12:35:29 web.1            |     super(SellingController, self).validate()
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/erpnext/erpnext/controllers/stock_controller.py", line 17, in validate
12:35:29 web.1            |     super(StockController, self).validate()
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/erpnext/erpnext/controllers/accounts_controller.py", line 41, in validate
12:35:29 web.1            |     self.set_missing_values(for_validate=True)
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/erpnext/erpnext/controllers/selling_controller.py", line 47, in set_missing_values
12:35:29 web.1            |     self.set_missing_lead_customer_details()
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/erpnext/erpnext/controllers/selling_controller.py", line 55, in set_missing_lead_customer_details
12:35:29 web.1            |     doctype=self.doctype, company=self.company)
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/erpnext/erpnext/accounts/party.py", line 51, in _get_party_details
12:35:29 web.1            |     out["taxes_and_charges"] = set_taxes(party.name, party_type, posting_date, company, out.customer_group, out.supplier_type)
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/erpnext/erpnext/accounts/party.py", line 330, in set_taxes
12:35:29 web.1            |     from erpnext.accounts.doctype.tax_rule.tax_rule import get_tax_template, get_party_details
12:35:29 web.1            |   File "/home/tablix/frappe-bench/apps/erpnext/erpnext/accounts/doctype/tax_rule/tax_rule.py", line 6, in <module>
12:35:29 web.1            |     from past.builtins import cmp
12:35:29 web.1            | ImportError: No module named past.builtins
```

### CODE REVIEW

**Comment by achillesrasquinha** [comment]
`bench setup requirements`

**Comment by nabinhait** [comment]
`future` is already in the frappe/requirements. Have you done `bench setup requirements` after pull frappe?

**Comment by navdeepghai1** [comment]
No I didn't, I thought after executing bench update, It's not required to execute  **bench setup requirements**

**Comment by achillesrasquinha** [comment]
`bench update` does update your requirements.

**Pull request closed without merging**
