### PR TITLE
fix: update zh.csv

### PR DESCRIPTION
**Pull request by szufisher**
> Please provide enough information so that others can review your pull request:

> Explain the **details** for making this change. What existing problem does the pull request solve?

> Screenshots/GIFs

update zh.csv

### CODE REVIEW

**Comment by szufisher** [comment]
Anyone can help to review and got it merged before official V13 release?

**Comment by ankush** [comment]
Contributions are handled through translation portal: https://translate.erpnext.com/ 

Please use the translation portal as there's no way to verify and approve translations using github.

**Comment by szufisher** [comment]
@ankush,
I would like to ask for your kind help to upload the csv file to the translate portal in the backend, otherwise change/verify the translated text one by one via translate portal is not feasible at all.
I remember in the past I have requested the same: upload in the back end via csv.

**Comment by ankush** [comment]
Sure. That would be possible.

**Comment by szufisher** [comment]
if possible, please also append these lines to the to-be uploaded csv file, thanks.

Unit of Measure (UOM),计量单位
Masters & Reports,主数据与报表
{}  Available,{} 可用,
{}  To Deliver,{} 待出货,
{}  To Receive,{} 待收货,
{} Active,{} 激活,
{} Assigned,{} 已分派,
{} Available,{} 可用,
{} Dashboard,{} 数据中心,
{} Draft,{} 草稿,
{} Open,{} 待处理,
{} Pending,{} 待处理,
{} Published,{} 已发布,
{} To Bill,{}待开票,
{} To Deliver,{} 待出货,
{} Vacant,{} 空缺,
Taxation,税
Compensations,报酬,
Forecasting,预测
Settings & Configurations,设置与配置
Opening & Closing,开始与结束
Total Sales Amount,总销售额
Total Qty Sold,总销售数量
Total Purchase Amount,总采购额
Total Qty Purchased,总采购数量
Available Stock Qty,总库存数量
Available Stock Value,可用库存金额

**Pull request closed without merging**
