### PR TITLE
fix: while making Sales Invoice from Sales Order payment term was not…

### PR DESCRIPTION
**Pull request by AfshanKhan**
… getting fetched before saving the document. 

Now the payment schedule also gets fetch.

### CODE REVIEW

**Review by Anurag810 — APPROVED** [review]

**Review by deepeshgarg007 — COMMENTED** [review]
@AfshanKhan @Anurag810 This is intentional I guess. The Invoice creation date and Sales Invoice creation dates are different in most case and it doesn't makes any sense to copy the payment terms then

**Comment by AfshanKhan** [comment]
@deepeshgarg007 @Anurag810 If payment term is getting fetch from Sales Order then payment schedule should also be same right. They could change it later if they want to.

**Comment by deepeshgarg007** [comment]
> @deepeshgarg007 @Anurag810 If payment term is getting fetch from Sales Order then payment schedule should also be same right. They could change it later if they want to.

Not necessarily, Refer my reply in this [PR](https://github.com/frappe/erpnext/pull/20509) for more info

**Comment by AfshanKhan** [comment]
> > @deepeshgarg007 @Anurag810 If payment term is getting fetch from Sales Order then payment schedule should also be same right. They could change it later if they want to.
> 
> Not necessarily, Refer my reply in this [PR](https://github.com/frappe/erpnext/pull/20509) for more info

Ok got it

**Comment by Anurag810** [comment]
I got your point @deepeshgarg007  that is a valid use case. It can vary from business to business payment can be taken at the Order level or Invoice level with different payment terms date.

**Pull request closed without merging**
