### PR TITLE
fix: fetch company terms

### PR DESCRIPTION
**Pull request by kunhimohamed**
System does not fetch the Company terms at Sales Invoicing.

### CODE REVIEW

**Review by barredterra — COMMENTED** [review]
The `get_party_account` section (lines 21–34) seems to be redundant and could be removed, right?

**Comment by kunhimohamed** [comment]
yes, then no need to override.

**Comment by kunhimohamed** [comment]
yes, no need to override.

**Review by barredterra — APPROVED** [review]

**Comment by kunhimohamed** [comment]
the same issue happens in version-14 also.

**Pull request merged**
