### PR TITLE
fix: add the company in payment request bcz delete company transactions

### LINKED ISSUE #42659: Payment requests are not being deleted when deleting company transactions
### Information about bug

When we want to delete a company's transactions, we go into company and select `Delete Transactions`. It creates a `Transaction Delete Record` and deletes the transactions. But this doesn't delete `Payment Request` docs while the related `Sales Invoice` docs are deleted. The transaction delete record completes successfully in this case too.

### Module

accounts

### Version

ERPNext 15.30.0
Frappe 15.35.0

### Installation method

FrappeCloud

### Relevant log output / Stack trace / Full Error Message.

_No response_

### PR DESCRIPTION
**Pull request by Nihantra-Patel**
version 15

fixes: #42659

**Before:**

https://github.com/user-attachments/assets/fcdf6747-5ba4-4cdb-b878-323b13dacd0f

**After:**

https://github.com/user-attachments/assets/131dd503-ed10-4602-a2fa-d39a5d60932f

### CODE REVIEW

**Comment by ruthra-kumar** [comment]
I think the company field is implicitly set. On a multi-company setup, this might incorrectly set the same company for all PR's. Can you test this?

@Nihantra-Patel

**Comment by Nihantra-Patel** [comment]
Hi @ruthra-kumar,

Video is long but check it out.

https://github.com/user-attachments/assets/39d2dfc1-90fd-4a6c-8a23-b9018c972699

**Comment by ruthra-kumar** [comment]
> Hi @ruthra-kumar,
> 
> Video is long but check it out.
> multi-company.with.PR.mp4

This is exactly what I had suspected.

Process flow should not rely upon user setting the correct session defaults. Not every user will do that.
Ex:

https://github.com/user-attachments/assets/e0e32a36-93c5-4d7d-9014-77372767d6c6

Explicit is always better than Implicit.

**Comment by ruthra-kumar** [comment]
With e3008843d15ef0301c3171250bfcd81db738e5ae, above issue should be fixed.

**Review by ruthra-kumar — APPROVED** [review]

**Pull request merged**
