### PR TITLE
[WIP] fix: improve translation pattern

### PR DESCRIPTION
**Pull request by barredterra**
I noticed that the following snippet is flagged as invalid, which made me tune the regex a bit:

```js
__("{0} edited this {1}", [
	frappe.user.full_name(this.frm.doc.modified_by).bold(),
	"<br>" + comment_when(this.frm.doc.modified),
])
```

### Before
Bildschirmfoto 2020-12-10 um 11 52 36

### After
Bildschirmfoto 2020-12-10 um 11 50 33
Bildschirmfoto 2020-12-10 um 11 49 47

Try it yourself: regexr.com/5i7as

### CODE REVIEW

**Comment by netchampfaris** [comment]
@barredterra Multiline translated strings are not supported. That is why they are not matched in the regex pattern.

@surajshetty3416 Am I missing something here?

**Comment by surajshetty3416** [comment]
https://frappeframework.com/docs/user/en/translations#3-blocks
According to docs, multiline translatable strings are not supported probably because there are some gotchas in translating multiline strings.

We can allow variables in a different line though (if it's not supported already).

**Comment by barredterra** [comment]
> We can allow variables in a different line though (if it's not supported already).

Yes, currently it's not supported. Do you know what the gotchas are with multiline strings?

**Comment by barredterra** [comment]
@surajshetty3416 I changed it so that multiline strings are not allowed.

**Review by surajshetty3416 — DISMISSED** [review]

**Pull request closed without merging**
