### PR TITLE
feat: BOM Comparison Tool

### PR DESCRIPTION
**Pull request by netchampfaris**
bom-comparison-tool

### CODE REVIEW

**Comment by netchampfaris** [comment]
@frappe-bot create instance

**Review by surajshetty3416 — APPROVED** [review]

**Comment by Thunderbottom** [comment]
@frappe-bot create instance

**Comment by Thunderbottom** [comment]
@frappe-bot create instance

**Comment by Thunderbottom** [comment]
@frappe-bot create instance

**Review by deepeshgarg007 — APPROVED** [review]

**Comment by deepeshgarg007** [comment]
@netchampfaris Please raise a PR for develop branch as well

**Pull request merged**
