### PR TITLE
[Enhancement] for Sidebar Menu with "Order" Page Route

### PR DESCRIPTION
**Pull request by creamdory**
I added a few enhancement and field additions for Sidebar Menu using "Order" as page route and "transaction_row.html" as list view.

1) Added Print Button:
print

2) Added Valid Till (for Quotation Only), Customer/Supplier Name and contact name:
name

3) Show Terms and Conditions if any:
terms

4) Adjust Column to avoid amounts with more precision like below:
break

5) Show Valid Till (for Quotation), Customer/Supplier Name and Contact in list view:
quotation
orders
invoices
shipments
supplier quotation

### CODE REVIEW

**Comment by kickapoo** [comment]
@nabinhait Can you please check this one for merge. Its a very nice addition and fix for our customers.

**Comment by mbauskar** [comment]
@creamdory,

Thanks for the PR,

It seems that travis checks failed can you please check and fix the tests cases. Also please add the simple UI tests case for Orders and Quotation page?

Closing the PR for now, but you can reopen it ..

**Comment by creamdory** [comment]
@mbauskar , available test cases for doctypes involve can be used for this as it only need to generate submitted data to test and nothing special. Thanks!

**Comment by rmehta** [comment]
@creamdory the alignment is incorrect (check horizontal alignment with the next element) for all your changes. Also if the value are not set, they appear as "None"

**Comment by rmehta** [comment]
https://github.com/frappe/erpnext/pull/10361

@creamdory please see my changes. Hoping for a better PR next time!

**Comment by creamdory** [comment]
Hi @rmehta , thanks! I'll make sure to send a better PR next time.

**Pull request closed without merging**
