### PR TITLE
feat: add deprecation dumpster

### PR DESCRIPTION
**Pull request by blaggacao**
### ERPNext: Add Deprecation Dumpster

This PR introduces a new `deprecation_dumpster.py` file to manage deprecated functions and methods in ERPNext. Key features:

- Custom `@deprecated` decorator for marking deprecated code
- Colorized warning messages for better visibility
- Enforces moving deprecated functions to the dumpster file
- Includes a `deprecation_warning` function for in-place warnings

This approach improves code maintenance by centralizing deprecated code and providing clear migration paths for users.

### CODE REVIEW

**Review by akhilnarang — COMMENTED** [review]
Any reason to not import these from framework directly? And just have a new exception class

**Comment by blaggacao** [comment]
> Any reason to not import these from framework directly?

Indeed. In order to ensure graduation within the dumpster, the `deprecated` decorator can only be used inside a file `deprecation_dumpster.py`. In the end, this is the prime feature of the dumpster that every deprecated code block must be located centrally inside this file.

The only exception is, when the deprecation doesn't concern an entire code block, but a value based code path. Then `deprecation_warning` can be used in-place (because there's just no other way).

**Comment by blaggacao** [comment]
We could do some mix and match, and DRY some parts, but not others. I think, though, given this special circumstance, it wouldn't necessarily become cleaner?

**Comment by ruthra-kumar** [comment]
> Enforces moving deprecated functions to the dumpster file

I don't understand how this is better? 

Just calling a decorator is much a simpler approach.

**Comment by blaggacao** [comment]
> I don't understand how this is better?

https://github.com/frappe/frappe/pull/27887#issuecomment-2371433065

I think most of the arguments there also apply here. We've seen the Frappe dumpster fill up quite considerably. But, on the other hand, ERPNext might have just much less stuff to deprecated so that such an institution has less benefit than in Frappe.

**Comment by ruthra-kumar** [comment]
Depreciation dumpter is mostly useful for apps that have external facing API. Framework is a good example; `frappe.get_doc`, `frappe.db.get_all` etc.

ERPNext is not a good contender for that. None of the internal methods are meant to be called / used by external apps. Such method are bound to change it's name, structure, parameter list or it's purpose, frequently.

What external app will benefit most is a reliable mechanism to hook into different stages of a document's cycle. Framework already has that - before_save(), after_insert() etc. Such kind of a "lifecycle" hooks, from an ERPNext point of view, is currently lacking. We need to think in that regard.

**Comment by blaggacao** [comment]
Indeed. Most of the code in ERPNext concerns DocType code and their specific lifecycle.

On the other hand, there are still some parts that have the character of a framework, such as controllers and other utils.

In fact, my first use case appears to be for a newly obsolete method in the tax and totals controller.

Therefore, I propose to narrow the purpose of this PR down to the framework-ish parts in ERPNext, where it makes sense.

The undeniable usefulness of clearly defined extension points among erpnext doctypes stands on its own and well beyond this PR.

---

Under this different angle, though, I see two questions emerging:
- Do we want to align with Frappe best practices and keep it centralized (arguments: https://github.com/frappe/frappe/pull/27887#issuecomment-2371433065)?
- Do we want to diverge from Frappe best practices and keep deprecations in-line?

It pretty much seems like you favor the latter, @ruthra-kumar &mdash; I propose to give it some more thought and maybe decide next week. I can then quickly refactor.

---

I just wanted to add, that besides "external apps", there are still more equivalent consumers of the API:
- Customizations
- Server Scripts 
- Forks or Patches (this is the one I deal constantly with myself)

**Comment by barredterra** [comment]
> I just wanted to add, that besides "external apps", there are still more equivalent consumers of the API:
>
> - Customizations
> - Server Scripts
> - Forks or Patches (this is the one I deal constantly with myself)

I agree. Basically my whole work-life consists of customizing ERPNext, which includes the more or less private methods  - they are not clearly separated, so everything could just as well be deemed public.

An external app calling a function that is defined in ERPNext is quite common, I think.

**Comment by blaggacao** [comment]
To ease in this facility, I'm removing the _enforcement_ of having to place deprecated methods inside the `deprecation_dumpster.py` file. This allows developers an escape hatch to deprecate methods in-place, if they so choose.

**Comment by ruthra-kumar** [comment]
@blaggacao 

Without the _enforcement_, I'm ok with this PR. As a mechanism for depreciation is useful.


Having said that, when and where they'll be used is what I'm more concerned with. Merely marking a method as deprecated implies - "it used be an externally accessable method, instead you can use this other method now"; which I don't agree with.

**Comment by blaggacao** [comment]
> Having said that, when and where they'll be used is what I'm more concerned with. Merely marking a method as deprecated implies - "it used be an externally accessable method, instead you can use this other method now"; which I don't agree with.

I totally agree with this concern, this will be always an individual PR decision. I hope that with a more conscientious approach to deprecation, we can make more conscientious deprecation decisions, always wisely balancing off the need for improvement with the need for stability.

**Comment by blaggacao** [comment]
Merging for a more readable diff on https://github.com/frappe/erpnext/pull/43372 &mdash; where already one such deprecation decision can be accepted or rejected.

**Pull request merged**
