### PR TITLE
Update hu_chart_of_accounts.json

### PR DESCRIPTION
**Pull request by krnkris**
Update hu_chart_of_accounts.json to be prepared for the account numbers

### CODE REVIEW

**Comment by nabinhait** [comment]
@krnkris Let's implement this after merging #10551 , where account number will be a separate field. The PR should be merged within a day or two. Closing it for now.

**Comment by krnkris** [comment]
@nabinhait 

there is a possibility to get in work the Hungarian chart of account with account numbers?
May this be modified in chart.erpnext.com or what is your suggestion?

**Comment by krnkris** [comment]
@nabinhait 

I almost ready with the new Hungarian chart of accounts with numbers.

I use the production branch.

Where is located the .json file what I create on my desktop environment?
I would like to share it.
I do not find in the 
/erpnext/accounts/doctype/account/chart_of_accounts/unverified
location.

**Comment by nabinhait** [comment]
https://github.com/frappe/erpnext/blob/master/erpnext/accounts/doctype/account/chart_of_accounts/verified/hu_chart_of_accounts.json

**Comment by krnkris** [comment]
@nabinhait

It seem my queston was not clear.
I found al the files on github.
What I don’t find is the new .json
file what I create in my self hosted production server.
I created a new chart of accounts.
Where save the program the .json file about this new chart of account? How can I export it from ERPNext?

Could you tell me please ?

**Comment by nabinhait** [comment]
If you want to contribute the chart you have created, you can add it under verified directory and commit and push into your fork. And then you can send a pull request. After verification and testing we will merge it into the main repository.

**Pull request closed without merging**
