### PR TITLE
Employee Promotion

### PR DESCRIPTION
**Pull request by rkurungadam**
https://github.com/frappe/erpnext/issues/13646
https://github.com/frappe/erpnext/issues/13642
TODO: 
- cancel allocated leaves and re-allocate to new company on Employee Transfer
- tests

### CODE REVIEW

**Comment by nabinhait** [comment]
Can you add some screenshots / GIF?

**Review by nabinhait — CHANGES_REQUESTED** [review]
- [ ] Rebase the branch with enterprise_sprint
- [ ] Add tests
- [ ] Add docs

**Review by nabinhait — CHANGES_REQUESTED** [review]
Most of the methods in transfer and promotion are same. Please commonify the methods.

**Comment by rkurungadam** [comment]
Ok, will do..

**Pull request closed without merging**
