### PR TITLE
fix: Wrong allocated_amount for sales_team in gross_profit report

### PR DESCRIPTION
**Pull request by devdiogenes**
I created a single Sales Invoice with two items, both sold for 50.00 (total: 100.00). The current code shows a wrong allocated_amount, because for each item, it sums the total amount of the invoice, instead the item amount.

Before fixing: 
before

After fixing: 
after

### CODE REVIEW

**Comment by devdiogenes** [comment]
Waiting review

**Comment by devdiogenes** [comment]
Waiting review

**Comment by devdiogenes** [comment]
Waiting review

**Comment by devdiogenes** [comment]
waiting review...

**Comment by devdiogenes** [comment]
i'm waiting review

**Comment by devdiogenes** [comment]
Waiting review

**Comment by devdiogenes** [comment]
Waiting for review

**Review by ruthra-kumar — APPROVED** [review]

**Pull request merged**
