### PR TITLE
Changed Manufacturer from Data to its own DocType

### PR DESCRIPTION
**Pull request by dottenbr**
After my pull request "new-manufacturer-logic" has been milling around for some time I decided to make a first small step that I believe we can all agree on. Please accept this pull request and reject "new-manufacturer-logic".

Thank you @anandpdoshi and @rmehta 

In case you have questions lets discuss this sooner than later.

### CODE REVIEW

**Comment by nabinhait** [comment]
@dottenbr 
You have to write a patch to create Manufacturer records based on existing manufacturer data in Item.

**Comment by dottenbr** [comment]
@nabinhait I am not able to do that quite yet :-( help!?

**Comment by nabinhait** [comment]
@dottenbr No issue, I will manually merge the PR after adding the patch.

**Comment by dottenbr** [comment]
Thank you so much @nabinhait !

**Comment by nabinhait** [comment]
merged manually

**Comment by dottenbr** [comment]
:heart:

**Comment by nabinhait** [comment]
You can check the patch https://github.com/frappe/erpnext/commit/a613ea8abf2ac27c0cb505144dea14dd0d8157f9

**Pull request closed without merging**
