### PR TITLE
feat: New Report Timesheet Billing Summary , combination of three report

### PR DESCRIPTION
**Pull request by viralpatel15**
#37020
@deepeshgarg007  changes has been done
This Report is Combination of three report

Project Billing Summary
Employee Billing Summary
Daily Timesheet Summary

270397903-b3b9b14a-1c5a-4103-91ba-3a4b06d6d28b

270397801-c879a600-a424-40a9-8d9b-36fb0f18070d

### CODE REVIEW

**Comment by deepeshgarg007** [comment]
@viralpatel15 You have just removed the function I mentioned specifically in my previous comment 😅 
I had also mentioned that there is other code duplication as well which still seems to be there like `get_timesheet_details` function.

Also don't see the project column being added anywhere as shown in the screenshot. Are these the correct changes that you have pushed?

**Comment by viralpatel15** [comment]
> @viralpatel15 You have just removed the function I mentioned specifically in my previous comment 😅 I had also mentioned that there is other code duplication as well which still seems to be there like `get_timesheet_details` function.
> 
> Also don't see the project column being added anywhere as shown in the screenshot. Are these the correct changes that you have pushed?

Thanks for your affert @deepeshgarg007 
Please check , now is it okay?

**Comment by basawaraj-fosserp** [comment]
@deepeshgarg007 Do you recommend any further changes?

**Comment by deepeshgarg007** [comment]
@basawaraj-fosserp This still has raw SQL queries
BTW a better version seems to be available at https://github.com/frappe/erpnext/pull/37451

**Pull request closed without merging**
